<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Lab 10 | Univariate Statistics and Methodology using R</title>
  <meta name="description" content="This is the page that contains the course labs materials" />
  <meta name="generator" content="bookdown 0.13 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Lab 10 | Univariate Statistics and Methodology using R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the page that contains the course labs materials" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Lab 10 | Univariate Statistics and Methodology using R" />
  
  <meta name="twitter:description" content="This is the page that contains the course labs materials" />
  

<meta name="author" content="Department of Psychology, University of Edinburgh" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="lab-9-interactions-and-glm.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script>
  $(document).ready(function() {
    $head = $('#header');
    $head.prepend('<img style="padding-right:25%; margin-bottom:10px;" src="https://www.ed.ac.uk/sites/all/themes/uoe/assets/logo.png" width="770px" align="left">')
  });
</script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">USMR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview of the Course</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#the-team"><i class="fa fa-check"></i>The team</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-cheatsheets"><i class="fa fa-check"></i>R Cheatsheets</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-community"><i class="fa fa-check"></i>R Community</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="lab-1.html"><a href="lab-1.html"><i class="fa fa-check"></i><b>1</b> Lab 1</a><ul>
<li class="chapter" data-level="1.1" data-path="lab-1.html"><a href="lab-1.html#lets-get-going"><i class="fa fa-check"></i><b>1.1</b> Let’s get going!</a><ul>
<li class="chapter" data-level="1.1.1" data-path="lab-1.html"><a href="lab-1.html#rstudio"><i class="fa fa-check"></i><b>1.1.1</b> RStudio</a></li>
<li class="chapter" data-level="1.1.2" data-path="lab-1.html"><a href="lab-1.html#console"><i class="fa fa-check"></i><b>1.1.2</b> Console</a></li>
<li class="chapter" data-level="1.1.3" data-path="lab-1.html"><a href="lab-1.html#editor"><i class="fa fa-check"></i><b>1.1.3</b> Editor</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="lab-1.html"><a href="lab-1.html#a-simple-analysis"><i class="fa fa-check"></i><b>1.2</b> A simple analysis</a><ul>
<li class="chapter" data-level="1.2.1" data-path="lab-1.html"><a href="lab-1.html#last-things"><i class="fa fa-check"></i><b>1.2.1</b> Last Things</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="lab-2.html"><a href="lab-2.html"><i class="fa fa-check"></i><b>2</b> Lab 2</a><ul>
<li class="chapter" data-level="2.1" data-path="lab-2.html"><a href="lab-2.html#first-things-first"><i class="fa fa-check"></i><b>2.1</b> First things first</a></li>
<li class="chapter" data-level="2.2" data-path="lab-2.html"><a href="lab-2.html#classes"><i class="fa fa-check"></i><b>2.2</b> Classes</a></li>
<li class="chapter" data-level="2.3" data-path="lab-2.html"><a href="lab-2.html#data-structures"><i class="fa fa-check"></i><b>2.3</b> Data structures</a><ul>
<li class="chapter" data-level="2.3.1" data-path="lab-2.html"><a href="lab-2.html#subsetting"><i class="fa fa-check"></i><b>2.3.1</b> Subsetting</a></li>
<li class="chapter" data-level="2.3.2" data-path="lab-2.html"><a href="lab-2.html#subsetting-using-names"><i class="fa fa-check"></i><b>2.3.2</b> Subsetting using names</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="lab-2.html"><a href="lab-2.html#replacement"><i class="fa fa-check"></i><b>2.4</b> Replacement</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="lab-3.html"><a href="lab-3.html"><i class="fa fa-check"></i><b>3</b> Lab 3</a><ul>
<li class="chapter" data-level="3.1" data-path="lab-3.html"><a href="lab-3.html#logical-subsetting"><i class="fa fa-check"></i><b>3.1</b> Logical subsetting</a><ul>
<li class="chapter" data-level="3.1.1" data-path="lab-3.html"><a href="lab-3.html#complementary-subsetting"><i class="fa fa-check"></i><b>3.1.1</b> Complementary subsetting</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="lab-3.html"><a href="lab-3.html#sorting"><i class="fa fa-check"></i><b>3.2</b> Sorting</a></li>
<li class="chapter" data-level="3.3" data-path="lab-3.html"><a href="lab-3.html#subsetting-with-commands"><i class="fa fa-check"></i><b>3.3</b> Subsetting with commands</a></li>
<li class="chapter" data-level="3.4" data-path="lab-3.html"><a href="lab-3.html#creating-variables"><i class="fa fa-check"></i><b>3.4</b> Creating variables</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="lab-4.html"><a href="lab-4.html"><i class="fa fa-check"></i><b>4</b> Lab 4</a><ul>
<li class="chapter" data-level="4.1" data-path="lab-4.html"><a href="lab-4.html#introduction"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="lab-4.html"><a href="lab-4.html#simple-plots"><i class="fa fa-check"></i><b>4.2</b> Simple Plots</a><ul>
<li class="chapter" data-level="4.2.1" data-path="lab-4.html"><a href="lab-4.html#categorical-variables"><i class="fa fa-check"></i><b>4.2.1</b> Categorical Variables</a></li>
<li class="chapter" data-level="4.2.2" data-path="lab-4.html"><a href="lab-4.html#ordinal-categorical-variables"><i class="fa fa-check"></i><b>4.2.2</b> Ordinal Categorical Variables</a></li>
<li class="chapter" data-level="4.2.3" data-path="lab-4.html"><a href="lab-4.html#continuous-variables"><i class="fa fa-check"></i><b>4.2.3</b> Continuous Variables</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="lab-4.html"><a href="lab-4.html#scatterplots-visualizing-associations"><i class="fa fa-check"></i><b>4.3</b> Scatterplots: Visualizing associations</a></li>
<li class="chapter" data-level="4.4" data-path="lab-4.html"><a href="lab-4.html#boxplots-visualizing-group-differences"><i class="fa fa-check"></i><b>4.4</b> Boxplots: Visualizing group differences</a></li>
<li class="chapter" data-level="4.5" data-path="lab-4.html"><a href="lab-4.html#descriptive-statistics"><i class="fa fa-check"></i><b>4.5</b> Descriptive Statistics</a></li>
<li class="chapter" data-level="4.6" data-path="lab-4.html"><a href="lab-4.html#more-advanced-plotting"><i class="fa fa-check"></i><b>4.6</b> More advanced plotting</a><ul>
<li class="chapter" data-level="4.6.1" data-path="lab-4.html"><a href="lab-4.html#pinpointing-data"><i class="fa fa-check"></i><b>4.6.1</b> Pinpointing data</a></li>
<li class="chapter" data-level="4.6.2" data-path="lab-4.html"><a href="lab-4.html#customising-plots"><i class="fa fa-check"></i><b>4.6.2</b> Customising plots</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="lab-4.html"><a href="lab-4.html#multiple-plots-in-one"><i class="fa fa-check"></i><b>4.7</b> Multiple Plots in One</a></li>
<li class="chapter" data-level="4.8" data-path="lab-4.html"><a href="lab-4.html#lets-put-all-this-into-practice"><i class="fa fa-check"></i><b>4.8</b> Let’s put all this into practice</a><ul>
<li class="chapter" data-level="4.8.1" data-path="lab-4.html"><a href="lab-4.html#code-book"><i class="fa fa-check"></i><b>4.8.1</b> Code Book</a></li>
<li class="chapter" data-level="4.8.2" data-path="lab-4.html"><a href="lab-4.html#questions"><i class="fa fa-check"></i><b>4.8.2</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="lab-4.html"><a href="lab-4.html#lab-4-ggplot"><i class="fa fa-check"></i><b>4.9</b> Lab 4 GGPLOT</a><ul>
<li class="chapter" data-level="4.9.1" data-path="lab-4.html"><a href="lab-4.html#introduction-1"><i class="fa fa-check"></i><b>4.9.1</b> Introduction</a></li>
<li class="chapter" data-level="4.9.2" data-path="lab-4.html"><a href="lab-4.html#ggplot2"><i class="fa fa-check"></i><b>4.9.2</b> <code>ggplot2</code></a></li>
<li class="chapter" data-level="4.9.3" data-path="lab-4.html"><a href="lab-4.html#qplot"><i class="fa fa-check"></i><b>4.9.3</b> <code>qplot()</code></a></li>
<li class="chapter" data-level="4.9.4" data-path="lab-4.html"><a href="lab-4.html#your-turn"><i class="fa fa-check"></i><b>4.9.4</b> Your Turn</a></li>
<li class="chapter" data-level="4.9.5" data-path="lab-4.html"><a href="lab-4.html#using-ggplot"><i class="fa fa-check"></i><b>4.9.5</b> Using <code>ggplot()</code></a></li>
<li class="chapter" data-level="4.9.6" data-path="lab-4.html"><a href="lab-4.html#your-turn-1"><i class="fa fa-check"></i><b>4.9.6</b> Your Turn</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="lab-5.html"><a href="lab-5.html"><i class="fa fa-check"></i><b>5</b> Lab 5</a><ul>
<li class="chapter" data-level="5.1" data-path="lab-5.html"><a href="lab-5.html#finally-stats"><i class="fa fa-check"></i><b>5.1</b> Finally stats</a><ul>
<li class="chapter" data-level="5.1.1" data-path="lab-5.html"><a href="lab-5.html#data-set"><i class="fa fa-check"></i><b>5.1.1</b> Data set</a></li>
<li class="chapter" data-level="5.1.2" data-path="lab-5.html"><a href="lab-5.html#read-in-and-clean-data"><i class="fa fa-check"></i><b>5.1.2</b> Read in and clean data</a></li>
<li class="chapter" data-level="5.1.3" data-path="lab-5.html"><a href="lab-5.html#impossible-values"><i class="fa fa-check"></i><b>5.1.3</b> Impossible values</a></li>
<li class="chapter" data-level="5.1.4" data-path="lab-5.html"><a href="lab-5.html#improbable-values"><i class="fa fa-check"></i><b>5.1.4</b> Improbable values</a></li>
<li class="chapter" data-level="5.1.5" data-path="lab-5.html"><a href="lab-5.html#non-integer-values"><i class="fa fa-check"></i><b>5.1.5</b> Non-integer values</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="lab-5.html"><a href="lab-5.html#lets-stats"><i class="fa fa-check"></i><b>5.2</b> Let’s stats!</a><ul>
<li class="chapter" data-level="5.2.1" data-path="lab-5.html"><a href="lab-5.html#categorical-variables-1"><i class="fa fa-check"></i><b>5.2.1</b> Categorical variables</a></li>
<li class="chapter" data-level="5.2.2" data-path="lab-5.html"><a href="lab-5.html#analysing-continuous-data"><i class="fa fa-check"></i><b>5.2.2</b> Analysing continuous data</a></li>
<li class="chapter" data-level="5.2.3" data-path="lab-5.html"><a href="lab-5.html#more-analysis"><i class="fa fa-check"></i><b>5.2.3</b> More analysis!</a></li>
<li class="chapter" data-level="5.2.4" data-path="lab-5.html"><a href="lab-5.html#extra-get-loopy"><i class="fa fa-check"></i><b>5.2.4</b> Extra: Get loopy</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="lab-6.html"><a href="lab-6.html"><i class="fa fa-check"></i><b>6</b> Lab 6</a><ul>
<li class="chapter" data-level="6.1" data-path="lab-6.html"><a href="lab-6.html#some-more-r-skills"><i class="fa fa-check"></i><b>6.1</b> Some more R skills</a><ul>
<li class="chapter" data-level="6.1.1" data-path="lab-6.html"><a href="lab-6.html#two-types-of-subscripting"><i class="fa fa-check"></i><b>6.1.1</b> Two types of subscripting</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="lab-6.html"><a href="lab-6.html#your-turn-2"><i class="fa fa-check"></i><b>6.2</b> Your Turn</a></li>
<li class="chapter" data-level="6.3" data-path="lab-6.html"><a href="lab-6.html#real-data"><i class="fa fa-check"></i><b>6.3</b> Real Data</a><ul>
<li class="chapter" data-level="6.3.1" data-path="lab-6.html"><a href="lab-6.html#the-data"><i class="fa fa-check"></i><b>6.3.1</b> The data</a></li>
<li class="chapter" data-level="6.3.2" data-path="lab-6.html"><a href="lab-6.html#the-questions"><i class="fa fa-check"></i><b>6.3.2</b> The questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="lab-7.html"><a href="lab-7.html"><i class="fa fa-check"></i><b>7</b> Lab 7</a><ul>
<li class="chapter" data-level="7.1" data-path="lab-7.html"><a href="lab-7.html#merging-and-missing-values"><i class="fa fa-check"></i><b>7.1</b> Merging and missing values</a><ul>
<li class="chapter" data-level="7.1.1" data-path="lab-7.html"><a href="lab-7.html#missing-values"><i class="fa fa-check"></i><b>7.1.1</b> Missing Values</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="lab-7.html"><a href="lab-7.html#writing-a-function"><i class="fa fa-check"></i><b>7.2</b> Writing a function</a></li>
<li class="chapter" data-level="7.3" data-path="lab-7.html"><a href="lab-7.html#some-data-manipulation"><i class="fa fa-check"></i><b>7.3</b> Some data manipulation</a></li>
<li class="chapter" data-level="7.4" data-path="lab-7.html"><a href="lab-7.html#a-note-on-correlation"><i class="fa fa-check"></i><b>7.4</b> A note on correlation</a></li>
<li class="chapter" data-level="7.5" data-path="lab-7.html"><a href="lab-7.html#some-statistics"><i class="fa fa-check"></i><b>7.5</b> Some statistics!</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html"><i class="fa fa-check"></i><b>8</b> Lab 8 - The General Linear Model</a><ul>
<li class="chapter" data-level="8.1" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html#a-brief-note-on-with"><i class="fa fa-check"></i><b>8.1</b> A brief note on <code>with()</code></a></li>
<li class="chapter" data-level="8.2" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html#linear-models"><i class="fa fa-check"></i><b>8.2</b> Linear Models</a></li>
<li class="chapter" data-level="8.3" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html#model-prediction-and-visualisation"><i class="fa fa-check"></i><b>8.3</b> Model prediction and visualisation</a><ul>
<li class="chapter" data-level="8.3.1" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html#predict"><i class="fa fa-check"></i><b>8.3.1</b> Predict()</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html#model-criticism"><i class="fa fa-check"></i><b>8.4</b> Model criticism</a></li>
<li class="chapter" data-level="8.5" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html#multiple-regression"><i class="fa fa-check"></i><b>8.5</b> Multiple regression</a></li>
<li class="chapter" data-level="8.6" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html#contrast-coding"><i class="fa fa-check"></i><b>8.6</b> Contrast coding</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html"><i class="fa fa-check"></i><b>9</b> Lab 9 - Interactions and GLM&quot;</a><ul>
<li class="chapter" data-level="9.1" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#interactions"><i class="fa fa-check"></i><b>9.1</b> Interactions</a><ul>
<li class="chapter" data-level="9.1.1" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#specifying-interactions-in-r"><i class="fa fa-check"></i><b>9.1.1</b> Specifying interactions in R</a></li>
<li class="chapter" data-level="9.1.2" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#simulating-data"><i class="fa fa-check"></i><b>9.1.2</b> Simulating data</a></li>
<li class="chapter" data-level="9.1.3" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#visualising-interactions"><i class="fa fa-check"></i><b>9.1.3</b> Visualising interactions</a></li>
<li class="chapter" data-level="9.1.4" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#modelling-interactions"><i class="fa fa-check"></i><b>9.1.4</b> Modelling interactions</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#generalised-linear-model-glm"><i class="fa fa-check"></i><b>9.2</b> General<strong>ised</strong> Linear Model (GLM)</a><ul>
<li class="chapter" data-level="9.2.1" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#log-odds-and-predicted-probabilities"><i class="fa fa-check"></i><b>9.2.1</b> Log-odds and predicted probabilities</a></li>
<li class="chapter" data-level="9.2.2" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#predicted-vs-observed"><i class="fa fa-check"></i><b>9.2.2</b> Predicted vs Observed</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#your-turn-less-guidance"><i class="fa fa-check"></i><b>9.3</b> Your turn (Less guidance)</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="lab-10.html"><a href="lab-10.html"><i class="fa fa-check"></i><b>10</b> Lab 10</a><ul>
<li class="chapter" data-level="10.1" data-path="lab-10.html"><a href="lab-10.html#apply-functions"><i class="fa fa-check"></i><b>10.1</b> <code>apply</code> functions</a></li>
<li class="chapter" data-level="10.2" data-path="lab-10.html"><a href="lab-10.html#lab-10-1"><i class="fa fa-check"></i><b>10.2</b> Lab 10</a><ul>
<li class="chapter" data-level="10.2.1" data-path="lab-10.html"><a href="lab-10.html#the-task"><i class="fa fa-check"></i><b>10.2.1</b> The Task</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Univariate Statistics and Methodology using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="lab-10" class="section level1">
<h1><span class="header-section-number">Chapter 10</span> Lab 10</h1>
<p><strong>This lab is a little less guided, and a little more like the take-home exam.</strong> The main thing to remember when carrying out an exercise like this is to make it clear <em>why</em> you made the decisions you made, either as a write-up or as comments (beginning with <code>#</code>) in the <code>R</code> code. There are no absolutely right or wrong answers, just sensible and less sensible things to try out!</p>
<p>Take some time to read this document fully before getting started with any analyses. Think about each variable in the dataset in terms of what it measures and the type of data it provides.</p>
<p><strong>Tip: </strong>Don’t be tempted to immediately run a certain model. Analysing a collected dataset is a process and these labs have been structured to illustrate many of the steps taken when analysing data ‘for real’. Think about some of the exercises from past labs to generate ideas about the steps you want to take.</p>
<div id="apply-functions" class="section level2">
<h2><span class="header-section-number">10.1</span> <code>apply</code> functions</h2>
<p>There is one more bit of programming we’d like you to be familiar with – the <code>apply()</code> family functions. These function take some data structure and apply any function to each element of that structure.</p>
<p>To illustrate, let’s look at <code>apply()</code>. Imagine I have a data frame like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mat &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">rnorm</span>(<span class="dv">100</span>), <span class="dt">ncol =</span> <span class="dv">5</span>)
df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">id =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">20</span>, mat)
<span class="kw">head</span>(df)</code></pre></div>
<pre><code>##   id         X1          X2         X3           X4         X5
## 1  1  1.6363745 -0.83842519  0.3728223  0.006180753 -0.6092358
## 2  2 -0.8760820  0.37245830 -0.1414563  2.046797547  0.5266528
## 3  3  1.8021205 -0.01405419 -1.0615777  1.905091329  2.9117237
## 4  4 -0.5493263  0.23579541  1.1208409  1.659623084  0.2307443
## 5  5  0.3001265  0.48284934 -0.1680932 -0.845594145  0.3560563
## 6  6  1.0421078  0.42371533  0.1735486 -0.175874533 -2.0643879</code></pre>
<p>let’s say I want to know which of the <code>X1</code>-<code>X5</code> columns contains the largest value <em>for each participant</em>. If we only take the first row, for example, then the task is easy, right?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df[<span class="dv">1</span>, <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>]</code></pre></div>
<pre><code>##         X1         X2        X3          X4         X5
## 1 1.636374 -0.8384252 0.3728223 0.006180753 -0.6092358</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">which.max</span>(df[<span class="dv">1</span>, <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>])</code></pre></div>
<pre><code>## X1 
##  1</code></pre>
<p>If we want to know this bit of information for every row of the data frame, doing it manually is quite tedious. We <em>could</em> instead use a <code>for</code> loop:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">max_col &lt;-<span class="st"> </span><span class="kw">c</span>()
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(df)) max_col &lt;-<span class="st"> </span><span class="kw">c</span>(max_col, <span class="kw">which.max</span>(df[i, <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>]))
max_col</code></pre></div>
<pre><code>## X1 X4 X5 X4 X2 X1 X3 X5 X5 X4 X2 X3 X3 X2 X2 X4 X2 X1 X1 X5 
##  1  4  5  4  2  1  3  5  5  4  2  3  3  2  2  4  2  1  1  5</code></pre>
<p>This loop iterates over the rows of <code>df</code> (<code>for (i in 1:nrow(df))</code>) and for each cycle it adds the output of the <code>which.max()</code> function to the <code>max_col</code> variable.</p>
<p>There is nothing wrong with this approach but it is a little wordy to write and not the fastest when it comes to computation time. The <code>apply()</code> function can be used to achieve the same outcome faster and using less code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">max_col2 &lt;-<span class="st"> </span><span class="kw">apply</span>(<span class="dt">X =</span> df[ , <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>], <span class="dt">MARGIN =</span> <span class="dv">1</span>, <span class="dt">FUN =</span> which.max)
max_col2</code></pre></div>
<pre><code>##  [1] 1 4 5 4 2 1 3 5 5 4 2 3 3 2 2 4 2 1 1 5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">all</span>(max_col <span class="op">==</span><span class="st"> </span>max_col2) <span class="co"># result is the same</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>So how does this work? <code>apply()</code> requires 3 arguments: - <code>X</code> – a matrix (remember that data frames can be treated as matrices) - <code>MARGIN</code> – <code>1</code> for by row, <code>2</code> for by column - <code>FUN</code> – name of function to apply (notice no <code>()</code>s)</p>
<p>Other arguments can be provided, for example <code>na.rm = T</code> if the function applied takes the <code>na.rm =</code> argument (<em>e.g.,</em> <code>mean()</code>).</p>
<p>The function takes the matrix provided to the <code>X =</code> argument and applies the function passed to <code>FUN =</code> along the margin (rows/columns) of the matrix, specified by the <code>MARGIN =</code> argument.</p>
<p>This is useful, don’t you think? The function becomes even more useful when you realise you can apply your own functions. Let’s say, we want to know the standard error estimate based on the 5 values for each participant:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> <span class="co"># define function</span>
std.error &lt;-<span class="st"> </span><span class="cf">function</span>(x, na.rm) <span class="kw">sd</span>(x, <span class="dt">na.rm =</span> na.rm)<span class="op">/</span><span class="kw">sqrt</span>(<span class="kw">length</span>(<span class="kw">na.omit</span>(x)))

<span class="kw">apply</span>(df[ , <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>], <span class="dv">1</span>, std.error, <span class="dt">na.rm =</span> T) <span class="co"># na.rm value will get passed on to std.error</span></code></pre></div>
<pre><code>##  [1] 0.4374026 0.4821450 0.7189106 0.3850806 0.2439404 0.5251694 0.3409391
##  [8] 0.3206761 0.5697642 0.2644058 0.1898708 0.4080338 0.6083222 0.4635421
## [15] 0.5036622 0.3922462 0.5230088 0.3590511 0.4263829 0.3458455</code></pre>
<p>You don’t even have to create a function object!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># same thing, different way</span>
<span class="kw">apply</span>(df[ , <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>], <span class="dv">1</span>,
      <span class="cf">function</span>(x) <span class="kw">sd</span>(x, <span class="dt">na.rm =</span> T)<span class="op">/</span><span class="kw">sqrt</span>(<span class="kw">length</span>(<span class="kw">na.omit</span>(x))))</code></pre></div>
<pre><code>##  [1] 0.4374026 0.4821450 0.7189106 0.3850806 0.2439404 0.5251694 0.3409391
##  [8] 0.3206761 0.5697642 0.2644058 0.1898708 0.4080338 0.6083222 0.4635421
## [15] 0.5036622 0.3922462 0.5230088 0.3590511 0.4263829 0.3458455</code></pre>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Calculate the standard deviation of each of the <code>X</code> <strong>columns</strong> of <code>df</code>.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">apply</span>(df[ , <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>], <span class="dv">2</span>, sd, <span class="dt">na.rm =</span> T)</code></pre></div>
<pre><code>##        X1        X2        X3        X4        X5 
## 0.9639913 0.8348326 0.9351637 1.2096203 1.2327756</code></pre>
<p>There are quite a few functions in the <code>apply()</code> family (<em>e.g.,</em> <code>vapply()</code>, <code>tapply()</code>, <code>mapply()</code>, <code>sapply()</code>), each doing something slightly different and each appropriate for a different data structure (<code>vector</code>, <code>matrix</code>, <code>list</code>, <code>data.frame</code>) and different task. You can read about all of them, if you want but we’d like to tell you about one in particular – <code>lapply()</code></p>
<p>The <code>lapply()</code> function takes a <code>list</code> (list apply) and applies a function to each of its elements. The function returns a list. This function is useful because data frames can also be treated as lists. This is what you do every time you use the <code>$</code> operator.</p>
<p>So, to do Task 1 using <code>lapply()</code>, you can simply do:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lapply</span>(df[ , <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>], sd, <span class="dt">na.rm =</span> T)</code></pre></div>
<pre><code>## $X1
## [1] 0.9639913
## 
## $X2
## [1] 0.8348326
## 
## $X3
## [1] 0.9351637
## 
## $X4
## [1] 1.20962
## 
## $X5
## [1] 1.232776</code></pre>
<p>If you don’t want the output to be a list, just use <code>unlist()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">unlist</span>(<span class="kw">lapply</span>(df[ , <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>], sd, <span class="dt">na.rm =</span> T))</code></pre></div>
<pre><code>##        X1        X2        X3        X4        X5 
## 0.9639913 0.8348326 0.9351637 1.2096203 1.2327756</code></pre>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Round all the <code>X</code> columns to 2 decimal places.</p>
<p><em>Hint: </em>Don’t forget you want to be modifying the columns in question.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">df[ , <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>] &lt;-<span class="st"> </span><span class="kw">lapply</span>(df[ , <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>], round, <span class="dv">2</span>)
<span class="kw">head</span>(df)</code></pre></div>
<pre><code>##   id    X1    X2    X3    X4    X5
## 1  1  1.64 -0.84  0.37  0.01 -0.61
## 2  2 -0.88  0.37 -0.14  2.05  0.53
## 3  3  1.80 -0.01 -1.06  1.91  2.91
## 4  4 -0.55  0.24  1.12  1.66  0.23
## 5  5  0.30  0.48 -0.17 -0.85  0.36
## 6  6  1.04  0.42  0.17 -0.18 -2.06</code></pre>
<p>So these are the two most useful functions from the <code>apply()</code> family you should know. As a general tip, you can use <code>apply()</code> for by-row operations and <code>lapply()</code> for by-column operations on data frames. The nice thing about these function is that they help you avoid repetitive code. For instance, you can now turn several columns of your data set into factors using something like <code>df[ , c(2, 5, 7, 8)] &lt;- lapply(df[ , c(2, 5, 7, 8)], factor)</code>. Cool, innit?</p>
<p> </p>
</div>
<div id="lab-10-1" class="section level2">
<h2><span class="header-section-number">10.2</span> Lab 10</h2>
<p>Load the data for this lab using the following code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">load</span>(<span class="kw">url</span>(<span class="st">&quot;https://edin.ac/2KNwiMU&quot;</span>))</code></pre></div>
<p>The data concerns a study investigating attitudes about fox-hunting in the UK. 412 participants were asked to rate their attitude towards hunting by marking a point along a line. The endpoints of the line were labelled <em>strongly opposed</em> and <em>strongly in favour</em>; the distance of each mark along its line was later measured, and scaled to a variable ranging from 1 (opposed) to 7 (in favour). The resulting variable is called <code>prohunt</code> in the dataset.</p>
<p>Also measured were where participants lived (<code>urban</code>, <code>suburban</code>, <code>country</code>) as well as their politics, using the Stone-Corley Wingedness Inventory, which returns a score along the political spectrum ranging from -100 (extremely left-wing, socialist) to 100 (extremely right-wing, conservative). This score can be found in the <code>spectrum</code> column. Finally, participants were asked to indicate whether they were prepared to participate in a follow-up interview; the <code>followup</code> column shows their response.</p>
<div id="the-task" class="section level3">
<h3><span class="header-section-number">10.2.1</span> The Task</h3>
<p><strong>Your job this week is to clean, describe and analyse the data to answer the questions below. You should also create some graphics to accompany your findings. </strong></p>
<p><strong>Questions: </strong></p>
<ul>
<li>How do participants’ political view and the rurality of where they live predict their attitudes towards foxhunting?<br />
Is the relationship between political views and foxhunting attitudes different between different ruralities? If so, how?</li>
</ul>
<p><strong>Some things you might want to think about first: </strong></p>
<ul>
<li><p>Does all of the data look sensible, given the descriptions above?</p></li>
<li><p>Did participants decide not to participate in the follow-up at random? What are the predicted probability of completing follow-up for each value of <code>spectrum</code>?</p></li>
</ul>
<p>The types of output you <em>might</em> produce include regression statistics, scatterplots, and graphs showing regression effects. Don’t forget to document your <code>R</code> code to show what you did.</p>
<p> </p>
<p><strong>Good luck with the exam!</strong></p>
<div class="solution" style="display:block">
<h2 id="an-example-analysis"><span class="header-section-number">10.2.1</span> An Example Analysis</h2>
<p><em>(N.B., this is not a ‘correct’ answer, just a sensible one!)</em></p>
<p>Start by loading the data and examining it…</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fox &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;data/fox.csv&#39;</span>)
<span class="kw">summary</span>(fox)</code></pre></div>
<pre><code>##        id            home        spectrum       followup    prohunt     
##  ABI    :  1   country :138   Min.   :-999.00   N: 25    Min.   :0.000  
##  ABK    :  1   suburban:137   1st Qu.: -25.00   Y:387    1st Qu.:3.095  
##  ABM    :  1   urban   :137   Median :  -3.00            Median :3.770  
##  ABR    :  1                  Mean   : -11.69            Mean   :3.732  
##  ABY    :  1                  3rd Qu.:  19.25            3rd Qu.:4.322  
##  ABZ    :  1                  Max.   :  86.00            Max.   :7.000  
##  (Other):406</code></pre>
<p>Most aspects look quite sensible; there are 412 rows, as promised, for example. However, there is <strong>at least</strong> one value of <span class="math inline">\(-999\)</span> in <code>spectrum</code> (likely indicates missing data) and also some 0s in <code>prohunt</code> (coding error perhaps as we know <code>prohunt</code> should be on the scale 1-7). Let’s fix this, and record how many datapoints have been removed (this might go into a writeup)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fox<span class="op">$</span>spectrum[fox<span class="op">$</span>spectrum <span class="op">==</span><span class="st"> </span><span class="op">-</span><span class="dv">999</span>] &lt;-<span class="st"> </span><span class="ot">NA</span>
fox<span class="op">$</span>prohunt[fox<span class="op">$</span>prohunt <span class="op">==</span><span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="ot">NA</span>
<span class="co"># complete.cases() might be new. Obviously there are other ways of doing it.</span>
<span class="co"># The &quot;!&quot; means &quot;not&quot;</span>
<span class="kw">sum</span>(<span class="op">!</span><span class="kw">complete.cases</span>(fox))</code></pre></div>
<pre><code>## [1] 6</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># alternative</span>
<span class="kw">sum</span>(<span class="kw">is.na</span>(fox<span class="op">$</span>prohunt))</code></pre></div>
<pre><code>## [1] 2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># etc.</span></code></pre></div>
<p>Probably the next thing I would do is do a scatterplot of the data, to get the ‘lay of the land’. <code>spectrum</code> makes a good <span class="math inline">\(x\)</span>-axis variable. Two plot commands are below: The first, I did just to see what was going on. In the second, I used colour and shape to try and work out what was happening (note the trick of using <code>col = as.numeric(home)</code>; the values will be <code>c(1, 2, 3)</code>, and as long as those map onto different colours, I’m good to go). You can see the output in Fig. 1</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Produces figure 1</span>
<span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)) <span class="co"># set two columns, 1 row</span>
<span class="kw">with</span>(fox, <span class="kw">plot</span>(spectrum, prohunt))
<span class="co"># second plot, this time with colour (for levels of &quot;home&quot;)</span>
<span class="co"># and shape (for &quot;non-followup people&quot;)</span>
<span class="kw">with</span>(fox, <span class="kw">plot</span>(spectrum, prohunt, <span class="dt">col =</span> <span class="kw">as.numeric</span>(home),
               <span class="dt">pch =</span> <span class="kw">ifelse</span>(followup<span class="op">==</span><span class="st">&#39;Y&#39;</span>, <span class="dv">2</span>, <span class="dv">4</span>)))</code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-364"></span>
<img src="bookdown-demo_files/figure-html/unnamed-chunk-364-1.png" alt="*Figure 1.*  Two scatterplots of `fox`; the second is coloured by `home` (black = country, red = suburban, green = urban) and shaped by whether participants want to participate in the followup (cross = no)." width="672" />
<p class="caption">
Figure 10.1: <em>Figure 1.</em> Two scatterplots of <code>fox</code>; the second is coloured by <code>home</code> (black = country, red = suburban, green = urban) and shaped by whether participants want to participate in the followup (cross = no).
</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># A ggplot alternative for exploring this (produces figure 2):</span>

<span class="kw">library</span>(ggplot2)
spec_pro &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data =</span> fox, <span class="kw">aes</span>(<span class="dt">x =</span> spectrum, <span class="dt">y =</span> prohunt, <span class="dt">colour =</span> followup))
spec_pro <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">theme_minimal</span>() <span class="op">+</span><span class="st"> </span><span class="kw">facet_grid</span>(. <span class="op">~</span><span class="st"> </span>home)</code></pre></div>
<pre><code>## Warning: Removed 6 rows containing missing values (geom_point).</code></pre>
<div class="figure"><span id="fig:unnamed-chunk-365"></span>
<img src="bookdown-demo_files/figure-html/unnamed-chunk-365-1.png" alt="*Figure 2. *A ggplot alternative to exploring the role of `home` on the relationship between `spectrum` and `prohunt` (also considering `followup`)" width="672" />
<p class="caption">
Figure 10.2: <em>Figure 2. </em>A ggplot alternative to exploring the role of <code>home</code> on the relationship between <code>spectrum</code> and <code>prohunt</code> (also considering <code>followup</code>)
</p>
</div>
<p>OK, there’s something weird about the no-followup guys. They all seem to be left-wing. Can I show that <code>spectrum</code> predicts whether you want to follow up? Remember this is a <em>logit</em> model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model &lt;-<span class="st"> </span><span class="kw">glm</span>(followup <span class="op">~</span><span class="st"> </span>spectrum, <span class="dt">data =</span> fox, <span class="dt">family =</span> binomial)
<span class="co"># the test below shows that knowing about spectrum improves model fit</span>
<span class="kw">anova</span>(model, <span class="dt">test =</span> <span class="st">&#39;Chisq&#39;</span>)</code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: binomial, link: logit
## 
## Response: followup
## 
## Terms added sequentially (first to last)
## 
## 
##          Df Deviance Resid. Df Resid. Dev  Pr(&gt;Chi)    
## NULL                       407    188.055              
## spectrum  1   111.69       406     76.368 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># and the summary here shows that political spectrum is important</span>
<span class="kw">summary</span>(model)</code></pre></div>
<pre><code>## 
## Call:
## glm(formula = followup ~ spectrum, family = binomial, data = fox)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -2.81851   0.00962   0.04340   0.13826   2.29444  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  6.84657    1.01355   6.755 1.43e-11 ***
## spectrum     0.12057    0.02079   5.799 6.68e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 188.055  on 407  degrees of freedom
## Residual deviance:  76.368  on 406  degrees of freedom
##   (4 observations deleted due to missingness)
## AIC: 80.368
## 
## Number of Fisher Scoring iterations: 8</code></pre>
<p>We can summarise the model by saying that for each point to the right on <code>spectrum</code>, you’re <span class="math inline">\(e^{0.12} = 1.13\)</span> times more likely to agree to a followup study. Left-wingers don’t seem keen at all!</p>
<p>Here’s how to draw a graph showing the model of the probability of accepting a followup depending on <code>spectrum</code> (output in Fig. 3). Note, it requires a bit of web-searching to find out about the <code>na.action = na.exclude</code> argument to <code>glm()</code> (and <code>lm()</code>). The search term I used was ``R include NAs in fitted()’’.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Produces figure 3</span>
model &lt;-<span class="st"> </span><span class="kw">glm</span>(followup <span class="op">~</span><span class="st"> </span>spectrum, <span class="dt">data =</span> fox, <span class="dt">family =</span> binomial, <span class="dt">na.action =</span> na.exclude)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">with</span>(fox, <span class="kw">plot</span>(<span class="kw">fitted</span>(model)[<span class="kw">order</span>(spectrum)] <span class="op">~</span><span class="st"> </span>spectrum[<span class="kw">order</span>(spectrum)],
               <span class="dt">type =</span> <span class="st">&#39;l&#39;</span>, <span class="dt">xlab =</span> <span class="st">&#39;spectrum&#39;</span>, <span class="dt">ylab =</span> <span class="st">&#39;p(followup)&#39;</span>))</code></pre></div>
<div class="figure"><span id="fig:unnamed-chunk-368"></span>
<img src="bookdown-demo_files/figure-html/unnamed-chunk-368-1.png" alt="*Figure 3. *Probability of allowing a followup as a function of `spectrum`: model fit." width="672" />
<p class="caption">
Figure 10.3: <em>Figure 3. </em>Probability of allowing a followup as a function of <code>spectrum</code>: model fit.
</p>
</div>
<h3 id="the-main-analysis"><span class="header-section-number">10.2.1</span> The main analysis</h3>
<p>Regardless of whether we decided to run the binomial model or not, it’s clear that these non-followup people are odd – they seem to be behaving differently to the rest of the population. I’d be tempted to take them out of the data and build a model without them. Note that the scatterplot makes it pretty obvious that there’ll be some kind of interaction, so:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># note the &quot;subset&quot; setting within &quot;lm()&quot; -- the lazy person&#39;s way!</span>
model &lt;-<span class="st"> </span><span class="kw">lm</span>(prohunt <span class="op">~</span><span class="st"> </span>spectrum<span class="op">*</span>home, <span class="dt">data =</span> fox, <span class="dt">subset =</span> followup <span class="op">==</span><span class="st"> &#39;Y&#39;</span>)
<span class="co"># this is equivalent:</span>
fox &lt;-<span class="st"> </span><span class="kw">subset</span>(fox, followup <span class="op">==</span><span class="st"> &#39;Y&#39;</span>)
model &lt;-<span class="st"> </span><span class="kw">lm</span>(prohunt <span class="op">~</span><span class="st"> </span>spectrum <span class="op">*</span><span class="st"> </span>home, <span class="dt">data =</span> fox)
<span class="kw">anova</span>(model)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: prohunt
##                Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## spectrum        1   4.049   4.049  6.0843 0.0140853 *  
## home            2  83.813  41.907 62.9758 &lt; 2.2e-16 ***
## spectrum:home   2   9.908   4.954  7.4446 0.0006752 ***
## Residuals     375 249.540   0.665                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># shows that each term improves the model</span>
<span class="kw">summary</span>(model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = prohunt ~ spectrum * home, data = fox)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.63294 -0.48986 -0.02376  0.51816  2.18220 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)            4.461984   0.074276  60.073  &lt; 2e-16 ***
## spectrum               0.012554   0.002743   4.577 6.43e-06 ***
## homesuburban          -0.931977   0.103005  -9.048  &lt; 2e-16 ***
## homeurban             -1.033300   0.103487  -9.985  &lt; 2e-16 ***
## spectrum:homesuburban -0.010994   0.003562  -3.087 0.002174 ** 
## spectrum:homeurban    -0.013265   0.003598  -3.687 0.000261 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8157 on 375 degrees of freedom
##   (6 observations deleted due to missingness)
## Multiple R-squared:  0.2815, Adjusted R-squared:  0.2719 
## F-statistic: 29.39 on 5 and 375 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>All the coefficients are significant in this model (<em>woop woop!</em>), and can be read top-to-bottom as follows:</p>
<ol style="list-style-type: decimal">
<li>People of middling political persuasion who live in the country, (<code>spectrum</code> = <code>0</code> and <code>home</code> = <code>country</code> at <code>(Intercept)</code>) have an attitude of 4.46.</li>
<li>For each additional <code>spectrum</code> point, that attitude goes up by 0.01, for people in the country.</li>
<li>People in suburban homes are less approving of foxhunting by -0.93.</li>
<li>People in urban homes are less approving of foxhunting by -1.03.</li>
<li>Points 3 and 4 hold for people at zero (intercept) on the political spectrum, but,</li>
<li>For suburban people the rise in 2 is reduced: actual rise <span class="math inline">\(=0.01+-0.01=0\)</span>.</li>
<li>Similarly, for urban people, the actual rise per point on the spectrum <span class="math inline">\(=0.01+-0.01=0\)</span>, or practically zero.</li>
</ol>
<p>So we can conclude that you need to live in the country and to be increasingly right-wing to have a positive attitude towards fox hunting.</p>
<h3 id="other-stuff-you-could-do"><span class="header-section-number">10.2.1</span> Other stuff you could do</h3>
<p>You could re-run the analysis above using <strong>orthogonal coding</strong>, to compare townies (urban and suburban) to country-dwellers, and then different types of townie to each other. That would look something like this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">contrasts</span>(fox<span class="op">$</span>home) &lt;-<span class="st"> </span><span class="kw">cbind</span>(<span class="dt">CvSU =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">1</span>) <span class="op">/</span><span class="st"> </span><span class="dv">3</span>, <span class="dt">SvU =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>) <span class="op">/</span><span class="st"> </span><span class="dv">2</span>)

<span class="co"># we&#39;ve already removed the no-followup guys</span>
model &lt;-<span class="st"> </span><span class="kw">lm</span>(prohunt <span class="op">~</span><span class="st"> </span>spectrum<span class="op">*</span>home, <span class="dt">data =</span> fox)

<span class="co"># anova(model) will be the same</span>

<span class="kw">summary</span>(model)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = prohunt ~ spectrum * home, data = fox)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.63294 -0.48986 -0.02376  0.51816  2.18220 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        3.806892   0.041903  90.850  &lt; 2e-16 ***
## spectrum           0.004467   0.001418   3.150 0.001766 ** 
## homeCvSU          -0.982639   0.089935 -10.926  &lt; 2e-16 ***
## homeSvU           -0.101323   0.101419  -0.999 0.318413    
## spectrum:homeCvSU -0.012129   0.003189  -3.803 0.000167 ***
## spectrum:homeSvU  -0.002270   0.003253  -0.698 0.485690    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8157 on 375 degrees of freedom
##   (6 observations deleted due to missingness)
## Multiple R-squared:  0.2815, Adjusted R-squared:  0.2719 
## F-statistic: 29.39 on 5 and 375 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This model shows that townie types (urban and suburban) are less likely to have positive attitudes to fox-hunting than country-dwellers (line 3); and that it’s only the townies’ attitudes are less affected by position on the political spectrum, although there’s no difference between urbanites and suburbanites (lines 5 and 6).</p>
<p>This last regression model may make the <em>most</em> sense of the data, such as it is, but, as long as you’ve explained why you’ve done what you’ve done, and as long as what you’ve done is reasonable, you’ve done a good job.</p>
</div>

</div>
</div>
</div>












            </section>

          </div>
        </div>
      </div>
<a href="lab-9-interactions-and-glm.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
