<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Lab 5 | Univariate Statistics and Methodology using R</title>
  <meta name="description" content="This is the page that contains the course labs materials" />
  <meta name="generator" content="bookdown 0.13 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Lab 5 | Univariate Statistics and Methodology using R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the page that contains the course labs materials" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Lab 5 | Univariate Statistics and Methodology using R" />
  
  <meta name="twitter:description" content="This is the page that contains the course labs materials" />
  

<meta name="author" content="Department of Psychology, University of Edinburgh" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="lab-4.html"/>
<link rel="next" href="lab-6.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script>
  $(document).ready(function() {
    $head = $('#header');
    $head.prepend('<img style="padding-right:25%; margin-bottom:10px;" src="https://www.ed.ac.uk/sites/all/themes/uoe/assets/logo.png" width="770px" align="left">')
  });
</script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">USMR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview of the Course</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#the-team"><i class="fa fa-check"></i>The team</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-cheatsheets"><i class="fa fa-check"></i>R Cheatsheets</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-community"><i class="fa fa-check"></i>R Community</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="lab-1.html"><a href="lab-1.html"><i class="fa fa-check"></i><b>1</b> Lab 1</a><ul>
<li class="chapter" data-level="1.1" data-path="lab-1.html"><a href="lab-1.html#lets-get-going"><i class="fa fa-check"></i><b>1.1</b> Let’s get going!</a><ul>
<li class="chapter" data-level="1.1.1" data-path="lab-1.html"><a href="lab-1.html#rstudio"><i class="fa fa-check"></i><b>1.1.1</b> RStudio</a></li>
<li class="chapter" data-level="1.1.2" data-path="lab-1.html"><a href="lab-1.html#console"><i class="fa fa-check"></i><b>1.1.2</b> Console</a></li>
<li class="chapter" data-level="1.1.3" data-path="lab-1.html"><a href="lab-1.html#editor"><i class="fa fa-check"></i><b>1.1.3</b> Editor</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="lab-1.html"><a href="lab-1.html#a-simple-analysis"><i class="fa fa-check"></i><b>1.2</b> A simple analysis</a><ul>
<li class="chapter" data-level="1.2.1" data-path="lab-1.html"><a href="lab-1.html#last-things"><i class="fa fa-check"></i><b>1.2.1</b> Last Things</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="lab-2.html"><a href="lab-2.html"><i class="fa fa-check"></i><b>2</b> Lab 2</a><ul>
<li class="chapter" data-level="2.1" data-path="lab-2.html"><a href="lab-2.html#first-things-first"><i class="fa fa-check"></i><b>2.1</b> First things first</a></li>
<li class="chapter" data-level="2.2" data-path="lab-2.html"><a href="lab-2.html#classes"><i class="fa fa-check"></i><b>2.2</b> Classes</a></li>
<li class="chapter" data-level="2.3" data-path="lab-2.html"><a href="lab-2.html#data-structures"><i class="fa fa-check"></i><b>2.3</b> Data structures</a><ul>
<li class="chapter" data-level="2.3.1" data-path="lab-2.html"><a href="lab-2.html#subsetting"><i class="fa fa-check"></i><b>2.3.1</b> Subsetting</a></li>
<li class="chapter" data-level="2.3.2" data-path="lab-2.html"><a href="lab-2.html#subsetting-using-names"><i class="fa fa-check"></i><b>2.3.2</b> Subsetting using names</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="lab-2.html"><a href="lab-2.html#replacement"><i class="fa fa-check"></i><b>2.4</b> Replacement</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="lab-3.html"><a href="lab-3.html"><i class="fa fa-check"></i><b>3</b> Lab 3</a><ul>
<li class="chapter" data-level="3.1" data-path="lab-3.html"><a href="lab-3.html#logical-subsetting"><i class="fa fa-check"></i><b>3.1</b> Logical subsetting</a><ul>
<li class="chapter" data-level="3.1.1" data-path="lab-3.html"><a href="lab-3.html#complementary-subsetting"><i class="fa fa-check"></i><b>3.1.1</b> Complementary subsetting</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="lab-3.html"><a href="lab-3.html#sorting"><i class="fa fa-check"></i><b>3.2</b> Sorting</a></li>
<li class="chapter" data-level="3.3" data-path="lab-3.html"><a href="lab-3.html#subsetting-with-commands"><i class="fa fa-check"></i><b>3.3</b> Subsetting with commands</a></li>
<li class="chapter" data-level="3.4" data-path="lab-3.html"><a href="lab-3.html#creating-variables"><i class="fa fa-check"></i><b>3.4</b> Creating variables</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="lab-4.html"><a href="lab-4.html"><i class="fa fa-check"></i><b>4</b> Lab 4</a><ul>
<li class="chapter" data-level="4.1" data-path="lab-4.html"><a href="lab-4.html#introduction"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="lab-4.html"><a href="lab-4.html#simple-plots"><i class="fa fa-check"></i><b>4.2</b> Simple Plots</a><ul>
<li class="chapter" data-level="4.2.1" data-path="lab-4.html"><a href="lab-4.html#categorical-variables"><i class="fa fa-check"></i><b>4.2.1</b> Categorical Variables</a></li>
<li class="chapter" data-level="4.2.2" data-path="lab-4.html"><a href="lab-4.html#ordinal-categorical-variables"><i class="fa fa-check"></i><b>4.2.2</b> Ordinal Categorical Variables</a></li>
<li class="chapter" data-level="4.2.3" data-path="lab-4.html"><a href="lab-4.html#continuous-variables"><i class="fa fa-check"></i><b>4.2.3</b> Continuous Variables</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="lab-4.html"><a href="lab-4.html#scatterplots-visualizing-associations"><i class="fa fa-check"></i><b>4.3</b> Scatterplots: Visualizing associations</a></li>
<li class="chapter" data-level="4.4" data-path="lab-4.html"><a href="lab-4.html#boxplots-visualizing-group-differences"><i class="fa fa-check"></i><b>4.4</b> Boxplots: Visualizing group differences</a></li>
<li class="chapter" data-level="4.5" data-path="lab-4.html"><a href="lab-4.html#descriptive-statistics"><i class="fa fa-check"></i><b>4.5</b> Descriptive Statistics</a></li>
<li class="chapter" data-level="4.6" data-path="lab-4.html"><a href="lab-4.html#more-advanced-plotting"><i class="fa fa-check"></i><b>4.6</b> More advanced plotting</a><ul>
<li class="chapter" data-level="4.6.1" data-path="lab-4.html"><a href="lab-4.html#pinpointing-data"><i class="fa fa-check"></i><b>4.6.1</b> Pinpointing data</a></li>
<li class="chapter" data-level="4.6.2" data-path="lab-4.html"><a href="lab-4.html#customising-plots"><i class="fa fa-check"></i><b>4.6.2</b> Customising plots</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="lab-4.html"><a href="lab-4.html#multiple-plots-in-one"><i class="fa fa-check"></i><b>4.7</b> Multiple Plots in One</a></li>
<li class="chapter" data-level="4.8" data-path="lab-4.html"><a href="lab-4.html#lets-put-all-this-into-practice"><i class="fa fa-check"></i><b>4.8</b> Let’s put all this into practice</a><ul>
<li class="chapter" data-level="4.8.1" data-path="lab-4.html"><a href="lab-4.html#code-book"><i class="fa fa-check"></i><b>4.8.1</b> Code Book</a></li>
<li class="chapter" data-level="4.8.2" data-path="lab-4.html"><a href="lab-4.html#questions"><i class="fa fa-check"></i><b>4.8.2</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="lab-4.html"><a href="lab-4.html#lab-4-ggplot"><i class="fa fa-check"></i><b>4.9</b> Lab 4 GGPLOT</a><ul>
<li class="chapter" data-level="4.9.1" data-path="lab-4.html"><a href="lab-4.html#introduction-1"><i class="fa fa-check"></i><b>4.9.1</b> Introduction</a></li>
<li class="chapter" data-level="4.9.2" data-path="lab-4.html"><a href="lab-4.html#ggplot2"><i class="fa fa-check"></i><b>4.9.2</b> <code>ggplot2</code></a></li>
<li class="chapter" data-level="4.9.3" data-path="lab-4.html"><a href="lab-4.html#qplot"><i class="fa fa-check"></i><b>4.9.3</b> <code>qplot()</code></a></li>
<li class="chapter" data-level="4.9.4" data-path="lab-4.html"><a href="lab-4.html#your-turn"><i class="fa fa-check"></i><b>4.9.4</b> Your Turn</a></li>
<li class="chapter" data-level="4.9.5" data-path="lab-4.html"><a href="lab-4.html#using-ggplot"><i class="fa fa-check"></i><b>4.9.5</b> Using <code>ggplot()</code></a></li>
<li class="chapter" data-level="4.9.6" data-path="lab-4.html"><a href="lab-4.html#your-turn-1"><i class="fa fa-check"></i><b>4.9.6</b> Your Turn</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="lab-5.html"><a href="lab-5.html"><i class="fa fa-check"></i><b>5</b> Lab 5</a><ul>
<li class="chapter" data-level="5.1" data-path="lab-5.html"><a href="lab-5.html#finally-stats"><i class="fa fa-check"></i><b>5.1</b> Finally stats</a><ul>
<li class="chapter" data-level="5.1.1" data-path="lab-5.html"><a href="lab-5.html#data-set"><i class="fa fa-check"></i><b>5.1.1</b> Data set</a></li>
<li class="chapter" data-level="5.1.2" data-path="lab-5.html"><a href="lab-5.html#read-in-and-clean-data"><i class="fa fa-check"></i><b>5.1.2</b> Read in and clean data</a></li>
<li class="chapter" data-level="5.1.3" data-path="lab-5.html"><a href="lab-5.html#impossible-values"><i class="fa fa-check"></i><b>5.1.3</b> Impossible values</a></li>
<li class="chapter" data-level="5.1.4" data-path="lab-5.html"><a href="lab-5.html#improbable-values"><i class="fa fa-check"></i><b>5.1.4</b> Improbable values</a></li>
<li class="chapter" data-level="5.1.5" data-path="lab-5.html"><a href="lab-5.html#non-integer-values"><i class="fa fa-check"></i><b>5.1.5</b> Non-integer values</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="lab-5.html"><a href="lab-5.html#lets-stats"><i class="fa fa-check"></i><b>5.2</b> Let’s stats!</a><ul>
<li class="chapter" data-level="5.2.1" data-path="lab-5.html"><a href="lab-5.html#categorical-variables-1"><i class="fa fa-check"></i><b>5.2.1</b> Categorical variables</a></li>
<li class="chapter" data-level="5.2.2" data-path="lab-5.html"><a href="lab-5.html#analysing-continuous-data"><i class="fa fa-check"></i><b>5.2.2</b> Analysing continuous data</a></li>
<li class="chapter" data-level="5.2.3" data-path="lab-5.html"><a href="lab-5.html#more-analysis"><i class="fa fa-check"></i><b>5.2.3</b> More analysis!</a></li>
<li class="chapter" data-level="5.2.4" data-path="lab-5.html"><a href="lab-5.html#extra-get-loopy"><i class="fa fa-check"></i><b>5.2.4</b> Extra: Get loopy</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="lab-6.html"><a href="lab-6.html"><i class="fa fa-check"></i><b>6</b> Lab 6</a><ul>
<li class="chapter" data-level="6.1" data-path="lab-6.html"><a href="lab-6.html#some-more-r-skills"><i class="fa fa-check"></i><b>6.1</b> Some more R skills</a><ul>
<li class="chapter" data-level="6.1.1" data-path="lab-6.html"><a href="lab-6.html#two-types-of-subscripting"><i class="fa fa-check"></i><b>6.1.1</b> Two types of subscripting</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="lab-6.html"><a href="lab-6.html#your-turn-2"><i class="fa fa-check"></i><b>6.2</b> Your Turn</a></li>
<li class="chapter" data-level="6.3" data-path="lab-6.html"><a href="lab-6.html#real-data"><i class="fa fa-check"></i><b>6.3</b> Real Data</a><ul>
<li class="chapter" data-level="6.3.1" data-path="lab-6.html"><a href="lab-6.html#the-data"><i class="fa fa-check"></i><b>6.3.1</b> The data</a></li>
<li class="chapter" data-level="6.3.2" data-path="lab-6.html"><a href="lab-6.html#the-questions"><i class="fa fa-check"></i><b>6.3.2</b> The questions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="lab-7.html"><a href="lab-7.html"><i class="fa fa-check"></i><b>7</b> Lab 7</a><ul>
<li class="chapter" data-level="7.1" data-path="lab-7.html"><a href="lab-7.html#merging-and-missing-values"><i class="fa fa-check"></i><b>7.1</b> Merging and missing values</a><ul>
<li class="chapter" data-level="7.1.1" data-path="lab-7.html"><a href="lab-7.html#missing-values"><i class="fa fa-check"></i><b>7.1.1</b> Missing Values</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="lab-7.html"><a href="lab-7.html#writing-a-function"><i class="fa fa-check"></i><b>7.2</b> Writing a function</a></li>
<li class="chapter" data-level="7.3" data-path="lab-7.html"><a href="lab-7.html#some-data-manipulation"><i class="fa fa-check"></i><b>7.3</b> Some data manipulation</a></li>
<li class="chapter" data-level="7.4" data-path="lab-7.html"><a href="lab-7.html#a-note-on-correlation"><i class="fa fa-check"></i><b>7.4</b> A note on correlation</a></li>
<li class="chapter" data-level="7.5" data-path="lab-7.html"><a href="lab-7.html#some-statistics"><i class="fa fa-check"></i><b>7.5</b> Some statistics!</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html"><i class="fa fa-check"></i><b>8</b> Lab 8 - The General Linear Model</a><ul>
<li class="chapter" data-level="8.1" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html#a-brief-note-on-with"><i class="fa fa-check"></i><b>8.1</b> A brief note on <code>with()</code></a></li>
<li class="chapter" data-level="8.2" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html#linear-models"><i class="fa fa-check"></i><b>8.2</b> Linear Models</a></li>
<li class="chapter" data-level="8.3" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html#model-prediction-and-visualisation"><i class="fa fa-check"></i><b>8.3</b> Model prediction and visualisation</a><ul>
<li class="chapter" data-level="8.3.1" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html#predict"><i class="fa fa-check"></i><b>8.3.1</b> Predict()</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html#model-criticism"><i class="fa fa-check"></i><b>8.4</b> Model criticism</a></li>
<li class="chapter" data-level="8.5" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html#multiple-regression"><i class="fa fa-check"></i><b>8.5</b> Multiple regression</a></li>
<li class="chapter" data-level="8.6" data-path="lab-8-the-general-linear-model.html"><a href="lab-8-the-general-linear-model.html#contrast-coding"><i class="fa fa-check"></i><b>8.6</b> Contrast coding</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html"><i class="fa fa-check"></i><b>9</b> Lab 9 - Interactions and GLM&quot;</a><ul>
<li class="chapter" data-level="9.1" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#interactions"><i class="fa fa-check"></i><b>9.1</b> Interactions</a><ul>
<li class="chapter" data-level="9.1.1" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#specifying-interactions-in-r"><i class="fa fa-check"></i><b>9.1.1</b> Specifying interactions in R</a></li>
<li class="chapter" data-level="9.1.2" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#simulating-data"><i class="fa fa-check"></i><b>9.1.2</b> Simulating data</a></li>
<li class="chapter" data-level="9.1.3" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#visualising-interactions"><i class="fa fa-check"></i><b>9.1.3</b> Visualising interactions</a></li>
<li class="chapter" data-level="9.1.4" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#modelling-interactions"><i class="fa fa-check"></i><b>9.1.4</b> Modelling interactions</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#generalised-linear-model-glm"><i class="fa fa-check"></i><b>9.2</b> General<strong>ised</strong> Linear Model (GLM)</a><ul>
<li class="chapter" data-level="9.2.1" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#log-odds-and-predicted-probabilities"><i class="fa fa-check"></i><b>9.2.1</b> Log-odds and predicted probabilities</a></li>
<li class="chapter" data-level="9.2.2" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#predicted-vs-observed"><i class="fa fa-check"></i><b>9.2.2</b> Predicted vs Observed</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="lab-9-interactions-and-glm.html"><a href="lab-9-interactions-and-glm.html#your-turn-less-guidance"><i class="fa fa-check"></i><b>9.3</b> Your turn (Less guidance)</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="lab-10.html"><a href="lab-10.html"><i class="fa fa-check"></i><b>10</b> Lab 10</a><ul>
<li class="chapter" data-level="10.1" data-path="lab-10.html"><a href="lab-10.html#apply-functions"><i class="fa fa-check"></i><b>10.1</b> <code>apply</code> functions</a></li>
<li class="chapter" data-level="10.2" data-path="lab-10.html"><a href="lab-10.html#lab-10-1"><i class="fa fa-check"></i><b>10.2</b> Lab 10</a><ul>
<li class="chapter" data-level="10.2.1" data-path="lab-10.html"><a href="lab-10.html#the-task"><i class="fa fa-check"></i><b>10.2.1</b> The Task</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Univariate Statistics and Methodology using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="lab-5" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Lab 5</h1>
<div id="finally-stats" class="section level2">
<h2><span class="header-section-number">5.1</span> Finally stats</h2>
<p>Welcome to lab 5! Today, we will dip our toes in the wonderful world of statistical analysis. We’ll use <code>R</code> to gain some experience analysing data.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>You know what’s coming, don’t you? That’s right, create a new <code>R</code> project.</p>
<p><strong>TIP: </strong>You <em>really</em> want to work from both the script and the console here. Any commands that <em>modify the data</em> or create plots and output analysis <em>that you want to have access to</em> belong in the script. Any other commands (one-off stuff) should be left for the console.</p>
<div id="data-set" class="section level3">
<h3><span class="header-section-number">5.1.1</span> Data set</h3>
<p>Big brother has been collecting some data on you. Go on LEARN, fetch the ‘Lab5_data.csv’ file in the Week 5 folder and save it into your project directory.</p>
<p>Here is the code book for the data set</p>
<ul>
<li><code>id</code>: categorical; student ID number</li>
<li><code>lab</code>: categorical with 2 levels (<code>&quot;Thursday&quot;</code>, <code>&quot;Friday&quot;</code>); student’s lab group</li>
<li><code>programme</code>: categorical with 3 levels (<code>1</code> = <code>&quot;Psychology&quot;</code>, <code>2</code> = <code>&quot;Linguistics&quot;</code>, <code>3</code> = <code>&quot;CogScience&quot;</code>); programme of study</li>
<li><code>lab_time</code>: numeric, integer; average time in minutes spent on the lab sheets across last 4 labs</li>
<li><code>tasks3</code>: numeric, integer; number of tasks completed in lab 3, maximum 18</li>
<li><code>tasks4</code>: numeric, integer; number of tasks completed in lab 4, maximum 18</li>
</ul>
</div>
<div id="read-in-and-clean-data" class="section level3">
<h3><span class="header-section-number">5.1.2</span> Read in and clean data</h3>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Read the data into <code>R</code>. Use the <code>read.csv()</code> function to save the data set into an object called <code>data</code>. <strong>Hint. </strong>If you save the file somewhere else than your project directory, you will have to specify the path to it so that <code>R</code> knows where to find it.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">data &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/Lab5_data.csv&quot;</span>)</code></pre></div>
<p> </p>
<p>As a first step in analysis, you need to familiarise yourself with the data. looking at the first few rows is a good way of doing this.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Use the <code>head()</code> function to see the first few rows of <code>data</code>.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">head</span>(data)</code></pre></div>
<pre><code>##   V_1      V_2 V_3 V_4 V_5 V_6
## 1   1 Thursday   1 100  10  12
## 2   2   Friday   3  NA  NA  NA
## 3   3 Thursday   1  NA  NA   4
## 4   4   Friday   2 115  11  13
## 5   5   Friday   2 104   6  12
## 6   6   Friday   3  75   5   2</code></pre>
<p> </p>
<p>OK, you can probably see that the data set isn’t quite ready for analysis. This is often the case with real data. You might get your hands on all sorts of data sets collected by people with varying degrees of methodological prowess. Getting data into shape for analysis can be a time-consuming and frustrating process and the ability to do it is a crucial skill.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Look, the data set doesn’t have proper variable names, just some <code>V</code> labels. Let’s remedy this. Name the columns according to the code book. <strong>Hint. </strong>The <code>names()</code> function will be handy here</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">names</span>(data) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;id&quot;</span>, <span class="st">&quot;lab&quot;</span>, <span class="st">&quot;programme&quot;</span>, <span class="st">&quot;lab_time&quot;</span>, <span class="st">&quot;task3&quot;</span>, <span class="st">&quot;task4&quot;</span>)</code></pre></div>
<p> </p>
<p>Now that our variables have informative names, let’s look at some descriptive statistics. This is a quick way of spotting obvious errors in the data set.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Use the <code>describe()</code> function from package <code>psych</code> to cast a first glance on your data. <strong>Hint. </strong>Don’t forget that to use functions from packages that are not pre-loaded at the start of the <code>R</code> session, you have to load them using <code>library()</code>.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">library</span>(psych)
<span class="kw">describe</span>(data)</code></pre></div>
<pre><code>##           vars   n   mean    sd median trimmed   mad min  max range  skew
## id           1 167  84.00 48.35     84   84.00 62.27   1  167   166  0.00
## lab*         2 167   2.39  1.50      1    2.36  0.00   1    5     4  0.16
## programme    3 167   1.96  0.82      2    1.95  1.48   1    3     2  0.08
## lab_time     4 155 103.79 90.92    100   98.71 14.83 -78 1200  1278 11.24
## task3        5 157   6.32  3.89      6    6.00  4.45   1   21    20  0.84
## task4        6 166   7.83  3.59      8    7.93  3.71  -2   16    18 -0.21
##           kurtosis   se
## id           -1.22 3.74
## lab*         -1.96 0.12
## programme    -1.53 0.06
## lab_time    133.42 7.30
## task3         0.67 0.31
## task4        -0.30 0.28</code></pre>
<p> </p>
<p>This should be raising some red flags! Check out the minima and maxima of the variables. Is this what you’d expect based on what the code book says? No, I didn’t think so… :)</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>What class is <code>id</code>? It’s a categorical variable so let’s tell <code>R</code> to treat is as such. <strong>Hint. </strong>You want to turn it into a <code>factor</code>.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">data<span class="op">$</span>id &lt;-<span class="st"> </span><span class="kw">factor</span>(data<span class="op">$</span>id)</code></pre></div>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Can you spot what’s wrong with the <code>lab</code> variable? How many levels does it have? How many is it supposed to have? Can you fix it? Read on for a more step-by-step guide if you’re feeling a bit lost.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">table</span>(data<span class="op">$</span>lab) <span class="co"># we have some typos!</span></code></pre></div>
<pre><code>## 
##   Friday   Fryday Thrusday Thursday  Tuesday 
##       89        1        1       75        1</code></pre>
<p><strong>Hint. </strong><code>table()</code> is a useful function for categorical variables/factors. It let’s you know what different values there are in the data and what their frequencies are.</p>
<p> </p>
<p>You might have noticed that <code>lab</code> is already a <code>factor</code>. That is because the <code>read.csv()</code> function turns variables with character strings. You can easily change factors into character vectors using <code>as.character()</code> but, as a general rule, it might be worth reading data in the rawest possible format.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Can you figure out how to tell <code>read.csv()</code> not to turn strings into factors? <strong>Hint. </strong>Look up the help file for the function and read through the list of arguments it takes.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">read.csv</span>(..., <span class="dt">stringsAsFactors =</span> F)</code></pre></div>
<p> </p>
<p>The nice thing about the script (you have been using the script, haven’t you?) is that if you realise you should have done something slightly different earlier in the process of cleaning and analysing your data, you can just edit and re-run the code.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Edit the script code to read in the data without turning strings into factors and re-run the remainder of the code you’ve written thus far.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="co"># only these 3 lines are required</span>
data &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/Lab5_data.csv&quot;</span>, <span class="dt">stringsAsFactors =</span> F)
<span class="kw">names</span>(data) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;id&quot;</span>, <span class="st">&quot;lab&quot;</span>, <span class="st">&quot;programme&quot;</span>, <span class="st">&quot;lab_time&quot;</span>, <span class="st">&quot;task3&quot;</span>, <span class="st">&quot;task4&quot;</span>)
data<span class="op">$</span>id &lt;-<span class="st"> </span><span class="kw">factor</span>(data<span class="op">$</span>id)</code></pre></div>
<p> </p>
<p>Now that’s done, you can do something about the <code>lab</code> variable.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Change the inappropriate values of <code>lab</code>. <strong>Hint. </strong>This is where logical subsetting comes in handy so good thing you spilled so much sweat over it!</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="co"># only these 3 lines are required</span>
data<span class="op">$</span>lab[data<span class="op">$</span>lab <span class="op">==</span><span class="st"> &quot;Thrusday&quot;</span>] &lt;-<span class="st"> &quot;Thursday&quot;</span>
data<span class="op">$</span>lab[data<span class="op">$</span>lab <span class="op">==</span><span class="st"> &quot;Fryday&quot;</span>] &lt;-<span class="st"> &quot;Friday&quot;</span>
data<span class="op">$</span>lab[data<span class="op">$</span>lab <span class="op">==</span><span class="st"> &quot;Tuesday&quot;</span>] &lt;-<span class="st"> </span><span class="ot">NA</span> <span class="co"># I think it&#39;s best to get rid of this one</span></code></pre></div>
<p><em>Want more hints?</em> To refresh your memory, something like <code>data$variable[data$variable == &quot;value&quot;] &lt;- &quot;different value&quot;</code> does the trick.</p>
<p> </p>
<div class="noteBox">
<title>
Analytical decisions
</title>
<p>You will have noticed that one of the weird values in <code>data$lab</code> is not really a typo. What to do about it is sort of your call. You might argue that it <em>is</em> a typo and change it to the value it resembles. However, it is possible that the data is self-reported, in which case you might legitimately ask if including data from some space cadet who doesn’t know what day it is is useful. I would probably exclude this person’s entry for the <code>lab</code> variable (by replacing it with <code>NA</code>). <strong>I would not recommend ever deleting entire rows from your data frames.</strong></p>
</div>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Good, now you can change the variable into a <code>factor</code>.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">data<span class="op">$</span>lab &lt;-<span class="st"> </span><span class="kw">factor</span>(data<span class="op">$</span>lab)</code></pre></div>
<p> </p>
<p>So that’s <code>lab</code> sorted. Let’s move on to <code>programme</code>. As you can see, it only has numeric values. It is also not a <code>factor</code>. It would be good to do something about this, don’t you think?</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>First things first though! Have a closer look at the variable. Does it look fine?</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>If you’re happy with it, tell <code>R</code> it’s a factor with labels as per the code book. <strong>Hint. </strong>There are several ways to do this. For instance, you can use the <code>factor(..., labels = ...)</code> approach, or opt for the <code>recode()</code> function from package <code>car</code>.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">data<span class="op">$</span>programme &lt;-<span class="st"> </span><span class="kw">factor</span>(data<span class="op">$</span>programme, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Psychology&quot;</span>, <span class="st">&quot;Linguistics&quot;</span>, <span class="st">&quot;CogScience&quot;</span>))</code></pre></div>
<p> </p>
<p>Grand! Moving on to <code>lab_time</code>. Definitely something fishy going on here. Can you spot what it is?</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Fix the <code>lab_time</code> so that it conforms to the criteria in the code book. <strong>Hint. </strong>There are 3 problems with the values: there are impossible ones, improbable ones, and the format of the numbers suggests that there are also non-integer ones. Dealing with the third issue is going to be a bit of a puzzle.</p>
</div>
<div id="impossible-values" class="section level3">
<h3><span class="header-section-number">5.1.3</span> Impossible values</h3>
<p>It stands to reason that average time spent on the lab sheets should not be negative.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Get rid of the negative values by replacing them with <code>NA</code>s. <strong>Hint. </strong>again, logical subsetting is the way to go!</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">data<span class="op">$</span>lab_time[data<span class="op">$</span>lab_time <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></code></pre></div>
<p> </p>
</div>
<div id="improbable-values" class="section level3">
<h3><span class="header-section-number">5.1.4</span> Improbable values</h3>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Have a look at the distribution of <code>lab_time</code>. Use a histogram or a box plot to visualise it.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">boxplot</span>(data<span class="op">$</span>lab_time)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-199-1.png" width="672" /></p>
<p>You should hopefully see that there’s an improbably large value in the variable.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Choose a safe cut-off point and use it to remove the offending data point.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">data<span class="op">$</span>lab_time[data<span class="op">$</span>lab_time <span class="op">&gt;</span><span class="st"> </span><span class="dv">200</span>] &lt;-<span class="st"> </span><span class="ot">NA</span> <span class="co"># only one point larger than 200</span></code></pre></div>
<p> </p>
<div class="noteBox">
<title>
Analytical decisions
</title>
<p>Should we have really removed the poor person who spends on average 20 hours on a lab sheet? Is it a typo? Probably… But what if not? Well, if not then, first of all, I sincerely apologise to this, brave, tenacious hero! That said, they are probably quite an extreme outlier. I think it’s safe to remove this value, what do you think?</p>
</div>
</div>
<div id="non-integer-values" class="section level3">
<h3><span class="header-section-number">5.1.5</span> Non-integer values</h3>
<p>Have a look at this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(data<span class="op">$</span>lab_time)</code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(data<span class="op">$</span>task3)</code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<p>You see that <code>task3</code> is a vector of integers, just like we’d expect it to be. <code>lab_time</code>, however, is not. The only reason for that is that <em>at least one</em> of the values of <code>lab_time</code> is a decimal number and so the entire vector must be decimal. Since the code book above tells us that <code>lab_time</code> is supposed to be an integer, any decimal values must be typos. To get rid of them, we first need to identify them</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>How can we programmatically spot non-integers?</p>
<p> </p>
<p>Well, non-integers will – by definition – not be divisible by 1 without a remainder. That means that if we can somehow ask <code>R</code> to give us the remainder of division by 1, any numbers that are not zero will identify non-integers.</p>
<p>As luck would have it, the mathematical operation we are looking for is called <em>modulo</em> and is implemented in <code>R</code> as the <code>%%</code> operator:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="fl">32.452</span> <span class="op">%%</span><span class="st"> </span><span class="dv">1</span></code></pre></div>
<pre><code>## [1] 0.452</code></pre>
<p>Putting it all together, <code>lab_time</code> modulo 1 should be 0. If it’s not, we should get rid of the value.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Use <code>%% 1</code> and logical subsetting to get rid of non-integer values.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">data<span class="op">$</span>lab_time[data<span class="op">$</span>lab_time <span class="op">%%</span><span class="st"> </span><span class="dv">1</span> <span class="op">!=</span><span class="st"> </span><span class="dv">0</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></code></pre></div>
<p> </p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>If we want, we can now safely turn <code>lab_time</code> into integer. <strong>Hint. </strong><code>as.integer()</code>.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">data<span class="op">$</span>lab_time &lt;-<span class="st"> </span><span class="kw">as.integer</span>(data<span class="op">$</span>lab_time)</code></pre></div>
<p> </p>
<p>Two more variables to go. These are fairly straight-forward so I’ll let you deal with them unaided. Just apply the same reasoning and principles as we did above.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Clean the <code>tasks3</code> and <code>tasks4</code> variables so that they conform to the code book rules.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">data<span class="op">$</span>task3[data<span class="op">$</span>task3 <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span> <span class="op">|</span><span class="st"> </span>data<span class="op">$</span>task3 <span class="op">&gt;</span><span class="st"> </span><span class="dv">18</span>] &lt;-<span class="st"> </span><span class="ot">NA</span>
data<span class="op">$</span>task4[data<span class="op">$</span>task4 <span class="op">&lt;</span><span class="st"> </span><span class="dv">0</span> <span class="op">|</span><span class="st"> </span>data<span class="op">$</span>task4 <span class="op">&gt;</span><span class="st"> </span><span class="dv">18</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></code></pre></div>
<p> </p>
<p>I think this is us, we have ourselves some nice and clean data. If you’ve done everything with me, you should see this output if you ask for <code>describe(data)</code> again:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">describe</span>(data)</code></pre></div>
<pre><code>##            vars   n  mean    sd median trimmed   mad min max range  skew
## id*           1 167 84.00 48.35     84   84.00 62.27   1 167   166  0.00
## lab*          2 166  1.46  0.50      1    1.45  0.00   1   2     1  0.17
## programme*    3 167  1.96  0.82      2    1.95  1.48   1   3     2  0.08
## lab_time      4 152 98.45 12.44    100   98.91 14.83  73 119    46 -0.27
## task3         5 155  6.15  3.59      6    5.91  4.45   1  15    14  0.50
## task4         6 163  7.99  3.40      8    8.04  2.97   1  16    15 -0.04
##            kurtosis   se
## id*           -1.22 3.74
## lab*          -1.98 0.04
## programme*    -1.53 0.06
## lab_time      -0.98 1.01
## task3         -0.58 0.29
## task4         -0.56 0.27</code></pre>
<p>The take-home message is that, in order to produce sensible analyses, you must make sure you work with sensible data. Cleaning data requires a great deal of attention to detail, thinking, and, well, coding. Having done that, we can move on to finding out about the world…</p>
</div>
</div>
<div id="lets-stats" class="section level2">
<h2><span class="header-section-number">5.2</span> Let’s stats!</h2>
<p>In this section, we will ask and answer questions about our variables and relationships between them. What I’d like you to do is to run at least one test “by hand”, <em>i.e.,</em> without using a built-in <code>R</code> function. Doing this will help you understand the basic principle common to all statistical tests we will cover on this course.</p>
<div id="categorical-variables-1" class="section level3">
<h3><span class="header-section-number">5.2.1</span> Categorical variables</h3>
<p>Let’s have a look at <code>lab</code> again. This time, we want to know if the number of students attending the Thursday lab is the same as the number attending the Friday lab. In other words,</p>
<p><span class="math display">\[H_0: P(Thursday) = P(Friday)\]</span></p>
<p>To test this null hypothesis, let’s first simply look at the frequency table.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Ask <code>R</code> to dive you a table of the <code>lab</code> variable. Save this table into an object called <code>lab_table</code> since it will come in handy later. Once that’s done, look at it in the console.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">lab_table &lt;-<span class="st"> </span><span class="kw">table</span>(data<span class="op">$</span>lab)
lab_table</code></pre></div>
<pre><code>## 
##   Friday Thursday 
##       90       76</code></pre>
<p> </p>
<p>If you want, you can visualise this distribution in a plot, such as this one:</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">barplot</span>(lab_table)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-208-1.png" width="672" /></p>
<p>We can test our hypothesis using a Chi-square test (specifically a goodness-of-fit test). In other words, we want to see if the distribution of <code>lab</code> is significantly different from uniform. To do that, we first need to know what frequencies we expect under a uniform distribution.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Create an object <code>exp</code> with the expected frequencies. Try doing this programmatically rather than manually typing in the numbers. <strong>Hint. </strong>The expected frequency of each category is half of all the observations.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">exp &lt;-<span class="st"> </span><span class="kw">rep</span>(<span class="kw">sum</span>(lab_table)<span class="op">/</span><span class="dv">2</span>, <span class="dv">2</span>)
exp</code></pre></div>
<pre><code>## [1] 83 83</code></pre>
<p> </p>
<p>Now we want a measure of just how much our observed distribution deviates from the expected one. Squares of differences are a good measure (if we just took differences they would cancel each other out), however, a difference of 1 if the expected value is 100 isn’t the same as a difference of 1 if the expected value is 10. So to get a more proportional measure, let’s scale the squared differences between the observed and expected counts by the expected counts (<span class="math inline">\((obs - exp)^2/exp\)</span>)</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Do this in <code>R</code>! Create an object <code>sq_scaled</code> that includes these scaled squared differences</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">sq_scaled &lt;-<span class="st"> </span>(lab_table <span class="op">-</span><span class="st"> </span>exp)<span class="op">^</span><span class="dv">2</span><span class="op">/</span>exp
sq_scaled</code></pre></div>
<pre><code>## 
##    Friday  Thursday 
## 0.5903614 0.5903614</code></pre>
<p>We still have as many numbers as we have categories. To get a single measure of the departure from expectation, let’s just add the numbers up. Since this is our test statistic, let’s call it <code>chi_sq</code>.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Calculate the <code>chi_sq</code> statistic.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">chi_sq &lt;-<span class="st"> </span><span class="kw">sum</span>(sq_scaled)
chi_sq</code></pre></div>
<pre><code>## [1] 1.180723</code></pre>
<p> </p>
<p>We know that this test statistic follows the <span class="math inline">\(\chi^2\)</span>-distribution. We also know that this distribution changes shape depending on the number of degrees of freedom. So our test statistic will have a different associated <em>p</em>-value under each of these distributions:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pchisq</span>(chi_sq, <span class="dv">3</span>, <span class="dt">lower.tail =</span> F)</code></pre></div>
<pre><code>## [1] 0.7576314</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pchisq</span>(chi_sq, <span class="dv">8</span>, <span class="dt">lower.tail =</span> F)</code></pre></div>
<pre><code>## [1] 0.9968287</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pchisq</span>(chi_sq, <span class="dv">147</span>, <span class="dt">lower.tail =</span> F)</code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>Let’s calculate the degrees of freedom. If you know what the marginal value is, <em>i.e.,</em> how many people are there altogether, how many entries in <code>lab_table</code> are free to vary?</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>OK, now that we have the number of <em>df</em>s figured out, let’s get the <em>p</em>-value associated with our observed <code>chi_sq</code>!</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">p &lt;-<span class="st"> </span><span class="kw">pchisq</span>(chi_sq, <span class="dv">1</span>, <span class="dt">lower.tail =</span> F)
p</code></pre></div>
<pre><code>## [1] 0.2772089</code></pre>
<p> </p>
<p>As a sanity check, we can run the test using <code>R</code>’s <code>chisq.test()</code> function. If you pull up its documentation, you’ll see that for a Chi-square test such as this one, it requires a table as the only argument.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Run the test using the <code>R</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">chisq.test</span>(lab_table)</code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  lab_table
## X-squared = 1.1807, df = 1, p-value = 0.2772</code></pre>
<p> </p>
<p>Hopefully, you will have got the same results from the by-hand calculation.</p>
<div class="noteBox">
<p>A Chi-square test showed that the distribution of lab group attendance did not significantly depart from uniform, <span class="math inline">\(\chi^2(1) = 1.18,\ p=.277\)</span>.</p>
</div>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Perform a Chi-square test on the distribution of <code>programme</code> separately for the Thursday and Friday labs. The null hypothesis assumes that both are uniform. Write up the results.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">chisq.test</span>(<span class="kw">table</span>(data<span class="op">$</span>programme[data<span class="op">$</span>lab <span class="op">==</span><span class="st"> &quot;Thursday&quot;</span>]))</code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  table(data$programme[data$lab == &quot;Thursday&quot;])
## X-squared = 9.0263, df = 2, p-value = 0.01096</code></pre>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">chisq.test</span>(<span class="kw">table</span>(data<span class="op">$</span>programme[data<span class="op">$</span>lab <span class="op">==</span><span class="st"> &quot;Friday&quot;</span>]))</code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  table(data$programme[data$lab == &quot;Friday&quot;])
## X-squared = 2.8667, df = 2, p-value = 0.2385</code></pre>
<div class="solutiontext" style="display:block">
<p>A Chi-square test showed that the distribution of lab group attendance was significantly different from uniform in the Thursday group (<span class="math inline">\(\chi^2(2) = 9.03,\ p=.011\)</span>) but not the Friday group (<span class="math inline">\(\chi^2(2) = 2.87,\ p=.239\)</span>).</p>
</div>
<p><strong>This is the kind of multiple testing that inflates Type I error, so don’t do it in practice! :)</strong></p>
<p>Instead, let’s see if there is a relationship between the day on which the lab takes place and who attends it.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>First, create a contingency table <code>cont</code>, cross-tabulating <code>lab</code> and <code>programme</code>. You can do this in several ways but two of the more convenient ones are using <code>table()</code> or <code>xtabs()</code>. The latter produces a table that looks like this:</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">cont &lt;-<span class="st"> </span><span class="kw">xtabs</span>(<span class="op">~</span><span class="st"> </span>lab <span class="op">+</span><span class="st"> </span>programme, data)
cont</code></pre></div>
<pre><code>##           programme
## lab        Psychology Linguistics CogScience
##   Friday           23          31         36
##   Thursday         37          23         16</code></pre>
<p> </p>
<p>Above, we used a Chi-square goodness-of-fit test to see how well a uniform distribution fit our data. We can also use a Chi-square test to compare two (or more) observed distributions in a Chi-square test of independance.</p>
<p>To perform a Chi-square test, we need the observed counts, the expected counts and the degrees of freedom. We just got the first one in our contingency table. The latter two can be derived using observed and marginal counts. <strong>Marginal</strong> counts are called marginal because they are the row and column sums of the contingency table and are, thus, in its margins.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Add margins to <code>cont</code>. There is a function that does that. <strong>Hint. </strong>If you don’t know its name, maybe try asking the internet how to add margins to a table in <code>R</code>.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">addmargins</span>(cont)</code></pre></div>
<pre><code>##           programme
## lab        Psychology Linguistics CogScience Sum
##   Friday           23          31         36  90
##   Thursday         37          23         16  76
##   Sum              60          54         52 166</code></pre>
<p> </p>
<p>If you want, you can calculate the expected counts by hand. However, what I’d like you to do is figure out how many degrees of freedom there are in this table. If the marginal counts are fixed, how many independent values do you need to know before you know what the others are?</p>
<p>Start by fixing the number of the cell <code>[1, 1]</code> to some number. Does that tell you anything about some other values in other cells, given that the marginal counts are fixed? Fix another one, say <code>[1, 2]</code>, what about now? Carry on in the same vein until you can solve the table. In a way, it’s a bit like sudoku. In fact, a sudoku with only one solution is basically a table with 0 degrees of freedom!</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>How many <em>df</em>s do we have?</p>
<p> </p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="co"># you can solve the table once you know 2 values:</span></code></pre></div>
<pre><code>##           programme
## lab        Psychology Linguistics CogScience Sum
##   Friday   23         31                     90 
##   Thursday                                   76 
##   Sum      60         54          52         166</code></pre>
<p>Great! Now, you should understand why the formula for <em>df</em> for Chi-square tests is what it is (<span class="math inline">\((r-1)(c-1)\)</span> where r is the number of rows and c is the number of columns).</p>
<p>Let’s run the test itself! There are, yet again, several ways of telling the <code>chisq.test()</code> function that you want to perform the test of independence. You can give it a contingency table (without marginal counts!) or two variables. Consult the function documentations (<code>?chisq.test</code>) for examples and details.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Run the Chi-square test of independence to see if the day of the lab is related to the distribution of programme. Write up the results.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">chisq.test</span>(data<span class="op">$</span>lab, data<span class="op">$</span>programme)</code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  data$lab and data$programme
## X-squared = 11.042, df = 2, p-value = 0.004002</code></pre>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="co"># equivalent ways</span>
<span class="co"># chisq.test(table(data$lab, data$programme))</span>
<span class="co"># chisq.test(xtabs(~ lab + programme, data))</span></code></pre></div>
<div class="solutiontext" style="display:block">
<p>According to a Chi-square test of independence, there was a relationship between the day of the lab and the distribution of attending students with respect to study programme, <span class="math inline">\(\chi^2(2) = 11.04,\ p=.004\)</span>.</p>
</div>
<p><strong>Have a think: </strong>Was the test we used appropriate for the kind of data we had? In other words, were the assumptions of the test met?</p>
<div class="solutiontext" style="display:block">
<p>Yes, the variables are both categorical, with expected cell counts of <span class="math inline">\(&gt; 5\)</span>, and the observations are random and independent.</p>
</div>
</div>
<div id="analysing-continuous-data" class="section level3">
<h3><span class="header-section-number">5.2.2</span> Analysing continuous data</h3>
<div id="known-sigma" class="section level4">
<h4><span class="header-section-number">5.2.2.1</span> Known <span class="math inline">\(\sigma\)</span></h4>
<p>Let’s look at the average time spent on a lab sheet. What if I told you, that – as far as undergraduate psychology students are concerned – the mean time spent on these kinds of labs sheets is 103.7 minutes with the population std. deviation <span class="math inline">\(\sigma = 14.6\)</span>? Could you use this knowledge to test whether USMR students are a random sample from the psych undergrad population or not?</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Try testing the null hypothesis using a 2-tailed <em>z</em>-test. Do it “by hand” (there’s no built-in <code>R</code> function for the <em>z</em>-test anyway). Remember, all you’re doing is calculating the <em>z</em>-statistic and getting the <em>p</em>-value of this <strong>or more extreme</strong> statistic under the standard normal distribution.</p>
<p><strong>Hint: </strong>The formula for the <em>z</em>-test is <span class="math inline">\(z = \frac{\bar{x} - \mu}{SE}\)</span>, with <span class="math inline">\(SE = \frac{\sigma}{\sqrt{n}}\)</span>. The function you need to get the <em>p</em>-value is <code>pnorm()</code>. Think about which tail of the normal distribution you’re interested in and how to get the 2-tailed <em>p</em>-value.</p>
<div class="noteBox">
<h5 id="warning"><span class="header-section-number">5.2.2.1</span> Warning</h5>
<p>Watch out for missing values!</p>
</div>
<p>These are the results you should have got:</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">mu &lt;-<span class="st"> </span><span class="fl">103.7</span>
sigma &lt;-<span class="st"> </span><span class="fl">14.6</span>
n &lt;-<span class="st"> </span><span class="kw">length</span>(<span class="kw">na.omit</span>(data<span class="op">$</span>lab_time))
z &lt;-<span class="st"> </span>(<span class="kw">mean</span>(data<span class="op">$</span>lab_time, <span class="dt">na.rm =</span> T) <span class="op">-</span><span class="st"> </span>mu) <span class="op">/</span>
<span class="st">  </span><span class="kw">sqrt</span>(sigma<span class="op">^</span><span class="dv">2</span><span class="op">/</span>n)
p &lt;-<span class="st"> </span><span class="kw">round</span>(<span class="kw">pnorm</span>(<span class="kw">abs</span>(z), <span class="dt">lower.tail =</span> F) <span class="op">*</span><span class="st"> </span><span class="dv">2</span>, <span class="dv">7</span>)
z &lt;-<span class="st"> </span><span class="kw">round</span>(z, <span class="dv">3</span>)
<span class="kw">paste</span>(<span class="st">&quot;z =&quot;</span>, z)</code></pre></div>
<pre><code>## [1] &quot;z = -4.43&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">paste</span>(<span class="st">&quot;p =&quot;</span>, p)</code></pre></div>
<pre><code>## [1] &quot;p = 9.4e-06&quot;</code></pre>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Write up the results of the <em>z</em>-test.</p>
<div class="solutiontext" style="display:block">
<p>The mean time spent on lab sheets in the sample of USMR students was significantly less than in the population of Psychology undergraduates, <span class="math inline">\(z=-4.43,\ p&lt;10^{-5}\)</span>.</p>
</div>
</div>
<div id="unknown-sigma" class="section level4">
<h4><span class="header-section-number">5.2.2.2</span> Unknown <span class="math inline">\(\sigma\)</span></h4>
<p>As you know, the <em>z</em>-test required the population variance to be known and so I told you what it is so that you could run the test. Let’s try a more realistic scenario, where we don’t know <span class="math inline">\(\sigma^2\)</span>. Let’s keep the hull hypothesis the same tough, <span class="math inline">\(H_0: \mu = 103.7\)</span>.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Run the one-sample <em>t</em>-test on the same variable and write up the results. Take note of the similarities and differences between the results of the <em>z</em>- and the <em>t</em>-test. <strong>Hint. </strong>By default, the test assumes that <span class="math inline">\(\mu = 0\)</span>. The documentation to the <code>t.test()</code> function will help you find out how to change this value.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">t.test</span>(data<span class="op">$</span>lab_time, <span class="dt">mu =</span> mu)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  data$lab_time
## t = -5.2003, df = 151, p-value = 6.375e-07
## alternative hypothesis: true mean is not equal to 103.7
## 95 percent confidence interval:
##   96.46076 100.44713
## sample estimates:
## mean of x 
##  98.45395</code></pre>
<div class="solutiontext" style="display:block">
<p>A one-sample <em>t</em>-test revealed a significant difference in time spent on lab sheets between USMR students (<em>Mean</em> = 98.45, 95% CI [96.46, 100.45]) and the population of Psychology undergraduates, <span class="math inline">\(t(151)=-5.2,\ p&lt;10^{-6}\)</span>.</p>
</div>
<p>The result of the <em>t</em>-test should be very close to that of the <em>z</em>-test. However, the smaller the sample size, the larger the effect of random statistical fluctuations.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Re-run the <em>t</em>-test on a random sample of 20 elements of <code>lab_time</code> to see that sometimes size really does matter!</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">t.test</span>(data<span class="op">$</span>lab_time[<span class="kw">sample</span>(n, <span class="dv">20</span>)], <span class="dt">mu =</span> mu)</code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  data$lab_time[sample(n, 20)]
## t = -0.64608, df = 16, p-value = 0.5274
## alternative hypothesis: true mean is not equal to 103.7
## 95 percent confidence interval:
##   95.66647 107.98059
## sample estimates:
## mean of x 
##  101.8235</code></pre>
<p> </p>
</div>
</div>
<div id="more-analysis" class="section level3">
<h3><span class="header-section-number">5.2.3</span> More analysis!</h3>
<p>Thinking about it, it doesn’t seem to me like we’ve explored <code>lab_time</code> enough yet. Let’s see what else hides within! To encourage some healthy rivalry (for when has that gone wrong?!), let’s compare the Thursday and the Friday folks to see who’s fastest with the lab sheets.</p>
<p>We can assume, that people attend either one or the other group.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Write down the null hypothesis. <strong>Hint. </strong>We are looking at differences in means of average time spent on lab sheets in the two groups.</p>
<div class="solutiontext style=" display:block"="">
<p><span class="math inline">\(H_0: \mu_{Thursday} = \mu_{Frisday}\)</span></p>
</div>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>OK, let’s test the null with a Welch’s <em>t</em>-test. That’s the one <code>R</code> does by default when you ask it to perform a <em>t</em>-test on independent data. Write up the results. <strong>Hint. </strong>The function documentation should help you find out how to specify the test formula. If it doesn’t, ask the Internet.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">t.test</span>(lab_time <span class="op">~</span><span class="st"> </span>lab, data)</code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  lab_time by lab
## t = -4.5055, df = 143.12, p-value = 1.365e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -12.249376  -4.778753
## sample estimates:
##   mean in group Friday mean in group Thursday 
##               94.43038              102.94444</code></pre>
<div class="solutiontext" style="display:block">
<p>A Welch’s <em>t</em>-test showed that the time spent on lab sheets in the Thursday group was significantly longer than that in the Friday group, <em>Mean diff</em> = <span class="math inline">\(-8.51\)</span>, 95% CI [<span class="math inline">\(-12.25,\ -4.78\)</span>], <span class="math inline">\(t(143.12)=-4.51,\ p&lt;10^{-4}\)</span>.</p>
</div>
<p>Great! Finally, let’s see if there’s been a change in the number of tasks students are able to complete in the labs between week 3 and 4.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>What is the null hypothesis and which test is appropriate to test it?</p>
<div class="solutiontext" style="display:block">
<p><span class="math inline">\(H_0: \mu_{wk3} = \mu_{wk4}\)</span></p>
<p>The paired sample <em>t</em>-test is the one to pick as the observations are paired (and therefore not independent) – one observation per week from each student.</p>
</div>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Run the test and write up the results.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">t.test</span>(data<span class="op">$</span>task3, data<span class="op">$</span>task4, <span class="dt">paired =</span> T)</code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  data$task3 and data$task4
## t = -7.5341, df = 152, p-value = 4.097e-12
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.582219 -1.509284
## sample estimates:
## mean of the differences 
##               -2.045752</code></pre>
<div class="solutiontext" style="display:block">
<p>“The students spent on average less time on the lab sheet in week 4 compared to week 3, <em>Mean diff</em> = <span class="math inline">\(-2.05\)</span>, 95% CI [<span class="math inline">\(-2.58,\ -1.51\)</span>], <span class="math inline">\(t(152)=-7.53,\ p&lt;10^{-11}\)</span>.</p>
</div>
<p><strong>You can now do statistical analysis of several types of data. Very well done indeed!</strong></p>
<p> </p>
<hr />
</div>
<div id="extra-get-loopy" class="section level3">
<h3><span class="header-section-number">5.2.4</span> Extra: Get loopy</h3>
<p>It’s important to understand where <em>p</em>-values come from. Simulating the sampling distribution of the test statistic is the best way of getting your head around the concept. So let’s do that!</p>
<p>Given what the sampling distribution is, simulating it involves taking many samples from the population. Every time you encounter a repetitive task you should start thinking about how to delegate as much of the legwork as possible to the computer.</p>
<p>This is where loops come in very handy. They are used to repeat a block of code an arbitrary number of times. There are other ways of implementing this in <code>R</code>, you could try using the <code>replicate()</code> function instead.</p>
<p>Let’s look at the anatomy of a loop in <code>R</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span> (i <span class="cf">in</span> n) {
  <span class="co"># code</span>
}</code></pre></div>
<p>The <code>for () {}</code> bit is just syntax and its sole function is to tell <code>R</code> that this is a loop. The bit in <code>()</code> defines the iterator variable <code>i</code> and the vector <code>n</code> over which the loop iterates. So <code>for (i in 1:10)</code> will be a loop that runs through 10 times. First, it will assign <code>i</code> the value of 1 and run the rest of the code. Then, it will assign it the next value in the <code>n</code> vector, <em>e.g.,</em> 2 and run the code again. It will repeat until it runs out of elements of <code>n</code>.</p>
<p>To demonstrate:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">5</span>) {
  <span class="kw">print</span>(i)
}</code></pre></div>
<pre><code>## [1] 1
## [1] 2
## [1] 3
## [1] 4
## [1] 5</code></pre>
<p>As you can see, the loop printed the value of <code>i</code> for each of the 5 iterations.</p>
<p>The code in the body of the loop <code>{}</code> can do whatever you want. you can use the current value of <code>i</code> to create, modify, or subset data structures, to do calculations with it, or simply not use it at all. The world’s your oyster!</p>
<p>Finally, loops can be nested, if needed:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span> (i <span class="cf">in</span> n) {
  <span class="cf">for</span> (j <span class="cf">in</span> m) {
    <span class="co"># code</span>
  }
}</code></pre></div>
<p>This will run all the iterations of the inner loop for each iteration of the outer one.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Have a go at writing a loop that will print <code>data[1, 1]</code>, then <code>data[2, 2]</code>, then <code>data[3, 3]</code>, <em>etc.,</em> for as many times as there are columns of <code>data</code>. <strong>Hint. </strong><code>ncol()</code> is a good function to use to specify the vector over which to loop. The output should look like this:</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">ncol</span>(data)) {
  <span class="kw">print</span>(data[i, i])
}</code></pre></div>
<pre><code>## [1] 1
## 167 Levels: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 ... 167
## [1] Friday
## Levels: Friday Thursday
## [1] Psychology
## Levels: Psychology Linguistics CogScience
## [1] 115
## [1] 6
## [1] 2</code></pre>
<p>Now, often you will want to save the output of each iteration of the loop. There are again many ways to do this but a straight-forward one is to first create an empty object and then start combining it with the output of the loop:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">out &lt;-<span class="st"> </span><span class="kw">c</span>() <span class="co"># empty vector</span>
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10</span>) {
  <span class="co"># append the result of some operation to to the vector</span>
  out &lt;-<span class="st"> </span><span class="kw">c</span>(out, data<span class="op">$</span>lab_time[i <span class="op">*</span><span class="st"> </span><span class="dv">10</span>])
}
out</code></pre></div>
<pre><code>##  [1]  NA  93 114 102 107  81  94  88  NA  87</code></pre>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Combine the two tasks above and create a vector <code>out</code> that includes <code>data[1, 1]</code>, <code>data[2, 2]</code>, <code>data[3, 3]</code>, <em>etc</em>.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">out &lt;-<span class="st"> </span><span class="kw">c</span>()
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">ncol</span>(data)) {
  out &lt;-<span class="st"> </span><span class="kw">c</span>(out, data[i, i])
}
out</code></pre></div>
<pre><code>## [1]   1   1   1 115   6   2</code></pre>
<hr />
<p>Now that you have an inkling about how to use loops, let’s see if we can make use of them to simulate our sampling distribution</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>First, let’s create an empty vector that will store each estimate of out <em>t</em>-statistic. Call it <code>t_est</code>, why not!</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">t_est &lt;-<span class="st"> </span><span class="kw">c</span>()</code></pre></div>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Next, let’s write the core structure of a loop. Say we want the loop to run 10<sup>4</sup> times. Don’t worry about the code inside <code>{}</code> just yet.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10</span><span class="op">^</span><span class="dv">4</span>) {
  <span class="co"># code</span>
}</code></pre></div>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Now, inside of the loop, you want to sample the same number of observation as we have in our data from a normally distributed population with <span class="math inline">\(\mu=103.7\)</span> and <em>SD</em> of <code>sd(data$lab_time, na.rm = T)</code>. Save this sample into an object called <code>samp</code>.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10</span><span class="op">^</span><span class="dv">4</span>) {
  <span class="co"># I defined both n and mu earlier, you might not have!</span>
  samp &lt;-<span class="st"> </span><span class="kw">rnorm</span>(n, mu, <span class="kw">sd</span>(data<span class="op">$</span>lab_time, <span class="dt">na.rm =</span> T))
}</code></pre></div>
<p><strong>Tip: </strong> You want to make sure each of the constituent commands within the loop run on it own, otherwise the entire loop won’t run either. You can trial-run things in the console.</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Now, we want to get the <em>t</em>-statistic for this sample and add it to our for now empty <code>t_est</code> vector. You can calculate it by hand if you wish but maybe you can somehow extract it from <code>t.test()</code>? <strong>Hint: </strong><code>t.test()</code> returns a list of values. This list, just like any list, can be queried using <code>$</code>. The <em>Value</em> section of the function documentations will tell you the rest.</p>
<div class="noteBox">
<h4 id="t.test"><span class="header-section-number">5.2.4</span> <code>t.test()</code></h4>
<p>Don’t forget to specify the <code>mu =</code> parameter if you are using <code>t.test()</code>!</p>
</div>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10</span><span class="op">^</span><span class="dv">4</span>) {
  samp &lt;-<span class="st"> </span><span class="kw">rnorm</span>(n, mu, <span class="kw">sd</span>(data<span class="op">$</span>lab_time, <span class="dt">na.rm =</span> T))
  t_est &lt;-<span class="st"> </span><span class="kw">c</span>(t_est, <span class="kw">t.test</span>(samp, <span class="dt">mu =</span> mu)<span class="op">$</span>statistic)
}</code></pre></div>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>That’s it! You can run the loop now and sit back</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Let’s look at the histogram of <code>t_est</code>. To see it in a higher resolution, let’s ask for 50 breaks.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r"><span class="kw">hist</span>(t_est, <span class="dt">breaks =</span> <span class="dv">50</span>)</code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-236-1.png" width="672" /></p>
<p> </p>
<p>Beautiful, isn’t it?</p>
<p>OK, final stretch! We have successfully simulated the sampling distribution of the <em>t</em>-statistic <strong>under the null hypothesis</strong>. Let’s use it to get a <em>p</em>-value for our observed <em>t</em> (-5.2003)</p>
<div style="position: absolute;">
<img style="position:relative;left:-20px;width:15px" src="images/task.png"/>
</div>
<p><strong>Task: </strong>Calculate the 2-tailed <em>p</em>-value using our sampling distribution. Basically, you want to know what proportion of the individual <em>t</em> estimates in the distribution have values that are more extreme than the observed one.</p>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">### step by step
## observed t
t_val &lt;-<span class="st"> </span><span class="kw">t.test</span>(data<span class="op">$</span>lab_time, <span class="dt">mu =</span> mu)<span class="op">$</span>statistic
t_val</code></pre></div>
<pre><code>##         t 
## -5.200296</code></pre>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">## logical condition
<span class="co"># abs(t_est) to consider both tails of the distribution</span>
<span class="co"># abs(t) to allow for negative t</span>
<span class="co"># this will be a LONG vector of TRUEs and FALSEs</span>
cond &lt;-<span class="st"> </span><span class="kw">abs</span>(t_est) <span class="op">&gt;=</span><span class="st"> </span><span class="kw">abs</span>(t_val) 

## how many TRUEs are there?
<span class="kw">sum</span>(cond)</code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode"><pre class="sourceCode r solution"><code class="sourceCode r">## p-value is the proportion
<span class="kw">sum</span>(cond)<span class="op">/</span><span class="kw">length</span>(t_est)</code></pre></div>
<pre><code>## [1] 0</code></pre>
<p> </p>
<p>Since none of our simulated estimates met the condition – at least when I did it! –, the simulated <em>p</em>-value is 0. However, this is just an approximation. To say, that there’s zero chance that you would find this or a more extreme result if the null is true, is incorrect! We can safely say, that the <em>p</em>-value is very small, though.</p>
<p><strong>Nicely done!</strong> This should bring the principle of NHST home.</p>
<p> </p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="lab-4.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="lab-6.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
