<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 13 Testing hypotheses | Data Analysis for Psychology in R (dapR1) - Labs</title>
  <meta name="description" content="This is the page that contains the course labs materials" />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 13 Testing hypotheses | Data Analysis for Psychology in R (dapR1) - Labs" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the page that contains the course labs materials" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 13 Testing hypotheses | Data Analysis for Psychology in R (dapR1) - Labs" />
  
  <meta name="twitter:description" content="This is the page that contains the course labs materials" />
  

<meta name="author" content="Department of Psychology, University of Edinburgh" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="bootstrapping-and-confidence-intervals.html"/>
<link rel="next" href="chap-typeerror.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script>
  $(document).ready(function() {
    $head = $('#header');
    $head.prepend('<img style="padding-right:25%; margin-bottom:10px;" src="https://www.ed.ac.uk/sites/all/themes/uoe/assets/logo.png" width="770px" align="left">')
  });
</script>

<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}
}
</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">DAPR1</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview of the Course</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#the-team"><i class="fa fa-check"></i>The team</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-cheatsheets"><i class="fa fa-check"></i>R Cheatsheets</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-community"><i class="fa fa-check"></i>R Community</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="week-1.html"><a href="week-1.html"><i class="fa fa-check"></i><b>1</b> Week 1</a><ul>
<li class="chapter" data-level="1.1" data-path="week-1.html"><a href="week-1.html#introduction-to-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> Introduction to R and RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="week-1.html"><a href="week-1.html#install-the-recent-version-of-r-and-r-studio"><i class="fa fa-check"></i><b>1.2</b> Install the recent version of R and R Studio</a><ul>
<li class="chapter" data-level="1.2.1" data-path="week-1.html"><a href="week-1.html#first-step"><i class="fa fa-check"></i><b>1.2.1</b> First Step</a></li>
<li class="chapter" data-level="1.2.2" data-path="week-1.html"><a href="week-1.html#second-step"><i class="fa fa-check"></i><b>1.2.2</b> Second Step</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="week-1.html"><a href="week-1.html#getting-started-in-rstudio"><i class="fa fa-check"></i><b>1.3</b> Getting Started in RStudio</a></li>
<li class="chapter" data-level="1.4" data-path="week-1.html"><a href="week-1.html#r-as-an-interactive-environment"><i class="fa fa-check"></i><b>1.4</b> R as an interactive environment</a></li>
<li class="chapter" data-level="1.5" data-path="week-1.html"><a href="week-1.html#check-your-settings"><i class="fa fa-check"></i><b>1.5</b> Check your settings</a><ul>
<li class="chapter" data-level="1.5.1" data-path="week-1.html"><a href="week-1.html#disable-automatic-saving-of-your-workspace"><i class="fa fa-check"></i><b>1.5.1</b> Disable automatic saving of your workspace</a></li>
<li class="chapter" data-level="1.5.2" data-path="week-1.html"><a href="week-1.html#adjust-fontscolours-if-you-like"><i class="fa fa-check"></i><b>1.5.2</b> Adjust fonts/colours if you like</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="week-1.html"><a href="week-1.html#setting-up-your-working-directory"><i class="fa fa-check"></i><b>1.6</b> Setting Up Your Working Directory</a></li>
<li class="chapter" data-level="1.7" data-path="week-1.html"><a href="week-1.html#the-console"><i class="fa fa-check"></i><b>1.7</b> The Console</a></li>
<li class="chapter" data-level="1.8" data-path="week-1.html"><a href="week-1.html#spacing"><i class="fa fa-check"></i><b>1.8</b> Spacing</a></li>
<li class="chapter" data-level="1.9" data-path="week-1.html"><a href="week-1.html#typos"><i class="fa fa-check"></i><b>1.9</b> Typos</a></li>
<li class="chapter" data-level="1.10" data-path="week-1.html"><a href="week-1.html#unfinishe.-d"><i class="fa fa-check"></i><b>1.10</b> Unfinishe…. d</a></li>
<li class="chapter" data-level="1.11" data-path="week-1.html"><a href="week-1.html#basic-arithmetic"><i class="fa fa-check"></i><b>1.11</b> Basic Arithmetic</a></li>
<li class="chapter" data-level="1.12" data-path="week-1.html"><a href="week-1.html#using-functions-for-calculations"><i class="fa fa-check"></i><b>1.12</b> Using Functions for Calculations</a></li>
<li class="chapter" data-level="1.13" data-path="week-1.html"><a href="week-1.html#r-scripts"><i class="fa fa-check"></i><b>1.13</b> R Scripts</a></li>
<li class="chapter" data-level="1.14" data-path="week-1.html"><a href="week-1.html#short-example"><i class="fa fa-check"></i><b>1.14</b> Short Example</a></li>
<li class="chapter" data-level="1.15" data-path="week-1.html"><a href="week-1.html#naming-variables"><i class="fa fa-check"></i><b>1.15</b> Naming variables</a></li>
<li class="chapter" data-level="1.16" data-path="week-1.html"><a href="week-1.html#now-over-to-you"><i class="fa fa-check"></i><b>1.16</b> Now over to you</a><ul>
<li class="chapter" data-level="1.16.1" data-path="week-1.html"><a href="week-1.html#exercise-1"><i class="fa fa-check"></i><b>1.16.1</b> Exercise 1</a></li>
<li class="chapter" data-level="1.16.2" data-path="week-1.html"><a href="week-1.html#exercise-2"><i class="fa fa-check"></i><b>1.16.2</b> Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="1.17" data-path="week-1.html"><a href="week-1.html#solutions"><i class="fa fa-check"></i><b>1.17</b> Solutions</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="week-2.html"><a href="week-2.html"><i class="fa fa-check"></i><b>2</b> Week 2</a><ul>
<li class="chapter" data-level="2.1" data-path="week-2.html"><a href="week-2.html#introduction-to-rmarkdown"><i class="fa fa-check"></i><b>2.1</b> Introduction to RMarkdown</a></li>
<li class="chapter" data-level="2.2" data-path="week-2.html"><a href="week-2.html#what-is-r-markdown"><i class="fa fa-check"></i><b>2.2</b> What is R Markdown?</a></li>
<li class="chapter" data-level="2.3" data-path="week-2.html"><a href="week-2.html#getting-things-ready"><i class="fa fa-check"></i><b>2.3</b> Getting things ready</a></li>
<li class="chapter" data-level="2.4" data-path="week-2.html"><a href="week-2.html#r-markdown-basics"><i class="fa fa-check"></i><b>2.4</b> R Markdown basics</a></li>
<li class="chapter" data-level="2.5" data-path="week-2.html"><a href="week-2.html#headings"><i class="fa fa-check"></i><b>2.5</b> Headings</a></li>
<li class="chapter" data-level="2.6" data-path="week-2.html"><a href="week-2.html#text"><i class="fa fa-check"></i><b>2.6</b> Text</a></li>
<li class="chapter" data-level="2.7" data-path="week-2.html"><a href="week-2.html#tables"><i class="fa fa-check"></i><b>2.7</b> Tables</a></li>
<li class="chapter" data-level="2.8" data-path="week-2.html"><a href="week-2.html#lists"><i class="fa fa-check"></i><b>2.8</b> Lists</a><ul>
<li class="chapter" data-level="2.8.1" data-path="week-2.html"><a href="week-2.html#unordered"><i class="fa fa-check"></i><b>2.8.1</b> Unordered</a></li>
<li class="chapter" data-level="2.8.2" data-path="week-2.html"><a href="week-2.html#ordered"><i class="fa fa-check"></i><b>2.8.2</b> Ordered</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="week-2.html"><a href="week-2.html#rmd-documents"><i class="fa fa-check"></i><b>2.9</b> Rmd documents</a></li>
<li class="chapter" data-level="2.10" data-path="week-2.html"><a href="week-2.html#code-chunks"><i class="fa fa-check"></i><b>2.10</b> Code chunks</a></li>
<li class="chapter" data-level="2.11" data-path="week-2.html"><a href="week-2.html#common-code-chunks-options"><i class="fa fa-check"></i><b>2.11</b> Common Code Chunks Options</a></li>
<li class="chapter" data-level="2.12" data-path="week-2.html"><a href="week-2.html#including-images-or-links"><i class="fa fa-check"></i><b>2.12</b> Including images or links</a><ul>
<li class="chapter" data-level="2.12.1" data-path="week-2.html"><a href="week-2.html#adding-links"><i class="fa fa-check"></i><b>2.12.1</b> Adding links</a></li>
<li class="chapter" data-level="2.12.2" data-path="week-2.html"><a href="week-2.html#adding-figures-pictures"><i class="fa fa-check"></i><b>2.12.2</b> Adding figures &amp; pictures</a></li>
</ul></li>
<li class="chapter" data-level="2.13" data-path="week-2.html"><a href="week-2.html#generating-documents"><i class="fa fa-check"></i><b>2.13</b> Generating documents</a></li>
<li class="chapter" data-level="2.14" data-path="week-2.html"><a href="week-2.html#extra-opensave-files-on-rstudio-cloud-chrome-users"><i class="fa fa-check"></i><b>2.14</b> Extra: Open/Save files on Rstudio Cloud (Chrome users)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-3.html"><a href="week-3.html"><i class="fa fa-check"></i><b>3</b> Week 3</a><ul>
<li class="chapter" data-level="3.1" data-path="week-3.html"><a href="week-3.html#vectors-lists-data-frames-and-data-types"><i class="fa fa-check"></i><b>3.1</b> Vectors, lists, data frames and data types</a></li>
<li class="chapter" data-level="3.2" data-path="week-3.html"><a href="week-3.html#get-the-package-first"><i class="fa fa-check"></i><b>3.2</b> Get the package first</a></li>
<li class="chapter" data-level="3.3" data-path="week-3.html"><a href="week-3.html#numeric-data"><i class="fa fa-check"></i><b>3.3</b> Numeric Data</a></li>
<li class="chapter" data-level="3.4" data-path="week-3.html"><a href="week-3.html#textcharacter-data"><i class="fa fa-check"></i><b>3.4</b> Text/Character Data</a></li>
<li class="chapter" data-level="3.5" data-path="week-3.html"><a href="week-3.html#logical-data"><i class="fa fa-check"></i><b>3.5</b> Logical Data</a></li>
<li class="chapter" data-level="3.6" data-path="week-3.html"><a href="week-3.html#variable-classes"><i class="fa fa-check"></i><b>3.6</b> Variable Classes</a></li>
<li class="chapter" data-level="3.7" data-path="week-3.html"><a href="week-3.html#factors"><i class="fa fa-check"></i><b>3.7</b> Factors</a></li>
<li class="chapter" data-level="3.8" data-path="week-3.html"><a href="week-3.html#lists-1"><i class="fa fa-check"></i><b>3.8</b> Lists</a></li>
<li class="chapter" data-level="3.9" data-path="week-3.html"><a href="week-3.html#practice.rmd-solutions"><i class="fa fa-check"></i><b>3.9</b> Practice.Rmd Solutions</a><ul>
<li class="chapter" data-level="3.9.1" data-path="week-3.html"><a href="week-3.html#exercise-1-1"><i class="fa fa-check"></i><b>3.9.1</b> Exercise 1</a></li>
<li class="chapter" data-level="3.9.2" data-path="week-3.html"><a href="week-3.html#exercise-2-1"><i class="fa fa-check"></i><b>3.9.2</b> Exercise 2</a></li>
<li class="chapter" data-level="3.9.3" data-path="week-3.html"><a href="week-3.html#exercise-3"><i class="fa fa-check"></i><b>3.9.3</b> Exercise 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-4.html"><a href="week-4.html"><i class="fa fa-check"></i><b>4</b> Week 4</a><ul>
<li class="chapter" data-level="4.1" data-path="week-4.html"><a href="week-4.html#introduction-to-plots-geoms-ggplot"><i class="fa fa-check"></i><b>4.1</b> Introduction to plots &amp; geoms (ggplot)</a></li>
<li class="chapter" data-level="4.2" data-path="week-4.html"><a href="week-4.html#visualisations"><i class="fa fa-check"></i><b>4.2</b> Visualisations</a></li>
<li class="chapter" data-level="4.3" data-path="week-4.html"><a href="week-4.html#get-our-data-sorted"><i class="fa fa-check"></i><b>4.3</b> Get our data sorted</a></li>
<li class="chapter" data-level="4.4" data-path="week-4.html"><a href="week-4.html#numerical-data"><i class="fa fa-check"></i><b>4.4</b> Numerical data</a></li>
<li class="chapter" data-level="4.5" data-path="week-4.html"><a href="week-4.html#simple-one-variable-plot-using-ggplot"><i class="fa fa-check"></i><b>4.5</b> Simple one-variable plot using ggplot()</a><ul>
<li class="chapter" data-level="4.5.1" data-path="week-4.html"><a href="week-4.html#continuous-variable"><i class="fa fa-check"></i><b>4.5.1</b> Continuous variable</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="week-4.html"><a href="week-4.html#categorical-variables"><i class="fa fa-check"></i><b>4.6</b> Categorical variables</a></li>
<li class="chapter" data-level="4.7" data-path="week-4.html"><a href="week-4.html#continuous-variables-grouped-by-a-categorical-one"><i class="fa fa-check"></i><b>4.7</b> Continuous variables grouped by a categorical one</a></li>
<li class="chapter" data-level="4.8" data-path="week-4.html"><a href="week-4.html#even-more-advanced"><i class="fa fa-check"></i><b>4.8</b> Even more advanced</a></li>
<li class="chapter" data-level="4.9" data-path="week-4.html"><a href="week-4.html#practice.rmd-solutions-1"><i class="fa fa-check"></i><b>4.9</b> Practice.Rmd Solutions</a><ul>
<li class="chapter" data-level="4.9.1" data-path="week-4.html"><a href="week-4.html#exercise-1-2"><i class="fa fa-check"></i><b>4.9.1</b> Exercise 1</a></li>
<li class="chapter" data-level="4.9.2" data-path="week-4.html"><a href="week-4.html#exercise-2-2"><i class="fa fa-check"></i><b>4.9.2</b> Exercise 2</a></li>
<li class="chapter" data-level="4.9.3" data-path="week-4.html"><a href="week-4.html#exercise-3---advanced"><i class="fa fa-check"></i><b>4.9.3</b> Exercise 3 - Advanced</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-5.html"><a href="week-5.html"><i class="fa fa-check"></i><b>5</b> Week 5</a><ul>
<li class="chapter" data-level="5.1" data-path="week-5.html"><a href="week-5.html#central-tendency-and-variability"><i class="fa fa-check"></i><b>5.1</b> Central Tendency and Variability</a></li>
<li class="chapter" data-level="5.2" data-path="week-5.html"><a href="week-5.html#load-all-the-necessary-packages"><i class="fa fa-check"></i><b>5.2</b> Load all the necessary packages</a></li>
<li class="chapter" data-level="5.3" data-path="week-5.html"><a href="week-5.html#descriptive-statistics"><i class="fa fa-check"></i><b>5.3</b> Descriptive Statistics</a></li>
<li class="chapter" data-level="5.4" data-path="week-5.html"><a href="week-5.html#central-tendency-variability"><i class="fa fa-check"></i><b>5.4</b> Central tendency &amp; variability</a></li>
<li class="chapter" data-level="5.5" data-path="week-5.html"><a href="week-5.html#mean-and-median"><i class="fa fa-check"></i><b>5.5</b> Mean and median</a><ul>
<li class="chapter" data-level="5.5.1" data-path="week-5.html"><a href="week-5.html#reading-data-in"><i class="fa fa-check"></i><b>5.5.1</b> Reading data in</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="week-5.html"><a href="week-5.html#using-piping-operator-for-descriptive-statistics"><i class="fa fa-check"></i><b>5.6</b> Using piping operator for descriptive statistics</a><ul>
<li class="chapter" data-level="5.6.1" data-path="week-5.html"><a href="week-5.html#mean"><i class="fa fa-check"></i><b>5.6.1</b> Mean</a></li>
<li class="chapter" data-level="5.6.2" data-path="week-5.html"><a href="week-5.html#median"><i class="fa fa-check"></i><b>5.6.2</b> Median</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="week-5.html"><a href="week-5.html#standard-deviation"><i class="fa fa-check"></i><b>5.7</b> Standard deviation</a></li>
<li class="chapter" data-level="5.8" data-path="week-5.html"><a href="week-5.html#visualise-your-data"><i class="fa fa-check"></i><b>5.8</b> Visualise your data</a></li>
<li class="chapter" data-level="5.9" data-path="week-5.html"><a href="week-5.html#practice.rmd-solutions-2"><i class="fa fa-check"></i><b>5.9</b> Practice.Rmd Solutions</a><ul>
<li class="chapter" data-level="5.9.1" data-path="week-5.html"><a href="week-5.html#income-distribution-example"><i class="fa fa-check"></i><b>5.9.1</b> Income Distribution Example</a></li>
<li class="chapter" data-level="5.9.2" data-path="week-5.html"><a href="week-5.html#visualisations-1"><i class="fa fa-check"></i><b>5.9.2</b> Visualisations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-6.html"><a href="week-6.html"><i class="fa fa-check"></i><b>6</b> Week 6</a><ul>
<li class="chapter" data-level="6.1" data-path="week-6.html"><a href="week-6.html#plotting-functions-and-simple-data-transformation"><i class="fa fa-check"></i><b>6.1</b> Plotting Functions and Simple Data Transformation</a></li>
<li class="chapter" data-level="6.2" data-path="week-6.html"><a href="week-6.html#load-all-the-necessary-packages-1"><i class="fa fa-check"></i><b>6.2</b> Load all the necessary packages</a></li>
<li class="chapter" data-level="6.3" data-path="week-6.html"><a href="week-6.html#part-1-hand-plotting-functions"><i class="fa fa-check"></i><b>6.3</b> Part 1: Hand plotting functions</a></li>
<li class="chapter" data-level="6.4" data-path="week-6.html"><a href="week-6.html#basics"><i class="fa fa-check"></i><b>6.4</b> Basics</a></li>
<li class="chapter" data-level="6.5" data-path="week-6.html"><a href="week-6.html#linear-functions"><i class="fa fa-check"></i><b>6.5</b> Linear functions</a><ul>
<li class="chapter" data-level="6.5.1" data-path="week-6.html"><a href="week-6.html#tree-height-example"><i class="fa fa-check"></i><b>6.5.1</b> Tree height example</a></li>
<li class="chapter" data-level="6.5.2" data-path="week-6.html"><a href="week-6.html#non-linear-functions-first-order-polynomials"><i class="fa fa-check"></i><b>6.5.2</b> Non-linear functions (first order polynomials)</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="week-6.html"><a href="week-6.html#practice-plotting"><i class="fa fa-check"></i><b>6.6</b> Practice plotting</a></li>
<li class="chapter" data-level="6.7" data-path="week-6.html"><a href="week-6.html#part-2-introduction-to-data-transformation"><i class="fa fa-check"></i><b>6.7</b> Part 2: Introduction to Data Transformation</a></li>
<li class="chapter" data-level="6.8" data-path="week-6.html"><a href="week-6.html#renaming"><i class="fa fa-check"></i><b>6.8</b> Renaming</a></li>
<li class="chapter" data-level="6.9" data-path="week-6.html"><a href="week-6.html#adding-new-variables"><i class="fa fa-check"></i><b>6.9</b> Adding new variables</a></li>
<li class="chapter" data-level="6.10" data-path="week-6.html"><a href="week-6.html#transformation-and-skewness"><i class="fa fa-check"></i><b>6.10</b> Transformation and skewness</a></li>
<li class="chapter" data-level="6.11" data-path="week-6.html"><a href="week-6.html#mean-centering"><i class="fa fa-check"></i><b>6.11</b> Mean Centering</a></li>
<li class="chapter" data-level="6.12" data-path="week-6.html"><a href="week-6.html#standardisation"><i class="fa fa-check"></i><b>6.12</b> Standardisation</a></li>
<li class="chapter" data-level="6.13" data-path="week-6.html"><a href="week-6.html#practice.rmd-solutions-3"><i class="fa fa-check"></i><b>6.13</b> Practice.Rmd Solutions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="week-7.html"><a href="week-7.html"><i class="fa fa-check"></i><b>7</b> Week 7</a><ul>
<li class="chapter" data-level="7.1" data-path="week-7.html"><a href="week-7.html#reading-in-data-merge-and-more-r-practice"><i class="fa fa-check"></i><b>7.1</b> Reading in Data, Merge and More R Practice</a></li>
<li class="chapter" data-level="7.2" data-path="week-7.html"><a href="week-7.html#dataset-1-.csv"><i class="fa fa-check"></i><b>7.2</b> Dataset 1 (.csv)</a></li>
<li class="chapter" data-level="7.3" data-path="week-7.html"><a href="week-7.html#dataset-2-.txt"><i class="fa fa-check"></i><b>7.3</b> Dataset 2 (.txt)</a></li>
<li class="chapter" data-level="7.4" data-path="week-7.html"><a href="week-7.html#dataset-3-.sav-and-.dta"><i class="fa fa-check"></i><b>7.4</b> Dataset 3 (.sav and .dta)</a></li>
<li class="chapter" data-level="7.5" data-path="week-7.html"><a href="week-7.html#merging-datasets-together"><i class="fa fa-check"></i><b>7.5</b> Merging datasets together</a></li>
<li class="chapter" data-level="7.6" data-path="week-7.html"><a href="week-7.html#sorting-and-arrange"><i class="fa fa-check"></i><b>7.6</b> Sorting and arrange()</a></li>
<li class="chapter" data-level="7.7" data-path="week-7.html"><a href="week-7.html#data-description"><i class="fa fa-check"></i><b>7.7</b> Data description</a></li>
<li class="chapter" data-level="7.8" data-path="week-7.html"><a href="week-7.html#using-filter"><i class="fa fa-check"></i><b>7.8</b> Using filter()</a></li>
<li class="chapter" data-level="7.9" data-path="week-7.html"><a href="week-7.html#visualisations-2"><i class="fa fa-check"></i><b>7.9</b> Visualisations</a></li>
<li class="chapter" data-level="7.10" data-path="week-7.html"><a href="week-7.html#save-the-file-in-your-folder"><i class="fa fa-check"></i><b>7.10</b> Save the file in your folder</a></li>
<li class="chapter" data-level="7.11" data-path="week-7.html"><a href="week-7.html#practice.rmd-solutions-4"><i class="fa fa-check"></i><b>7.11</b> Practice.Rmd Solutions</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="week-8.html"><a href="week-8.html"><i class="fa fa-check"></i><b>8</b> Week 8</a><ul>
<li class="chapter" data-level="8.1" data-path="week-8.html"><a href="week-8.html#introduction-to-probability"><i class="fa fa-check"></i><b>8.1</b> Introduction to Probability</a></li>
<li class="chapter" data-level="8.2" data-path="week-8.html"><a href="week-8.html#example-1-hot-hand"><i class="fa fa-check"></i><b>8.2</b> Example 1 (hot hand)</a></li>
<li class="chapter" data-level="8.3" data-path="week-8.html"><a href="week-8.html#example-2-coin-toss"><i class="fa fa-check"></i><b>8.3</b> Example 2 (coin toss)</a></li>
<li class="chapter" data-level="8.4" data-path="week-8.html"><a href="week-8.html#example-3-independent-shooter"><i class="fa fa-check"></i><b>8.4</b> Example 3 (Independent shooter)</a></li>
<li class="chapter" data-level="8.5" data-path="week-8.html"><a href="week-8.html#practice-rmd.-solutions"><i class="fa fa-check"></i><b>8.5</b> Practice Rmd. Solutions</a><ul>
<li class="chapter" data-level="8.5.1" data-path="week-8.html"><a href="week-8.html#sex-of-the-babies-born-in-the-uk"><i class="fa fa-check"></i><b>8.5.1</b> Sex of the babies born in the UK</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="week-8.html"><a href="week-8.html#pen-and-paper-exercises"><i class="fa fa-check"></i><b>8.6</b> Pen and Paper Exercises</a><ul>
<li class="chapter" data-level="8.6.1" data-path="week-8.html"><a href="week-8.html#boys-and-girls-paradox-mr.jones-and-mr.smith"><i class="fa fa-check"></i><b>8.6.1</b> Boys and girls paradox (Mr. Jones and Mr. Smith)</a></li>
<li class="chapter" data-level="8.6.2" data-path="week-8.html"><a href="week-8.html#rugby-captain"><i class="fa fa-check"></i><b>8.6.2</b> Rugby captain</a></li>
<li class="chapter" data-level="8.6.3" data-path="week-8.html"><a href="week-8.html#answers"><i class="fa fa-check"></i><b>8.6.3</b> Answers</a></li>
<li class="chapter" data-level="8.6.4" data-path="week-8.html"><a href="week-8.html#defective"><i class="fa fa-check"></i><b>8.6.4</b> Defective</a></li>
<li class="chapter" data-level="8.6.5" data-path="week-8.html"><a href="week-8.html#answers-1"><i class="fa fa-check"></i><b>8.6.5</b> Answers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="week-9.html"><a href="week-9.html"><i class="fa fa-check"></i><b>9</b> Week 9</a><ul>
<li class="chapter" data-level="9.1" data-path="week-9.html"><a href="week-9.html#introduction-to-probability-distributions-and-revision"><i class="fa fa-check"></i><b>9.1</b> Introduction to Probability Distributions and Revision</a></li>
<li class="chapter" data-level="9.2" data-path="week-9.html"><a href="week-9.html#discrete-example-guessing-homework-answers"><i class="fa fa-check"></i><b>9.2</b> Discrete example (guessing homework answers)</a></li>
<li class="chapter" data-level="9.3" data-path="week-9.html"><a href="week-9.html#generate-a-homework-attempt"><i class="fa fa-check"></i><b>9.3</b> Generate a homework attempt</a></li>
<li class="chapter" data-level="9.4" data-path="week-9.html"><a href="week-9.html#changing-the-probability-truefalse"><i class="fa fa-check"></i><b>9.4</b> Changing the probability (TRUE/FALSE)</a></li>
<li class="chapter" data-level="9.5" data-path="week-9.html"><a href="week-9.html#studying-the-distribution"><i class="fa fa-check"></i><b>9.5</b> Studying the distribution</a></li>
<li class="chapter" data-level="9.6" data-path="week-9.html"><a href="week-9.html#cumulative-probability-advanced"><i class="fa fa-check"></i><b>9.6</b> Cumulative Probability (Advanced)</a></li>
<li class="chapter" data-level="9.7" data-path="week-9.html"><a href="week-9.html#revision-practice-rmd.-solutions"><i class="fa fa-check"></i><b>9.7</b> Revision Practice Rmd. Solutions</a><ul>
<li class="chapter" data-level="9.7.1" data-path="week-9.html"><a href="week-9.html#provide-descriptive-statistics-for-age-and-memory-score-variables"><i class="fa fa-check"></i><b>9.7.1</b> Provide descriptive statistics for age and memory score variables</a></li>
<li class="chapter" data-level="9.7.2" data-path="week-9.html"><a href="week-9.html#descriptives-by-groups"><i class="fa fa-check"></i><b>9.7.2</b> Descriptives by groups</a></li>
<li class="chapter" data-level="9.7.3" data-path="week-9.html"><a href="week-9.html#visualise"><i class="fa fa-check"></i><b>9.7.3</b> Visualise</a></li>
<li class="chapter" data-level="9.7.4" data-path="week-9.html"><a href="week-9.html#visualise-a-subset"><i class="fa fa-check"></i><b>9.7.4</b> Visualise a subset</a></li>
<li class="chapter" data-level="9.7.5" data-path="week-9.html"><a href="week-9.html#variable-by-a-group"><i class="fa fa-check"></i><b>9.7.5</b> Variable by a group</a></li>
<li class="chapter" data-level="9.7.6" data-path="week-9.html"><a href="week-9.html#create-a-new-variable-using-mutate"><i class="fa fa-check"></i><b>9.7.6</b> Create a new variable using mutate()</a></li>
<li class="chapter" data-level="9.7.7" data-path="week-9.html"><a href="week-9.html#subset-observations-using-filter"><i class="fa fa-check"></i><b>9.7.7</b> Subset observations using filter()</a></li>
<li class="chapter" data-level="9.7.8" data-path="week-9.html"><a href="week-9.html#sort-via-arrange"><i class="fa fa-check"></i><b>9.7.8</b> Sort via arrange()</a></li>
<li class="chapter" data-level="9.7.9" data-path="week-9.html"><a href="week-9.html#lets-do-some-specific-count-using-filter"><i class="fa fa-check"></i><b>9.7.9</b> Let’s do some specific count() using filter()</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="week-9.html"><a href="week-9.html#extra-probability-practice"><i class="fa fa-check"></i><b>9.8</b> Extra Probability Practice</a><ul>
<li class="chapter" data-level="9.8.1" data-path="week-9.html"><a href="week-9.html#truefalse-questions"><i class="fa fa-check"></i><b>9.8.1</b> TRUE/FALSE questions</a></li>
<li class="chapter" data-level="9.8.2" data-path="week-9.html"><a href="week-9.html#count-the-occurencies"><i class="fa fa-check"></i><b>9.8.2</b> Count the occurencies</a></li>
<li class="chapter" data-level="9.8.3" data-path="week-9.html"><a href="week-9.html#plot"><i class="fa fa-check"></i><b>9.8.3</b> Plot</a></li>
<li class="chapter" data-level="9.8.4" data-path="week-9.html"><a href="week-9.html#use-dbinom-to-study-the-probability"><i class="fa fa-check"></i><b>9.8.4</b> Use dbinom() to study the probability</a></li>
<li class="chapter" data-level="9.8.5" data-path="week-9.html"><a href="week-9.html#less-than-five-or-more-than-five"><i class="fa fa-check"></i><b>9.8.5</b> Less than five or more than five?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="week-10-lab-test.html"><a href="week-10-lab-test.html"><i class="fa fa-check"></i><b>10</b> Week 10: Lab test</a></li>
<li class="chapter" data-level="11" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html"><i class="fa fa-check"></i><b>11</b> Sampling distributions</a><ul>
<li class="chapter" data-level="11.1" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#recap"><i class="fa fa-check"></i><b>11.1</b> Recap</a></li>
<li class="chapter" data-level="11.2" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#population-sample"><i class="fa fa-check"></i><b>11.2</b> Population vs sample</a></li>
<li class="chapter" data-level="11.3" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#parameter-statistic"><i class="fa fa-check"></i><b>11.3</b> Population parameter vs sample statistic</a></li>
<li class="chapter" data-level="11.4" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#sec-sampling-distributions"><i class="fa fa-check"></i><b>11.4</b> Sampling distributions</a></li>
<li class="chapter" data-level="11.5" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#standard-error"><i class="fa fa-check"></i><b>11.5</b> The standard error of a statistic</a></li>
<li class="chapter" data-level="11.6" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#sample-size-standard-error"><i class="fa fa-check"></i><b>11.6</b> The effect of sample size on the sampling distribution</a></li>
<li class="chapter" data-level="11.7" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#take-home-message"><i class="fa fa-check"></i><b>11.7</b> Take-home message</a></li>
<li class="chapter" data-level="11.8" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#lab-hollywood-movies"><i class="fa fa-check"></i><b>11.8</b> Lab: Hollywood movies</a></li>
<li class="chapter" data-level="11.9" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#summary"><i class="fa fa-check"></i><b>11.9</b> Summary</a></li>
<li class="chapter" data-level="11.10" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#glossary"><i class="fa fa-check"></i><b>11.10</b> Glossary</a></li>
<li class="chapter" data-level="11.11" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#references"><i class="fa fa-check"></i><b>11.11</b> References</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html"><i class="fa fa-check"></i><b>12</b> Bootstrapping and Confidence Intervals</a><ul>
<li class="chapter" data-level="12.1" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#recap-1"><i class="fa fa-check"></i><b>12.1</b> Recap</a></li>
<li class="chapter" data-level="12.2" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#from-sampling-to-resampling"><i class="fa fa-check"></i><b>12.2</b> From Sampling to Resampling</a></li>
<li class="chapter" data-level="12.3" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#getting-to-the-bootstrap-distribution"><i class="fa fa-check"></i><b>12.3</b> Getting to the bootstrap distribution</a></li>
<li class="chapter" data-level="12.4" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#more-generally"><i class="fa fa-check"></i><b>12.4</b> More generally…</a></li>
<li class="chapter" data-level="12.5" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#confidence-intervals"><i class="fa fa-check"></i><b>12.5</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="12.5.1" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#calculating-confidence-intervals-using-a-bootstrap-standard-error"><i class="fa fa-check"></i><b>12.5.1</b> Calculating confidence intervals using a bootstrap standard error</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#summary-1"><i class="fa fa-check"></i><b>12.6</b> Summary</a></li>
<li class="chapter" data-level="12.7" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#take-home-message-1"><i class="fa fa-check"></i><b>12.7</b> Take-home message</a></li>
<li class="chapter" data-level="12.8" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#lab"><i class="fa fa-check"></i><b>12.8</b> Lab</a><ul>
<li class="chapter" data-level="" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#exercise-1-hollywood-movies"><i class="fa fa-check"></i>Exercise 1: Hollywood Movies</a></li>
<li class="chapter" data-level="" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#exercise-2-nfl-players"><i class="fa fa-check"></i>Exercise 2: NFL Players</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#glossary-1"><i class="fa fa-check"></i><b>12.9</b> Glossary</a></li>
<li class="chapter" data-level="12.10" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#references-1"><i class="fa fa-check"></i><b>12.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html"><i class="fa fa-check"></i><b>13</b> Testing hypotheses</a><ul>
<li class="chapter" data-level="13.1" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#recap-2"><i class="fa fa-check"></i><b>13.1</b> Recap</a></li>
<li class="chapter" data-level="13.2" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#walkthrough"><i class="fa fa-check"></i><b>13.2</b> Walkthrough</a><ul>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#extrasensory-perception-esp"><i class="fa fa-check"></i>Extrasensory perception (ESP)</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#example-esp-results"><i class="fa fa-check"></i>Example 1: ESP experimental results</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#example-in-class"><i class="fa fa-check"></i>Example 2: In-class activity</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#the-random-chance-model"><i class="fa fa-check"></i>The random chance model</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#the-alternative-explanation"><i class="fa fa-check"></i>The alternative explanation</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#statistical-test"><i class="fa fa-check"></i>Statistical test</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#understanding-statistical-evidence"><i class="fa fa-check"></i>Understanding statistical evidence</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#statistical-hypotheses"><i class="fa fa-check"></i>Statistical hypotheses</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#statistical-significance"><i class="fa fa-check"></i>Statistical significance</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#null-distribution"><i class="fa fa-check"></i>Null distribution</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#p-value"><i class="fa fa-check"></i>P-value</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#making-a-formal-decision"><i class="fa fa-check"></i>Making a formal decision</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#summary-2"><i class="fa fa-check"></i><b>13.3</b> Summary</a></li>
<li class="chapter" data-level="13.4" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#lab-1"><i class="fa fa-check"></i><b>13.4</b> Lab</a><ul>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#required-packages"><i class="fa fa-check"></i>Required packages</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#importing-the-data"><i class="fa fa-check"></i>Importing the data</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#data-inspection"><i class="fa fa-check"></i>Data inspection</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#sample-average-and-standard-deviation"><i class="fa fa-check"></i>Sample average and standard deviation</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#null-and-alternative-hypothesis"><i class="fa fa-check"></i>Null and alternative hypothesis</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#bootstrap-distribution-and-null-distribution"><i class="fa fa-check"></i>Bootstrap distribution and null distribution</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#visualise-the-observed-statistic-on-the-null-distribution"><i class="fa fa-check"></i>Visualise the observed statistic on the null distribution</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#p-value-2"><i class="fa fa-check"></i>P-value</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#interpreting-the-p-value"><i class="fa fa-check"></i>Interpreting the p-value</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#glossary-2"><i class="fa fa-check"></i><b>13.5</b> Glossary</a></li>
<li class="chapter" data-level="13.6" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#references-2"><i class="fa fa-check"></i><b>13.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="chap-typeerror.html"><a href="chap-typeerror.html"><i class="fa fa-check"></i><b>14</b> Type I, Type II errors and Power</a><ul>
<li class="chapter" data-level="14.1" data-path="chap-typeerror.html"><a href="chap-typeerror.html#overview-of-last-week"><i class="fa fa-check"></i><b>14.1</b> Overview of last week</a></li>
<li class="chapter" data-level="14.2" data-path="chap-typeerror.html"><a href="chap-typeerror.html#walkthrough-1"><i class="fa fa-check"></i><b>14.2</b> Walkthrough</a><ul>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#example-1-coin-flip"><i class="fa fa-check"></i>Example 1: Coin flip</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#an-analogy-in-law"><i class="fa fa-check"></i>An analogy in law</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#two-different-types-of-errors"><i class="fa fa-check"></i>Two different types of errors</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#type-i-errors"><i class="fa fa-check"></i>Type I errors</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#type-ii-errors-and-power"><i class="fa fa-check"></i>Type II Errors and Power</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#example-2-a-biased-coin"><i class="fa fa-check"></i>Example 2: A biased coin</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#overlapping-distributions"><i class="fa fa-check"></i>Overlapping distributions</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#generalising-it"><i class="fa fa-check"></i>Generalising it</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="chap-typeerror.html"><a href="chap-typeerror.html#summary-3"><i class="fa fa-check"></i><b>14.3</b> Summary</a></li>
<li class="chapter" data-level="14.4" data-path="chap-typeerror.html"><a href="chap-typeerror.html#lab-2"><i class="fa fa-check"></i><b>14.4</b> Lab</a><ul>
<li class="chapter" data-level="14.4.1" data-path="chap-typeerror.html"><a href="chap-typeerror.html#exercise-1-rock-paper-scissors"><i class="fa fa-check"></i><b>14.4.1</b> Exercise 1: Rock Paper Scissors!</a></li>
<li class="chapter" data-level="14.4.2" data-path="chap-typeerror.html"><a href="chap-typeerror.html#exercise-2-calculating-power-for-a-different-coin."><i class="fa fa-check"></i><b>14.4.2</b> Exercise 2: Calculating power for a different coin.</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="chap-typeerror.html"><a href="chap-typeerror.html#extra-exercises"><i class="fa fa-check"></i><b>14.5</b> Extra Exercises</a><ul>
<li class="chapter" data-level="14.5.1" data-path="chap-typeerror.html"><a href="chap-typeerror.html#exercise-3-sample-size-number-of-flips-and-power"><i class="fa fa-check"></i><b>14.5.1</b> Exercise 3: Sample size (number of flips) and power</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="chap-typeerror.html"><a href="chap-typeerror.html#glossary-3"><i class="fa fa-check"></i><b>14.6</b> Glossary</a></li>
<li class="chapter" data-level="14.7" data-path="chap-typeerror.html"><a href="chap-typeerror.html#references-3"><i class="fa fa-check"></i><b>14.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="chap-normal.html"><a href="chap-normal.html"><i class="fa fa-check"></i><b>15</b> Normal distribution &amp; probability</a><ul>
<li class="chapter" data-level="15.1" data-path="chap-normal.html"><a href="chap-normal.html#recap-3"><i class="fa fa-check"></i><b>15.1</b> Recap</a></li>
<li class="chapter" data-level="15.2" data-path="chap-normal.html"><a href="chap-normal.html#walkthrough-2"><i class="fa fa-check"></i><b>15.2</b> Walkthrough</a><ul>
<li class="chapter" data-level="15.2.1" data-path="chap-normal.html"><a href="chap-normal.html#from-histograms-to-normal-curves"><i class="fa fa-check"></i><b>15.2.1</b> From histograms to normal curves</a></li>
<li class="chapter" data-level="15.2.2" data-path="chap-normal.html"><a href="chap-normal.html#sec-area-and-prob"><i class="fa fa-check"></i><b>15.2.2</b> The relation between area and probability</a></li>
<li class="chapter" data-level="15.2.3" data-path="chap-normal.html"><a href="chap-normal.html#probabilities-for-normally-distributed-random-variables"><i class="fa fa-check"></i><b>15.2.3</b> Probabilities for normally distributed random variables</a></li>
<li class="chapter" data-level="15.2.4" data-path="chap-normal.html"><a href="chap-normal.html#z-scores"><i class="fa fa-check"></i><b>15.2.4</b> Z-scores</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="chap-normal.html"><a href="chap-normal.html#summary-4"><i class="fa fa-check"></i><b>15.3</b> Summary</a></li>
<li class="chapter" data-level="15.4" data-path="chap-normal.html"><a href="chap-normal.html#lab-3"><i class="fa fa-check"></i><b>15.4</b> Lab</a></li>
<li class="chapter" data-level="15.5" data-path="chap-normal.html"><a href="chap-normal.html#glossary-4"><i class="fa fa-check"></i><b>15.5</b> Glossary</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html"><i class="fa fa-check"></i><b>16</b> One Sample Mean Test</a><ul>
<li class="chapter" data-level="16.1" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#recap-4"><i class="fa fa-check"></i><b>16.1</b> Recap</a></li>
<li class="chapter" data-level="16.2" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#where-we-are-now"><i class="fa fa-check"></i><b>16.2</b> Where we are now</a></li>
<li class="chapter" data-level="16.3" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#where-we-are-going"><i class="fa fa-check"></i><b>16.3</b> Where we are going</a></li>
<li class="chapter" data-level="16.4" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#one-sample-mean-test"><i class="fa fa-check"></i><b>16.4</b> One sample mean test</a><ul>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#example-questions"><i class="fa fa-check"></i>Example questions</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#hypotheses"><i class="fa fa-check"></i>Hypotheses</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#formula"><i class="fa fa-check"></i>Formula</a></li>
<li><a href="chap-one-mean-test.html#t-distributions"><span class="math inline">\(t\)</span>-distributions</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#critical-values-significance"><i class="fa fa-check"></i>Critical values &amp; significance</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#walkthrough---tempo-of-rock-music-on-spotify"><i class="fa fa-check"></i><b>16.5</b> Walkthrough - Tempo of rock music on Spotify</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#all-in-one-line-of-code"><i class="fa fa-check"></i>ALL IN ONE LINE OF CODE!</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#assumptions"><i class="fa fa-check"></i>Assumptions</a></li>
<li class="chapter" data-level="16.6" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#summary-5"><i class="fa fa-check"></i><b>16.6</b> Summary</a></li>
<li class="chapter" data-level="16.7" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#lab-4"><i class="fa fa-check"></i><b>16.7</b> Lab</a><ul>
<li class="chapter" data-level="16.7.1" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#pets-weights"><i class="fa fa-check"></i><b>16.7.1</b> Pets’ weights</a></li>
<li class="chapter" data-level="16.7.2" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#procrastination-scores"><i class="fa fa-check"></i><b>16.7.2</b> Procrastination scores</a></li>
<li class="chapter" data-level="16.7.3" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#cat-weights"><i class="fa fa-check"></i><b>16.7.3</b> Cat weights!</a></li>
<li class="chapter" data-level="16.7.4" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#glossary-5"><i class="fa fa-check"></i><b>16.7.4</b> Glossary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="two-indep-samples.html"><a href="two-indep-samples.html"><i class="fa fa-check"></i><b>17</b> Comparing two means (independent samples)</a><ul>
<li class="chapter" data-level="17.1" data-path="two-indep-samples.html"><a href="two-indep-samples.html#recap-5"><i class="fa fa-check"></i><b>17.1</b> Recap</a></li>
<li class="chapter" data-level="17.2" data-path="two-indep-samples.html"><a href="two-indep-samples.html#key-terminology"><i class="fa fa-check"></i><b>17.2</b> Key terminology</a></li>
<li class="chapter" data-level="17.3" data-path="two-indep-samples.html"><a href="two-indep-samples.html#walkthrough-got-a-friend"><i class="fa fa-check"></i><b>17.3</b> Walkthrough: Got a friend?</a></li>
<li class="chapter" data-level="17.4" data-path="two-indep-samples.html"><a href="two-indep-samples.html#lab-does-name-increase-tips"><i class="fa fa-check"></i><b>17.4</b> Lab: Does name increase tips?</a></li>
<li class="chapter" data-level="17.5" data-path="two-indep-samples.html"><a href="two-indep-samples.html#glossary-6"><i class="fa fa-check"></i><b>17.5</b> Glossary</a></li>
<li class="chapter" data-level="17.6" data-path="two-indep-samples.html"><a href="two-indep-samples.html#w17-references"><i class="fa fa-check"></i><b>17.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html"><i class="fa fa-check"></i><b>18</b> Paired T-Test</a><ul>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#recap-6"><i class="fa fa-check"></i>Recap</a></li>
<li><a href="chap-paired-t-test.html#paired-t-test">Paired <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="18.1" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#walkthrough-3"><i class="fa fa-check"></i><b>18.1</b> Walkthrough</a><ul>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#change-in-score-on-the-ace-iii"><i class="fa fa-check"></i>Change in score on the ACE-III</a></li>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#data-organisation---reshaping"><i class="fa fa-check"></i>Data organisation - reshaping</a></li>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#effect-sizes"><i class="fa fa-check"></i>Effect sizes</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#summary-6"><i class="fa fa-check"></i><b>18.2</b> Summary</a></li>
<li class="chapter" data-level="18.3" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#lab-5"><i class="fa fa-check"></i><b>18.3</b> Lab</a><ul>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#age-differences-in-heterosexual-marriages"><i class="fa fa-check"></i>Age differences in heterosexual marriages</a></li>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#smoking-interventions"><i class="fa fa-check"></i>Smoking interventions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="chap-chi-square.html"><a href="chap-chi-square.html"><i class="fa fa-check"></i><b>19</b> Chi-square tests</a><ul>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#recap-7"><i class="fa fa-check"></i>Recap</a></li>
<li><a href="chap-chi-square.html#walkthrough-birthdays-of-the-week-the-chi-square-goodness-of-fit-test">Walkthrough: Birthdays of the week <br>The chi-square goodness-of-fit test</a></li>
<li><a href="chap-chi-square.html#lab-joking-for-a-tip-the-chi-square-test-of-independence">Lab: Joking for a tip <br>The chi-square test of independence</a></li>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#summary-7"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#glossary-7"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#references-4"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analysis for Psychology in R (dapR1) - Labs</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap-hyp-test" class="section level1">
<h1><span class="header-section-number">Chapter 13</span> Testing hypotheses</h1>
<div class="lo">
<h4 id="instructions-2" class="unnumbered">Instructions</h4>
<ul>
<li>In this two-hour lab we will go through worked examples in the first hour, and you will attempt to answer some questions in the second hour.</li>
<li>The Rmarkdown file for this week is <a href="https://uoe-psychology.github.io/uoe_psystats/dapr1/labsheets/week_13_practice.Rmd">here</a>.</li>
</ul>
<h4 id="learning-outcomes-2" class="unnumbered">Learning outcomes</h4>
<p><strong>LO1.</strong> Understand null and alternative hypotheses, and how to specify them for a given research question.</p>
<p><strong>LO2.</strong> Understand how to obtain a null distribution via simulation.</p>
<p><strong>LO3.</strong> Understand statistical significance and how to calculate p-values from null distributions.</p>
</div>
<div id="recap-2" class="section level2">
<h2><span class="header-section-number">13.1</span> Recap</h2>
<p>In <a href="chap-sampling-distributions.html#chap-sampling-distributions">Week 11</a> we saw that a population is described by parameters, and samples are described by statistics. We typically can not measure the entire population, so a population parameter needs to be estimated by a sample statistic. We quantified the uncertainty in our estimate by the standard error (SE) of the sample statistic. This is defined as the standard deviation of the sampling distribution. The latter shows the values of the sample statistic when computed on many samples of the same size from the same population.</p>
<p>In practice, however, we are not able to quantify the SE by taking repeated samples from the population, as due to money or time constraints we only have one sample of size <span class="math inline">\(n\)</span>. In <a href="bootstrapping-and-confidence-intervals.html#bootstrapping-and-confidence-intervals">Week 12</a> we learned to approximate the sampling distribution by bootstrapping.
This approach repeatedly samples with replacement from the observed sample, using the same sample size.
The standard deviation of the bootstrap distribution is an estimate of the SE of the statistic.
Using the statistic from the observed sample, and the estimated SE from the bootstrap distribution, we learned how to give a range of plausible values for the population parameter.</p>
<p>This week we will learn how to use the sample data to answer a wide range of questions about a population.</p>
</div>
<div id="walkthrough" class="section level2">
<h2><span class="header-section-number">13.2</span> Walkthrough</h2>
<div class="red">
<h4 id="research-question-of-the-walkthrough" class="unnumbered">Research question of the walkthrough</h4>
<p>Is there such a thing as extrasensory perception (ESP), also known as the “sixth sense”?</p>
</div>
<div id="extrasensory-perception-esp" class="section level3 unnumbered">
<h3>Extrasensory perception (ESP)</h3>
<p>According to <a href="https://en.wikipedia.org/wiki/Extrasensory_perception">Wikipedia</a>, “<strong>Extrasensory perception</strong> or <strong>ESP</strong>, also called the sixth sense, includes claimed reception of information not gained through the recognized physical senses, but sensed with the mind.”</p>
A famous test for ESP involves a set of cards, shown in Figure <a href="chap-hyp-test.html#fig:zener">13.1</a>, known as Zener cards:
<div class="figure" style="text-align: center"><span id="fig:zener"></span>
<img src="images/zener.png" alt="Zener cards (Source: https://en.wikipedia.org/wiki/Extrasensory_perception)" width="80%" />
<p class="caption">
Figure 13.1: Zener cards (Source: <a href="https://en.wikipedia.org/wiki/Extrasensory_perception" class="uri">https://en.wikipedia.org/wiki/Extrasensory_perception</a>)
</p>
</div>
<p>There are five different cards, one for each of the following symbols:</p>
<ol style="list-style-type: decimal">
<li>circle</li>
<li>cross</li>
<li>wavy lines</li>
<li>square</li>
<li>star</li>
</ol>
<p>Subjects randomly draw a card from these five, and telepathically communicate the chosen card to another subject who then tries to guess the symbol. No visual or auditory clues are allowed.</p>
</div>
<div id="example-esp-results" class="section level3 unnumbered">
<h3>Example 1: ESP experimental results</h3>
<p>In an experiment conducted on a class of <span class="math inline">\(n = 98\)</span> students, 25 of them correctly guessed their partner’s card.</p>
<p>This is equivalent to saying that the observed sample proportion of correct guesses is <span class="math inline">\(\hat{p} = 25/98 = 0.26\)</span>.</p>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>Is the sample proportion of correct guesses high enough to provide evidence of ESP?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-27" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-27&#39;, &#39;sol-start-27&#39;)"></span>
</p>
<div id="sol-body-27" class="solution-body" style="display: none;">
<p>We are not sure yet.</p>
<p>We still have to introduce the statistical framework that, assuming no ESP, allows us to determine either:</p>
<ul>
<li>if the observed sample statistic is highly unlikely to happen due to sampling variability,</li>
<li>or if it would be very likely to see such a value by sampling variation.</li>
</ul>
<p>As we will see, this framework is called <strong>hypothesis testing</strong> and involves using a <strong>statistical test</strong>.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="example-in-class" class="section level3 unnumbered">
<h3>Example 2: In-class activity</h3>
<ul>
<li>Everyone in the class randomly picks one of the five symbols in Figure <a href="chap-hyp-test.html#fig:zener">13.1</a>.</li>
<li>Draw the symbol on a bit of paper <strong>without showing it to anyone!</strong></li>
<li>Pair up with someone.</li>
<li>Telepathically communicate your symbol to your partner, who has to guess it without any visual or auditory clues.</li>
<li>Switch roles.</li>
<li>Did your partner guess your card correctly?</li>
</ul>
<p>Keep track of the sample size <span class="math inline">\(n\)</span> of the in-class experiment, and the sample statistic <span class="math inline">\(\hat{p}\)</span>.
We will use these two values later on to see if we have evidence of ESP in this class.</p>
</div>
<div id="the-random-chance-model" class="section level3 unnumbered">
<h3>The random chance model</h3>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>If there was no such thing as ESP, what proportion of guesses do you expect to be correct?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-28" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-28&#39;, &#39;sol-start-28&#39;)"></span>
</p>
<div id="sol-body-28" class="solution-body" style="display: none;">
<p>If there is no ESP, because there are five cards, each person has a chance of correctly guessing the symbol equal to <span class="math inline">\(1/5 = 0.2\)</span>.</p>
<p>This is similar to asking: what’s the chance of correctly guessing the face of a die? If we had to randomly guess, since there are 6 faces, we have a probability of <span class="math inline">\(1/6\)</span>.
The only difference is that instead of six faces, here we only have five, hence the <span class="math inline">\(1/5\)</span> chance.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>We use the chance-alone model to help us decide whether:</p>
<ul>
<li>the observed proportion could easily happen by sampling variation if we are randomly guessing the symbol, or</li>
<li>the underlying process is something else, such as having extrasensory perception.</li>
</ul>
<p>The chance model for the ESP example is specified by the probability of correctly guessing the symbol if we were to guess at random: <span class="math inline">\(p = 1/5\)</span>.</p>
<p>We call this probability the <strong>null hypothesis</strong>, and it represents what we would expect if there was no ESP (“no effect”).</p>
We denote the null hypothesis by:
<center>
<span class="math display">\[
H_0 : \  p = \frac{1}{5}
\]</span>
</center>
</div>
<div id="the-alternative-explanation" class="section level3 unnumbered">
<h3>The alternative explanation</h3>
<p>The research question of interest (i.e. if ESP exists) is captured by the <strong>alternative hypothesis</strong>, which contradicts the null hypothesis.
We always put the research claim of interest in the alternative hypothesis, rather than the null one.</p>
<p>The null and the alternative hypotheses are competing claims about the population parameter and we can not have the same value of the parameter included in both the null and the alternative.</p>
<p>In the ESP example, we would have evidence of ESP if the chance of correctly guessing the symbol was greater than when randomly guessing it:</p>
<center>
<span class="math display">\[
H_1 : p &gt; \frac{1}{5}
\]</span>
</center>
</div>
<div id="statistical-test" class="section level3 unnumbered">
<h3>Statistical test</h3>
<p>As we saw in <a href="chap-sampling-distributions.html#chap-sampling-distributions">Week 11</a>, sample statistics vary from sample to sample.
Even if the population proportion was really equal to 1/5, not every random sample would have a sample proportion exactly equal to 1/5.</p>
<p>The key question is then: <strong>how do we decide in a principled way if a sample proportion is sufficiently above 1/5 to suggest presence of ESP?</strong></p>
<p>In <a href="chap-hyp-test.html#example-esp-results">Example 1</a> we obtained a sample proportion of 25/98 = 0.26.
Is 0.26 sufficiently higher than 0.20 to suggest presence of ESP?</p>
<p>The set of principles that allows us to make an informed claim under uncertainty about the population is called <strong>statistical hypothesis testing</strong>.</p>
<div class="def">
<h4 id="statistical-test-1" class="unnumbered">Statistical test</h4>
<p>A <strong><em>statistical test</em></strong> is a method that uses the data collected on a sample to assess a claim about the population.</p>
</div>
</div>
<div id="understanding-statistical-evidence" class="section level3 unnumbered">
<h3>Understanding statistical evidence</h3>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>If <span class="math inline">\(\hat{p}\)</span> denotes the proportion of correctly guessed symbols in an ESP experiment, which of the following sample proportions provide the strongest evidence <strong>in favour</strong> of ESP?</p>
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(\hat{p} = 0\)</span></li>
<li><span class="math inline">\(\hat{p} = 1/5\)</span></li>
<li><span class="math inline">\(\hat{p} = 1/2\)</span></li>
<li><span class="math inline">\(\hat{p} = 3/4\)</span></li>
</ol>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-29" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-29&#39;, &#39;sol-start-29&#39;)"></span>
</p>
<div id="sol-body-29" class="solution-body" style="display: none;">
<p>The correct answer is (d) as <span class="math inline">\(\hat{p} = 3/4 = 0.75\)</span> is the highest proportion of correctly guessed symbols.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>This example shows us that we assess a claim about a population parameter by quantifying the statistical evidence that the observed statistic gives against the null hypothesis and in favour of the alternative hypothesis.</p>
</div>
<div id="statistical-hypotheses" class="section level3 unnumbered">
<h3>Statistical hypotheses</h3>
<p>We perform statistical tests on two competing hypotheses about a population parameter:</p>
<ul>
<li><strong>Null hypothesis</strong> <span class="math inline">\(H_0\)</span>: typically a claim about “no effect” or “no difference between groups”;</li>
<li><strong>Alternative hypothesis</strong> <span class="math inline">\(H_1\)</span>: the claim we seek evidence for.</li>
</ul>
<p>The null hypothesis is typically a very specific claim about the population parameter, while the alternative hypothesis is a broader statement.</p>
<p>To visually help you identify the null vs the alternative, typically:</p>
<ul>
<li><span class="math inline">\(H_0\)</span> includes an <span class="math inline">\(=\)</span> sign</li>
<li><span class="math inline">\(H_1\)</span> includes <span class="math inline">\(&gt;\)</span>, <span class="math inline">\(&lt;\)</span> or <span class="math inline">\(\neq\)</span></li>
</ul>
<p>If <span class="math inline">\(H_1\)</span> contains either <span class="math inline">\(&gt;\)</span> or <span class="math inline">\(&lt;\)</span>, we say that the alternative hypothesis is <strong>one-sided</strong>.
If <span class="math inline">\(H_1\)</span> contains <span class="math inline">\(\neq\)</span>, we say that the alternative hypothesis is <strong>two-sided</strong>.</p>
<p>Putting this together, in the ESP investigation we have two competing hypotheses:</p>
<center>
<span class="math display">\[
H_0 : \  p = \frac{1}{5} \\
H_1 : \  p &gt; \frac{1}{5}
\]</span>
</center>
</div>
<div id="statistical-significance" class="section level3 unnumbered">
<h3>Statistical significance</h3>
<p>Now that we have defined a framework to assess two competing hypotheses about a population parameter, how do we quantify the evidence that the sample data bring in favour of the alternative hypothesis?</p>
<p>We do this by quantifying how unusual it is to obtain a statistic as extreme or more extreme than the observed statistic, if the null hypothesis is true.
If it is very unusual, we have significant evidence against the null hypothesis.</p>
<div class="def">
<h4 id="def-statistical-significance" class="unnumbered">Statistical significance</h4>
<p>Assuming the null hypothesis to be true, we say that the sample results are <strong><em>statistically significant</em></strong> if it is unlikely that by random chance alone we obtain a statistic that is as extreme as the observed sample statistic, or more extreme (in the direction specified by the alternative hypothesis).</p>
</div>
<p>Hypothesis testing basically boils down to quantifying how likely or unlikely it is to observe the sample statistic if the null hypothesis is true. Two decisions are possible:</p>
<ul>
<li>If the sample data are statistically significant, we <strong>reject</strong> <span class="math inline">\(H_0\)</span> as we have enough evidence against <span class="math inline">\(H_0\)</span> and in favour of <span class="math inline">\(H_1\)</span>.</li>
<li>If the sample data are not statistically significant, we <strong>do not reject</strong> <span class="math inline">\(H_0\)</span> as we do not have convincing evidence against <span class="math inline">\(H_0\)</span>.</li>
</ul>
<p>This has an analogy in law. One of the fundamental legal principles is the <strong>presumption of innocence</strong>, which says that a person is considered innocent until proven guilty, and that the evidence must be beyond reasonable doubt.</p>
<p>The null hypothesis (<span class="math inline">\(H_0\)</span>), corresponding to no effect, is that the defendant is innocent. The alternative hypothesis (<span class="math inline">\(H_1\)</span>) is that the defendant is guilty.</p>
<p>The court presumes <span class="math inline">\(H_0\)</span> to be true (the defendant is innocent) unless the prosecutor can provide strong evidence that the defendant is guilty beyond a reasonable doubt. The burden of proof is on the prosecutor (in our case, the data) to convince the court that the defendant is guilty.</p>
<p>Similarly, we retain <span class="math inline">\(H_0\)</span> unless there is strong evidence to reject <span class="math inline">\(H_0\)</span>.</p>
<p>Recall that:</p>
<ul>
<li><span class="math inline">\(p\)</span> = proportion of correct guesses of the symbol</li>
<li><span class="math inline">\(H_0 : \  p = 1/5\)</span> vs <span class="math inline">\(H_1 : \  p &gt; 1/5\)</span></li>
</ul>
<div id="scenario-1-statistically-significant-results" class="section level4 unnumbered">
<h4>Scenario 1: statistically significant results</h4>
<p>If results are <strong>statistically significant</strong>:</p>
<ul>
<li>The sample proportion <span class="math inline">\(\hat{p}\)</span> of correct guesses is unlikely to occur by random chance alone. Recall that by random chance we mean if ESP does not exist and thus <span class="math inline">\(p = 1/5\)</span>.</li>
<li>The sample data provide evidence that the population proportion of correct guesses is higher than 1/5, meaning that we have evidence of ESP.</li>
</ul>
</div>
<div id="scenario-2-not-statistically-significant-results" class="section level4 unnumbered">
<h4>Scenario 2: not statistically significant results</h4>
<p>If results are <strong>not statistically significant</strong>:</p>
<ul>
<li>The sample proportion <span class="math inline">\(\hat{p}\)</span> of correct guesses could easily happen by random chance alone.
Recall that by random chance we mean if ESP does not exist and thus <span class="math inline">\(p = 1/5\)</span>.</li>
<li>The sample data do not provide enough evidence to conclude that <span class="math inline">\(p &gt; 1/5\)</span> or that ESP exists.</li>
</ul>
</div>
</div>
<div id="null-distribution" class="section level3 unnumbered">
<h3>Null distribution</h3>
<p>In the previous section, we said that if the observed statistic is very unusual, we have significant evidence against the null hypothesis. But <strong>how do we quantify if a value is unusual?</strong></p>
<p>The key idea is to look at the sampling distribution of the statistic if <span class="math inline">\(H_0\)</span> were true. We do this by generating many samples, assuming the null hypothesis to be true, and computing the statistic on each of the generated samples. The distribution of these statistics is called the <strong>null distribution</strong>.</p>
<div class="def">
<h4 id="null-distribution-1" class="unnumbered">Null distribution</h4>
<p>The <strong><em>null distribution</em></strong> is the sampling distribution of the statistic assuming the null hypothesis to be true.</p>
<p><strong>Centre</strong>: The null distribution is centred at the value of the population parameter specified in the null hypothesis.</p>
</div>
<p>We will now compute the null distribution for <a href="chap-hyp-test.html#example-esp-results">Example 1</a> on ESP. One experiment is a sequence of <span class="math inline">\(n = 98\)</span> guesses (resulting in a sequence of S’s and F’s, where S = success and F = failure) and this represents <strong>one sample</strong>. The required steps are:</p>
<ol style="list-style-type: decimal">
<li>Obtain many random samples of size <span class="math inline">\(n = 98\)</span>, assuming a probability of success equal to 1/5</li>
<li>Compute the proportion of successes for each sample</li>
<li>Plot the distribution of proportions</li>
</ol>
<p>Load the required packages:</p>
<div class="sourceCode" id="cb587"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb587-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb587-2" data-line-number="2"><span class="kw">library</span>(moderndive)</a></code></pre></div>
<p>Create a tibble with the possible outcome of one play. Either:</p>
<ul>
<li>your partner correctly guesses your card (S = success), or</li>
<li>your partner does not correctly guess your card (F = failure).</li>
</ul>
<p><em><strong>Note:</strong> Make sure the column name in the tibble is <code>vals</code> and that it is a factor.</em></p>
<div class="sourceCode" id="cb588"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb588-1" data-line-number="1">outcomes &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">vals =</span> <span class="kw">factor</span>(<span class="kw">c</span>(<span class="st">&#39;S&#39;</span>, <span class="st">&#39;F&#39;</span>)))</a>
<a class="sourceLine" id="cb588-2" data-line-number="2">outcomes</a></code></pre></div>
<pre><code>## # A tibble: 2 x 1
##   vals 
##   &lt;fct&gt;
## 1 S    
## 2 F</code></pre>
<p>Assign the probabilities of each possible outcome, remembering that the probabilities must sum to one:</p>
<ul>
<li>Probability of success (S) = probability of correctly guessing the symbol: <span class="math inline">\(p = 1/5\)</span></li>
<li>Probability of failure (F) is the complement to one: <span class="math inline">\(1 - p = 1 - 1/5 = 4/5\)</span>.</li>
</ul>
<div class="sourceCode" id="cb590"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb590-1" data-line-number="1">prob &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">5</span>, <span class="dv">4</span><span class="op">/</span><span class="dv">5</span>)</a></code></pre></div>
<p>Generate 1,000 samples of size <span class="math inline">\(n = 98\)</span> with the probabilities specified by the null hypothesis:</p>
<div class="sourceCode" id="cb591"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb591-1" data-line-number="1">samples &lt;-<span class="st"> </span><span class="kw">rep_sample_n</span>(outcomes, <span class="dt">size =</span> <span class="dv">98</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>, <span class="dt">reps =</span> <span class="dv">1000</span>, <span class="dt">prob =</span> prob)</a>
<a class="sourceLine" id="cb591-2" data-line-number="2">samples</a></code></pre></div>
<pre><code>## # A tibble: 98,000 x 2
## # Groups:   replicate [1,000]
##    replicate vals 
##        &lt;int&gt; &lt;fct&gt;
##  1         1 F    
##  2         1 F    
##  3         1 F    
##  4         1 S    
##  5         1 F    
##  6         1 S    
##  7         1 S    
##  8         1 F    
##  9         1 F    
## 10         1 F    
## # … with 97,990 more rows</code></pre>
<p>Note that the tibble has <span class="math inline">\(98,000\)</span> rows. Each sample of size <span class="math inline">\(n = 98\)</span> represents a sequence of 98 plays where each play can either be S (your partner correctly guessed your card) or F (your partner didn’t guess correctly). Hence, each sample is a sequence of S’s and F’s. Because we have 1,000 of such samples, the total number of rows will be <span class="math inline">\(98 \times 1,000 = 98,000\)</span>.</p>
<p>We can now compute the proportion of successes in each sample:</p>
<div class="sourceCode" id="cb593"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb593-1" data-line-number="1">null_distribution &lt;-<span class="st"> </span>samples <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb593-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb593-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">prop =</span> <span class="kw">sum</span>(vals <span class="op">==</span><span class="st"> &#39;S&#39;</span>) <span class="op">/</span><span class="st"> </span><span class="kw">n</span>())</a>
<a class="sourceLine" id="cb593-4" data-line-number="4"></a>
<a class="sourceLine" id="cb593-5" data-line-number="5">null_distribution</a></code></pre></div>
<pre><code>## # A tibble: 1,000 x 2
##    replicate  prop
##        &lt;int&gt; &lt;dbl&gt;
##  1         1 0.163
##  2         2 0.184
##  3         3 0.143
##  4         4 0.235
##  5         5 0.224
##  6         6 0.214
##  7         7 0.204
##  8         8 0.184
##  9         9 0.224
## 10        10 0.224
## # … with 990 more rows</code></pre>
<p>Let us now plot the 1,000 sample proportions obtained assuming the null hypothesis to be true. This plot shows the <strong>null distribution</strong>, and each dot represents one of the 1000 proportions from the above tibble:</p>
<div class="sourceCode" id="cb595"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb595-1" data-line-number="1"><span class="kw">ggplot</span>(null_distribution, <span class="kw">aes</span>(<span class="dt">x =</span> prop)) <span class="op">+</span></a>
<a class="sourceLine" id="cb595-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_dotplot</span>(<span class="dt">binwidth =</span> <span class="fl">0.01</span>, <span class="dt">dotsize =</span> <span class="fl">0.5</span>, <span class="dt">fill =</span> <span class="st">&#39;white&#39;</span>, <span class="dt">stackratio =</span> <span class="fl">0.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb595-3" data-line-number="3"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expr</span>(<span class="kw">hat</span>(p)))</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-371-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>Where does the sample statistic from <a href="chap-hyp-test.html#example-esp-results">Example 1</a> lie in the null distribution? Let’s add a red vertical line showing the value of the observed statistic, <span class="math inline">\(\hat{p} = 0.26\)</span>:</p>
<div class="sourceCode" id="cb596"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb596-1" data-line-number="1"><span class="kw">ggplot</span>(null_distribution, <span class="kw">aes</span>(<span class="dt">x =</span> prop)) <span class="op">+</span></a>
<a class="sourceLine" id="cb596-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_dotplot</span>(<span class="dt">binwidth =</span> <span class="fl">0.01</span>, <span class="dt">dotsize =</span> <span class="fl">0.5</span>, <span class="dt">fill =</span> <span class="st">&#39;white&#39;</span>, <span class="dt">stackratio =</span> <span class="fl">0.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb596-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="fl">0.26</span>, <span class="dt">color =</span> <span class="st">&#39;tomato1&#39;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb596-4" data-line-number="4"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expr</span>(<span class="kw">hat</span>(p)))</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-372-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>Do we have a high chance of observing the statistic <span class="math inline">\(\hat{p} = 0.26\)</span> under the null hypothesis of random guessing?</p>
<p>Different researchers might reach different conclusions by looking at this plot.
Rather than taking a decision by visually inspecting the plot, we want to find a generically applicable tool that would make different researchers all reach to the same conclusion.</p>
</div>
<div id="p-value" class="section level3 unnumbered">
<h3>P-value</h3>
<p>Recall now the definition of <a href="chap-hyp-test.html#def-statistical-significance">statistical significance</a>. We have evidence against the null hypothesis if it would be very unusual to obtain statistics as extreme or more extreme than the observed statistic in the null distribution.</p>
<p>To summarise: in order to measure how unusual the observed statistic is under the null hypothesis, we need to generate many statistics under the null hypothesis (null distribution) and see what’s the proportion of the generated statistics that are as extreme as, or more extreme than, the observed statistic.</p>
<p>The proportion of statistics in the null distribution as extreme or more extreme than the observed statistic is known as the <strong>p-value</strong>.</p>
<p><strong>The smaller the p-value, the higher the statistical evidence against the null hypothesis.</strong></p>
<div class="def">
<h4 id="p-value-1" class="unnumbered">P-value</h4>
<p>The <strong><em>p-value</em></strong> represents the chance of obtaining a statistic as extreme or more extreme than the observed one, if the null hypothesis were true.</p>
</div>
<p>In <a href="chap-hyp-test.html#example-esp-results">Example 1</a> on ESP, we can identify the statistics in the null distribution that are as extreme or more extreme than the observed one (<span class="math inline">\(\hat{p} = 0.26\)</span>) by colour-coding them:</p>
<div class="sourceCode" id="cb597"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb597-1" data-line-number="1"><span class="kw">ggplot</span>(null_distribution, <span class="kw">aes</span>(<span class="dt">x =</span> prop, <span class="dt">fill =</span> (prop <span class="op">&gt;=</span><span class="st"> </span><span class="fl">0.26</span>))) <span class="op">+</span></a>
<a class="sourceLine" id="cb597-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_dotplot</span>(<span class="dt">binwidth =</span> <span class="fl">0.01</span>, <span class="dt">dotsize =</span> <span class="fl">0.5</span>, <span class="dt">stackratio =</span> <span class="fl">0.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb597-3" data-line-number="3"><span class="st">  </span><span class="kw">scale_fill_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&#39;white&#39;</span>, <span class="st">&#39;tomato1&#39;</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb597-4" data-line-number="4"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expr</span>(<span class="kw">hat</span>(p)), <span class="dt">fill =</span> <span class="kw">expr</span>(<span class="kw">hat</span>(p) <span class="op">&gt;=</span><span class="st"> </span><span class="fl">0.26</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb597-5" data-line-number="5"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position=</span><span class="st">&quot;top&quot;</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-373-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>We now calculate the proportion of statistics in the null distribution which are greater than or equal 0.26. You can either do that by eye, counting the red dots and dividing them by the total number of dots (1,000) or, more quickly:</p>
<div class="sourceCode" id="cb598"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb598-1" data-line-number="1">pvalue &lt;-<span class="st"> </span>null_distribution <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb598-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">pvalue =</span> <span class="kw">sum</span>(prop <span class="op">&gt;=</span><span class="st"> </span><span class="fl">0.26</span>) <span class="op">/</span><span class="st"> </span><span class="kw">n</span>())</a>
<a class="sourceLine" id="cb598-3" data-line-number="3"></a>
<a class="sourceLine" id="cb598-4" data-line-number="4">pvalue</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   pvalue
##    &lt;dbl&gt;
## 1   0.07</code></pre>
<p><em><strong>Interpretation of the p-value:</strong> If we were to randomly guess the card symbol in <a href="chap-hyp-test.html#example-esp-results">Example 1</a>, the chance of getting a proportion as high as 0.26 is 0.07.</em></p>
<p>The p-value needs to be calculated in the direction specified by the alternative hypothesis:</p>
<ul>
<li>The p-value of a one-sided hypothesis is the proportion in tail specified by <span class="math inline">\(H_1\)</span>.</li>
<li>The p-value of a two-sided hypothesis is twice the proportion in the smallest tail, i.e. the tail with the smallest count.</li>
</ul>
<p>In the example below, the smallest tail (the tail with the lowest count) is the right tail. So if we were to perform an hypothesis test for the two-sided alternative <span class="math inline">\(p \neq 1/5\)</span>, we would compute it as twice the proportion of statistics greater than or equal to the observed statistic (twice the proportion in the right tail):
<img src="bookdown-demo_files/figure-html/unnamed-chunk-375-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p><em><strong>Note:</strong> If you were to calculate the p-value as twice the proportion in the bigger tail, you would obtain a p-value greater than 1. But remember, a probability must always be between 0 and 1!</em></p>
<p>You can calculate a p-value via randomization for any statistic:</p>
<ol style="list-style-type: decimal">
<li>Simulate many samples assuming <span class="math inline">\(H_0\)</span> to be true.</li>
<li>Compute the statistic on each of the simulated samples.</li>
<li>Compute the proportion of simulated statistics as extreme or more extreme than the observed statistic, in the direction specified by the alternative hypothesis.</li>
</ol>
</div>
<div id="making-a-formal-decision" class="section level3 unnumbered">
<h3>Making a formal decision</h3>
<p>The smaller the p-value, the greater the evidence that the data provide against the null hypothesis <span class="math inline">\(H_0\)</span>.</p>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>Which of the following p-values gives the strongest evidence against <span class="math inline">\(H_0\)</span>?</p>
<ol style="list-style-type: lower-alpha">
<li>0.005</li>
<li>0.1</li>
<li>0.35</li>
<li>0.92</li>
</ol>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-30" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-30&#39;, &#39;sol-start-30&#39;)"></span>
</p>
<div id="sol-body-30" class="solution-body" style="display: none;">
<p>The correct answer is (a) as it is the smallest p-value.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>To summarise, the outcome of a statistical test is either:</p>
<ol style="list-style-type: decimal">
<li>The p-value is small:
<ul>
<li>we reject the null hypothesis;</li>
<li>the observed sample statistic would be extreme in the null distribution;</li>
<li>the results are statistically significant;</li>
<li>the test concludes that we have enough evidence in favour of <span class="math inline">\(H_1\)</span>.</li>
</ul></li>
<li>The p-value is not small:
<ul>
<li>we do not reject the null hypothesis;</li>
<li>the observed sample statistic would not be extreme in the null distribution;</li>
<li>the results are not statistically significant;</li>
<li>we do not have sufficient evidence to reject <span class="math inline">\(H_0\)</span>.</li>
</ul></li>
</ol>
<p><strong>How small should the p-value be?</strong></p>
<p>This is set by the researcher before seeing any data.
We decide if a p-value is small or not by specifying a threshold below which a p-value is deemed to be small.</p>
<div class="def">
<h4 id="significance-level" class="unnumbered">Significance level</h4>
<p>The <strong><em>significance level</em></strong> <span class="math inline">\(\alpha\)</span> is the threshold below which we deem a p-value small enough to reject the null hypothesis.</p>
</div>
<p>For a given significance level <span class="math inline">\(\alpha\)</span>, specified before collecting any data:</p>
<ul>
<li>if the p-value <span class="math inline">\(\leq \alpha\)</span> we reject <span class="math inline">\(H_0\)</span>,</li>
<li>if the p-value <span class="math inline">\(&gt; \alpha\)</span> we do not reject <span class="math inline">\(H_0\)</span>.</li>
</ul>
<p>Typically, “default” choices for <span class="math inline">\(\alpha\)</span> are <span class="math inline">\(0.05\)</span> or <span class="math inline">\(0.01\)</span>.</p>
<p><em><strong>Caution:</strong> Never accept <span class="math inline">\(H_0\)</span>. “Do not reject <span class="math inline">\(H_0\)</span>” is not the same as “accept <span class="math inline">\(H_0\)</span>”. Not having sufficient evidence against <span class="math inline">\(H_0\)</span> does not mean having evidence for <span class="math inline">\(H_0\)</span>.</em></p>
<p>The following table summarizes in words the strength of evidence that the sample results bring in favour of the alternative hypothesis for different p-values:</p>
<table>
<thead>
<tr class="header">
<th align="center">p-value</th>
<th align="left">strength of evidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">0.1 <span class="math inline">\(&lt;\)</span> p-value</td>
<td align="left">not much evidence against null hypothesis</td>
</tr>
<tr class="even">
<td align="center">0.05 <span class="math inline">\(&lt;\)</span> p-value <span class="math inline">\(\leq\)</span> 0.1</td>
<td align="left">moderate evidence against the null hypothesis</td>
</tr>
<tr class="odd">
<td align="center">0.01 <span class="math inline">\(&lt;\)</span> p-value <span class="math inline">\(\leq\)</span> 0.05</td>
<td align="left">strong evidence against the null hypothesis</td>
</tr>
<tr class="even">
<td align="center">p-value <span class="math inline">\(\leq\)</span> 0.01</td>
<td align="left">very strong evidence against the null hypothesis</td>
</tr>
</tbody>
</table>
<p>We can now wrap up <a href="chap-hyp-test.html#example-esp-results">Example 1</a> on ESP, and conclude that at a significance level of 0.05, we do not reject the null hypothesis as the p-value 0.07 is greater than <span class="math inline">\(\alpha = 0.05\)</span>. Hence, the sample data do not show significant evidence for ESP.</p>
<p>An alternative to the p-value as a measure of the strength of evidence is given by the <strong>standardized statistic</strong>. This measures how many standard deviations away from the mean of the null distribution the observed statistic is. A standardized statistic is typically denoted by <span class="math inline">\(z\)</span>, and can be calculated as:</p>
<p><span class="math display">\[
\textrm{standardized statistic} = z = \frac{\textrm{statistic} - \textrm{mean of null distribution}}{\textrm{standard deviation of null distribution}}
\]</span></p>
<p>We interpret a standardized statistic according to the following table:</p>
<table>
<thead>
<tr class="header">
<th align="center">standardized statistic</th>
<th align="left">strength of evidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">between −1.5 and 1.5</td>
<td align="left">little or no evidence against the null hypothesis</td>
</tr>
<tr class="even">
<td align="center">below −1.5 or above 1.5</td>
<td align="left">moderate evidence against the null hypothesis</td>
</tr>
<tr class="odd">
<td align="center">below −2 or above 2</td>
<td align="left">strong evidence against the null hypothesis</td>
</tr>
<tr class="even">
<td align="center">below −3 or above 3</td>
<td align="left">very strong evidence against the null hypothesis</td>
</tr>
</tbody>
</table>
<p>To compute the standardized statistic for <a href="chap-hyp-test.html#example-esp-results">Example 1</a> on ESP, we first need to find the standard deviation of the null distribution:</p>
<div class="sourceCode" id="cb600"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb600-1" data-line-number="1">null_distribution <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb600-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">sd =</span> <span class="kw">sd</span>(prop))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##       sd
##    &lt;dbl&gt;
## 1 0.0404</code></pre>
The standardized statistic is then:
<center>
<span class="math display">\[
\textrm{standardized statistic} = z = \frac{0.26 - 0.20}{0.04} = 1.5
\]</span>
</center>
<p>If we interpreted the standardized statistic, rather than the p-value, for <a href="chap-hyp-test.html#example-esp-results">Example 1</a> on ESP, we would have reached the same conclusion. As the observed statistic (0.26) is only 1.5 standard deviations above the mean of the null distribution (0.20), the sample data bring little or no evidence against the null hypothesis, thus we do not reject <span class="math inline">\(H_0\)</span>.</p>
<p>This idealized version of a histogram shows how far from the mean of the null distribution each standardized statistic value is:
<img src="bookdown-demo_files/figure-html/standardized-statistic-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Recall from <a href="bootstrapping-and-confidence-intervals.html#calculating-confidence-intervals-using-a-bootstrap-standard-error">Week 12</a> that within 2 standard deviations around the mean lie approximately 95% of all values.
Similarly, within 3 standard deviations around the mean lie 99.7% of all values.</p>
<p><em><strong>Note:</strong> The p-value is a probability, so it’s always between 0 and 1. A standardized statistic, instead, can be positive or negative.</em></p>
</div>
</div>
<div id="summary-2" class="section level2">
<h2><span class="header-section-number">13.3</span> Summary</h2>
<p>Today we have learned to assess how much evidence the sample data bring against the null hypothesis and in favour of the alternative hypothesis.</p>
<p>The null hypothesis, denoted <span class="math inline">\(H_0\)</span>, is a claim about a population parameter that is initially assumed to be true. It typically represents “no effect” or “no difference between groups”.</p>
<p>The alternative hypothesis, denoted <span class="math inline">\(H_1\)</span>, is the claim we seek evidence for.</p>
<p>We assessed the strength of evidence against <span class="math inline">\(H_0\)</span> following these steps:</p>
<ol style="list-style-type: decimal">
<li>Generate many samples assuming the null hypothesis to be true;</li>
<li>Obtain the null distribution by computing the statistic on each of the generated samples;</li>
<li>Compute the p-value as the proportion of statistics in the null distribution as extreme or more extreme than the observed statistic, in the direction specified by the alternative hypothesis.</li>
</ol>
<p>The sample size and the observed statistic in the ESP experiment are:</p>
<div class="sourceCode" id="cb602"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb602-1" data-line-number="1">size &lt;-<span class="st"> </span><span class="dv">98</span></a>
<a class="sourceLine" id="cb602-2" data-line-number="2">observed_prop &lt;-<span class="st"> </span><span class="fl">0.26</span></a></code></pre></div>
<p>We obtained the null distribution with the following code:</p>
<div class="sourceCode" id="cb603"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb603-1" data-line-number="1">outcomes &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">vals =</span> <span class="kw">factor</span>(<span class="kw">c</span>(<span class="st">&#39;S&#39;</span>, <span class="st">&#39;F&#39;</span>)))</a>
<a class="sourceLine" id="cb603-2" data-line-number="2">prob &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span><span class="op">/</span><span class="dv">5</span>, <span class="dv">4</span><span class="op">/</span><span class="dv">5</span>)</a>
<a class="sourceLine" id="cb603-3" data-line-number="3">reps &lt;-<span class="st"> </span><span class="dv">1000</span></a>
<a class="sourceLine" id="cb603-4" data-line-number="4"></a>
<a class="sourceLine" id="cb603-5" data-line-number="5">null_distribution &lt;-<span class="st"> </span>outcomes <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb603-6" data-line-number="6"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> size, <span class="dt">replace =</span> <span class="ot">TRUE</span>, <span class="dt">reps =</span> reps, <span class="dt">prob =</span> prob) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb603-7" data-line-number="7"><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb603-8" data-line-number="8"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">prop =</span> <span class="kw">sum</span>(vals <span class="op">==</span><span class="st"> &#39;S&#39;</span>) <span class="op">/</span><span class="st"> </span><span class="kw">n</span>())</a></code></pre></div>
<p>The following code chunk plots the null distribution and shows in red the statistics that are as extreme or more extreme than the observed statistic:</p>
<div class="sourceCode" id="cb604"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb604-1" data-line-number="1"><span class="kw">ggplot</span>(null_distribution, <span class="kw">aes</span>(<span class="dt">x =</span> prop, <span class="dt">fill =</span> (prop <span class="op">&gt;=</span><span class="st"> </span>observed_prop))) <span class="op">+</span></a>
<a class="sourceLine" id="cb604-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_dotplot</span>(<span class="dt">binwidth =</span> <span class="fl">0.01</span>, <span class="dt">dotsize =</span> <span class="fl">0.5</span>, <span class="dt">stackratio =</span> <span class="fl">0.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb604-3" data-line-number="3"><span class="st">  </span><span class="kw">scale_fill_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&#39;white&#39;</span>, <span class="st">&#39;tomato1&#39;</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb604-4" data-line-number="4"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expr</span>(<span class="kw">hat</span>(p)), <span class="dt">fill =</span> <span class="kw">expr</span>(<span class="kw">hat</span>(p) <span class="op">&gt;=</span><span class="st"> </span><span class="op">!!</span>observed_prop)) <span class="op">+</span></a>
<a class="sourceLine" id="cb604-5" data-line-number="5"><span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position=</span><span class="st">&quot;top&quot;</span>)</a></code></pre></div>
<p>We compute the p-value as the proportion of statistics in the null distribution which are as extreme or more extreme than the observed statistic:</p>
<div class="sourceCode" id="cb605"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb605-1" data-line-number="1">pvalue &lt;-<span class="st"> </span>null_distribution <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb605-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">pvalue =</span> <span class="kw">sum</span>(prop <span class="op">&gt;=</span><span class="st"> </span>observed_prop) <span class="op">/</span><span class="st"> </span><span class="kw">n</span>())</a>
<a class="sourceLine" id="cb605-3" data-line-number="3"></a>
<a class="sourceLine" id="cb605-4" data-line-number="4">pvalue</a></code></pre></div>
</div>
<div id="lab-1" class="section level2">
<h2><span class="header-section-number">13.4</span> Lab</h2>
<div class="red">
<h4 id="w13-question-lab" class="unnumbered">Research question of the lab</h4>
<p>Has the average body temperature for healthy humans changed from the long-thought 37 °C?</p>
</div>
<p>In today’s lab we will investigate the average body temperature for healthy humans.
You might probably be thinking that the average is about 37 °C, and this is what most people would answer as this has been taken as granted for many years.</p>
<p>However, could it be possible that the average body temperature for healthy humans has changed over time? Perhaps this could be due to the climate change?</p>
<p>We will use data<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a> comprising measurements on body temperature and pulse rate for a sample of <span class="math inline">\(n = 50\)</span> healthy subjects.</p>
<p>Using the concepts learned today, the question boils down to:
<em>do the sample data provide significant evidence (at a 5% level) that the average body temperature is really different from the long-thought 37 °C?</em></p>
<div id="required-packages" class="section level3 unnumbered">
<h3>Required packages</h3>
<p>Before attempting to answer the following questions, make sure to run the following code chunk, which assumes that you have already installed the packages <code>tidyverse</code> and <code>moderndive</code>.
If you have not installed them yet, type <code>install.packages(&quot;tidyverse&quot;)</code> and <code>install.packages(&quot;moderndive&quot;)</code> in the R console.</p>
<p>Load the <code>tidyverse</code> and <code>moderndive</code> packages:</p>
<div class="sourceCode" id="cb606"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb606-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb606-2" data-line-number="2"><span class="kw">library</span>(moderndive)</a></code></pre></div>
</div>
<div id="importing-the-data" class="section level3 unnumbered">
<h3>Importing the data</h3>
<p>Let’s start by loading the data using the function <code>read_tsv</code> to read tab separated values:</p>
<div class="sourceCode" id="cb607"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb607-1" data-line-number="1">bodytemp &lt;-<span class="st"> </span><span class="kw">read_tsv</span>(<span class="st">&#39;https://edin.ac/2vkjSaw&#39;</span>)</a>
<a class="sourceLine" id="cb607-2" data-line-number="2">bodytemp</a></code></pre></div>
<pre><code>## # A tibble: 50 x 2
##    BodyTemp Pulse
##       &lt;dbl&gt; &lt;dbl&gt;
##  1     36.4    69
##  2     37.4    77
##  3     37.2    75
##  4     37.1    84
##  5     36.7    71
##  6     37.2    76
##  7     37.2    81
##  8     36.6    77
##  9     36      75
## 10     37.2    81
## # … with 40 more rows</code></pre>
</div>
<div id="data-inspection" class="section level3 unnumbered">
<h3>Data inspection</h3>
<div class="question">
<p class="question-begin">
► Question 1
</p>
<div class="question-body">
<ol style="list-style-type: decimal">
<li>What are the names of the variables in the dataset?</li>
<li>What are the dimensions of the tibble?</li>
<li>Are there any missing values? <em><strong>Hint:</strong> Use the function <code>anyNA()</code> to check if there are any Not Available (NA) entries.</em></li>
</ol>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-31" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-31&#39;, &#39;sol-start-31&#39;)"></span>
</p>
<div id="sol-body-31" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb609"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb609-1" data-line-number="1"><span class="kw">names</span>(bodytemp)</a></code></pre></div>
<pre><code>## [1] &quot;BodyTemp&quot; &quot;Pulse&quot;</code></pre>
<ol style="list-style-type: decimal">
<li>The variable names are <code>BodyTemp</code> and <code>Pulse</code>.</li>
</ol>
<div class="sourceCode" id="cb611"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb611-1" data-line-number="1"><span class="kw">dim</span>(bodytemp)</a></code></pre></div>
<pre><code>## [1] 50  2</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>The tibble has 50 rows and two columns.</li>
</ol>
<div class="sourceCode" id="cb613"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb613-1" data-line-number="1"><span class="kw">anyNA</span>(bodytemp)</a></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<ol start="3" style="list-style-type: decimal">
<li>The tibble does not appear to have missing values.</li>
</ol>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="sample-average-and-standard-deviation" class="section level3 unnumbered">
<h3>Sample average and standard deviation</h3>
<div class="question">
<p class="question-begin">
► Question 2
</p>
<div class="question-body">
<p>What is the average temperature in the sample and the standard deviation?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-32" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-32&#39;, &#39;sol-start-32&#39;)"></span>
</p>
<div id="sol-body-32" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb615"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb615-1" data-line-number="1">sample_stats &lt;-<span class="st"> </span>bodytemp <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb615-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg_temp =</span> <span class="kw">mean</span>(BodyTemp), </a>
<a class="sourceLine" id="cb615-3" data-line-number="3">            <span class="dt">sd_temp =</span> <span class="kw">sd</span>(BodyTemp))</a>
<a class="sourceLine" id="cb615-4" data-line-number="4"></a>
<a class="sourceLine" id="cb615-5" data-line-number="5">sample_stats</a></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   avg_temp sd_temp
##      &lt;dbl&gt;   &lt;dbl&gt;
## 1     36.8   0.425</code></pre>
<p>The average body temperature in the sample is <span class="math inline">\(\bar{x} =\)</span> 36.81 °C and the standard deviation is <span class="math inline">\(s =\)</span> 0.43 °C.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="null-and-alternative-hypothesis" class="section level3 unnumbered">
<h3>Null and alternative hypothesis</h3>
<div class="question">
<p class="question-begin">
► Question 3
</p>
<div class="question-body">
<p>State the null and alternative hypothesis for the research question of this lab.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-33" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-33&#39;, &#39;sol-start-33&#39;)"></span>
</p>
<div id="sol-body-33" class="solution-body" style="display: none;">
<center>
<span class="math display">\[
H_0: \ \mu = 37\ {}^\circ\mathrm{C} \\
H_1: \ \mu \neq 37\ {}^\circ\mathrm{C}
\]</span>
</center>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="bootstrap-distribution-and-null-distribution" class="section level3 unnumbered">
<h3>Bootstrap distribution and null distribution</h3>
<p>In order to calculate a p-value, we need to obtain the sampling distribution of the mean assuming that the null hypothesis is true (<strong>null distribution</strong>).</p>
<p>However, we only have one sample, so we must approximate the sampling distribution with a bootstrap distribution showing how the sample mean varies from bootstrap sample to bootstrap sample.</p>
<p>The required steps are:</p>
<ol style="list-style-type: decimal">
<li>Obtain a bootstrap distribution (this is centred at the sample mean <span class="math inline">\(\bar{x} =\)</span> 36.81)</li>
<li>Shift the bootstrap distribution to be centred at the parameter value specified in the null hypothesis (<span class="math inline">\(\mu =\)</span> 37). This is the null distribution.</li>
</ol>
<p><em><strong>Note:</strong> Why did we shift the bootstrap distribution to obtain the null distribution? Because the null distribution must be centred at the value of the population parameter specified in the null hypothesis.</em></p>
<div class="question">
<p class="question-begin">
► Question 4
</p>
<div class="question-body">
<p>Compute the bootstrap distribution of the mean using 10,000 repeated samples.</p>
<p>Plot the bootstrap distribution using a histogram.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-34" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-34&#39;, &#39;sol-start-34&#39;)"></span>
</p>
<div id="sol-body-34" class="solution-body" style="display: none;">
<p>The following code chunk computes the bootstrap distribution using 10,000 repeated samples:</p>
<div class="sourceCode" id="cb617"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb617-1" data-line-number="1">bootstrap_distribution &lt;-<span class="st"> </span>bodytemp <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb617-2" data-line-number="2"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">50</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>, <span class="dt">reps =</span> <span class="dv">10000</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb617-3" data-line-number="3"><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb617-4" data-line-number="4"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg_temp =</span> <span class="kw">mean</span>(BodyTemp))</a>
<a class="sourceLine" id="cb617-5" data-line-number="5"></a>
<a class="sourceLine" id="cb617-6" data-line-number="6">bootstrap_distribution</a></code></pre></div>
<pre><code>## # A tibble: 10,000 x 2
##    replicate avg_temp
##        &lt;int&gt;    &lt;dbl&gt;
##  1         1     36.7
##  2         2     36.8
##  3         3     36.8
##  4         4     36.7
##  5         5     36.9
##  6         6     36.8
##  7         7     36.8
##  8         8     36.8
##  9         9     36.9
## 10        10     36.8
## # … with 9,990 more rows</code></pre>
<p>Let’s plot the bootstrap distribution as a histogram, rather than a dotplot:</p>
<div class="sourceCode" id="cb619"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb619-1" data-line-number="1"><span class="kw">ggplot</span>(bootstrap_distribution, <span class="kw">aes</span>(<span class="dt">x =</span> avg_temp)) <span class="op">+</span></a>
<a class="sourceLine" id="cb619-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&#39;white&#39;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb619-3" data-line-number="3"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expr</span>(<span class="kw">bar</span>(x)))</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-388-1.png" width="672" /></p>
<p>The bootstrap distribution is centred around the sample mean:</p>
<div class="sourceCode" id="cb620"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb620-1" data-line-number="1">bootstrap_distribution <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb620-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg =</span> <span class="kw">mean</span>(avg_temp))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##     avg
##   &lt;dbl&gt;
## 1  36.8</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question 5
</p>
<div class="question-body">
<p>Compute the null distribution, which needs to be centred at the value of the parameter specified by the null hypothesis.</p>
<p>Plot the null distribution using a histogram.</p>
<p><em><strong>Hint</strong>: Since you already have the bootstrap distribution, which is centred at the sample mean, you can shift the original sample by adding to each body temperature the difference between the parameter value in the null hypothesis and the sample mean.</em></p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-35" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-35&#39;, &#39;sol-start-35&#39;)"></span>
</p>
<div id="sol-body-35" class="solution-body" style="display: none;">
<p>The null distribution needs to be centred at the value of the parameter specified by the null hypothesis.
The bootstrap distribution we computed earlier is centred at the sample mean.</p>
Recall that:
<center>
<span class="math display">\[
H_0: \ \mu = 37\ {}^\circ\mathrm{C} \\
H_1: \ \mu \neq 37\ {}^\circ\mathrm{C}
\]</span>
</center>
<p>We could shift the bootstrap distribution to have mean 37 °C by adding 37 - 36.81 °C = 0.19 °C to each body temperature in the sample.</p>
<p>Let us calculate the shift:</p>
<div class="sourceCode" id="cb622"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb622-1" data-line-number="1">null_hypothesis &lt;-<span class="st"> </span><span class="dv">37</span></a>
<a class="sourceLine" id="cb622-2" data-line-number="2"></a>
<a class="sourceLine" id="cb622-3" data-line-number="3">observed_mean &lt;-<span class="st"> </span>bodytemp <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb622-4" data-line-number="4"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg_temp =</span> <span class="kw">mean</span>(BodyTemp)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb622-5" data-line-number="5"><span class="st">  </span><span class="kw">pull</span>(avg_temp)</a>
<a class="sourceLine" id="cb622-6" data-line-number="6">observed_mean</a></code></pre></div>
<pre><code>## [1] 36.81111</code></pre>
<div class="sourceCode" id="cb624"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb624-1" data-line-number="1">shift &lt;-<span class="st"> </span>null_hypothesis <span class="op">-</span><span class="st"> </span>observed_mean</a>
<a class="sourceLine" id="cb624-2" data-line-number="2">shift</a></code></pre></div>
<pre><code>## [1] 0.1888889</code></pre>
<p>Shift the original sample data values:</p>
<div class="sourceCode" id="cb626"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb626-1" data-line-number="1">bodytemp_shifted &lt;-<span class="st"> </span>bodytemp <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb626-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">BodyTemp =</span> BodyTemp <span class="op">+</span><span class="st"> </span>shift)</a>
<a class="sourceLine" id="cb626-3" data-line-number="3"></a>
<a class="sourceLine" id="cb626-4" data-line-number="4">null_distribution &lt;-<span class="st"> </span>bodytemp_shifted <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb626-5" data-line-number="5"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">50</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>, <span class="dt">reps =</span> <span class="dv">10000</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb626-6" data-line-number="6"><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb626-7" data-line-number="7"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg_temp =</span> <span class="kw">mean</span>(BodyTemp))</a>
<a class="sourceLine" id="cb626-8" data-line-number="8">null_distribution</a></code></pre></div>
<pre><code>## # A tibble: 10,000 x 2
##    replicate avg_temp
##        &lt;int&gt;    &lt;dbl&gt;
##  1         1     37.1
##  2         2     37.1
##  3         3     37.0
##  4         4     36.9
##  5         5     37.0
##  6         6     37.1
##  7         7     37.1
##  8         8     36.9
##  9         9     36.9
## 10        10     37.1
## # … with 9,990 more rows</code></pre>
<p>The null distribution is centred at the parameter value specified in the null:</p>
<div class="sourceCode" id="cb628"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb628-1" data-line-number="1">null_distribution <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb628-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg =</span> <span class="kw">mean</span>(avg_temp))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##     avg
##   &lt;dbl&gt;
## 1  37.0</code></pre>
<p>We can visualise the null distribution using a histogram:</p>
<div class="sourceCode" id="cb630"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb630-1" data-line-number="1"><span class="kw">ggplot</span>(null_distribution, <span class="kw">aes</span>(<span class="dt">x =</span> avg_temp)) <span class="op">+</span></a>
<a class="sourceLine" id="cb630-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&#39;white&#39;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb630-3" data-line-number="3"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expr</span>(<span class="kw">bar</span>(x)))</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-393-1.png" width="672" /></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="visualise-the-observed-statistic-on-the-null-distribution" class="section level3 unnumbered">
<h3>Visualise the observed statistic on the null distribution</h3>
<div class="question">
<p class="question-begin">
► Question 6
</p>
<div class="question-body">
<p>Show a histogram of the null distribution, superimposing a vertical red line displaying the observed statistic.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-36" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-36&#39;, &#39;sol-start-36&#39;)"></span>
</p>
<div id="sol-body-36" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb631"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb631-1" data-line-number="1"><span class="kw">ggplot</span>(null_distribution, <span class="kw">aes</span>(<span class="dt">x =</span> avg_temp)) <span class="op">+</span></a>
<a class="sourceLine" id="cb631-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&#39;white&#39;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb631-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> observed_mean, <span class="dt">color =</span> <span class="st">&#39;tomato1&#39;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb631-4" data-line-number="4"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expr</span>(<span class="kw">bar</span>(x)))</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-394-1.png" width="672" /></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="p-value-2" class="section level3 unnumbered">
<h3>P-value</h3>
<div class="question">
<p class="question-begin">
► Question 7
</p>
<div class="question-body">
<p>Calculate the proportion of means as extreme as the observed statistic in the null distribution.</p>
<p><em><strong>Hint:</strong> As this is a double-sided alternative hypothesis, remember to use 2 * p-value of the smallest tail.</em></p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-37" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-37&#39;, &#39;sol-start-37&#39;)"></span>
</p>
<div id="sol-body-37" class="solution-body" style="display: none;">
<p>This is a two-sided alternative, hence the p-value is two times the proportion in the smallest tail.</p>
<p>Let’s plot the smallest tail:</p>
<div class="sourceCode" id="cb632"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb632-1" data-line-number="1"><span class="kw">ggplot</span>(null_distribution, <span class="kw">aes</span>(<span class="dt">x =</span> avg_temp, <span class="dt">fill =</span> (avg_temp <span class="op">&lt;=</span><span class="st"> </span>observed_mean))) <span class="op">+</span></a>
<a class="sourceLine" id="cb632-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&#39;black&#39;</span>, <span class="dt">binwidth =</span> <span class="fl">0.01</span>, <span class="dt">size =</span> <span class="fl">0.1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb632-3" data-line-number="3"><span class="st">  </span><span class="kw">scale_fill_manual</span>(<span class="dt">values =</span> <span class="kw">c</span>(<span class="st">&#39;white&#39;</span>, <span class="st">&#39;tomato1&#39;</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb632-4" data-line-number="4"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expr</span>(<span class="kw">bar</span>(x)), <span class="dt">fill =</span> <span class="kw">expr</span>(<span class="kw">bar</span>(x) <span class="op">&lt;=</span><span class="st"> </span><span class="op">!!</span><span class="kw">round</span>(observed_mean, <span class="dv">2</span>)))</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-395-1.png" width="672" /></p>
<div class="sourceCode" id="cb633"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb633-1" data-line-number="1">null_distribution <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb633-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">count_smaller =</span> <span class="kw">sum</span>(avg_temp <span class="op">&lt;=</span><span class="st"> </span>observed_mean))</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   count_smaller
##           &lt;int&gt;
## 1             7</code></pre>
<p>Out of the 10,000 means in the null distribution, 7 of them are lower than the observed sample statistic (36.81).</p>
<p>The proportion of means as low as the observed mean (36.81) in the null distribution is then:</p>
<div class="sourceCode" id="cb635"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb635-1" data-line-number="1">null_distribution <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb635-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">prop_smaller =</span> <span class="kw">sum</span>(avg_temp <span class="op">&lt;=</span><span class="st"> </span>observed_mean) <span class="op">/</span><span class="st"> </span><span class="kw">n</span>())</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   prop_smaller
##          &lt;dbl&gt;
## 1       0.0007</code></pre>
<p>Since this test has a double-sided alternative, we must double this proportion in order to obtain the p-value. This represents the proportion of means in the null distribution as extreme as the observed one:</p>
<div class="sourceCode" id="cb637"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb637-1" data-line-number="1">pvalue &lt;-<span class="st"> </span>null_distribution <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb637-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">pvalue =</span> <span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">sum</span>(avg_temp <span class="op">&lt;=</span><span class="st"> </span>observed_mean) <span class="op">/</span><span class="st"> </span><span class="kw">n</span>())</a>
<a class="sourceLine" id="cb637-3" data-line-number="3"></a>
<a class="sourceLine" id="cb637-4" data-line-number="4">pvalue</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   pvalue
##    &lt;dbl&gt;
## 1 0.0014</code></pre>
<p>The p-value is equal to 0.0014.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="interpreting-the-p-value" class="section level3 unnumbered">
<h3>Interpreting the p-value</h3>
<div class="question">
<p class="question-begin">
► Question 8
</p>
<div class="question-body">
<p>Using the p-value found in the previous question, how would you answer the <a href="chap-hyp-test.html#w13-question-lab">research question</a> of the lab?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-38" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-38&#39;, &#39;sol-start-38&#39;)"></span>
</p>
<div id="sol-body-38" class="solution-body" style="display: none;">
<p>At a significance level of 5%, the very small p-value we have found, 0.0014 &lt; 0.05, gives very strong evidence against the null hypothesis that the average body temperature for healthy humans is 37 °C.</p>
<p>However, it is worth noting the difference between <em>statistical significance</em> and <em>practical significance</em>.
Even if the sample results lead to convincingly rejecting the null hypothesis, assuming the average body temperature for healthy humans to be closer to 36.8 °C rather than 37 °C has a very minimal impact in practice.
More generally, with large sample sizes a small difference might turn out to be statistically significant.
However, this does not mean that the difference will be of practical importance to decision-makers.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
</div>
<div id="glossary-2" class="section level2">
<h2><span class="header-section-number">13.5</span> Glossary</h2>
<ul>
<li><em>Alternative hypothesis.</em> A claim about the population parameter for which we seek evidence for. It contradicts the null hypothesis.</li>
<li><em>Statistical test.</em> A set of principles for measuring the strength of evidence against a null hypothesis about the parameter of interest.</li>
<li><em>Null hypothesis.</em> A claim about the population parameter typically involving “no effect” or “no difference between groups”.</li>
<li><em>Null distribution.</em> The values of the statistic that we expect to obtain by sampling variation if the null hypothesis is true. In other words, the sampling distribution of the statistic assuming the null hypothesis to be true.</li>
<li><em>P-value.</em> The probability of obtaining a value of the statistic at least as extreme as the observed statistic when the null hypothesis is true.</li>
<li><em>Significance level.</em> A threshold used as a criterion for deciding when a p-value is small enough to provide convincing evidence against the null hypothesis. It is typically denoted by <span class="math inline">\(\alpha\)</span> and common values are 0.01 or 0.05.</li>
<li><em>Statistically significant.</em> Unlikely to occur just by random chance.</li>
</ul>
</div>
<div id="references-2" class="section level2">
<h2><span class="header-section-number">13.6</span> References</h2>
<ul>
<li>Lock, R. H., Lock, P. F., Morgan, K. L., Lock, E. F., &amp; Lock, D. F. (2013). <em>Statistics: Unlocking the power of data.</em> John Wiley &amp; Sons.</li>
<li>Tintle, N., Chance, B. L., Cobb, G. W., Rossman, A. J., Roy, S., Swanson, T., &amp; VanderStoep, J. (2015). <em>Introduction to statistical investigations.</em> New York: Wiley.</li>
</ul>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="5">
<li id="fn5"><p>Shoemaker, A. L. (1996). <em>What’s Normal: Temperature, Gender and Heartrate. Journal of Statistics Education, 4</em>(2), 4.<a href="chap-hyp-test.html#fnref5" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="bootstrapping-and-confidence-intervals.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-typeerror.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
