<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 15 Normal distribution &amp; probability | Data Analysis for Psychology in R (dapR1) - Labs</title>
  <meta name="description" content="This is the page that contains the course labs materials" />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 15 Normal distribution &amp; probability | Data Analysis for Psychology in R (dapR1) - Labs" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the page that contains the course labs materials" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 15 Normal distribution &amp; probability | Data Analysis for Psychology in R (dapR1) - Labs" />
  
  <meta name="twitter:description" content="This is the page that contains the course labs materials" />
  

<meta name="author" content="Department of Psychology, University of Edinburgh" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="chap-typeerror.html"/>
<link rel="next" href="chap-one-mean-test.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script>
  $(document).ready(function() {
    $head = $('#header');
    $head.prepend('<img style="padding-right:25%; margin-bottom:10px;" src="https://www.ed.ac.uk/sites/all/themes/uoe/assets/logo.png" width="770px" align="left">')
  });
</script>

<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}
}
</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">DAPR1</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview of the Course</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#the-team"><i class="fa fa-check"></i>The team</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-cheatsheets"><i class="fa fa-check"></i>R Cheatsheets</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-community"><i class="fa fa-check"></i>R Community</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="week-1.html"><a href="week-1.html"><i class="fa fa-check"></i><b>1</b> Week 1</a><ul>
<li class="chapter" data-level="1.1" data-path="week-1.html"><a href="week-1.html#introduction-to-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> Introduction to R and RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="week-1.html"><a href="week-1.html#install-the-recent-version-of-r-and-r-studio"><i class="fa fa-check"></i><b>1.2</b> Install the recent version of R and R Studio</a><ul>
<li class="chapter" data-level="1.2.1" data-path="week-1.html"><a href="week-1.html#first-step"><i class="fa fa-check"></i><b>1.2.1</b> First Step</a></li>
<li class="chapter" data-level="1.2.2" data-path="week-1.html"><a href="week-1.html#second-step"><i class="fa fa-check"></i><b>1.2.2</b> Second Step</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="week-1.html"><a href="week-1.html#getting-started-in-rstudio"><i class="fa fa-check"></i><b>1.3</b> Getting Started in RStudio</a></li>
<li class="chapter" data-level="1.4" data-path="week-1.html"><a href="week-1.html#r-as-an-interactive-environment"><i class="fa fa-check"></i><b>1.4</b> R as an interactive environment</a></li>
<li class="chapter" data-level="1.5" data-path="week-1.html"><a href="week-1.html#check-your-settings"><i class="fa fa-check"></i><b>1.5</b> Check your settings</a><ul>
<li class="chapter" data-level="1.5.1" data-path="week-1.html"><a href="week-1.html#disable-automatic-saving-of-your-workspace"><i class="fa fa-check"></i><b>1.5.1</b> Disable automatic saving of your workspace</a></li>
<li class="chapter" data-level="1.5.2" data-path="week-1.html"><a href="week-1.html#adjust-fontscolours-if-you-like"><i class="fa fa-check"></i><b>1.5.2</b> Adjust fonts/colours if you like</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="week-1.html"><a href="week-1.html#setting-up-your-working-directory"><i class="fa fa-check"></i><b>1.6</b> Setting Up Your Working Directory</a></li>
<li class="chapter" data-level="1.7" data-path="week-1.html"><a href="week-1.html#the-console"><i class="fa fa-check"></i><b>1.7</b> The Console</a></li>
<li class="chapter" data-level="1.8" data-path="week-1.html"><a href="week-1.html#spacing"><i class="fa fa-check"></i><b>1.8</b> Spacing</a></li>
<li class="chapter" data-level="1.9" data-path="week-1.html"><a href="week-1.html#typos"><i class="fa fa-check"></i><b>1.9</b> Typos</a></li>
<li class="chapter" data-level="1.10" data-path="week-1.html"><a href="week-1.html#unfinishe.-d"><i class="fa fa-check"></i><b>1.10</b> Unfinishe…. d</a></li>
<li class="chapter" data-level="1.11" data-path="week-1.html"><a href="week-1.html#basic-arithmetic"><i class="fa fa-check"></i><b>1.11</b> Basic Arithmetic</a></li>
<li class="chapter" data-level="1.12" data-path="week-1.html"><a href="week-1.html#using-functions-for-calculations"><i class="fa fa-check"></i><b>1.12</b> Using Functions for Calculations</a></li>
<li class="chapter" data-level="1.13" data-path="week-1.html"><a href="week-1.html#r-scripts"><i class="fa fa-check"></i><b>1.13</b> R Scripts</a></li>
<li class="chapter" data-level="1.14" data-path="week-1.html"><a href="week-1.html#short-example"><i class="fa fa-check"></i><b>1.14</b> Short Example</a></li>
<li class="chapter" data-level="1.15" data-path="week-1.html"><a href="week-1.html#naming-variables"><i class="fa fa-check"></i><b>1.15</b> Naming variables</a></li>
<li class="chapter" data-level="1.16" data-path="week-1.html"><a href="week-1.html#now-over-to-you"><i class="fa fa-check"></i><b>1.16</b> Now over to you</a><ul>
<li class="chapter" data-level="1.16.1" data-path="week-1.html"><a href="week-1.html#exercise-1"><i class="fa fa-check"></i><b>1.16.1</b> Exercise 1</a></li>
<li class="chapter" data-level="1.16.2" data-path="week-1.html"><a href="week-1.html#exercise-2"><i class="fa fa-check"></i><b>1.16.2</b> Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="1.17" data-path="week-1.html"><a href="week-1.html#solutions"><i class="fa fa-check"></i><b>1.17</b> Solutions</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="week-2.html"><a href="week-2.html"><i class="fa fa-check"></i><b>2</b> Week 2</a><ul>
<li class="chapter" data-level="2.1" data-path="week-2.html"><a href="week-2.html#introduction-to-rmarkdown"><i class="fa fa-check"></i><b>2.1</b> Introduction to RMarkdown</a></li>
<li class="chapter" data-level="2.2" data-path="week-2.html"><a href="week-2.html#what-is-r-markdown"><i class="fa fa-check"></i><b>2.2</b> What is R Markdown?</a></li>
<li class="chapter" data-level="2.3" data-path="week-2.html"><a href="week-2.html#getting-things-ready"><i class="fa fa-check"></i><b>2.3</b> Getting things ready</a></li>
<li class="chapter" data-level="2.4" data-path="week-2.html"><a href="week-2.html#r-markdown-basics"><i class="fa fa-check"></i><b>2.4</b> R Markdown basics</a></li>
<li class="chapter" data-level="2.5" data-path="week-2.html"><a href="week-2.html#headings"><i class="fa fa-check"></i><b>2.5</b> Headings</a></li>
<li class="chapter" data-level="2.6" data-path="week-2.html"><a href="week-2.html#text"><i class="fa fa-check"></i><b>2.6</b> Text</a></li>
<li class="chapter" data-level="2.7" data-path="week-2.html"><a href="week-2.html#tables"><i class="fa fa-check"></i><b>2.7</b> Tables</a></li>
<li class="chapter" data-level="2.8" data-path="week-2.html"><a href="week-2.html#lists"><i class="fa fa-check"></i><b>2.8</b> Lists</a><ul>
<li class="chapter" data-level="2.8.1" data-path="week-2.html"><a href="week-2.html#unordered"><i class="fa fa-check"></i><b>2.8.1</b> Unordered</a></li>
<li class="chapter" data-level="2.8.2" data-path="week-2.html"><a href="week-2.html#ordered"><i class="fa fa-check"></i><b>2.8.2</b> Ordered</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="week-2.html"><a href="week-2.html#rmd-documents"><i class="fa fa-check"></i><b>2.9</b> Rmd documents</a></li>
<li class="chapter" data-level="2.10" data-path="week-2.html"><a href="week-2.html#code-chunks"><i class="fa fa-check"></i><b>2.10</b> Code chunks</a></li>
<li class="chapter" data-level="2.11" data-path="week-2.html"><a href="week-2.html#common-code-chunks-options"><i class="fa fa-check"></i><b>2.11</b> Common Code Chunks Options</a></li>
<li class="chapter" data-level="2.12" data-path="week-2.html"><a href="week-2.html#including-images-or-links"><i class="fa fa-check"></i><b>2.12</b> Including images or links</a><ul>
<li class="chapter" data-level="2.12.1" data-path="week-2.html"><a href="week-2.html#adding-links"><i class="fa fa-check"></i><b>2.12.1</b> Adding links</a></li>
<li class="chapter" data-level="2.12.2" data-path="week-2.html"><a href="week-2.html#adding-figures-pictures"><i class="fa fa-check"></i><b>2.12.2</b> Adding figures &amp; pictures</a></li>
</ul></li>
<li class="chapter" data-level="2.13" data-path="week-2.html"><a href="week-2.html#generating-documents"><i class="fa fa-check"></i><b>2.13</b> Generating documents</a></li>
<li class="chapter" data-level="2.14" data-path="week-2.html"><a href="week-2.html#extra-opensave-files-on-rstudio-cloud-chrome-users"><i class="fa fa-check"></i><b>2.14</b> Extra: Open/Save files on Rstudio Cloud (Chrome users)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-3.html"><a href="week-3.html"><i class="fa fa-check"></i><b>3</b> Week 3</a><ul>
<li class="chapter" data-level="3.1" data-path="week-3.html"><a href="week-3.html#vectors-lists-data-frames-and-data-types"><i class="fa fa-check"></i><b>3.1</b> Vectors, lists, data frames and data types</a></li>
<li class="chapter" data-level="3.2" data-path="week-3.html"><a href="week-3.html#get-the-package-first"><i class="fa fa-check"></i><b>3.2</b> Get the package first</a></li>
<li class="chapter" data-level="3.3" data-path="week-3.html"><a href="week-3.html#numeric-data"><i class="fa fa-check"></i><b>3.3</b> Numeric Data</a></li>
<li class="chapter" data-level="3.4" data-path="week-3.html"><a href="week-3.html#textcharacter-data"><i class="fa fa-check"></i><b>3.4</b> Text/Character Data</a></li>
<li class="chapter" data-level="3.5" data-path="week-3.html"><a href="week-3.html#logical-data"><i class="fa fa-check"></i><b>3.5</b> Logical Data</a></li>
<li class="chapter" data-level="3.6" data-path="week-3.html"><a href="week-3.html#variable-classes"><i class="fa fa-check"></i><b>3.6</b> Variable Classes</a></li>
<li class="chapter" data-level="3.7" data-path="week-3.html"><a href="week-3.html#factors"><i class="fa fa-check"></i><b>3.7</b> Factors</a></li>
<li class="chapter" data-level="3.8" data-path="week-3.html"><a href="week-3.html#lists-1"><i class="fa fa-check"></i><b>3.8</b> Lists</a></li>
<li class="chapter" data-level="3.9" data-path="week-3.html"><a href="week-3.html#practice.rmd-solutions"><i class="fa fa-check"></i><b>3.9</b> Practice.Rmd Solutions</a><ul>
<li class="chapter" data-level="3.9.1" data-path="week-3.html"><a href="week-3.html#exercise-1-1"><i class="fa fa-check"></i><b>3.9.1</b> Exercise 1</a></li>
<li class="chapter" data-level="3.9.2" data-path="week-3.html"><a href="week-3.html#exercise-2-1"><i class="fa fa-check"></i><b>3.9.2</b> Exercise 2</a></li>
<li class="chapter" data-level="3.9.3" data-path="week-3.html"><a href="week-3.html#exercise-3"><i class="fa fa-check"></i><b>3.9.3</b> Exercise 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-4.html"><a href="week-4.html"><i class="fa fa-check"></i><b>4</b> Week 4</a><ul>
<li class="chapter" data-level="4.1" data-path="week-4.html"><a href="week-4.html#introduction-to-plots-geoms-ggplot"><i class="fa fa-check"></i><b>4.1</b> Introduction to plots &amp; geoms (ggplot)</a></li>
<li class="chapter" data-level="4.2" data-path="week-4.html"><a href="week-4.html#visualisations"><i class="fa fa-check"></i><b>4.2</b> Visualisations</a></li>
<li class="chapter" data-level="4.3" data-path="week-4.html"><a href="week-4.html#get-our-data-sorted"><i class="fa fa-check"></i><b>4.3</b> Get our data sorted</a></li>
<li class="chapter" data-level="4.4" data-path="week-4.html"><a href="week-4.html#numerical-data"><i class="fa fa-check"></i><b>4.4</b> Numerical data</a></li>
<li class="chapter" data-level="4.5" data-path="week-4.html"><a href="week-4.html#simple-one-variable-plot-using-ggplot"><i class="fa fa-check"></i><b>4.5</b> Simple one-variable plot using ggplot()</a><ul>
<li class="chapter" data-level="4.5.1" data-path="week-4.html"><a href="week-4.html#continuous-variable"><i class="fa fa-check"></i><b>4.5.1</b> Continuous variable</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="week-4.html"><a href="week-4.html#categorical-variables"><i class="fa fa-check"></i><b>4.6</b> Categorical variables</a></li>
<li class="chapter" data-level="4.7" data-path="week-4.html"><a href="week-4.html#continuous-variables-grouped-by-a-categorical-one"><i class="fa fa-check"></i><b>4.7</b> Continuous variables grouped by a categorical one</a></li>
<li class="chapter" data-level="4.8" data-path="week-4.html"><a href="week-4.html#even-more-advanced"><i class="fa fa-check"></i><b>4.8</b> Even more advanced</a></li>
<li class="chapter" data-level="4.9" data-path="week-4.html"><a href="week-4.html#practice.rmd-solutions-1"><i class="fa fa-check"></i><b>4.9</b> Practice.Rmd Solutions</a><ul>
<li class="chapter" data-level="4.9.1" data-path="week-4.html"><a href="week-4.html#exercise-1-2"><i class="fa fa-check"></i><b>4.9.1</b> Exercise 1</a></li>
<li class="chapter" data-level="4.9.2" data-path="week-4.html"><a href="week-4.html#exercise-2-2"><i class="fa fa-check"></i><b>4.9.2</b> Exercise 2</a></li>
<li class="chapter" data-level="4.9.3" data-path="week-4.html"><a href="week-4.html#exercise-3---advanced"><i class="fa fa-check"></i><b>4.9.3</b> Exercise 3 - Advanced</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-5.html"><a href="week-5.html"><i class="fa fa-check"></i><b>5</b> Week 5</a><ul>
<li class="chapter" data-level="5.1" data-path="week-5.html"><a href="week-5.html#central-tendency-and-variability"><i class="fa fa-check"></i><b>5.1</b> Central Tendency and Variability</a></li>
<li class="chapter" data-level="5.2" data-path="week-5.html"><a href="week-5.html#load-all-the-necessary-packages"><i class="fa fa-check"></i><b>5.2</b> Load all the necessary packages</a></li>
<li class="chapter" data-level="5.3" data-path="week-5.html"><a href="week-5.html#descriptive-statistics"><i class="fa fa-check"></i><b>5.3</b> Descriptive Statistics</a></li>
<li class="chapter" data-level="5.4" data-path="week-5.html"><a href="week-5.html#central-tendency-variability"><i class="fa fa-check"></i><b>5.4</b> Central tendency &amp; variability</a></li>
<li class="chapter" data-level="5.5" data-path="week-5.html"><a href="week-5.html#mean-and-median"><i class="fa fa-check"></i><b>5.5</b> Mean and median</a><ul>
<li class="chapter" data-level="5.5.1" data-path="week-5.html"><a href="week-5.html#reading-data-in"><i class="fa fa-check"></i><b>5.5.1</b> Reading data in</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="week-5.html"><a href="week-5.html#using-piping-operator-for-descriptive-statistics"><i class="fa fa-check"></i><b>5.6</b> Using piping operator for descriptive statistics</a><ul>
<li class="chapter" data-level="5.6.1" data-path="week-5.html"><a href="week-5.html#mean"><i class="fa fa-check"></i><b>5.6.1</b> Mean</a></li>
<li class="chapter" data-level="5.6.2" data-path="week-5.html"><a href="week-5.html#median"><i class="fa fa-check"></i><b>5.6.2</b> Median</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="week-5.html"><a href="week-5.html#standard-deviation"><i class="fa fa-check"></i><b>5.7</b> Standard deviation</a></li>
<li class="chapter" data-level="5.8" data-path="week-5.html"><a href="week-5.html#visualise-your-data"><i class="fa fa-check"></i><b>5.8</b> Visualise your data</a></li>
<li class="chapter" data-level="5.9" data-path="week-5.html"><a href="week-5.html#practice.rmd-solutions-2"><i class="fa fa-check"></i><b>5.9</b> Practice.Rmd Solutions</a><ul>
<li class="chapter" data-level="5.9.1" data-path="week-5.html"><a href="week-5.html#income-distribution-example"><i class="fa fa-check"></i><b>5.9.1</b> Income Distribution Example</a></li>
<li class="chapter" data-level="5.9.2" data-path="week-5.html"><a href="week-5.html#visualisations-1"><i class="fa fa-check"></i><b>5.9.2</b> Visualisations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-6.html"><a href="week-6.html"><i class="fa fa-check"></i><b>6</b> Week 6</a><ul>
<li class="chapter" data-level="6.1" data-path="week-6.html"><a href="week-6.html#plotting-functions-and-simple-data-transformation"><i class="fa fa-check"></i><b>6.1</b> Plotting Functions and Simple Data Transformation</a></li>
<li class="chapter" data-level="6.2" data-path="week-6.html"><a href="week-6.html#load-all-the-necessary-packages-1"><i class="fa fa-check"></i><b>6.2</b> Load all the necessary packages</a></li>
<li class="chapter" data-level="6.3" data-path="week-6.html"><a href="week-6.html#part-1-hand-plotting-functions"><i class="fa fa-check"></i><b>6.3</b> Part 1: Hand plotting functions</a></li>
<li class="chapter" data-level="6.4" data-path="week-6.html"><a href="week-6.html#basics"><i class="fa fa-check"></i><b>6.4</b> Basics</a></li>
<li class="chapter" data-level="6.5" data-path="week-6.html"><a href="week-6.html#linear-functions"><i class="fa fa-check"></i><b>6.5</b> Linear functions</a><ul>
<li class="chapter" data-level="6.5.1" data-path="week-6.html"><a href="week-6.html#tree-height-example"><i class="fa fa-check"></i><b>6.5.1</b> Tree height example</a></li>
<li class="chapter" data-level="6.5.2" data-path="week-6.html"><a href="week-6.html#non-linear-functions-first-order-polynomials"><i class="fa fa-check"></i><b>6.5.2</b> Non-linear functions (first order polynomials)</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="week-6.html"><a href="week-6.html#practice-plotting"><i class="fa fa-check"></i><b>6.6</b> Practice plotting</a></li>
<li class="chapter" data-level="6.7" data-path="week-6.html"><a href="week-6.html#part-2-introduction-to-data-transformation"><i class="fa fa-check"></i><b>6.7</b> Part 2: Introduction to Data Transformation</a></li>
<li class="chapter" data-level="6.8" data-path="week-6.html"><a href="week-6.html#renaming"><i class="fa fa-check"></i><b>6.8</b> Renaming</a></li>
<li class="chapter" data-level="6.9" data-path="week-6.html"><a href="week-6.html#adding-new-variables"><i class="fa fa-check"></i><b>6.9</b> Adding new variables</a></li>
<li class="chapter" data-level="6.10" data-path="week-6.html"><a href="week-6.html#transformation-and-skewness"><i class="fa fa-check"></i><b>6.10</b> Transformation and skewness</a></li>
<li class="chapter" data-level="6.11" data-path="week-6.html"><a href="week-6.html#mean-centering"><i class="fa fa-check"></i><b>6.11</b> Mean Centering</a></li>
<li class="chapter" data-level="6.12" data-path="week-6.html"><a href="week-6.html#standardisation"><i class="fa fa-check"></i><b>6.12</b> Standardisation</a></li>
<li class="chapter" data-level="6.13" data-path="week-6.html"><a href="week-6.html#practice.rmd-solutions-3"><i class="fa fa-check"></i><b>6.13</b> Practice.Rmd Solutions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="week-7.html"><a href="week-7.html"><i class="fa fa-check"></i><b>7</b> Week 7</a><ul>
<li class="chapter" data-level="7.1" data-path="week-7.html"><a href="week-7.html#reading-in-data-merge-and-more-r-practice"><i class="fa fa-check"></i><b>7.1</b> Reading in Data, Merge and More R Practice</a></li>
<li class="chapter" data-level="7.2" data-path="week-7.html"><a href="week-7.html#dataset-1-.csv"><i class="fa fa-check"></i><b>7.2</b> Dataset 1 (.csv)</a></li>
<li class="chapter" data-level="7.3" data-path="week-7.html"><a href="week-7.html#dataset-2-.txt"><i class="fa fa-check"></i><b>7.3</b> Dataset 2 (.txt)</a></li>
<li class="chapter" data-level="7.4" data-path="week-7.html"><a href="week-7.html#dataset-3-.sav-and-.dta"><i class="fa fa-check"></i><b>7.4</b> Dataset 3 (.sav and .dta)</a></li>
<li class="chapter" data-level="7.5" data-path="week-7.html"><a href="week-7.html#merging-datasets-together"><i class="fa fa-check"></i><b>7.5</b> Merging datasets together</a></li>
<li class="chapter" data-level="7.6" data-path="week-7.html"><a href="week-7.html#sorting-and-arrange"><i class="fa fa-check"></i><b>7.6</b> Sorting and arrange()</a></li>
<li class="chapter" data-level="7.7" data-path="week-7.html"><a href="week-7.html#data-description"><i class="fa fa-check"></i><b>7.7</b> Data description</a></li>
<li class="chapter" data-level="7.8" data-path="week-7.html"><a href="week-7.html#using-filter"><i class="fa fa-check"></i><b>7.8</b> Using filter()</a></li>
<li class="chapter" data-level="7.9" data-path="week-7.html"><a href="week-7.html#visualisations-2"><i class="fa fa-check"></i><b>7.9</b> Visualisations</a></li>
<li class="chapter" data-level="7.10" data-path="week-7.html"><a href="week-7.html#save-the-file-in-your-folder"><i class="fa fa-check"></i><b>7.10</b> Save the file in your folder</a></li>
<li class="chapter" data-level="7.11" data-path="week-7.html"><a href="week-7.html#practice.rmd-solutions-4"><i class="fa fa-check"></i><b>7.11</b> Practice.Rmd Solutions</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="week-8.html"><a href="week-8.html"><i class="fa fa-check"></i><b>8</b> Week 8</a><ul>
<li class="chapter" data-level="8.1" data-path="week-8.html"><a href="week-8.html#introduction-to-probability"><i class="fa fa-check"></i><b>8.1</b> Introduction to Probability</a></li>
<li class="chapter" data-level="8.2" data-path="week-8.html"><a href="week-8.html#example-1-hot-hand"><i class="fa fa-check"></i><b>8.2</b> Example 1 (hot hand)</a></li>
<li class="chapter" data-level="8.3" data-path="week-8.html"><a href="week-8.html#example-2-coin-toss"><i class="fa fa-check"></i><b>8.3</b> Example 2 (coin toss)</a></li>
<li class="chapter" data-level="8.4" data-path="week-8.html"><a href="week-8.html#example-3-independent-shooter"><i class="fa fa-check"></i><b>8.4</b> Example 3 (Independent shooter)</a></li>
<li class="chapter" data-level="8.5" data-path="week-8.html"><a href="week-8.html#practice-rmd.-solutions"><i class="fa fa-check"></i><b>8.5</b> Practice Rmd. Solutions</a><ul>
<li class="chapter" data-level="8.5.1" data-path="week-8.html"><a href="week-8.html#sex-of-the-babies-born-in-the-uk"><i class="fa fa-check"></i><b>8.5.1</b> Sex of the babies born in the UK</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="week-8.html"><a href="week-8.html#pen-and-paper-exercises"><i class="fa fa-check"></i><b>8.6</b> Pen and Paper Exercises</a><ul>
<li class="chapter" data-level="8.6.1" data-path="week-8.html"><a href="week-8.html#boys-and-girls-paradox-mr.jones-and-mr.smith"><i class="fa fa-check"></i><b>8.6.1</b> Boys and girls paradox (Mr. Jones and Mr. Smith)</a></li>
<li class="chapter" data-level="8.6.2" data-path="week-8.html"><a href="week-8.html#rugby-captain"><i class="fa fa-check"></i><b>8.6.2</b> Rugby captain</a></li>
<li class="chapter" data-level="8.6.3" data-path="week-8.html"><a href="week-8.html#answers"><i class="fa fa-check"></i><b>8.6.3</b> Answers</a></li>
<li class="chapter" data-level="8.6.4" data-path="week-8.html"><a href="week-8.html#defective"><i class="fa fa-check"></i><b>8.6.4</b> Defective</a></li>
<li class="chapter" data-level="8.6.5" data-path="week-8.html"><a href="week-8.html#answers-1"><i class="fa fa-check"></i><b>8.6.5</b> Answers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="week-9.html"><a href="week-9.html"><i class="fa fa-check"></i><b>9</b> Week 9</a><ul>
<li class="chapter" data-level="9.1" data-path="week-9.html"><a href="week-9.html#introduction-to-probability-distributions-and-revision"><i class="fa fa-check"></i><b>9.1</b> Introduction to Probability Distributions and Revision</a></li>
<li class="chapter" data-level="9.2" data-path="week-9.html"><a href="week-9.html#discrete-example-guessing-homework-answers"><i class="fa fa-check"></i><b>9.2</b> Discrete example (guessing homework answers)</a></li>
<li class="chapter" data-level="9.3" data-path="week-9.html"><a href="week-9.html#generate-a-homework-attempt"><i class="fa fa-check"></i><b>9.3</b> Generate a homework attempt</a></li>
<li class="chapter" data-level="9.4" data-path="week-9.html"><a href="week-9.html#changing-the-probability-truefalse"><i class="fa fa-check"></i><b>9.4</b> Changing the probability (TRUE/FALSE)</a></li>
<li class="chapter" data-level="9.5" data-path="week-9.html"><a href="week-9.html#studying-the-distribution"><i class="fa fa-check"></i><b>9.5</b> Studying the distribution</a></li>
<li class="chapter" data-level="9.6" data-path="week-9.html"><a href="week-9.html#cumulative-probability-advanced"><i class="fa fa-check"></i><b>9.6</b> Cumulative Probability (Advanced)</a></li>
<li class="chapter" data-level="9.7" data-path="week-9.html"><a href="week-9.html#revision-practice-rmd.-solutions"><i class="fa fa-check"></i><b>9.7</b> Revision Practice Rmd. Solutions</a><ul>
<li class="chapter" data-level="9.7.1" data-path="week-9.html"><a href="week-9.html#provide-descriptive-statistics-for-age-and-memory-score-variables"><i class="fa fa-check"></i><b>9.7.1</b> Provide descriptive statistics for age and memory score variables</a></li>
<li class="chapter" data-level="9.7.2" data-path="week-9.html"><a href="week-9.html#descriptives-by-groups"><i class="fa fa-check"></i><b>9.7.2</b> Descriptives by groups</a></li>
<li class="chapter" data-level="9.7.3" data-path="week-9.html"><a href="week-9.html#visualise"><i class="fa fa-check"></i><b>9.7.3</b> Visualise</a></li>
<li class="chapter" data-level="9.7.4" data-path="week-9.html"><a href="week-9.html#visualise-a-subset"><i class="fa fa-check"></i><b>9.7.4</b> Visualise a subset</a></li>
<li class="chapter" data-level="9.7.5" data-path="week-9.html"><a href="week-9.html#variable-by-a-group"><i class="fa fa-check"></i><b>9.7.5</b> Variable by a group</a></li>
<li class="chapter" data-level="9.7.6" data-path="week-9.html"><a href="week-9.html#create-a-new-variable-using-mutate"><i class="fa fa-check"></i><b>9.7.6</b> Create a new variable using mutate()</a></li>
<li class="chapter" data-level="9.7.7" data-path="week-9.html"><a href="week-9.html#subset-observations-using-filter"><i class="fa fa-check"></i><b>9.7.7</b> Subset observations using filter()</a></li>
<li class="chapter" data-level="9.7.8" data-path="week-9.html"><a href="week-9.html#sort-via-arrange"><i class="fa fa-check"></i><b>9.7.8</b> Sort via arrange()</a></li>
<li class="chapter" data-level="9.7.9" data-path="week-9.html"><a href="week-9.html#lets-do-some-specific-count-using-filter"><i class="fa fa-check"></i><b>9.7.9</b> Let’s do some specific count() using filter()</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="week-9.html"><a href="week-9.html#extra-probability-practice"><i class="fa fa-check"></i><b>9.8</b> Extra Probability Practice</a><ul>
<li class="chapter" data-level="9.8.1" data-path="week-9.html"><a href="week-9.html#truefalse-questions"><i class="fa fa-check"></i><b>9.8.1</b> TRUE/FALSE questions</a></li>
<li class="chapter" data-level="9.8.2" data-path="week-9.html"><a href="week-9.html#count-the-occurencies"><i class="fa fa-check"></i><b>9.8.2</b> Count the occurencies</a></li>
<li class="chapter" data-level="9.8.3" data-path="week-9.html"><a href="week-9.html#plot"><i class="fa fa-check"></i><b>9.8.3</b> Plot</a></li>
<li class="chapter" data-level="9.8.4" data-path="week-9.html"><a href="week-9.html#use-dbinom-to-study-the-probability"><i class="fa fa-check"></i><b>9.8.4</b> Use dbinom() to study the probability</a></li>
<li class="chapter" data-level="9.8.5" data-path="week-9.html"><a href="week-9.html#less-than-five-or-more-than-five"><i class="fa fa-check"></i><b>9.8.5</b> Less than five or more than five?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="week-10-lab-test.html"><a href="week-10-lab-test.html"><i class="fa fa-check"></i><b>10</b> Week 10: Lab test</a></li>
<li class="chapter" data-level="11" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html"><i class="fa fa-check"></i><b>11</b> Sampling distributions</a><ul>
<li class="chapter" data-level="11.1" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#recap"><i class="fa fa-check"></i><b>11.1</b> Recap</a></li>
<li class="chapter" data-level="11.2" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#population-sample"><i class="fa fa-check"></i><b>11.2</b> Population vs sample</a></li>
<li class="chapter" data-level="11.3" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#parameter-statistic"><i class="fa fa-check"></i><b>11.3</b> Population parameter vs sample statistic</a></li>
<li class="chapter" data-level="11.4" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#sec-sampling-distributions"><i class="fa fa-check"></i><b>11.4</b> Sampling distributions</a></li>
<li class="chapter" data-level="11.5" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#standard-error"><i class="fa fa-check"></i><b>11.5</b> The standard error of a statistic</a></li>
<li class="chapter" data-level="11.6" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#sample-size-standard-error"><i class="fa fa-check"></i><b>11.6</b> The effect of sample size on the sampling distribution</a></li>
<li class="chapter" data-level="11.7" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#take-home-message"><i class="fa fa-check"></i><b>11.7</b> Take-home message</a></li>
<li class="chapter" data-level="11.8" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#lab-hollywood-movies"><i class="fa fa-check"></i><b>11.8</b> Lab: Hollywood movies</a></li>
<li class="chapter" data-level="11.9" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#summary"><i class="fa fa-check"></i><b>11.9</b> Summary</a></li>
<li class="chapter" data-level="11.10" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#glossary"><i class="fa fa-check"></i><b>11.10</b> Glossary</a></li>
<li class="chapter" data-level="11.11" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#references"><i class="fa fa-check"></i><b>11.11</b> References</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html"><i class="fa fa-check"></i><b>12</b> Bootstrapping and Confidence Intervals</a><ul>
<li class="chapter" data-level="12.1" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#recap-1"><i class="fa fa-check"></i><b>12.1</b> Recap</a></li>
<li class="chapter" data-level="12.2" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#from-sampling-to-resampling"><i class="fa fa-check"></i><b>12.2</b> From Sampling to Resampling</a></li>
<li class="chapter" data-level="12.3" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#getting-to-the-bootstrap-distribution"><i class="fa fa-check"></i><b>12.3</b> Getting to the bootstrap distribution</a></li>
<li class="chapter" data-level="12.4" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#more-generally"><i class="fa fa-check"></i><b>12.4</b> More generally…</a></li>
<li class="chapter" data-level="12.5" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#confidence-intervals"><i class="fa fa-check"></i><b>12.5</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="12.5.1" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#calculating-confidence-intervals-using-a-bootstrap-standard-error"><i class="fa fa-check"></i><b>12.5.1</b> Calculating confidence intervals using a bootstrap standard error</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#summary-1"><i class="fa fa-check"></i><b>12.6</b> Summary</a></li>
<li class="chapter" data-level="12.7" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#take-home-message-1"><i class="fa fa-check"></i><b>12.7</b> Take-home message</a></li>
<li class="chapter" data-level="12.8" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#lab"><i class="fa fa-check"></i><b>12.8</b> Lab</a><ul>
<li class="chapter" data-level="" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#exercise-1-hollywood-movies"><i class="fa fa-check"></i>Exercise 1: Hollywood Movies</a></li>
<li class="chapter" data-level="" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#exercise-2-nfl-players"><i class="fa fa-check"></i>Exercise 2: NFL Players</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#glossary-1"><i class="fa fa-check"></i><b>12.9</b> Glossary</a></li>
<li class="chapter" data-level="12.10" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#references-1"><i class="fa fa-check"></i><b>12.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html"><i class="fa fa-check"></i><b>13</b> Testing hypotheses</a><ul>
<li class="chapter" data-level="13.1" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#recap-2"><i class="fa fa-check"></i><b>13.1</b> Recap</a></li>
<li class="chapter" data-level="13.2" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#walkthrough"><i class="fa fa-check"></i><b>13.2</b> Walkthrough</a><ul>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#extrasensory-perception-esp"><i class="fa fa-check"></i>Extrasensory perception (ESP)</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#example-esp-results"><i class="fa fa-check"></i>Example 1: ESP experimental results</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#example-in-class"><i class="fa fa-check"></i>Example 2: In-class activity</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#the-random-chance-model"><i class="fa fa-check"></i>The random chance model</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#the-alternative-explanation"><i class="fa fa-check"></i>The alternative explanation</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#statistical-test"><i class="fa fa-check"></i>Statistical test</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#understanding-statistical-evidence"><i class="fa fa-check"></i>Understanding statistical evidence</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#statistical-hypotheses"><i class="fa fa-check"></i>Statistical hypotheses</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#statistical-significance"><i class="fa fa-check"></i>Statistical significance</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#null-distribution"><i class="fa fa-check"></i>Null distribution</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#p-value"><i class="fa fa-check"></i>P-value</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#making-a-formal-decision"><i class="fa fa-check"></i>Making a formal decision</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#summary-2"><i class="fa fa-check"></i><b>13.3</b> Summary</a></li>
<li class="chapter" data-level="13.4" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#lab-1"><i class="fa fa-check"></i><b>13.4</b> Lab</a><ul>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#required-packages"><i class="fa fa-check"></i>Required packages</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#importing-the-data"><i class="fa fa-check"></i>Importing the data</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#data-inspection"><i class="fa fa-check"></i>Data inspection</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#sample-average-and-standard-deviation"><i class="fa fa-check"></i>Sample average and standard deviation</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#null-and-alternative-hypothesis"><i class="fa fa-check"></i>Null and alternative hypothesis</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#bootstrap-distribution-and-null-distribution"><i class="fa fa-check"></i>Bootstrap distribution and null distribution</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#visualise-the-observed-statistic-on-the-null-distribution"><i class="fa fa-check"></i>Visualise the observed statistic on the null distribution</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#p-value-2"><i class="fa fa-check"></i>P-value</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#interpreting-the-p-value"><i class="fa fa-check"></i>Interpreting the p-value</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#glossary-2"><i class="fa fa-check"></i><b>13.5</b> Glossary</a></li>
<li class="chapter" data-level="13.6" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#references-2"><i class="fa fa-check"></i><b>13.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="chap-typeerror.html"><a href="chap-typeerror.html"><i class="fa fa-check"></i><b>14</b> Type I, Type II errors and Power</a><ul>
<li class="chapter" data-level="14.1" data-path="chap-typeerror.html"><a href="chap-typeerror.html#overview-of-last-week"><i class="fa fa-check"></i><b>14.1</b> Overview of last week</a></li>
<li class="chapter" data-level="14.2" data-path="chap-typeerror.html"><a href="chap-typeerror.html#walkthrough-1"><i class="fa fa-check"></i><b>14.2</b> Walkthrough</a><ul>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#example-1-coin-flip"><i class="fa fa-check"></i>Example 1: Coin flip</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#an-analogy-in-law"><i class="fa fa-check"></i>An analogy in law</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#two-different-types-of-errors"><i class="fa fa-check"></i>Two different types of errors</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#type-i-errors"><i class="fa fa-check"></i>Type I errors</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#type-ii-errors-and-power"><i class="fa fa-check"></i>Type II Errors and Power</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#example-2-a-biased-coin"><i class="fa fa-check"></i>Example 2: A biased coin</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#overlapping-distributions"><i class="fa fa-check"></i>Overlapping distributions</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#generalising-it"><i class="fa fa-check"></i>Generalising it</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="chap-typeerror.html"><a href="chap-typeerror.html#summary-3"><i class="fa fa-check"></i><b>14.3</b> Summary</a></li>
<li class="chapter" data-level="14.4" data-path="chap-typeerror.html"><a href="chap-typeerror.html#lab-2"><i class="fa fa-check"></i><b>14.4</b> Lab</a><ul>
<li class="chapter" data-level="14.4.1" data-path="chap-typeerror.html"><a href="chap-typeerror.html#exercise-1-rock-paper-scissors"><i class="fa fa-check"></i><b>14.4.1</b> Exercise 1: Rock Paper Scissors!</a></li>
<li class="chapter" data-level="14.4.2" data-path="chap-typeerror.html"><a href="chap-typeerror.html#exercise-2-calculating-power-for-a-different-coin."><i class="fa fa-check"></i><b>14.4.2</b> Exercise 2: Calculating power for a different coin.</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="chap-typeerror.html"><a href="chap-typeerror.html#extra-exercises"><i class="fa fa-check"></i><b>14.5</b> Extra Exercises</a><ul>
<li class="chapter" data-level="14.5.1" data-path="chap-typeerror.html"><a href="chap-typeerror.html#exercise-3-sample-size-number-of-flips-and-power"><i class="fa fa-check"></i><b>14.5.1</b> Exercise 3: Sample size (number of flips) and power</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="chap-typeerror.html"><a href="chap-typeerror.html#glossary-3"><i class="fa fa-check"></i><b>14.6</b> Glossary</a></li>
<li class="chapter" data-level="14.7" data-path="chap-typeerror.html"><a href="chap-typeerror.html#references-3"><i class="fa fa-check"></i><b>14.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="chap-normal.html"><a href="chap-normal.html"><i class="fa fa-check"></i><b>15</b> Normal distribution &amp; probability</a><ul>
<li class="chapter" data-level="15.1" data-path="chap-normal.html"><a href="chap-normal.html#recap-3"><i class="fa fa-check"></i><b>15.1</b> Recap</a></li>
<li class="chapter" data-level="15.2" data-path="chap-normal.html"><a href="chap-normal.html#walkthrough-2"><i class="fa fa-check"></i><b>15.2</b> Walkthrough</a><ul>
<li class="chapter" data-level="15.2.1" data-path="chap-normal.html"><a href="chap-normal.html#from-histograms-to-normal-curves"><i class="fa fa-check"></i><b>15.2.1</b> From histograms to normal curves</a></li>
<li class="chapter" data-level="15.2.2" data-path="chap-normal.html"><a href="chap-normal.html#sec-area-and-prob"><i class="fa fa-check"></i><b>15.2.2</b> The relation between area and probability</a></li>
<li class="chapter" data-level="15.2.3" data-path="chap-normal.html"><a href="chap-normal.html#probabilities-for-normally-distributed-random-variables"><i class="fa fa-check"></i><b>15.2.3</b> Probabilities for normally distributed random variables</a></li>
<li class="chapter" data-level="15.2.4" data-path="chap-normal.html"><a href="chap-normal.html#z-scores"><i class="fa fa-check"></i><b>15.2.4</b> Z-scores</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="chap-normal.html"><a href="chap-normal.html#summary-4"><i class="fa fa-check"></i><b>15.3</b> Summary</a></li>
<li class="chapter" data-level="15.4" data-path="chap-normal.html"><a href="chap-normal.html#lab-3"><i class="fa fa-check"></i><b>15.4</b> Lab</a></li>
<li class="chapter" data-level="15.5" data-path="chap-normal.html"><a href="chap-normal.html#glossary-4"><i class="fa fa-check"></i><b>15.5</b> Glossary</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html"><i class="fa fa-check"></i><b>16</b> One Sample Mean Test</a><ul>
<li class="chapter" data-level="16.1" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#recap-4"><i class="fa fa-check"></i><b>16.1</b> Recap</a></li>
<li class="chapter" data-level="16.2" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#where-we-are-now"><i class="fa fa-check"></i><b>16.2</b> Where we are now</a></li>
<li class="chapter" data-level="16.3" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#where-we-are-going"><i class="fa fa-check"></i><b>16.3</b> Where we are going</a></li>
<li class="chapter" data-level="16.4" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#one-sample-mean-test"><i class="fa fa-check"></i><b>16.4</b> One sample mean test</a><ul>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#example-questions"><i class="fa fa-check"></i>Example questions</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#hypotheses"><i class="fa fa-check"></i>Hypotheses</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#formula"><i class="fa fa-check"></i>Formula</a></li>
<li><a href="chap-one-mean-test.html#t-distributions"><span class="math inline">\(t\)</span>-distributions</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#critical-values-significance"><i class="fa fa-check"></i>Critical values &amp; significance</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#walkthrough---tempo-of-rock-music-on-spotify"><i class="fa fa-check"></i><b>16.5</b> Walkthrough - Tempo of rock music on Spotify</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#all-in-one-line-of-code"><i class="fa fa-check"></i>ALL IN ONE LINE OF CODE!</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#assumptions"><i class="fa fa-check"></i>Assumptions</a></li>
<li class="chapter" data-level="16.6" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#summary-5"><i class="fa fa-check"></i><b>16.6</b> Summary</a></li>
<li class="chapter" data-level="16.7" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#lab-4"><i class="fa fa-check"></i><b>16.7</b> Lab</a><ul>
<li class="chapter" data-level="16.7.1" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#pets-weights"><i class="fa fa-check"></i><b>16.7.1</b> Pets’ weights</a></li>
<li class="chapter" data-level="16.7.2" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#procrastination-scores"><i class="fa fa-check"></i><b>16.7.2</b> Procrastination scores</a></li>
<li class="chapter" data-level="16.7.3" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#cat-weights"><i class="fa fa-check"></i><b>16.7.3</b> Cat weights!</a></li>
<li class="chapter" data-level="16.7.4" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#glossary-5"><i class="fa fa-check"></i><b>16.7.4</b> Glossary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="two-indep-samples.html"><a href="two-indep-samples.html"><i class="fa fa-check"></i><b>17</b> Comparing two means (independent samples)</a><ul>
<li class="chapter" data-level="17.1" data-path="two-indep-samples.html"><a href="two-indep-samples.html#recap-5"><i class="fa fa-check"></i><b>17.1</b> Recap</a></li>
<li class="chapter" data-level="17.2" data-path="two-indep-samples.html"><a href="two-indep-samples.html#key-terminology"><i class="fa fa-check"></i><b>17.2</b> Key terminology</a></li>
<li class="chapter" data-level="17.3" data-path="two-indep-samples.html"><a href="two-indep-samples.html#walkthrough-got-a-friend"><i class="fa fa-check"></i><b>17.3</b> Walkthrough: Got a friend?</a></li>
<li class="chapter" data-level="17.4" data-path="two-indep-samples.html"><a href="two-indep-samples.html#lab-does-name-increase-tips"><i class="fa fa-check"></i><b>17.4</b> Lab: Does name increase tips?</a></li>
<li class="chapter" data-level="17.5" data-path="two-indep-samples.html"><a href="two-indep-samples.html#glossary-6"><i class="fa fa-check"></i><b>17.5</b> Glossary</a></li>
<li class="chapter" data-level="17.6" data-path="two-indep-samples.html"><a href="two-indep-samples.html#w17-references"><i class="fa fa-check"></i><b>17.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html"><i class="fa fa-check"></i><b>18</b> Paired T-Test</a><ul>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#recap-6"><i class="fa fa-check"></i>Recap</a></li>
<li><a href="chap-paired-t-test.html#paired-t-test">Paired <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="18.1" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#walkthrough-3"><i class="fa fa-check"></i><b>18.1</b> Walkthrough</a><ul>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#change-in-score-on-the-ace-iii"><i class="fa fa-check"></i>Change in score on the ACE-III</a></li>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#data-organisation---reshaping"><i class="fa fa-check"></i>Data organisation - reshaping</a></li>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#effect-sizes"><i class="fa fa-check"></i>Effect sizes</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#summary-6"><i class="fa fa-check"></i><b>18.2</b> Summary</a></li>
<li class="chapter" data-level="18.3" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#lab-5"><i class="fa fa-check"></i><b>18.3</b> Lab</a><ul>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#age-differences-in-heterosexual-marriages"><i class="fa fa-check"></i>Age differences in heterosexual marriages</a></li>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#smoking-interventions"><i class="fa fa-check"></i>Smoking interventions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="chap-chi-square.html"><a href="chap-chi-square.html"><i class="fa fa-check"></i><b>19</b> Chi-square tests</a><ul>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#recap-7"><i class="fa fa-check"></i>Recap</a></li>
<li><a href="chap-chi-square.html#walkthrough-birthdays-of-the-week-the-chi-square-goodness-of-fit-test">Walkthrough: Birthdays of the week <br>The chi-square goodness-of-fit test</a></li>
<li><a href="chap-chi-square.html#lab-joking-for-a-tip-the-chi-square-test-of-independence">Lab: Joking for a tip <br>The chi-square test of independence</a></li>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#summary-7"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#glossary-7"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#references-4"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analysis for Psychology in R (dapR1) - Labs</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap-normal" class="section level1">
<h1><span class="header-section-number">Chapter 15</span> Normal distribution &amp; probability</h1>
<div class="lo">
<h4 id="instructions-4" class="unnumbered">Instructions</h4>
<ul>
<li>In this two-hour lab we will go through worked examples in the first hour, and you will attempt to answer some questions in the second hour.</li>
<li><strong>Please attempt the lab questions as they are not just a mere copy of the walkthrough code using a different dataset. They consolidate key points that were covered in the lecture, but not in the walkthrough.</strong></li>
<li>The Rmarkdown file for this week is <a href="https://uoe-psychology.github.io/uoe_psystats/dapr1/labsheets/week_15_practice.Rmd">here</a>.</li>
</ul>
<h4 id="learning-outcomes-4" class="unnumbered">Learning outcomes</h4>
<p><strong>LO1.</strong> Understand the normal distribution.</p>
<p><strong>LO2.</strong> Compute probabilities using density functions.</p>
<p><strong>LO3.</strong> Understand the link between simulation-based standard errors and theory-based standard errors.</p>
</div>
<div id="recap-3" class="section level2">
<h2><span class="header-section-number">15.1</span> Recap</h2>
<ul>
<li><p>Flow-chart revising how to perform hypothesis testing using the <a href="images/recap_pvalues.pdf">p-value method</a>.</p></li>
<li><p>Flow-chart revising how to perform hypothesis testing using the <a href="images/recap_rr.pdf">critical value or rejection region method</a>).</p></li>
</ul>
</div>
<div id="walkthrough-2" class="section level2">
<h2><span class="header-section-number">15.2</span> Walkthrough</h2>
<div id="from-histograms-to-normal-curves" class="section level3">
<h3><span class="header-section-number">15.2.1</span> From histograms to normal curves</h3>
<p>In the past four weeks, we plotted many histograms and dotplots. These plots helped us understand the <strong>distribution</strong> of a variable or a statistic.</p>
<div class="def">
<h4 id="distribution" class="unnumbered">Distribution</h4>
<p>The distribution of a variable shows how frequently different values of the variable occur.</p>
<p>The graph showing the distribution of a variable shows us where the values are centred, how the values vary, and gives some information about where a typical value might fall. It can also alert you to the presence of outliers (unexpected observations).</p>
</div>
<!-- By looking at the distribution of a given statistic we saw how, in different scenarios, the statistic varied due to sampling variation: -->
<!-- - [Week 11](#chap-sampling-distributions) displayed the variability due to sampling from the population (__sampling distribution__) -->
<!-- - [Week 12](#bootstrapping-and-confidence-intervals) displayed the variability due to sampling with replacement from the only available sample (__bootstrap distribution__) -->
<!-- - [Week 13](#chap-hyp-test) displayed the variability when sampling from a population assuming the null hypothesis to be true (__null distribution__) -->
<p>Pretty much all of the distributions we saw were <strong>symmetric</strong> and <strong>bell-shaped</strong>. This typically is the case when the sample size is large enough.</p>
<p>Figure <a href="chap-normal.html#fig:normal-fits">15.1</a> shows some of the distributions we plotted in the past four weeks, with a red curve superimposed on top. Note how the red curve closely approximates the histograms.</p>
<ol style="list-style-type: lower-alpha">
<li>NFL example: sampling distribution of the mean for sample size <span class="math inline">\(n = 50\)</span>;</li>
<li>NFL example: sampling distribution of the mean for sample size <span class="math inline">\(n = 500\)</span>;</li>
<li>Coin example: sampling distribution of the proportion of heads in <span class="math inline">\(n = 50\)</span> tosses with probability of heads <span class="math inline">\(p = 0.3\)</span>;</li>
<li>Coin example: sampling distribution of the proportion of heads in <span class="math inline">\(n = 50\)</span> tosses with probability of heads <span class="math inline">\(p = 0.7\)</span>.</li>
</ol>
<div class="figure" style="text-align: center"><span id="fig:normal-fits"></span>
<img src="bookdown-demo_files/figure-html/normal-fits-1.png" alt="Different distributions with their corresponding normal curves shown in red." width="100%" />
<p class="caption">
Figure 15.1: Different distributions with their corresponding normal curves shown in red.
</p>
</div>
<p>The symmetric and bell-shaped red curve is known as the <strong>normal curve</strong> and is a mathematical model (i.e. an equation or graph) which is used to describe reality (see Figure <a href="chap-normal.html#fig:normal-curve">15.2</a>).</p>
<div class="figure" style="text-align: center"><span id="fig:normal-curve"></span>
<img src="bookdown-demo_files/figure-html/normal-curve-1.png" alt="Normal curve." width="60%" />
<p class="caption">
Figure 15.2: Normal curve.
</p>
</div>
<div class="def">
<h4 id="normal-distribution" class="unnumbered">Normal distribution</h4>
<p>A continuous variable is said to be a <strong>normally distributed</strong>, or to have a <strong>normal probability distribution</strong>, if its distribution has the shape of a normal curve (i.e. it is symmetric and bell-shaped).</p>
</div>
<div class="red">
<h4 id="key-question" class="unnumbered">Key question</h4>
<p>How can we make sure that the normal curve can adapt to any symmetric and bell-shaped histogram?</p>
</div>
<p><strong>Every histogram can be centred at a different value and have a different spread.</strong></p>
<p>We can specify the normal curve appropriate for each histogram by specifying</p>
<ol style="list-style-type: decimal">
<li>where it should be centred at,</li>
<li>and what should its spread be.</li>
</ol>
<p>Hence, the normal curve depends on two quantities called the <strong>parameters</strong> of the normal distribution (see Figure <a href="chap-normal.html#fig:vary-params">15.3</a>):</p>
<ol style="list-style-type: decimal">
<li>the mean <span class="math inline">\(\mu\)</span>, specifying the centre of the distribution;</li>
<li>the standard deviation <span class="math inline">\(\sigma\)</span>, specifying the spread of the distribution.</li>
</ol>
<pre><code>## Warning: `mapping` is not used by stat_function()

## Warning: `mapping` is not used by stat_function()

## Warning: `mapping` is not used by stat_function()

## Warning: `mapping` is not used by stat_function()</code></pre>
<div class="figure" style="text-align: center"><span id="fig:vary-params"></span>
<img src="bookdown-demo_files/figure-html/vary-params-1.png" alt="Normal curves for different means and standard deviations." width="768" />
<p class="caption">
Figure 15.3: Normal curves for different means and standard deviations.
</p>
</div>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>What happens when we vary the mean and the standard deviation parameters?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-53" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-53&#39;, &#39;sol-start-53&#39;)"></span>
</p>
<div id="sol-body-53" class="solution-body" style="display: none;">
<p>By varying the mean only, we can model histograms that are centred at different values but have the same spread.</p>
<p>By varying the standard deviation only, we can model histograms with different spreads but that have the same mean.</p>
<p>By varying both the mean and the standard deviation we can model any symmetric and bell-shaped histogram.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="def">
<h4 id="notation" class="unnumbered">Notation</h4>
<p>We will write that a random variable <span class="math inline">\(X\)</span> follows a normal distribution with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> as:
<span class="math display">\[X \sim N(\mu, \sigma)\]</span></p>
</div>
</div>
<div id="sec-area-and-prob" class="section level3">
<h3><span class="header-section-number">15.2.2</span> The relation between area and probability</h3>
<p>Consider panel (a) in Figure <a href="chap-normal.html#fig:normal-fits">15.1</a>.
Each bar in the histogram shows the proportion of all the generated statistics falling in a given interval. For example, the proportion of sample means between 2.2 and 2.3 is equal to 0.09.</p>
<p>This proportion can be interpreted as a probability. So, the proportion of means between 2.2 and 2.3 has two possible interpretations:</p>
<ul>
<li>the proportion of all samples with a mean between 2.2 and 2.3 is 9%;</li>
<li>there is a 9% probability that a randomly selected sample from the population has a mean between 2.2 and 2.3.</li>
</ul>
<p>We will now discuss the <strong>uniform distribution</strong> to understand the relation between area and probability.</p>
<div class="noteBox">
<p>Suppose that you are performing an experiment to study the time until loss of attention.
You are currently monitoring a subject from a starting point, coded as time = 0, until up to 30 minutes later.</p>
<p>The subject is equally likely to lose attention at any point across the 30 minutes.
They are equally likely to lose attention after 3-4 minutes as they are likely after 25-26 minutes, or after 6-10 minutes as they are after 20-24 minutes.</p>
<p>More generally, the subject is equally likely to lose attention in intervals of time that have the same length.
Such a random variable is said to follow a <strong>uniform distribution</strong>.</p>
</div>
<p>For discrete random variables, i.e. random variables whose possible values are only whole numbers without decimals, we compute probabilities as the <strong>number of favourable cases divided by the total number of possibilities</strong>.</p>
<p>The probability of seeing an even face when throwing a die is obtained by dividing the number of ways the event “even face” can occur (three even faces in a die: ⚁, ⚃, ⚅) by the total number of possibilities (six total faces in a die: ⚀, ⚁, ⚂, ⚃, ⚄, ⚅):
<span class="math display">\[
P(\textrm{even face}) = \frac{n_\textrm{even faces}}{n_\textrm{faces}} = \frac{3}{6} = 0.5
\]</span></p>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>Think about continuous random variables, such as time until loss of attention or reaction times.
For continuous random variables, can we compute probabilities in the same way?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-54" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-54&#39;, &#39;sol-start-54&#39;)"></span>
</p>
<div id="sol-body-54" class="solution-body" style="display: none;">
<p>The answer is no.</p>
<p>A continuous random variable can take an infinite number of values.
For this reason, the probability of observing a specific value is zero.</p>
<p>For example, the probability of your subject losing focus after exactly 3.9483627298 minutes is zero. There is only one particular way to observe 3.9483627298, and there is an infinite number of values between 0 and 30.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="red">
<h4 id="key-point-1" class="unnumbered">Key point</h4>
<p>For continuous random variables, we can only compute the probability of <strong>intervals</strong> of values.</p>
</div>
<p>In order to find probabilities for continuous random variables, we use <strong>probability density functions</strong>.</p>
<div class="def">
<h4 id="probability-density-function" class="unnumbered">Probability density function</h4>
<p>A <strong>probability density function</strong> is an equation used to compute the probabilities for continuous random variables.</p>
<p>It must satisfy the following properties:</p>
<ol style="list-style-type: decimal">
<li>the total area under the graph of the equation must be equal to one, equivalent to the fact that the total probability must be one;</li>
<li>the graph of the equation must be greater than or equal to zero for all possible values.</li>
</ol>
</div>
<p>For discrete random variables, property 1 is similar to saying that the sum of all probabilities must be equal to 100%. Property 2 is similar to saying that probabilities can not be negative.</p>
<div class="figure" style="text-align: center"><span id="fig:unif-distr"></span>
<img src="images/unif_distr.png" alt="Uniform distribution between 0 and 30 minutes." width="60%" />
<p class="caption">
Figure 15.4: Uniform distribution between 0 and 30 minutes.
</p>
</div>
<p>Figure <a href="chap-normal.html#fig:unif-distr">15.4</a> shows the uniform distribution for the <a href="chap-normal.html#sec-area-and-prob">loss of attention example</a>. Let’s analyse it in more detail. Each value between 0 and 30 minutes is equally likely, so the graph is a rectangle.
The width of the rectangle is 30 as the possible values of the random variable are 0 to 30.
Property 1 of density functions states that the total area under the graph must be 1.
We will use this relationship to find what the height of the rectangle should be.</p>
<p>Recalling that the area of a rectangle is given by the width times height,</p>
<p><span class="math display">\[
\begin{aligned}
a &amp;= w \times h \\
1 &amp;= 30 \times h
\end{aligned}
\]</span></p>
<p>we find that the density is given by the height:
<span class="math display">\[
h = \frac{1}{30} = \textrm{density}
\]</span></p>
<p><strong>How can we use this density function to calculate probabilities?</strong></p>
<p>In order to find the probability of your subject losing attention between 10 and 20 minutes after the start of the experiment, we must calculate the shaded area in Figure <a href="chap-normal.html#fig:unif-shaded">15.5</a>.</p>
<p>The width of the shaded region is <span class="math inline">\(20-10 = 10\)</span>.
The height of the shaded region is <span class="math inline">\(1/30\)</span>.
The area between 10 and 20 is <span class="math inline">\(10 \times \frac{1}{30} = \frac{1}{3}\)</span>.</p>
<p>So, the probability of the subject losing attention between 10 and 20 minutes from the beginning of the study is <span class="math inline">\(1/3\)</span>.</p>
<div class="figure" style="text-align: center"><span id="fig:unif-shaded"></span>
<img src="images/unif_shaded.png" alt="Probability of losing attention after 10 to 20 minutes." width="60%" />
<p class="caption">
Figure 15.5: Probability of losing attention after 10 to 20 minutes.
</p>
</div>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>How would you calculate the probability of the subject losing focus either in the first 10 minutes or the last 10 minutes?
In other words, between 0-10 minutes and 20-30 minutes?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-55" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-55&#39;, &#39;sol-start-55&#39;)"></span>
</p>
<div id="sol-body-55" class="solution-body" style="display: none;">
<p>Since the total area of the rectangle is 1 (the total probability must be 1), we can compute this area as 1 - the shaded area.</p>
<p>The probability of losing focus between 0-10 minutes or 20-30 minutes is <span class="math inline">\(1 - \frac{1}{3} = \frac{2}{3}\)</span>.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>We have introduced the uniform distribution to link the concepts of probability and area under a curve.</p>
<p>Now, strong in what we have learned, we will move towards a more widely used model for continuous random variables: the normal distribution, which we have previously introduced.</p>
</div>
<div id="probabilities-for-normally-distributed-random-variables" class="section level3">
<h3><span class="header-section-number">15.2.3</span> Probabilities for normally distributed random variables</h3>
<p>We used a rectangle to find the probability of a uniformly distributed variable being in a given range.
However, only a few continuous random variables follow such a graph.</p>
<p>More common is to see random variables whose distribution is symmetric and bell-shaped.
This is the case for aptitude-test scores, the birth weights of newborns, and so on…
We previously learned that if a random variable has a histogram which is symmetric and bell-shaped, we say that the variable follows a normal distribution.</p>
<p>Consider the following sample of 10,000 people, for which we have recorded their score on a cognitive test.</p>
<p>Let’s load the data and inspect them:</p>
<div class="sourceCode" id="cb673"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb673-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb673-2" data-line-number="2"></a>
<a class="sourceLine" id="cb673-3" data-line-number="3"><span class="co"># Load the sample</span></a>
<a class="sourceLine" id="cb673-4" data-line-number="4">cognitive &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&#39;https://edin.ac/39jPFa5&#39;</span>, <span class="dt">col_names =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb673-5" data-line-number="5"></a>
<a class="sourceLine" id="cb673-6" data-line-number="6"><span class="co"># Display the first six rows</span></a>
<a class="sourceLine" id="cb673-7" data-line-number="7"><span class="kw">head</span>(cognitive)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   SubjectID CognitiveScore
##       &lt;dbl&gt;          &lt;dbl&gt;
## 1         1           90.6
## 2         2          103. 
## 3         3           87.5
## 4         4          124. 
## 5         5          105. 
## 6         6           87.7</code></pre>
<div class="sourceCode" id="cb675"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb675-1" data-line-number="1"><span class="co"># Check the dimensions of the tibble</span></a>
<a class="sourceLine" id="cb675-2" data-line-number="2"><span class="kw">dim</span>(cognitive)</a></code></pre></div>
<pre><code>## [1] 10000     2</code></pre>
<p>We have 10,000 rows (subjects) and two columns (measured variables).</p>
<p>Let’s plot the distribution of the variable of interest, <code>CognitiveScore</code>, as a histogram.
However, on the y-axis, instead of the absolute counts of the values we ask for the density or proportion.
This makes it easier to compare across samples of different sizes, as the range of the y-axis won’t change with the sample size.</p>
<p>We plot the density by specifying <code>y = stat(density)</code> in the <code>aes()</code> function:</p>
<div class="sourceCode" id="cb677"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb677-1" data-line-number="1"><span class="kw">ggplot</span>(cognitive, <span class="kw">aes</span>(<span class="dt">x =</span> CognitiveScore, <span class="dt">y =</span> <span class="kw">stat</span>(density))) <span class="op">+</span></a>
<a class="sourceLine" id="cb677-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&#39;white&#39;</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-431-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>We can see that the distribution of cognitive scores is symmetric, centres approximately around 100, and is bell-shaped. We can therefore try to fit a normal curve to it.</p>
<p>We must specify:</p>
<ul>
<li>where the normal curve should be centred at. This should be the centre of the histogram/data;</li>
<li>how spread out or narrow the normal curve should be. This should be the spread of the histogram, i.e. the standard deviation of the data.</li>
</ul>
<p><strong>Centre:</strong></p>
<div class="sourceCode" id="cb678"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb678-1" data-line-number="1">sample_mean &lt;-<span class="st"> </span>cognitive <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb678-2" data-line-number="2"><span class="st">  </span><span class="kw">pull</span>(CognitiveScore) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb678-3" data-line-number="3"><span class="st">  </span><span class="kw">mean</span>()</a>
<a class="sourceLine" id="cb678-4" data-line-number="4"></a>
<a class="sourceLine" id="cb678-5" data-line-number="5">sample_mean</a></code></pre></div>
<pre><code>## [1] 99.9019</code></pre>
<p><strong>Spread:</strong></p>
<div class="sourceCode" id="cb680"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb680-1" data-line-number="1">sample_sd &lt;-<span class="st"> </span>cognitive <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb680-2" data-line-number="2"><span class="st">  </span><span class="kw">pull</span>(CognitiveScore) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb680-3" data-line-number="3"><span class="st">  </span><span class="kw">sd</span>()</a>
<a class="sourceLine" id="cb680-4" data-line-number="4"></a>
<a class="sourceLine" id="cb680-5" data-line-number="5">sample_sd</a></code></pre></div>
<pre><code>## [1] 15.18534</code></pre>
<p>Hence the normal curve should be centred at the mean of the data, 99.9 and have standard deviation 15.19.</p>
<p>The equation of the normal density curve is provided by the following function:</p>
<div class="sourceCode" id="cb682"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb682-1" data-line-number="1"><span class="kw">dnorm</span>(x, mean, sd)</a></code></pre></div>
<p>where:</p>
<ul>
<li><code>x</code> represents the value of the random variable</li>
<li><code>mean</code> the mean of the normal curve</li>
<li><code>sd</code> the standard deviation of the curve</li>
</ul>
<p>Let’s add the red curve on top of the histogram using <code>stat_function()</code>. It takes as arguments:</p>
<ul>
<li><code>fun</code>: the function to plot</li>
<li><code>args</code>: parameters of the function to be plotted</li>
<li>plotting specifications</li>
</ul>
<div class="sourceCode" id="cb683"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb683-1" data-line-number="1"><span class="kw">ggplot</span>(cognitive) <span class="op">+</span></a>
<a class="sourceLine" id="cb683-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> CognitiveScore, <span class="dt">y =</span> <span class="kw">stat</span>(density)), <span class="dt">color =</span> <span class="st">&#39;white&#39;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb683-3" data-line-number="3"><span class="st">  </span><span class="kw">stat_function</span>(<span class="dt">fun =</span> dnorm, </a>
<a class="sourceLine" id="cb683-4" data-line-number="4">                <span class="dt">args =</span> <span class="kw">list</span>(<span class="dt">mean =</span> sample_mean, <span class="dt">sd =</span> sample_sd), </a>
<a class="sourceLine" id="cb683-5" data-line-number="5">                <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">size =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-435-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>We can now calculate the probability that a randomly selected individual has a cognitive score between 120 and 130 as the area under the normal curve between 120 and 130:</p>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-436-1.png" width="70%" style="display: block; margin: auto;" /></p>
<hr />
<p>We compute areas for normal curves using the function <code>pnorm(x, mean, sd)</code>.</p>
<p>This function computes the area to the left of <code>x</code> in a normal curve centred at <code>mean</code> and having standard deviation <code>sd</code>.</p>
<p><strong>1. Area to the left of a value <span class="math inline">\(x\)</span></strong>
<img src="images/pnorm_left.png" width="80%" style="display: block; margin: auto;" /></p>
<p><strong>2. Area between the values <span class="math inline">\(x_l\)</span> and <span class="math inline">\(x_u\)</span></strong>
<img src="images/pnorm_interval.png" width="100%" style="display: block; margin: auto;" /></p>
<p><strong>3. Area to the right of <span class="math inline">\(x\)</span></strong>
<img src="images/pnorm_right.png" width="100%" style="display: block; margin: auto;" /></p>
<hr />
<p>The probability that a randomly selected individual has a cognitive score between 120 and 130 is the area under the normal curve between 120 and 130:</p>
<div class="sourceCode" id="cb684"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb684-1" data-line-number="1">theory_prob &lt;-<span class="st"> </span><span class="kw">pnorm</span>(<span class="dv">130</span>, <span class="dt">mean =</span> sample_mean, <span class="dt">sd =</span> sample_sd) <span class="op">-</span><span class="st"> </span></a>
<a class="sourceLine" id="cb684-2" data-line-number="2"><span class="st">  </span><span class="kw">pnorm</span>(<span class="dv">120</span>, <span class="dt">mean =</span> sample_mean, <span class="dt">sd =</span> sample_sd)</a>
<a class="sourceLine" id="cb684-3" data-line-number="3">theory_prob</a></code></pre></div>
<pre><code>## [1] 0.06909445</code></pre>
<p>Let’s compare that with the proportion obtained from the histogram:</p>
<div class="sourceCode" id="cb686"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb686-1" data-line-number="1">sample_prob &lt;-<span class="st"> </span>cognitive <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb686-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">prop =</span> <span class="kw">sum</span>(CognitiveScore <span class="op">&gt;=</span><span class="st"> </span><span class="dv">120</span> <span class="op">&amp;</span><span class="st"> </span>CognitiveScore <span class="op">&lt;=</span><span class="st"> </span><span class="dv">130</span>) <span class="op">/</span><span class="st"> </span><span class="kw">n</span>())</a>
<a class="sourceLine" id="cb686-3" data-line-number="3">sample_prob</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##     prop
##    &lt;dbl&gt;
## 1 0.0705</code></pre>
<p>As we can see the theoretical probability and the sample estimate, rounded to two decimal places, are similar:</p>
<table>
<thead>
<tr class="header">
<th align="center">Simulation-based</th>
<th align="center">Theory-based</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">0.07</td>
<td align="center">0.07</td>
</tr>
</tbody>
</table>
<p>There is a 7% chance that a randomly selected individual from the population has a cognitive score between 120 and 130.</p>
<p>To summarise, the calculation of probabilities for normally distributed random variables follows three steps:</p>
<ol style="list-style-type: decimal">
<li><p>find the mean of the variable,</p></li>
<li><p>find the standard deviation of the variable,</p></li>
<li><p>compute the probability as the area under the normal curve with the mean found in (1) and the standard deviation found in (2).</p></li>
</ol>
</div>
<div id="z-scores" class="section level3">
<h3><span class="header-section-number">15.2.4</span> Z-scores</h3>
<p>Instead of always specifying the mean and the standard deviation of the normal curve, we can work with a reference normal curve that has mean = 0 and sd = 1. This is known as the <strong>standard normal distribution</strong>.</p>
<div class="def">
<h4 id="standard-normal-distribution" class="unnumbered">Standard normal distribution</h4>
<p>A standard normal distribution, denoted <span class="math inline">\(N(0, 1)\)</span>, is a normal distribution with mean = 0 and sd = 1.</p>
</div>
<p>The functions <code>dnorm</code> and <code>pnorm</code> assume that the mean = 0 and the sd = 1 if not provided, i.e. they assume a standard normal distribution by default.</p>
<p>In order to transform a value <span class="math inline">\(x\)</span> from a normal distribution with mean = <span class="math inline">\(\mu\)</span> and sd = <span class="math inline">\(\sigma\)</span> to a score on the standard normal scale, we must use the z-score transformation:
<span class="math display">\[
z = \frac{x - \mu}{\sigma}
\]</span></p>
<p>Let’s compute again the probability that a randomly selected individual has a cognitive score between 120 and 130 using a standard normal distribution.</p>
<p>First, we must convert the values to z-scores by subtracting the mean and the standard deviation of the distribution. Then we use the function <code>pnorm()</code>:</p>
<div class="sourceCode" id="cb688"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb688-1" data-line-number="1">z_u &lt;-<span class="st"> </span>(<span class="dv">130</span> <span class="op">-</span><span class="st"> </span>sample_mean) <span class="op">/</span><span class="st"> </span>sample_sd</a>
<a class="sourceLine" id="cb688-2" data-line-number="2">z_l &lt;-<span class="st"> </span>(<span class="dv">120</span> <span class="op">-</span><span class="st"> </span>sample_mean) <span class="op">/</span><span class="st"> </span>sample_sd</a>
<a class="sourceLine" id="cb688-3" data-line-number="3"></a>
<a class="sourceLine" id="cb688-4" data-line-number="4"><span class="kw">pnorm</span>(z_u) <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(z_l)</a></code></pre></div>
<pre><code>## [1] 0.06909445</code></pre>
<p>There is a 7% chance that a randomly selected individual from the population has a cognitive score between 120 and 130.</p>
<p>As you can see, this is exactly the same value we found before with the shifted and scaled normal distribution.</p>
</div>
</div>
<div id="summary-4" class="section level2">
<h2><span class="header-section-number">15.3</span> Summary</h2>
<p>When a histogram shows that a variable’s distribution is symmetric and bell-shaped, we can say that the variable is normally distributed and we can model the distribution with a mathematical curve called the normal probability distribution.</p>
<p>We saw that the normal distribution depends on two parameters that control the centre and spread of the normal curve:</p>
<ul>
<li>the mean;</li>
<li>the standard deviation.</li>
</ul>
<p>These two parameters let the normal curve model histograms that have different centres and different spreads.</p>
<p>In R, the equation of the normal density curve is given by the function <code>dnorm(x, mean, sd)</code>.</p>
<p>We can use the normal curve to compute the probability of intervals as the area under the curve in that interval.</p>
<p>The function to compute the area under a normal curve to the left of <code>x</code> is <code>pnorm(x, mean, sd)</code>.</p>
<table>
<colgroup>
<col width="54%" />
<col width="45%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Probability</th>
<th align="left">R command</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Probability of observing a value less than or equal <code>x</code></td>
<td align="left"><code>pnorm(x, mean, sd)</code></td>
</tr>
<tr class="even">
<td align="left">Probability of observing a value between <code>xl</code> and <code>xu</code></td>
<td align="left"><code>pnorm(xu, mean, sd) - pnorm(xl, mean, sd)</code></td>
</tr>
<tr class="odd">
<td align="left">Probability of observing a value greater than <code>xu</code></td>
<td align="left"><code>1 - pnorm(xu, mean, sd)</code></td>
</tr>
</tbody>
</table>
</div>
<div id="lab-3" class="section level2">
<h2><span class="header-section-number">15.4</span> Lab</h2>
<p>In today’s lab we will fit a normal curve to the sampling distribution of the mean using the <a href="chap-sampling-distributions.html#sec-sampling-distributions">NFL example</a> introduced in Week 11.</p>
<p>Consider again the dataset with the yearly salaries of National Football League (NFL) players. We are interested in the average yearly salary of a NFL player.</p>
<p>We have data on 2,099 players: their name, position, team they played for, total money while on a NFL payroll, and yearly salary.</p>
<p>Since we are only interested in the yearly salary, we can select the relevant columns:</p>
<div class="sourceCode" id="cb690"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb690-1" data-line-number="1"><span class="co"># Step 1: load the required libraries</span></a>
<a class="sourceLine" id="cb690-2" data-line-number="2"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb690-3" data-line-number="3"><span class="kw">library</span>(moderndive)</a>
<a class="sourceLine" id="cb690-4" data-line-number="4"></a>
<a class="sourceLine" id="cb690-5" data-line-number="5"><span class="co"># Step 2: load the data and select the columns of interest</span></a>
<a class="sourceLine" id="cb690-6" data-line-number="6">nfl &lt;-<span class="st"> </span><span class="kw">read_tsv</span>(<span class="st">&#39;https://edin.ac/2TexAFA&#39;</span>)</a>
<a class="sourceLine" id="cb690-7" data-line-number="7"></a>
<a class="sourceLine" id="cb690-8" data-line-number="8"><span class="co"># Step 3: look at the first rows of the data</span></a>
<a class="sourceLine" id="cb690-9" data-line-number="9"><span class="kw">head</span>(nfl)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##   Player             Position Team     TotalMoney YearlySalary
##   &lt;chr&gt;              &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt;        &lt;dbl&gt;
## 1 Aaron Rodgers      QB       Packers       110           22  
## 2 Russell Wilson     QB       Seahawks       87.6         21.9
## 3 Ben Roethlisberger QB       Steelers       87.4         21.8
## 4 Philip Rivers      QB       Chargers       83.2         20.8
## 5 Cam Newton         QB       Panthers      104.          20.8
## 6 Matt Ryan          QB       Falcons       104.          20.8</code></pre>
<div class="sourceCode" id="cb692"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb692-1" data-line-number="1"><span class="co"># Step 4: check the dimensions of the tibble</span></a>
<a class="sourceLine" id="cb692-2" data-line-number="2"><span class="kw">dim</span>(nfl)</a></code></pre></div>
<pre><code>## [1] 2099    5</code></pre>
<div class="sourceCode" id="cb694"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb694-1" data-line-number="1"><span class="co"># Step 5: select relevant variables</span></a>
<a class="sourceLine" id="cb694-2" data-line-number="2">nfl &lt;-<span class="st"> </span>nfl <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb694-3" data-line-number="3"><span class="st">  </span><span class="kw">select</span>(Player, YearlySalary)</a></code></pre></div>
<div class="question">
<p class="question-begin">
► Question 1
</p>
<div class="question-body">
<p>Compute the sampling distribution of the mean using 10,000 samples of 100 players each.</p>
<p>Display the sampling distribution using a density histogram.</p>
<p><em><strong>Hint</strong>. Remember to use <code>y = stat(density)</code> inside the function <code>aes()</code>.</em></p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-56" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-56&#39;, &#39;sol-start-56&#39;)"></span>
</p>
<div id="sol-body-56" class="solution-body" style="display: none;">
<p>Let’s compute the sampling distribution of the mean for samples of size <span class="math inline">\(n = 100\)</span>, using 10,000 samples:</p>
<div class="sourceCode" id="cb695"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb695-1" data-line-number="1"><span class="co"># Step 1: obtain many samples of size 100 and compute the mean of each sample</span></a>
<a class="sourceLine" id="cb695-2" data-line-number="2">sampling_distrib_of_mean &lt;-<span class="st"> </span>nfl <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb695-3" data-line-number="3"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">100</span>, <span class="dt">reps =</span> <span class="dv">10000</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb695-4" data-line-number="4"><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb695-5" data-line-number="5"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg =</span> <span class="kw">mean</span>(YearlySalary))</a>
<a class="sourceLine" id="cb695-6" data-line-number="6"></a>
<a class="sourceLine" id="cb695-7" data-line-number="7"><span class="co"># Step 2: plot the sampling distribution of the mean for samples of size 100</span></a>
<a class="sourceLine" id="cb695-8" data-line-number="8"><span class="kw">ggplot</span>(sampling_distrib_of_mean) <span class="op">+</span></a>
<a class="sourceLine" id="cb695-9" data-line-number="9"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> avg, <span class="dt">y =</span> <span class="kw">stat</span>(density)), <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb695-10" data-line-number="10"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expr</span>(<span class="kw">bar</span>(x)))</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:nfl-hist-norm"></span>
<img src="bookdown-demo_files/figure-html/nfl-hist-norm-1.png" alt="Sampling distribution of the mean." width="672" />
<p class="caption">
Figure 15.6: Sampling distribution of the mean.
</p>
</div>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question 2
</p>
<div class="question-body">
<p>Does the sampling distribution of the mean for samples of size 100 follow a normal curve?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-57" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-57&#39;, &#39;sol-start-57&#39;)"></span>
</p>
<div id="sol-body-57" class="solution-body" style="display: none;">
<p>The distribution of sample means seems to be symmetric and bell-shaped, hence the sample mean is a normally distributed random variable.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question 3
</p>
<div class="question-body">
<p>Find the normal probability density function that models the sampling distribution of the mean for samples of size <span class="math inline">\(n = 100\)</span>.</p>
<p>Plot the normal curve in red on top of the histogram.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-58" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-58&#39;, &#39;sol-start-58&#39;)"></span>
</p>
<div id="sol-body-58" class="solution-body" style="display: none;">
<p>The required steps are:</p>
<ol style="list-style-type: decimal">
<li>Compute the mean of the sample means, which is used to specify where the normal curve should be centred at;</li>
<li>Compute the standard deviation of the sample means (SE of the mean) which is used to specify the spread of the normal curve.</li>
</ol>
<div class="sourceCode" id="cb696"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb696-1" data-line-number="1"><span class="co"># Sample mean</span></a>
<a class="sourceLine" id="cb696-2" data-line-number="2">mean_of_distrib &lt;-<span class="st"> </span>sampling_distrib_of_mean <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb696-3" data-line-number="3"><span class="st">  </span><span class="kw">pull</span>(avg) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb696-4" data-line-number="4"><span class="st">  </span><span class="kw">mean</span>()</a>
<a class="sourceLine" id="cb696-5" data-line-number="5">mean_of_distrib</a></code></pre></div>
<pre><code>## [1] 2.240886</code></pre>
<div class="sourceCode" id="cb698"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb698-1" data-line-number="1"><span class="co"># Sample sd</span></a>
<a class="sourceLine" id="cb698-2" data-line-number="2">sd_of_distrib &lt;-<span class="st"> </span>sampling_distrib_of_mean <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb698-3" data-line-number="3"><span class="st">  </span><span class="kw">pull</span>(avg) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb698-4" data-line-number="4"><span class="st">  </span><span class="kw">sd</span>()</a>
<a class="sourceLine" id="cb698-5" data-line-number="5">sd_of_distrib</a></code></pre></div>
<pre><code>## [1] 0.297133</code></pre>
<div class="sourceCode" id="cb700"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb700-1" data-line-number="1"><span class="co"># Plot the histogram of the sampling distribution and the fitted normal curve</span></a>
<a class="sourceLine" id="cb700-2" data-line-number="2"><span class="kw">ggplot</span>(sampling_distrib_of_mean) <span class="op">+</span></a>
<a class="sourceLine" id="cb700-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(<span class="dt">x =</span> avg, <span class="dt">y =</span> <span class="kw">stat</span>(density)), <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb700-4" data-line-number="4"><span class="st">  </span><span class="kw">stat_function</span>(<span class="dt">fun =</span> dnorm, </a>
<a class="sourceLine" id="cb700-5" data-line-number="5">                <span class="dt">args =</span> <span class="kw">list</span>(<span class="dt">mean =</span> mean_of_distrib, <span class="dt">sd =</span> sd_of_distrib), </a>
<a class="sourceLine" id="cb700-6" data-line-number="6">                <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb700-7" data-line-number="7"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expr</span>(<span class="kw">bar</span>(x)))</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-444-1.png" width="672" /></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question 4
</p>
<div class="question-body">
<p>What are the population mean and standard deviation?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-59" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-59&#39;, &#39;sol-start-59&#39;)"></span>
</p>
<div id="sol-body-59" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb701"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb701-1" data-line-number="1">mu &lt;-<span class="st"> </span>nfl <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb701-2" data-line-number="2"><span class="st">  </span><span class="kw">pull</span>(YearlySalary) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb701-3" data-line-number="3"><span class="st">  </span><span class="kw">mean</span>()</a>
<a class="sourceLine" id="cb701-4" data-line-number="4">mu</a></code></pre></div>
<pre><code>## [1] 2.238363</code></pre>
<div class="sourceCode" id="cb703"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb703-1" data-line-number="1">sigma &lt;-<span class="st"> </span>nfl <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb703-2" data-line-number="2"><span class="st">  </span><span class="kw">pull</span>(YearlySalary) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb703-3" data-line-number="3"><span class="st">  </span><span class="kw">sd</span>()</a>
<a class="sourceLine" id="cb703-4" data-line-number="4">sigma</a></code></pre></div>
<pre><code>## [1] 3.066385</code></pre>
<ul>
<li>The population mean is <span class="math inline">\(\mu =\)</span> 2.24.</li>
<li>The population standard deviation is <span class="math inline">\(\sigma =\)</span> 3.07.</li>
</ul>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question 5
</p>
<div class="question-body">
<p>What are the mean and the standard deviation of the sampling distribution of the mean?</p>
<p><em><strong>Reminder:</strong> Remember that the standard deviation of the sampling distribution of the mean is also known as the standard error (SE) of the mean.</em></p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-60" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-60&#39;, &#39;sol-start-60&#39;)"></span>
</p>
<div id="sol-body-60" class="solution-body" style="display: none;">
<p>We have already calculated them to find the centre and spread of the normal curve:</p>
<div class="sourceCode" id="cb705"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb705-1" data-line-number="1">mean_of_distrib</a></code></pre></div>
<pre><code>## [1] 2.240886</code></pre>
<div class="sourceCode" id="cb707"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb707-1" data-line-number="1">sd_of_distrib</a></code></pre></div>
<pre><code>## [1] 0.297133</code></pre>
<ul>
<li>The distribution of sample means has mean 2.24.</li>
<li>The distribution of sample means has standard deviation 0.3.</li>
</ul>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question 6
</p>
<div class="question-body">
<p>What is the relation between the population mean and the mean of the sampling distribution?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-61" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-61&#39;, &#39;sol-start-61&#39;)"></span>
</p>
<div id="sol-body-61" class="solution-body" style="display: none;">
<p>The sampling distribution of the mean is centred at the population mean, <span class="math inline">\(\mu =\)</span> 2.24. In other words, the average of the sampling distribution of the mean is equal to the population mean.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question 7
</p>
<div class="question-body">
<p>Do you notice any relation between the population standard deviation and the standard error of the mean?</p>
<p><em><strong>Hint.</strong> If the population standard deviation is <span class="math inline">\(\sigma\)</span>, the sampling distribution of the mean should have standard deviation <span class="math inline">\(\frac{\sigma}{\sqrt{n}}\)</span>, where <span class="math inline">\(n\)</span> is the sample size.</em></p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-62" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-62&#39;, &#39;sol-start-62&#39;)"></span>
</p>
<div id="sol-body-62" class="solution-body" style="display: none;">
<ul>
<li>Population standard deviation: <span class="math inline">\(\sigma =\)</span> 3.07</li>
<li>Standard error of the mean: <span class="math inline">\(SE(\bar{x}) =\)</span> 0.3</li>
</ul>
<p>It looks like the SE of the mean is the population standard deviation divided by 10. However, recall that the sample size was 100, so <span class="math inline">\(10 = \sqrt{100}\)</span>.</p>
<p>In general, assume that the population has mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>.</p>
<p>It is possible to prove that the distribution of the mean, computed on samples of size <span class="math inline">\(n\)</span>, has mean equal to the population mean, <span class="math inline">\(\mu\)</span>, and standard error: <span class="math display">\[SE(\bar{x}) = \frac{\sigma}{\sqrt{n}}\]</span></p>
<div class="sourceCode" id="cb709"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb709-1" data-line-number="1"><span class="co"># Simulation-based standard error</span></a>
<a class="sourceLine" id="cb709-2" data-line-number="2">sd_of_distrib</a></code></pre></div>
<pre><code>## [1] 0.297133</code></pre>
<div class="sourceCode" id="cb711"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb711-1" data-line-number="1"><span class="co"># Theory-based standard error</span></a>
<a class="sourceLine" id="cb711-2" data-line-number="2">sigma <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(<span class="dv">100</span>)</a></code></pre></div>
<pre><code>## [1] 0.3066385</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question 8
</p>
<div class="question-body">
<p><strong>Comparison of the simulation-based and theory-based sampling distribution of the mean.</strong></p>
<p><em>Write down on paper the table below and fill the ? with the mean and the standard error computed using the simulation-based approach and the theory-based approach.</em></p>
<p>The sampling distribution of the mean is a normal distribution with mean and standard deviation:</p>
<table>
<thead>
<tr class="header">
<th align="center"></th>
<th align="center">Simulation-based approach</th>
<th align="center">Theory-based approach</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Mean</td>
<td align="center">?</td>
<td align="center"><span class="math inline">\(\mu =\)</span> ?</td>
</tr>
<tr class="even">
<td align="center">SE</td>
<td align="center">?</td>
<td align="center"><span class="math inline">\(\frac{\sigma}{\sqrt{n}} =\)</span> ?</td>
</tr>
</tbody>
</table>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-63" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-63&#39;, &#39;sol-start-63&#39;)"></span>
</p>
<div id="sol-body-63" class="solution-body" style="display: none;">
<table>
<thead>
<tr class="header">
<th align="center"></th>
<th align="center">Simulation-based approach</th>
<th align="center">Theory-based approach</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Mean</td>
<td align="center">2.24</td>
<td align="center"><span class="math inline">\(\mu =\)</span> 2.24</td>
</tr>
<tr class="even">
<td align="center">SE</td>
<td align="center">0.3</td>
<td align="center"><span class="math inline">\(\frac{\sigma}{\sqrt{n}} =\)</span> 0.31</td>
</tr>
</tbody>
</table>
<p>The simulation-based approach and the theory-based approach lead to very similar results.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>This is an important result. It means that, in order to show the sampling distribution of the mean, we would just:</p>
<ol style="list-style-type: decimal">
<li>load the data,</li>
<li>find the population mean <span class="math inline">\(\mu\)</span>,</li>
<li>find the population sd <span class="math inline">\(\sigma\)</span>,</li>
<li>plot a normal curve with mean = <span class="math inline">\(\mu\)</span> and sd = <span class="math inline">\(\frac{\sigma}{\sqrt{n}}\)</span>.</li>
</ol>
<p>This avoids us the burden of:</p>
<ul>
<li>repeatedly sampling from the population;</li>
<li>calculating the sample mean for each sample;</li>
<li>plotting the histogram of the sample means.</li>
</ul>
<div class="question">
<p class="question-begin">
► Question 9
</p>
<div class="question-body">
<p>The lengths of human pregnancies are normally distributed with mean <span class="math inline">\(\mu = 266\)</span> days and standard deviation <span class="math inline">\(\sigma = 16\)</span> days.</p>
<p>Plot the normal curve representing the length of human pregnancies.</p>
<p><em><strong>Hint:</strong> This requires the following steps:</em></p>
<ol style="list-style-type: decimal">
<li><em>Find the population mean and standard deviation</em>.</li>
<li><em>Create a grid of values for the length of pregnancy variable. Recall from <a href="bootstrapping-and-confidence-intervals.html#calculating-confidence-intervals-using-a-bootstrap-standard-error">Week 12</a> that 99.7% of all values lie between the mean plus or minus three standard deviations. To be sure to capture all of the values, use the mean plus or minus four standard deviations as limits</em>.</li>
<li><em>Compute the normal curve for the grid of values in (2)</em>.</li>
<li><em>Plot using <code>geom_line()</code></em>.</li>
</ol>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-64" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-64&#39;, &#39;sol-start-64&#39;)"></span>
</p>
<div id="sol-body-64" class="solution-body" style="display: none;">
<p>First we need to create a grid of days for the plot.</p>
<p>Remember from <a href="bootstrapping-and-confidence-intervals.html#calculating-confidence-intervals-using-a-bootstrap-standard-error">Week 12</a> that 99.7% of all values lie between the mean plus or minus three standard deviations.</p>
<p>To capture all of the values, we will use four times the standard deviation:</p>
<div class="sourceCode" id="cb713"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb713-1" data-line-number="1">mu &lt;-<span class="st"> </span><span class="dv">266</span></a>
<a class="sourceLine" id="cb713-2" data-line-number="2">sigma &lt;-<span class="st"> </span><span class="dv">16</span></a>
<a class="sourceLine" id="cb713-3" data-line-number="3"></a>
<a class="sourceLine" id="cb713-4" data-line-number="4">x &lt;-<span class="st"> </span><span class="kw">seq</span>(mu <span class="op">-</span><span class="st"> </span><span class="dv">4</span> <span class="op">*</span><span class="st"> </span>sigma, mu <span class="op">+</span><span class="st"> </span><span class="dv">4</span> <span class="op">*</span><span class="st"> </span>sigma, <span class="dt">by =</span> <span class="fl">0.1</span>)</a>
<a class="sourceLine" id="cb713-5" data-line-number="5">y &lt;-<span class="st"> </span><span class="kw">dnorm</span>(x, mu, sigma)</a>
<a class="sourceLine" id="cb713-6" data-line-number="6">df &lt;-<span class="st"> </span><span class="kw">tibble</span>(x, y)</a>
<a class="sourceLine" id="cb713-7" data-line-number="7"></a>
<a class="sourceLine" id="cb713-8" data-line-number="8"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y)) <span class="op">+</span></a>
<a class="sourceLine" id="cb713-9" data-line-number="9"><span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb713-10" data-line-number="10"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&#39;length of pregnancy (in days)&#39;</span>, <span class="dt">y =</span> <span class="st">&#39;normal density&#39;</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-448-1.png" width="672" /></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question 10
</p>
<div class="question-body">
<p>What is the proportion of the population with length of pregnancy greater than 280 days?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-65" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-65&#39;, &#39;sol-start-65&#39;)"></span>
</p>
<div id="sol-body-65" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb714"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb714-1" data-line-number="1"><span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="dv">280</span>, <span class="dt">mean =</span> mu, <span class="dt">sd =</span> sigma)</a></code></pre></div>
<pre><code>## [1] 0.190787</code></pre>
<p>The proportion of the population with length of pregnancy greater than 280 days is 19%.
Another way to say this is, the probability that a randomly selected person from the population will have a length of pregnancy greater than 280 days is 0.19.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question 11
</p>
<div class="question-body">
<p>What is the proportion of the population with length of pregnancy between 230 and 260 days?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-66" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-66&#39;, &#39;sol-start-66&#39;)"></span>
</p>
<div id="sol-body-66" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb716"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb716-1" data-line-number="1"><span class="kw">pnorm</span>(<span class="dv">260</span>, <span class="dt">mean =</span> mu, <span class="dt">sd =</span> sigma) <span class="op">-</span><span class="st"> </span><span class="kw">pnorm</span>(<span class="dv">230</span>, <span class="dt">mean =</span> mu, <span class="dt">sd =</span> sigma)</a></code></pre></div>
<pre><code>## [1] 0.3416058</code></pre>
<p>The proportion of the population with length of pregnancy between 230 and 260 days is 34%.
Another way to say this is, the probability that a randomly selected person from the population will have a length of pregnancy between 230 and 260 days is 0.34.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question 12
</p>
<div class="question-body">
<p>Using the theory-based approach, write down:</p>
<ol style="list-style-type: decimal">
<li>the mean of the sampling distribution of the average length of pregnancy using samples of size 50;</li>
<li>the standard error of the mean.</li>
</ol>
<p>Plot the sampling distribution of the mean for samples of size 50.</p>
<p><em><strong>Hint:</strong> Remember to create a grid of values going from <code>mean - 4 * SE</code> to <code>mean + 4 * SE</code>.</em></p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-67" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-67&#39;, &#39;sol-start-67&#39;)"></span>
</p>
<div id="sol-body-67" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb718"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb718-1" data-line-number="1">n &lt;-<span class="st"> </span><span class="dv">50</span></a>
<a class="sourceLine" id="cb718-2" data-line-number="2">SE &lt;-<span class="st"> </span>sigma <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(n)</a>
<a class="sourceLine" id="cb718-3" data-line-number="3">SE</a></code></pre></div>
<pre><code>## [1] 2.262742</code></pre>
<ol style="list-style-type: decimal">
<li>the sampling distribution is centred at the population mean, <span class="math inline">\(\mu = 266\)</span>;</li>
<li>the standard error of the mean is <span class="math inline">\(SE(\bar{x}) = \frac{\sigma}{\sqrt{n}} = \frac{16}{\sqrt{50}} = 2.26\)</span>.</li>
</ol>
<p>Let’s plot the sampling distribution of the mean:</p>
<div class="sourceCode" id="cb720"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb720-1" data-line-number="1">x &lt;-<span class="st"> </span><span class="kw">seq</span>(mu <span class="op">-</span><span class="st"> </span><span class="dv">4</span> <span class="op">*</span><span class="st"> </span>SE, mu <span class="op">+</span><span class="st"> </span><span class="dv">4</span> <span class="op">*</span><span class="st"> </span>SE, <span class="dt">by =</span> <span class="fl">0.1</span>)</a>
<a class="sourceLine" id="cb720-2" data-line-number="2">y &lt;-<span class="st"> </span><span class="kw">dnorm</span>(x, mu, SE)</a>
<a class="sourceLine" id="cb720-3" data-line-number="3">df &lt;-<span class="st"> </span><span class="kw">tibble</span>(x, y)</a>
<a class="sourceLine" id="cb720-4" data-line-number="4"></a>
<a class="sourceLine" id="cb720-5" data-line-number="5"><span class="kw">ggplot</span>(df, <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y)) <span class="op">+</span></a>
<a class="sourceLine" id="cb720-6" data-line-number="6"><span class="st">  </span><span class="kw">geom_line</span>(<span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">size =</span> <span class="dv">2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb720-7" data-line-number="7"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expr</span>(<span class="kw">bar</span>(x)), <span class="dt">y =</span> <span class="st">&#39;normal density&#39;</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-452-1.png" width="672" /></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="glossary-4" class="section level2">
<h2><span class="header-section-number">15.5</span> Glossary</h2>
<ul>
<li><em>Normal curve.</em> A density curve used to model symmetric and bell-shaped distributions of continuous random variables.</li>
<li><em>Distribution of the sample mean.</em> The sample mean is a random variable which is normally distributed. Its mean is <span class="math inline">\(\mu\)</span> and its standard deviation (standard error of the mean) is <span class="math inline">\(\frac{\sigma}{\sqrt{n}}\)</span>.</li>
<li><em>Simulation-based SE of the mean.</em> The standard deviation of the sampling distribution of the mean, obtained by generating many random samples and calculating the mean for each sample.</li>
<li><em>Theory-based SE of the mean.</em> For a population with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>, the SE of the mean computed on samples of size <span class="math inline">\(n\)</span> is <span class="math inline">\(SE(\bar{x}) = \frac{\sigma}{\sqrt{n}}\)</span>.</li>
<li><em>Z-score.</em> The transformation <span class="math inline">\(\frac{x - \mu}{\sigma}\)</span>. It translates a value from a <span class="math inline">\(N(\mu, \sigma)\)</span> scale to a <span class="math inline">\(N(0,1)\)</span> scale.</li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="chap-typeerror.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-one-mean-test.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
