<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 11 Sampling distributions | Data Analysis for Psychology in R (dapR1) - Labs</title>
  <meta name="description" content="This is the page that contains the course labs materials" />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 11 Sampling distributions | Data Analysis for Psychology in R (dapR1) - Labs" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the page that contains the course labs materials" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 11 Sampling distributions | Data Analysis for Psychology in R (dapR1) - Labs" />
  
  <meta name="twitter:description" content="This is the page that contains the course labs materials" />
  

<meta name="author" content="Department of Psychology, University of Edinburgh" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="week-10-lab-test.html"/>
<link rel="next" href="bootstrapping-and-confidence-intervals.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script>
  $(document).ready(function() {
    $head = $('#header');
    $head.prepend('<img style="padding-right:25%; margin-bottom:10px;" src="https://www.ed.ac.uk/sites/all/themes/uoe/assets/logo.png" width="770px" align="left">')
  });
</script>

<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}
}
</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">DAPR1</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview of the Course</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#the-team"><i class="fa fa-check"></i>The team</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-cheatsheets"><i class="fa fa-check"></i>R Cheatsheets</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-community"><i class="fa fa-check"></i>R Community</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="week-1.html"><a href="week-1.html"><i class="fa fa-check"></i><b>1</b> Week 1</a><ul>
<li class="chapter" data-level="1.1" data-path="week-1.html"><a href="week-1.html#introduction-to-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> Introduction to R and RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="week-1.html"><a href="week-1.html#install-the-recent-version-of-r-and-r-studio"><i class="fa fa-check"></i><b>1.2</b> Install the recent version of R and R Studio</a><ul>
<li class="chapter" data-level="1.2.1" data-path="week-1.html"><a href="week-1.html#first-step"><i class="fa fa-check"></i><b>1.2.1</b> First Step</a></li>
<li class="chapter" data-level="1.2.2" data-path="week-1.html"><a href="week-1.html#second-step"><i class="fa fa-check"></i><b>1.2.2</b> Second Step</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="week-1.html"><a href="week-1.html#getting-started-in-rstudio"><i class="fa fa-check"></i><b>1.3</b> Getting Started in RStudio</a></li>
<li class="chapter" data-level="1.4" data-path="week-1.html"><a href="week-1.html#r-as-an-interactive-environment"><i class="fa fa-check"></i><b>1.4</b> R as an interactive environment</a></li>
<li class="chapter" data-level="1.5" data-path="week-1.html"><a href="week-1.html#check-your-settings"><i class="fa fa-check"></i><b>1.5</b> Check your settings</a><ul>
<li class="chapter" data-level="1.5.1" data-path="week-1.html"><a href="week-1.html#disable-automatic-saving-of-your-workspace"><i class="fa fa-check"></i><b>1.5.1</b> Disable automatic saving of your workspace</a></li>
<li class="chapter" data-level="1.5.2" data-path="week-1.html"><a href="week-1.html#adjust-fontscolours-if-you-like"><i class="fa fa-check"></i><b>1.5.2</b> Adjust fonts/colours if you like</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="week-1.html"><a href="week-1.html#setting-up-your-working-directory"><i class="fa fa-check"></i><b>1.6</b> Setting Up Your Working Directory</a></li>
<li class="chapter" data-level="1.7" data-path="week-1.html"><a href="week-1.html#the-console"><i class="fa fa-check"></i><b>1.7</b> The Console</a></li>
<li class="chapter" data-level="1.8" data-path="week-1.html"><a href="week-1.html#spacing"><i class="fa fa-check"></i><b>1.8</b> Spacing</a></li>
<li class="chapter" data-level="1.9" data-path="week-1.html"><a href="week-1.html#typos"><i class="fa fa-check"></i><b>1.9</b> Typos</a></li>
<li class="chapter" data-level="1.10" data-path="week-1.html"><a href="week-1.html#unfinishe.-d"><i class="fa fa-check"></i><b>1.10</b> Unfinishe…. d</a></li>
<li class="chapter" data-level="1.11" data-path="week-1.html"><a href="week-1.html#basic-arithmetic"><i class="fa fa-check"></i><b>1.11</b> Basic Arithmetic</a></li>
<li class="chapter" data-level="1.12" data-path="week-1.html"><a href="week-1.html#using-functions-for-calculations"><i class="fa fa-check"></i><b>1.12</b> Using Functions for Calculations</a></li>
<li class="chapter" data-level="1.13" data-path="week-1.html"><a href="week-1.html#r-scripts"><i class="fa fa-check"></i><b>1.13</b> R Scripts</a></li>
<li class="chapter" data-level="1.14" data-path="week-1.html"><a href="week-1.html#short-example"><i class="fa fa-check"></i><b>1.14</b> Short Example</a></li>
<li class="chapter" data-level="1.15" data-path="week-1.html"><a href="week-1.html#naming-variables"><i class="fa fa-check"></i><b>1.15</b> Naming variables</a></li>
<li class="chapter" data-level="1.16" data-path="week-1.html"><a href="week-1.html#now-over-to-you"><i class="fa fa-check"></i><b>1.16</b> Now over to you</a><ul>
<li class="chapter" data-level="1.16.1" data-path="week-1.html"><a href="week-1.html#exercise-1"><i class="fa fa-check"></i><b>1.16.1</b> Exercise 1</a></li>
<li class="chapter" data-level="1.16.2" data-path="week-1.html"><a href="week-1.html#exercise-2"><i class="fa fa-check"></i><b>1.16.2</b> Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="1.17" data-path="week-1.html"><a href="week-1.html#solutions"><i class="fa fa-check"></i><b>1.17</b> Solutions</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="week-2.html"><a href="week-2.html"><i class="fa fa-check"></i><b>2</b> Week 2</a><ul>
<li class="chapter" data-level="2.1" data-path="week-2.html"><a href="week-2.html#introduction-to-rmarkdown"><i class="fa fa-check"></i><b>2.1</b> Introduction to RMarkdown</a></li>
<li class="chapter" data-level="2.2" data-path="week-2.html"><a href="week-2.html#what-is-r-markdown"><i class="fa fa-check"></i><b>2.2</b> What is R Markdown?</a></li>
<li class="chapter" data-level="2.3" data-path="week-2.html"><a href="week-2.html#getting-things-ready"><i class="fa fa-check"></i><b>2.3</b> Getting things ready</a></li>
<li class="chapter" data-level="2.4" data-path="week-2.html"><a href="week-2.html#r-markdown-basics"><i class="fa fa-check"></i><b>2.4</b> R Markdown basics</a></li>
<li class="chapter" data-level="2.5" data-path="week-2.html"><a href="week-2.html#headings"><i class="fa fa-check"></i><b>2.5</b> Headings</a></li>
<li class="chapter" data-level="2.6" data-path="week-2.html"><a href="week-2.html#text"><i class="fa fa-check"></i><b>2.6</b> Text</a></li>
<li class="chapter" data-level="2.7" data-path="week-2.html"><a href="week-2.html#tables"><i class="fa fa-check"></i><b>2.7</b> Tables</a></li>
<li class="chapter" data-level="2.8" data-path="week-2.html"><a href="week-2.html#lists"><i class="fa fa-check"></i><b>2.8</b> Lists</a><ul>
<li class="chapter" data-level="2.8.1" data-path="week-2.html"><a href="week-2.html#unordered"><i class="fa fa-check"></i><b>2.8.1</b> Unordered</a></li>
<li class="chapter" data-level="2.8.2" data-path="week-2.html"><a href="week-2.html#ordered"><i class="fa fa-check"></i><b>2.8.2</b> Ordered</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="week-2.html"><a href="week-2.html#rmd-documents"><i class="fa fa-check"></i><b>2.9</b> Rmd documents</a></li>
<li class="chapter" data-level="2.10" data-path="week-2.html"><a href="week-2.html#code-chunks"><i class="fa fa-check"></i><b>2.10</b> Code chunks</a></li>
<li class="chapter" data-level="2.11" data-path="week-2.html"><a href="week-2.html#common-code-chunks-options"><i class="fa fa-check"></i><b>2.11</b> Common Code Chunks Options</a></li>
<li class="chapter" data-level="2.12" data-path="week-2.html"><a href="week-2.html#including-images-or-links"><i class="fa fa-check"></i><b>2.12</b> Including images or links</a><ul>
<li class="chapter" data-level="2.12.1" data-path="week-2.html"><a href="week-2.html#adding-links"><i class="fa fa-check"></i><b>2.12.1</b> Adding links</a></li>
<li class="chapter" data-level="2.12.2" data-path="week-2.html"><a href="week-2.html#adding-figures-pictures"><i class="fa fa-check"></i><b>2.12.2</b> Adding figures &amp; pictures</a></li>
</ul></li>
<li class="chapter" data-level="2.13" data-path="week-2.html"><a href="week-2.html#generating-documents"><i class="fa fa-check"></i><b>2.13</b> Generating documents</a></li>
<li class="chapter" data-level="2.14" data-path="week-2.html"><a href="week-2.html#extra-opensave-files-on-rstudio-cloud-chrome-users"><i class="fa fa-check"></i><b>2.14</b> Extra: Open/Save files on Rstudio Cloud (Chrome users)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-3.html"><a href="week-3.html"><i class="fa fa-check"></i><b>3</b> Week 3</a><ul>
<li class="chapter" data-level="3.1" data-path="week-3.html"><a href="week-3.html#vectors-lists-data-frames-and-data-types"><i class="fa fa-check"></i><b>3.1</b> Vectors, lists, data frames and data types</a></li>
<li class="chapter" data-level="3.2" data-path="week-3.html"><a href="week-3.html#get-the-package-first"><i class="fa fa-check"></i><b>3.2</b> Get the package first</a></li>
<li class="chapter" data-level="3.3" data-path="week-3.html"><a href="week-3.html#numeric-data"><i class="fa fa-check"></i><b>3.3</b> Numeric Data</a></li>
<li class="chapter" data-level="3.4" data-path="week-3.html"><a href="week-3.html#textcharacter-data"><i class="fa fa-check"></i><b>3.4</b> Text/Character Data</a></li>
<li class="chapter" data-level="3.5" data-path="week-3.html"><a href="week-3.html#logical-data"><i class="fa fa-check"></i><b>3.5</b> Logical Data</a></li>
<li class="chapter" data-level="3.6" data-path="week-3.html"><a href="week-3.html#variable-classes"><i class="fa fa-check"></i><b>3.6</b> Variable Classes</a></li>
<li class="chapter" data-level="3.7" data-path="week-3.html"><a href="week-3.html#factors"><i class="fa fa-check"></i><b>3.7</b> Factors</a></li>
<li class="chapter" data-level="3.8" data-path="week-3.html"><a href="week-3.html#lists-1"><i class="fa fa-check"></i><b>3.8</b> Lists</a></li>
<li class="chapter" data-level="3.9" data-path="week-3.html"><a href="week-3.html#practice.rmd-solutions"><i class="fa fa-check"></i><b>3.9</b> Practice.Rmd Solutions</a><ul>
<li class="chapter" data-level="3.9.1" data-path="week-3.html"><a href="week-3.html#exercise-1-1"><i class="fa fa-check"></i><b>3.9.1</b> Exercise 1</a></li>
<li class="chapter" data-level="3.9.2" data-path="week-3.html"><a href="week-3.html#exercise-2-1"><i class="fa fa-check"></i><b>3.9.2</b> Exercise 2</a></li>
<li class="chapter" data-level="3.9.3" data-path="week-3.html"><a href="week-3.html#exercise-3"><i class="fa fa-check"></i><b>3.9.3</b> Exercise 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-4.html"><a href="week-4.html"><i class="fa fa-check"></i><b>4</b> Week 4</a><ul>
<li class="chapter" data-level="4.1" data-path="week-4.html"><a href="week-4.html#introduction-to-plots-geoms-ggplot"><i class="fa fa-check"></i><b>4.1</b> Introduction to plots &amp; geoms (ggplot)</a></li>
<li class="chapter" data-level="4.2" data-path="week-4.html"><a href="week-4.html#visualisations"><i class="fa fa-check"></i><b>4.2</b> Visualisations</a></li>
<li class="chapter" data-level="4.3" data-path="week-4.html"><a href="week-4.html#get-our-data-sorted"><i class="fa fa-check"></i><b>4.3</b> Get our data sorted</a></li>
<li class="chapter" data-level="4.4" data-path="week-4.html"><a href="week-4.html#numerical-data"><i class="fa fa-check"></i><b>4.4</b> Numerical data</a></li>
<li class="chapter" data-level="4.5" data-path="week-4.html"><a href="week-4.html#simple-one-variable-plot-using-ggplot"><i class="fa fa-check"></i><b>4.5</b> Simple one-variable plot using ggplot()</a><ul>
<li class="chapter" data-level="4.5.1" data-path="week-4.html"><a href="week-4.html#continuous-variable"><i class="fa fa-check"></i><b>4.5.1</b> Continuous variable</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="week-4.html"><a href="week-4.html#categorical-variables"><i class="fa fa-check"></i><b>4.6</b> Categorical variables</a></li>
<li class="chapter" data-level="4.7" data-path="week-4.html"><a href="week-4.html#continuous-variables-grouped-by-a-categorical-one"><i class="fa fa-check"></i><b>4.7</b> Continuous variables grouped by a categorical one</a></li>
<li class="chapter" data-level="4.8" data-path="week-4.html"><a href="week-4.html#even-more-advanced"><i class="fa fa-check"></i><b>4.8</b> Even more advanced</a></li>
<li class="chapter" data-level="4.9" data-path="week-4.html"><a href="week-4.html#practice.rmd-solutions-1"><i class="fa fa-check"></i><b>4.9</b> Practice.Rmd Solutions</a><ul>
<li class="chapter" data-level="4.9.1" data-path="week-4.html"><a href="week-4.html#exercise-1-2"><i class="fa fa-check"></i><b>4.9.1</b> Exercise 1</a></li>
<li class="chapter" data-level="4.9.2" data-path="week-4.html"><a href="week-4.html#exercise-2-2"><i class="fa fa-check"></i><b>4.9.2</b> Exercise 2</a></li>
<li class="chapter" data-level="4.9.3" data-path="week-4.html"><a href="week-4.html#exercise-3---advanced"><i class="fa fa-check"></i><b>4.9.3</b> Exercise 3 - Advanced</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-5.html"><a href="week-5.html"><i class="fa fa-check"></i><b>5</b> Week 5</a><ul>
<li class="chapter" data-level="5.1" data-path="week-5.html"><a href="week-5.html#central-tendency-and-variability"><i class="fa fa-check"></i><b>5.1</b> Central Tendency and Variability</a></li>
<li class="chapter" data-level="5.2" data-path="week-5.html"><a href="week-5.html#load-all-the-necessary-packages"><i class="fa fa-check"></i><b>5.2</b> Load all the necessary packages</a></li>
<li class="chapter" data-level="5.3" data-path="week-5.html"><a href="week-5.html#descriptive-statistics"><i class="fa fa-check"></i><b>5.3</b> Descriptive Statistics</a></li>
<li class="chapter" data-level="5.4" data-path="week-5.html"><a href="week-5.html#central-tendency-variability"><i class="fa fa-check"></i><b>5.4</b> Central tendency &amp; variability</a></li>
<li class="chapter" data-level="5.5" data-path="week-5.html"><a href="week-5.html#mean-and-median"><i class="fa fa-check"></i><b>5.5</b> Mean and median</a><ul>
<li class="chapter" data-level="5.5.1" data-path="week-5.html"><a href="week-5.html#reading-data-in"><i class="fa fa-check"></i><b>5.5.1</b> Reading data in</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="week-5.html"><a href="week-5.html#using-piping-operator-for-descriptive-statistics"><i class="fa fa-check"></i><b>5.6</b> Using piping operator for descriptive statistics</a><ul>
<li class="chapter" data-level="5.6.1" data-path="week-5.html"><a href="week-5.html#mean"><i class="fa fa-check"></i><b>5.6.1</b> Mean</a></li>
<li class="chapter" data-level="5.6.2" data-path="week-5.html"><a href="week-5.html#median"><i class="fa fa-check"></i><b>5.6.2</b> Median</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="week-5.html"><a href="week-5.html#standard-deviation"><i class="fa fa-check"></i><b>5.7</b> Standard deviation</a></li>
<li class="chapter" data-level="5.8" data-path="week-5.html"><a href="week-5.html#visualise-your-data"><i class="fa fa-check"></i><b>5.8</b> Visualise your data</a></li>
<li class="chapter" data-level="5.9" data-path="week-5.html"><a href="week-5.html#practice.rmd-solutions-2"><i class="fa fa-check"></i><b>5.9</b> Practice.Rmd Solutions</a><ul>
<li class="chapter" data-level="5.9.1" data-path="week-5.html"><a href="week-5.html#income-distribution-example"><i class="fa fa-check"></i><b>5.9.1</b> Income Distribution Example</a></li>
<li class="chapter" data-level="5.9.2" data-path="week-5.html"><a href="week-5.html#visualisations-1"><i class="fa fa-check"></i><b>5.9.2</b> Visualisations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-6.html"><a href="week-6.html"><i class="fa fa-check"></i><b>6</b> Week 6</a><ul>
<li class="chapter" data-level="6.1" data-path="week-6.html"><a href="week-6.html#plotting-functions-and-simple-data-transformation"><i class="fa fa-check"></i><b>6.1</b> Plotting Functions and Simple Data Transformation</a></li>
<li class="chapter" data-level="6.2" data-path="week-6.html"><a href="week-6.html#load-all-the-necessary-packages-1"><i class="fa fa-check"></i><b>6.2</b> Load all the necessary packages</a></li>
<li class="chapter" data-level="6.3" data-path="week-6.html"><a href="week-6.html#part-1-hand-plotting-functions"><i class="fa fa-check"></i><b>6.3</b> Part 1: Hand plotting functions</a></li>
<li class="chapter" data-level="6.4" data-path="week-6.html"><a href="week-6.html#basics"><i class="fa fa-check"></i><b>6.4</b> Basics</a></li>
<li class="chapter" data-level="6.5" data-path="week-6.html"><a href="week-6.html#linear-functions"><i class="fa fa-check"></i><b>6.5</b> Linear functions</a><ul>
<li class="chapter" data-level="6.5.1" data-path="week-6.html"><a href="week-6.html#tree-height-example"><i class="fa fa-check"></i><b>6.5.1</b> Tree height example</a></li>
<li class="chapter" data-level="6.5.2" data-path="week-6.html"><a href="week-6.html#non-linear-functions-first-order-polynomials"><i class="fa fa-check"></i><b>6.5.2</b> Non-linear functions (first order polynomials)</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="week-6.html"><a href="week-6.html#practice-plotting"><i class="fa fa-check"></i><b>6.6</b> Practice plotting</a></li>
<li class="chapter" data-level="6.7" data-path="week-6.html"><a href="week-6.html#part-2-introduction-to-data-transformation"><i class="fa fa-check"></i><b>6.7</b> Part 2: Introduction to Data Transformation</a></li>
<li class="chapter" data-level="6.8" data-path="week-6.html"><a href="week-6.html#renaming"><i class="fa fa-check"></i><b>6.8</b> Renaming</a></li>
<li class="chapter" data-level="6.9" data-path="week-6.html"><a href="week-6.html#adding-new-variables"><i class="fa fa-check"></i><b>6.9</b> Adding new variables</a></li>
<li class="chapter" data-level="6.10" data-path="week-6.html"><a href="week-6.html#transformation-and-skewness"><i class="fa fa-check"></i><b>6.10</b> Transformation and skewness</a></li>
<li class="chapter" data-level="6.11" data-path="week-6.html"><a href="week-6.html#mean-centering"><i class="fa fa-check"></i><b>6.11</b> Mean Centering</a></li>
<li class="chapter" data-level="6.12" data-path="week-6.html"><a href="week-6.html#standardisation"><i class="fa fa-check"></i><b>6.12</b> Standardisation</a></li>
<li class="chapter" data-level="6.13" data-path="week-6.html"><a href="week-6.html#practice.rmd-solutions-3"><i class="fa fa-check"></i><b>6.13</b> Practice.Rmd Solutions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="week-7.html"><a href="week-7.html"><i class="fa fa-check"></i><b>7</b> Week 7</a><ul>
<li class="chapter" data-level="7.1" data-path="week-7.html"><a href="week-7.html#reading-in-data-merge-and-more-r-practice"><i class="fa fa-check"></i><b>7.1</b> Reading in Data, Merge and More R Practice</a></li>
<li class="chapter" data-level="7.2" data-path="week-7.html"><a href="week-7.html#dataset-1-.csv"><i class="fa fa-check"></i><b>7.2</b> Dataset 1 (.csv)</a></li>
<li class="chapter" data-level="7.3" data-path="week-7.html"><a href="week-7.html#dataset-2-.txt"><i class="fa fa-check"></i><b>7.3</b> Dataset 2 (.txt)</a></li>
<li class="chapter" data-level="7.4" data-path="week-7.html"><a href="week-7.html#dataset-3-.sav-and-.dta"><i class="fa fa-check"></i><b>7.4</b> Dataset 3 (.sav and .dta)</a></li>
<li class="chapter" data-level="7.5" data-path="week-7.html"><a href="week-7.html#merging-datasets-together"><i class="fa fa-check"></i><b>7.5</b> Merging datasets together</a></li>
<li class="chapter" data-level="7.6" data-path="week-7.html"><a href="week-7.html#sorting-and-arrange"><i class="fa fa-check"></i><b>7.6</b> Sorting and arrange()</a></li>
<li class="chapter" data-level="7.7" data-path="week-7.html"><a href="week-7.html#data-description"><i class="fa fa-check"></i><b>7.7</b> Data description</a></li>
<li class="chapter" data-level="7.8" data-path="week-7.html"><a href="week-7.html#using-filter"><i class="fa fa-check"></i><b>7.8</b> Using filter()</a></li>
<li class="chapter" data-level="7.9" data-path="week-7.html"><a href="week-7.html#visualisations-2"><i class="fa fa-check"></i><b>7.9</b> Visualisations</a></li>
<li class="chapter" data-level="7.10" data-path="week-7.html"><a href="week-7.html#save-the-file-in-your-folder"><i class="fa fa-check"></i><b>7.10</b> Save the file in your folder</a></li>
<li class="chapter" data-level="7.11" data-path="week-7.html"><a href="week-7.html#practice.rmd-solutions-4"><i class="fa fa-check"></i><b>7.11</b> Practice.Rmd Solutions</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="week-8.html"><a href="week-8.html"><i class="fa fa-check"></i><b>8</b> Week 8</a><ul>
<li class="chapter" data-level="8.1" data-path="week-8.html"><a href="week-8.html#introduction-to-probability"><i class="fa fa-check"></i><b>8.1</b> Introduction to Probability</a></li>
<li class="chapter" data-level="8.2" data-path="week-8.html"><a href="week-8.html#example-1-hot-hand"><i class="fa fa-check"></i><b>8.2</b> Example 1 (hot hand)</a></li>
<li class="chapter" data-level="8.3" data-path="week-8.html"><a href="week-8.html#example-2-coin-toss"><i class="fa fa-check"></i><b>8.3</b> Example 2 (coin toss)</a></li>
<li class="chapter" data-level="8.4" data-path="week-8.html"><a href="week-8.html#example-3-independent-shooter"><i class="fa fa-check"></i><b>8.4</b> Example 3 (Independent shooter)</a></li>
<li class="chapter" data-level="8.5" data-path="week-8.html"><a href="week-8.html#practice-rmd.-solutions"><i class="fa fa-check"></i><b>8.5</b> Practice Rmd. Solutions</a><ul>
<li class="chapter" data-level="8.5.1" data-path="week-8.html"><a href="week-8.html#sex-of-the-babies-born-in-the-uk"><i class="fa fa-check"></i><b>8.5.1</b> Sex of the babies born in the UK</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="week-8.html"><a href="week-8.html#pen-and-paper-exercises"><i class="fa fa-check"></i><b>8.6</b> Pen and Paper Exercises</a><ul>
<li class="chapter" data-level="8.6.1" data-path="week-8.html"><a href="week-8.html#boys-and-girls-paradox-mr.jones-and-mr.smith"><i class="fa fa-check"></i><b>8.6.1</b> Boys and girls paradox (Mr. Jones and Mr. Smith)</a></li>
<li class="chapter" data-level="8.6.2" data-path="week-8.html"><a href="week-8.html#rugby-captain"><i class="fa fa-check"></i><b>8.6.2</b> Rugby captain</a></li>
<li class="chapter" data-level="8.6.3" data-path="week-8.html"><a href="week-8.html#answers"><i class="fa fa-check"></i><b>8.6.3</b> Answers</a></li>
<li class="chapter" data-level="8.6.4" data-path="week-8.html"><a href="week-8.html#defective"><i class="fa fa-check"></i><b>8.6.4</b> Defective</a></li>
<li class="chapter" data-level="8.6.5" data-path="week-8.html"><a href="week-8.html#answers-1"><i class="fa fa-check"></i><b>8.6.5</b> Answers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="week-9.html"><a href="week-9.html"><i class="fa fa-check"></i><b>9</b> Week 9</a><ul>
<li class="chapter" data-level="9.1" data-path="week-9.html"><a href="week-9.html#introduction-to-probability-distributions-and-revision"><i class="fa fa-check"></i><b>9.1</b> Introduction to Probability Distributions and Revision</a></li>
<li class="chapter" data-level="9.2" data-path="week-9.html"><a href="week-9.html#discrete-example-guessing-homework-answers"><i class="fa fa-check"></i><b>9.2</b> Discrete example (guessing homework answers)</a></li>
<li class="chapter" data-level="9.3" data-path="week-9.html"><a href="week-9.html#generate-a-homework-attempt"><i class="fa fa-check"></i><b>9.3</b> Generate a homework attempt</a></li>
<li class="chapter" data-level="9.4" data-path="week-9.html"><a href="week-9.html#changing-the-probability-truefalse"><i class="fa fa-check"></i><b>9.4</b> Changing the probability (TRUE/FALSE)</a></li>
<li class="chapter" data-level="9.5" data-path="week-9.html"><a href="week-9.html#studying-the-distribution"><i class="fa fa-check"></i><b>9.5</b> Studying the distribution</a></li>
<li class="chapter" data-level="9.6" data-path="week-9.html"><a href="week-9.html#cumulative-probability-advanced"><i class="fa fa-check"></i><b>9.6</b> Cumulative Probability (Advanced)</a></li>
<li class="chapter" data-level="9.7" data-path="week-9.html"><a href="week-9.html#revision-practice-rmd.-solutions"><i class="fa fa-check"></i><b>9.7</b> Revision Practice Rmd. Solutions</a><ul>
<li class="chapter" data-level="9.7.1" data-path="week-9.html"><a href="week-9.html#provide-descriptive-statistics-for-age-and-memory-score-variables"><i class="fa fa-check"></i><b>9.7.1</b> Provide descriptive statistics for age and memory score variables</a></li>
<li class="chapter" data-level="9.7.2" data-path="week-9.html"><a href="week-9.html#descriptives-by-groups"><i class="fa fa-check"></i><b>9.7.2</b> Descriptives by groups</a></li>
<li class="chapter" data-level="9.7.3" data-path="week-9.html"><a href="week-9.html#visualise"><i class="fa fa-check"></i><b>9.7.3</b> Visualise</a></li>
<li class="chapter" data-level="9.7.4" data-path="week-9.html"><a href="week-9.html#visualise-a-subset"><i class="fa fa-check"></i><b>9.7.4</b> Visualise a subset</a></li>
<li class="chapter" data-level="9.7.5" data-path="week-9.html"><a href="week-9.html#variable-by-a-group"><i class="fa fa-check"></i><b>9.7.5</b> Variable by a group</a></li>
<li class="chapter" data-level="9.7.6" data-path="week-9.html"><a href="week-9.html#create-a-new-variable-using-mutate"><i class="fa fa-check"></i><b>9.7.6</b> Create a new variable using mutate()</a></li>
<li class="chapter" data-level="9.7.7" data-path="week-9.html"><a href="week-9.html#subset-observations-using-filter"><i class="fa fa-check"></i><b>9.7.7</b> Subset observations using filter()</a></li>
<li class="chapter" data-level="9.7.8" data-path="week-9.html"><a href="week-9.html#sort-via-arrange"><i class="fa fa-check"></i><b>9.7.8</b> Sort via arrange()</a></li>
<li class="chapter" data-level="9.7.9" data-path="week-9.html"><a href="week-9.html#lets-do-some-specific-count-using-filter"><i class="fa fa-check"></i><b>9.7.9</b> Let’s do some specific count() using filter()</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="week-9.html"><a href="week-9.html#extra-probability-practice"><i class="fa fa-check"></i><b>9.8</b> Extra Probability Practice</a><ul>
<li class="chapter" data-level="9.8.1" data-path="week-9.html"><a href="week-9.html#truefalse-questions"><i class="fa fa-check"></i><b>9.8.1</b> TRUE/FALSE questions</a></li>
<li class="chapter" data-level="9.8.2" data-path="week-9.html"><a href="week-9.html#count-the-occurencies"><i class="fa fa-check"></i><b>9.8.2</b> Count the occurencies</a></li>
<li class="chapter" data-level="9.8.3" data-path="week-9.html"><a href="week-9.html#plot"><i class="fa fa-check"></i><b>9.8.3</b> Plot</a></li>
<li class="chapter" data-level="9.8.4" data-path="week-9.html"><a href="week-9.html#use-dbinom-to-study-the-probability"><i class="fa fa-check"></i><b>9.8.4</b> Use dbinom() to study the probability</a></li>
<li class="chapter" data-level="9.8.5" data-path="week-9.html"><a href="week-9.html#less-than-five-or-more-than-five"><i class="fa fa-check"></i><b>9.8.5</b> Less than five or more than five?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="week-10-lab-test.html"><a href="week-10-lab-test.html"><i class="fa fa-check"></i><b>10</b> Week 10: Lab test</a></li>
<li class="chapter" data-level="11" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html"><i class="fa fa-check"></i><b>11</b> Sampling distributions</a><ul>
<li class="chapter" data-level="11.1" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#recap"><i class="fa fa-check"></i><b>11.1</b> Recap</a></li>
<li class="chapter" data-level="11.2" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#population-sample"><i class="fa fa-check"></i><b>11.2</b> Population vs sample</a></li>
<li class="chapter" data-level="11.3" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#parameter-statistic"><i class="fa fa-check"></i><b>11.3</b> Population parameter vs sample statistic</a></li>
<li class="chapter" data-level="11.4" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#sec-sampling-distributions"><i class="fa fa-check"></i><b>11.4</b> Sampling distributions</a></li>
<li class="chapter" data-level="11.5" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#standard-error"><i class="fa fa-check"></i><b>11.5</b> The standard error of a statistic</a></li>
<li class="chapter" data-level="11.6" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#sample-size-standard-error"><i class="fa fa-check"></i><b>11.6</b> The effect of sample size on the sampling distribution</a></li>
<li class="chapter" data-level="11.7" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#take-home-message"><i class="fa fa-check"></i><b>11.7</b> Take-home message</a></li>
<li class="chapter" data-level="11.8" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#lab-hollywood-movies"><i class="fa fa-check"></i><b>11.8</b> Lab: Hollywood movies</a></li>
<li class="chapter" data-level="11.9" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#summary"><i class="fa fa-check"></i><b>11.9</b> Summary</a></li>
<li class="chapter" data-level="11.10" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#glossary"><i class="fa fa-check"></i><b>11.10</b> Glossary</a></li>
<li class="chapter" data-level="11.11" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#references"><i class="fa fa-check"></i><b>11.11</b> References</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html"><i class="fa fa-check"></i><b>12</b> Bootstrapping and Confidence Intervals</a><ul>
<li class="chapter" data-level="12.1" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#recap-1"><i class="fa fa-check"></i><b>12.1</b> Recap</a></li>
<li class="chapter" data-level="12.2" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#from-sampling-to-resampling"><i class="fa fa-check"></i><b>12.2</b> From Sampling to Resampling</a></li>
<li class="chapter" data-level="12.3" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#getting-to-the-bootstrap-distribution"><i class="fa fa-check"></i><b>12.3</b> Getting to the bootstrap distribution</a></li>
<li class="chapter" data-level="12.4" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#more-generally"><i class="fa fa-check"></i><b>12.4</b> More generally…</a></li>
<li class="chapter" data-level="12.5" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#confidence-intervals"><i class="fa fa-check"></i><b>12.5</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="12.5.1" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#calculating-confidence-intervals-using-a-bootstrap-standard-error"><i class="fa fa-check"></i><b>12.5.1</b> Calculating confidence intervals using a bootstrap standard error</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#summary-1"><i class="fa fa-check"></i><b>12.6</b> Summary</a></li>
<li class="chapter" data-level="12.7" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#take-home-message-1"><i class="fa fa-check"></i><b>12.7</b> Take-home message</a></li>
<li class="chapter" data-level="12.8" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#lab"><i class="fa fa-check"></i><b>12.8</b> Lab</a><ul>
<li class="chapter" data-level="" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#exercise-1-hollywood-movies"><i class="fa fa-check"></i>Exercise 1: Hollywood Movies</a></li>
<li class="chapter" data-level="" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#exercise-2-nfl-players"><i class="fa fa-check"></i>Exercise 2: NFL Players</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#glossary-1"><i class="fa fa-check"></i><b>12.9</b> Glossary</a></li>
<li class="chapter" data-level="12.10" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#references-1"><i class="fa fa-check"></i><b>12.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html"><i class="fa fa-check"></i><b>13</b> Testing hypotheses</a><ul>
<li class="chapter" data-level="13.1" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#recap-2"><i class="fa fa-check"></i><b>13.1</b> Recap</a></li>
<li class="chapter" data-level="13.2" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#walkthrough"><i class="fa fa-check"></i><b>13.2</b> Walkthrough</a><ul>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#extrasensory-perception-esp"><i class="fa fa-check"></i>Extrasensory perception (ESP)</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#example-esp-results"><i class="fa fa-check"></i>Example 1: ESP experimental results</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#example-in-class"><i class="fa fa-check"></i>Example 2: In-class activity</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#the-random-chance-model"><i class="fa fa-check"></i>The random chance model</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#the-alternative-explanation"><i class="fa fa-check"></i>The alternative explanation</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#statistical-test"><i class="fa fa-check"></i>Statistical test</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#understanding-statistical-evidence"><i class="fa fa-check"></i>Understanding statistical evidence</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#statistical-hypotheses"><i class="fa fa-check"></i>Statistical hypotheses</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#statistical-significance"><i class="fa fa-check"></i>Statistical significance</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#null-distribution"><i class="fa fa-check"></i>Null distribution</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#p-value"><i class="fa fa-check"></i>P-value</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#making-a-formal-decision"><i class="fa fa-check"></i>Making a formal decision</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#summary-2"><i class="fa fa-check"></i><b>13.3</b> Summary</a></li>
<li class="chapter" data-level="13.4" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#lab-1"><i class="fa fa-check"></i><b>13.4</b> Lab</a><ul>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#required-packages"><i class="fa fa-check"></i>Required packages</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#importing-the-data"><i class="fa fa-check"></i>Importing the data</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#data-inspection"><i class="fa fa-check"></i>Data inspection</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#sample-average-and-standard-deviation"><i class="fa fa-check"></i>Sample average and standard deviation</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#null-and-alternative-hypothesis"><i class="fa fa-check"></i>Null and alternative hypothesis</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#bootstrap-distribution-and-null-distribution"><i class="fa fa-check"></i>Bootstrap distribution and null distribution</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#visualise-the-observed-statistic-on-the-null-distribution"><i class="fa fa-check"></i>Visualise the observed statistic on the null distribution</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#p-value-2"><i class="fa fa-check"></i>P-value</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#interpreting-the-p-value"><i class="fa fa-check"></i>Interpreting the p-value</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#glossary-2"><i class="fa fa-check"></i><b>13.5</b> Glossary</a></li>
<li class="chapter" data-level="13.6" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#references-2"><i class="fa fa-check"></i><b>13.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="chap-typeerror.html"><a href="chap-typeerror.html"><i class="fa fa-check"></i><b>14</b> Type I, Type II errors and Power</a><ul>
<li class="chapter" data-level="14.1" data-path="chap-typeerror.html"><a href="chap-typeerror.html#overview-of-last-week"><i class="fa fa-check"></i><b>14.1</b> Overview of last week</a></li>
<li class="chapter" data-level="14.2" data-path="chap-typeerror.html"><a href="chap-typeerror.html#walkthrough-1"><i class="fa fa-check"></i><b>14.2</b> Walkthrough</a><ul>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#example-1-coin-flip"><i class="fa fa-check"></i>Example 1: Coin flip</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#an-analogy-in-law"><i class="fa fa-check"></i>An analogy in law</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#two-different-types-of-errors"><i class="fa fa-check"></i>Two different types of errors</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#type-i-errors"><i class="fa fa-check"></i>Type I errors</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#type-ii-errors-and-power"><i class="fa fa-check"></i>Type II Errors and Power</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#example-2-a-biased-coin"><i class="fa fa-check"></i>Example 2: A biased coin</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#overlapping-distributions"><i class="fa fa-check"></i>Overlapping distributions</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#generalising-it"><i class="fa fa-check"></i>Generalising it</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="chap-typeerror.html"><a href="chap-typeerror.html#summary-3"><i class="fa fa-check"></i><b>14.3</b> Summary</a></li>
<li class="chapter" data-level="14.4" data-path="chap-typeerror.html"><a href="chap-typeerror.html#lab-2"><i class="fa fa-check"></i><b>14.4</b> Lab</a><ul>
<li class="chapter" data-level="14.4.1" data-path="chap-typeerror.html"><a href="chap-typeerror.html#exercise-1-rock-paper-scissors"><i class="fa fa-check"></i><b>14.4.1</b> Exercise 1: Rock Paper Scissors!</a></li>
<li class="chapter" data-level="14.4.2" data-path="chap-typeerror.html"><a href="chap-typeerror.html#exercise-2-calculating-power-for-a-different-coin."><i class="fa fa-check"></i><b>14.4.2</b> Exercise 2: Calculating power for a different coin.</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="chap-typeerror.html"><a href="chap-typeerror.html#extra-exercises"><i class="fa fa-check"></i><b>14.5</b> Extra Exercises</a><ul>
<li class="chapter" data-level="14.5.1" data-path="chap-typeerror.html"><a href="chap-typeerror.html#exercise-3-sample-size-number-of-flips-and-power"><i class="fa fa-check"></i><b>14.5.1</b> Exercise 3: Sample size (number of flips) and power</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="chap-typeerror.html"><a href="chap-typeerror.html#glossary-3"><i class="fa fa-check"></i><b>14.6</b> Glossary</a></li>
<li class="chapter" data-level="14.7" data-path="chap-typeerror.html"><a href="chap-typeerror.html#references-3"><i class="fa fa-check"></i><b>14.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="chap-normal.html"><a href="chap-normal.html"><i class="fa fa-check"></i><b>15</b> Normal distribution &amp; probability</a><ul>
<li class="chapter" data-level="15.1" data-path="chap-normal.html"><a href="chap-normal.html#recap-3"><i class="fa fa-check"></i><b>15.1</b> Recap</a></li>
<li class="chapter" data-level="15.2" data-path="chap-normal.html"><a href="chap-normal.html#walkthrough-2"><i class="fa fa-check"></i><b>15.2</b> Walkthrough</a><ul>
<li class="chapter" data-level="15.2.1" data-path="chap-normal.html"><a href="chap-normal.html#from-histograms-to-normal-curves"><i class="fa fa-check"></i><b>15.2.1</b> From histograms to normal curves</a></li>
<li class="chapter" data-level="15.2.2" data-path="chap-normal.html"><a href="chap-normal.html#sec-area-and-prob"><i class="fa fa-check"></i><b>15.2.2</b> The relation between area and probability</a></li>
<li class="chapter" data-level="15.2.3" data-path="chap-normal.html"><a href="chap-normal.html#probabilities-for-normally-distributed-random-variables"><i class="fa fa-check"></i><b>15.2.3</b> Probabilities for normally distributed random variables</a></li>
<li class="chapter" data-level="15.2.4" data-path="chap-normal.html"><a href="chap-normal.html#z-scores"><i class="fa fa-check"></i><b>15.2.4</b> Z-scores</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="chap-normal.html"><a href="chap-normal.html#summary-4"><i class="fa fa-check"></i><b>15.3</b> Summary</a></li>
<li class="chapter" data-level="15.4" data-path="chap-normal.html"><a href="chap-normal.html#lab-3"><i class="fa fa-check"></i><b>15.4</b> Lab</a></li>
<li class="chapter" data-level="15.5" data-path="chap-normal.html"><a href="chap-normal.html#glossary-4"><i class="fa fa-check"></i><b>15.5</b> Glossary</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html"><i class="fa fa-check"></i><b>16</b> One Sample Mean Test</a><ul>
<li class="chapter" data-level="16.1" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#recap-4"><i class="fa fa-check"></i><b>16.1</b> Recap</a></li>
<li class="chapter" data-level="16.2" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#where-we-are-now"><i class="fa fa-check"></i><b>16.2</b> Where we are now</a></li>
<li class="chapter" data-level="16.3" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#where-we-are-going"><i class="fa fa-check"></i><b>16.3</b> Where we are going</a></li>
<li class="chapter" data-level="16.4" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#one-sample-mean-test"><i class="fa fa-check"></i><b>16.4</b> One sample mean test</a><ul>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#example-questions"><i class="fa fa-check"></i>Example questions</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#hypotheses"><i class="fa fa-check"></i>Hypotheses</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#formula"><i class="fa fa-check"></i>Formula</a></li>
<li><a href="chap-one-mean-test.html#t-distributions"><span class="math inline">\(t\)</span>-distributions</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#critical-values-significance"><i class="fa fa-check"></i>Critical values &amp; significance</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#walkthrough---tempo-of-rock-music-on-spotify"><i class="fa fa-check"></i><b>16.5</b> Walkthrough - Tempo of rock music on Spotify</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#all-in-one-line-of-code"><i class="fa fa-check"></i>ALL IN ONE LINE OF CODE!</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#assumptions"><i class="fa fa-check"></i>Assumptions</a></li>
<li class="chapter" data-level="16.6" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#summary-5"><i class="fa fa-check"></i><b>16.6</b> Summary</a></li>
<li class="chapter" data-level="16.7" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#lab-4"><i class="fa fa-check"></i><b>16.7</b> Lab</a><ul>
<li class="chapter" data-level="16.7.1" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#pets-weights"><i class="fa fa-check"></i><b>16.7.1</b> Pets’ weights</a></li>
<li class="chapter" data-level="16.7.2" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#procrastination-scores"><i class="fa fa-check"></i><b>16.7.2</b> Procrastination scores</a></li>
<li class="chapter" data-level="16.7.3" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#cat-weights"><i class="fa fa-check"></i><b>16.7.3</b> Cat weights!</a></li>
<li class="chapter" data-level="16.7.4" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#glossary-5"><i class="fa fa-check"></i><b>16.7.4</b> Glossary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="two-indep-samples.html"><a href="two-indep-samples.html"><i class="fa fa-check"></i><b>17</b> Comparing two means (independent samples)</a><ul>
<li class="chapter" data-level="17.1" data-path="two-indep-samples.html"><a href="two-indep-samples.html#recap-5"><i class="fa fa-check"></i><b>17.1</b> Recap</a></li>
<li class="chapter" data-level="17.2" data-path="two-indep-samples.html"><a href="two-indep-samples.html#key-terminology"><i class="fa fa-check"></i><b>17.2</b> Key terminology</a></li>
<li class="chapter" data-level="17.3" data-path="two-indep-samples.html"><a href="two-indep-samples.html#walkthrough-got-a-friend"><i class="fa fa-check"></i><b>17.3</b> Walkthrough: Got a friend?</a></li>
<li class="chapter" data-level="17.4" data-path="two-indep-samples.html"><a href="two-indep-samples.html#lab-does-name-increase-tips"><i class="fa fa-check"></i><b>17.4</b> Lab: Does name increase tips?</a></li>
<li class="chapter" data-level="17.5" data-path="two-indep-samples.html"><a href="two-indep-samples.html#glossary-6"><i class="fa fa-check"></i><b>17.5</b> Glossary</a></li>
<li class="chapter" data-level="17.6" data-path="two-indep-samples.html"><a href="two-indep-samples.html#w17-references"><i class="fa fa-check"></i><b>17.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html"><i class="fa fa-check"></i><b>18</b> Paired T-Test</a><ul>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#recap-6"><i class="fa fa-check"></i>Recap</a></li>
<li><a href="chap-paired-t-test.html#paired-t-test">Paired <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="18.1" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#walkthrough-3"><i class="fa fa-check"></i><b>18.1</b> Walkthrough</a><ul>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#change-in-score-on-the-ace-iii"><i class="fa fa-check"></i>Change in score on the ACE-III</a></li>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#data-organisation---reshaping"><i class="fa fa-check"></i>Data organisation - reshaping</a></li>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#effect-sizes"><i class="fa fa-check"></i>Effect sizes</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#summary-6"><i class="fa fa-check"></i><b>18.2</b> Summary</a></li>
<li class="chapter" data-level="18.3" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#lab-5"><i class="fa fa-check"></i><b>18.3</b> Lab</a><ul>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#age-differences-in-heterosexual-marriages"><i class="fa fa-check"></i>Age differences in heterosexual marriages</a></li>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#smoking-interventions"><i class="fa fa-check"></i>Smoking interventions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="chap-chi-square.html"><a href="chap-chi-square.html"><i class="fa fa-check"></i><b>19</b> Chi-square tests</a><ul>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#recap-7"><i class="fa fa-check"></i>Recap</a></li>
<li><a href="chap-chi-square.html#walkthrough-birthdays-of-the-week-the-chi-square-goodness-of-fit-test">Walkthrough: Birthdays of the week <br>The chi-square goodness-of-fit test</a></li>
<li><a href="chap-chi-square.html#lab-joking-for-a-tip-the-chi-square-test-of-independence">Lab: Joking for a tip <br>The chi-square test of independence</a></li>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#summary-7"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#glossary-7"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#references-4"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analysis for Psychology in R (dapR1) - Labs</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap-sampling-distributions" class="section level1">
<h1><span class="header-section-number">Chapter 11</span> Sampling distributions</h1>
<div class="lo">
<h4 id="instructions" class="unnumbered">Instructions</h4>
<ul>
<li>In this two-hour lab we will go through worked examples in the first hour, and you will attempt to answer some questions in the second hour.</li>
<li>The Rmarkdown file for this week is <a href="https://uoe-psychology.github.io/uoe_psystats/dapr1/labsheets/week_11_practice.Rmd">here</a>.</li>
</ul>
<h4 id="learning-outcomes" class="unnumbered">Learning outcomes</h4>
<p><strong>LO1.</strong> Understand the difference between a population parameter and a sample statistic.</p>
<p><strong>LO2.</strong> Understand that a sampling distribution shows how sample statistics vary from sample to sample.</p>
<p><strong>LO3.</strong> Understand the effect of sample size on the sampling distribution, and how to quantify the variability of a statistic.</p>
<h4 id="reading" class="unnumbered">Reading</h4>
<p>This week’s reading is <a href="https://moderndive.com/7-sampling.html">Chapter 7</a> of the book by Chester Ismay and Albert Y. Kim. <em>Statistical Inference via Data Science: A ModernDive into R and the Tidyverse</em>. Chapman and Hall/CRC, 2019. Freely available online at: <a href="https://moderndive.com/" class="uri">https://moderndive.com/</a></p>
</div>
<div id="recap" class="section level2">
<h2><span class="header-section-number">11.1</span> Recap</h2>
<div class="figure" style="text-align: center"><span id="fig:data-analysis-pipeline"></span>
<img src="https://d33wubrfki0l68.cloudfront.net/86cc45e87bb755a3bcecce462a6524e68d13a466/67469/images/r4ds/data_science_pipeline.png" alt="The data analysis pipeline." width="75%" />
<p class="caption">
Figure 11.1: The data analysis pipeline.
</p>
</div>
<p>In Semester 1 (Weeks 1-10), we started walking through the required steps of a statistical investigation, conveniently summarized in Figure <a href="chap-sampling-distributions.html#fig:data-analysis-pipeline">11.1</a>.</p>
<p>Suppose that you are interested in a research question that can be answered by collecting data on some statistical units.
Once collected, you (a) import/load the data into R;
(b) tidy them so that each column corresponds to a single variable of interest;
(c) transform the variables if needed;
(d) visualise your data and inspect for unusual values;
(e) fit statistical models to the data; and
(f) communicate your results and conclusions to the wider community.</p>
<p><em><strong>Note</strong>: The inner cycle (c-d-e) might need to be re-iterated a few times.</em></p>
<p>In the first semester we saw:</p>
<ol style="list-style-type: lower-alpha">
<li>how to import data into R;</li>
<li>how to tidy datasets (for example by making sure that some variables are factors);</li>
<li>how to transform variables (e.g. standardizing via <code>scale()</code>, log-transforming data, …);</li>
<li>how to visualise the data using the <code>ggplot2</code> package.</li>
</ol>
<p>In this semester we will focus on</p>
<ol start="5" style="list-style-type: lower-alpha">
<li>modelling, and</li>
<li>communicating our findings to the wider community.</li>
</ol>
</div>
<div id="population-sample" class="section level2">
<h2><span class="header-section-number">11.2</span> Population vs sample</h2>
<p>Typically, it is either infeasible in terms of time or cost to perform an exhaustive data collection on the entire population of interest (also known as <strong>census</strong>). This is why, for instance, the UK Office for National Statistics only performs a census every 10 years and the next one will be in 2021.
To save time and money, we typically record the variables of interest on a smaller subset of the entire population, also known as a <strong>sample</strong>.
In order to make sure that any conclusions we draw from the sample are <strong>generalisable</strong> to the wider population, this sample needs to be taken at <strong>random</strong>.
This avoids <strong>representation bias</strong>, where some units are less represented than others, which would lead to wrong conclusions for the entire population.</p>
<div class="question">
<p class="question-begin">
► Example
</p>
<div class="question-body">
<p><strong>Average montly salary in Sweden</strong></p>
<p>Suppose you are interested in the average monthly salary of people working in Sweden. Unfortunately, you neither have the time nor the money to go to Sweden and ask each single person their own salary.
Hence, you decide to ask some people at random.</p>
<p>What are the problems of the following sample selection criteria?</p>
<ol style="list-style-type: decimal">
<li>Asking 500 random people from Facebook that live in Sweden.</li>
<li>Asking 1000 random people from the web that live in Sweden.</li>
<li>Calling 200 phone numbers from the phone book.</li>
<li>Asking 500 people working near the central bank of Sweden.</li>
</ol>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-1" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-1&#39;, &#39;sol-start-1&#39;)"></span>
</p>
<div id="sol-body-1" class="solution-body" style="display: none;">
<p>All four criteria lead to samples that are not representative of the entire population.
This is because the population units will not have the same probability of being included in the sample: some people will have a higher chance of being included in the sample than others. This leads to <strong>sampling bias</strong>.
Because of this, any conclusion we might make from the sample is not generalisable to the whole population.</p>
<ol style="list-style-type: decimal">
<li>People that do not have Facebook are not considered in the sample.</li>
<li>People that do not use the Internet are not represented.</li>
<li>People without a landline phone are not included.</li>
<li>People working in this area will very likely have higher salaries than the rest of the country. This sample does not represent fairly people working in farming or other sectors.</li>
</ol>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>In <a href="week-8.html#week-8">Week 8</a> of Semester 1, we discussed how to obtain sample data from a bigger population of interest; this is known as data collection.
We now take the opposite direction as we try to use the information from the sample data to draw conclusions about the entire population. This is summarised in Figure <a href="chap-sampling-distributions.html#fig:data-collection-stat-inference">11.2</a>.
Furthermore, we will spend some time assessing how accurate our conclusions about the entire population are.</p>
<div class="def">
<h4 id="statistical-inference" class="unnumbered">Statistical inference</h4>
<p><strong>Statistical inference</strong> is the process of using the sample data to draw conclusions about the entire population.</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:data-collection-stat-inference"></span>
<img src="images/statistical_inference.png" alt="Data collection vs statistical inference" width="75%" />
<p class="caption">
Figure 11.2: Data collection vs statistical inference
</p>
</div>
<p><em><strong>Caution</strong>: The inferential process <strong>assumes</strong> that the sample is randomly drawn from the population of interest.
Any sample selection method that is biased, i.e. leading to samples which are not representative of the entire population, will mean that the results we obtain from the data in the sample can not be generalised to the entire population.</em></p>
<p>In the average salary of Sweden example, none of the four sample selection strategies consisted of random sampling.
They systematically excluded some people from the samples, leading to samples that were not representative of the population.
For this reason, the average salary computed on any sample could not have been used to draw conclusions about the average salary in Sweden.</p>
</div>
<div id="parameter-statistic" class="section level2">
<h2><span class="header-section-number">11.3</span> Population parameter vs sample statistic</h2>
<p>To clarify whether we are referring to the entire population or a sample, we use the term <strong>parameter</strong> when referring to a numerical summary of the entire population, and the term <strong>statistic</strong> for a numerical summary of the sample.</p>
<div class="def">
<h4 id="parameter-vs-statistic" class="unnumbered">Parameter vs statistic</h4>
<ul>
<li>A <strong>parameter</strong> is a number describing some aspect of the population.</li>
<li>A <strong>statistic</strong> is a number that is computed from the data in a sample.</li>
</ul>
</div>
<div class="question">
<p class="question-begin">
► Example
</p>
<div class="question-body">
<p><strong>Average price of goods sold by ACME Corporation</strong></p>
<p>Suppose you work for a company that is interested in buying ACME Corporation<a href="#fn3" class="footnote-ref" id="fnref3"><sup>3</sup></a> and your boss wants to know within the next hour what is the average price of goods sold by that company and how the prices of the goods they sell differ from each other.</p>
<p>Since ACME Corporation has such a big mail order catalogue, see Figure <a href="chap-sampling-distributions.html#fig:acme">11.3</a>, we will assume that the company sells many products. Furthermore, we only have the catalogue in paper-form and no online list of prices is available.</p>
<div class="figure" style="text-align: center"><span id="fig:acme"></span>
<img src="https://i.pinimg.com/474x/e5/bc/52/e5bc52b78be204a8d6d1f4932492ea3d--bugs-bunny-coyote.jpg" alt="Product catalogue of ACME corporation." width="50%" />
<p class="caption">
Figure 11.3: Product catalogue of ACME corporation.
</p>
</div>
<ol style="list-style-type: decimal">
<li>Identify the population of interest and the population parameters.</li>
<li>Can we compute the parameters within the next hour?</li>
<li>How would you proceed in estimating the population parameters if you just had time to read through 100 item descriptions? Would you pick the first 100 items or would you pick 100 random page numbers?</li>
<li>State which statistics you would use to estimate the population parameters.</li>
</ol>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-2" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-2&#39;, &#39;sol-start-2&#39;)"></span>
</p>
<div id="sol-body-2" class="solution-body" style="display: none;">
<ol style="list-style-type: decimal">
<li>The population of interest is all products sold by ACME Corporation. The population parameters are the mean price <span class="math inline">\(\mu\)</span> and the standard deviation <span class="math inline">\(\sigma\)</span>.</li>
<li>Because the catalogue has so many pages, we can not compute the population parameters within the next hour.</li>
<li>We must estimate the population mean and standard deviation from a sample of size <span class="math inline">\(n = 100\)</span>. We should choose the items entering the sample at random, to avoid sampling bias. If we were to choose 100 consecutive items, we might end up with a very good estimate of the average price for the category those contecutive items belong to (e.g. gardening). However, this would not be a good estimate of the overall price across the multiple categories of products sold.</li>
<li>Our best guess of the population mean would be the sample mean, <span class="math inline">\(\bar{x}\)</span>, and our best guess of the population standard deviation would be the sample standard deviation, denoted <span class="math inline">\(s\)</span> or <span class="math inline">\(\hat{\sigma}\)</span>.</li>
</ol>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>From this example, you can see that the population parameter and the sample statistic generally have the same name.
However, these are often written with different symbols to convey with just one letter:</p>
<ol style="list-style-type: decimal">
<li>what <strong>feature</strong> they represent;</li>
<li>if it is a <strong>population</strong> quantity or a quantity <strong>computed on a sample</strong>.</li>
</ol>
<p>The following table summarizes standard notation for some population parameters, typically unknown, and the corresponding “best guesses” computed on a sample.</p>
<table>
<caption>Notation for common parameters and statistics.</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="center">Population parameter</th>
<th align="center">Sample statistic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Mean</td>
<td align="center"><span class="math inline">\(\mu\)</span></td>
<td align="center"><span class="math inline">\(\bar{x}\)</span> or <span class="math inline">\(\hat{\mu}\)</span></td>
</tr>
<tr class="even">
<td align="left">Standard deviation</td>
<td align="center"><span class="math inline">\(\sigma\)</span></td>
<td align="center"><span class="math inline">\(s\)</span> or <span class="math inline">\(\hat{\sigma}\)</span></td>
</tr>
<tr class="odd">
<td align="left">Proportion</td>
<td align="center"><span class="math inline">\(p\)</span></td>
<td align="center"><span class="math inline">\(\hat{p}\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li>The greek letter <span class="math inline">\(\mu\)</span> (mu) is used as a parameter to denote the population mean/average, while <span class="math inline">\(\bar{x}\)</span> (x-bar) or <span class="math inline">\(\hat{\mu}\)</span> (mu-hat) is used as a statistic for the mean computed on a sample.</li>
<li>The greek letter <span class="math inline">\(\sigma\)</span> (sigma) is used as a parameter to denote the population standard deviation, while <span class="math inline">\(s\)</span> or <span class="math inline">\(\hat{\sigma}\)</span> (sigma-hat) is used as a statistic for the standard deviation of the collected sample.</li>
<li>The letter <span class="math inline">\(p\)</span> is used as a parameter to denote the population proportion, while <span class="math inline">\(\hat{p}\)</span> (p-hat) is used as a statistic for the sample proportion.</li>
</ul>
<div class="question">
<p class="question-begin">
► Example
</p>
<div class="question-body">
<p><strong>Proportion of UK people aged between 25 and 34 with a Bachelor’s degree or higher</strong></p>
<p>The last UK Census, done in 2011, reports that 40% of people aged 25 to 34 years had a degree-level or above qualification.
Suppose that in a random sample of <span class="math inline">\(n = 200\)</span> UK residents who are between 25 and 34 years old, 58 of them have a Bachelor’s degree or higher.
Using the appropriate notation, state what is the population parameter and what is the sample statistic.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-3" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-3&#39;, &#39;sol-start-3&#39;)"></span>
</p>
<div id="sol-body-3" class="solution-body" style="display: none;">
<ul>
<li>The population parameter is the proportion of <em>all</em> UK people aged between 25 and 34 years old with a Bachelor’s degree or higher: <span class="math inline">\(p = 0.4\)</span>.</li>
<li>The sample statistic is the proportion with a Bachelor’s degree or higher <em>for those in the sample</em>: <span class="math inline">\(\hat{p} = 58/200 = 0.29\)</span>.</li>
</ul>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>As discussed, it is generally infeasible to be able to know the value of the population parameter exactly. This would require collecting data for the entire population and then computing the required quantity.
Instead, we typically select a random sample from the population, and then compute the quantity of interest for the sample data.
We then use this sample statistic as a <strong>(point) estimate</strong> or <strong>best guess</strong> of the population parameter.</p>
</div>
<div id="sec-sampling-distributions" class="section level2">
<h2><span class="header-section-number">11.4</span> Sampling distributions</h2>
<p>A population parameter is typically considered to be a <strong>fixed</strong> value.
A sample statistic, however, <strong>varies from sample to sample</strong>.
This is because a sample statistic, i.e. a quantity computed on a sample, will depend on which units are selected to enter the sample.
This can be seen as a downside to sampling, but we must remember that time and resources often prevent us from finding out the true value of a population parameter, whereas it is comparatively easy to collect a sample and compute a statistic.</p>
<p>A fundamental question that arises when we estimate an unknown population parameter by a sample statistic is: how accurate do we believe our best guess to be?</p>
<p>Remembering that the parameter is fixed, while the statistics varies from sample to sample, we might proceed in answering this question by looking at how the computed statistic varies depending on the sample.</p>
<div class="question">
<p class="question-begin">
► Example
</p>
<div class="question-body">
<p><strong>Average yearly salary of American National Football League (NFL) players</strong></p>
<p>We will read a file containing the yearly salaries (in millions of dollars) for all players being paid at the start of 2015 by a National Football League (NFL) team.
This entire dataset represents the population of all National Football League players in 2015.<a href="#fn4" class="footnote-ref" id="fnref4"><sup>4</sup></a></p>
<p>We are interested in the following question: what was the average yearly salary of a NFL player in 2015?</p>
<p><em>In this particular example, we actually <strong>do</strong> know the population parameter, because we have data on the whole population. We resort to sampling, however, to show how the value of a statistic varies when computed on different samples.</em></p>
<ol style="list-style-type: decimal">
<li>Read in the data and state, with appropriate notation, what is the population parameter.</li>
<li>Select a random sample of <span class="math inline">\(n = 50\)</span> players and compute the average yearly salary for the players in the sample. How does your statistic compare to the population parameter?</li>
<li>Take another sample of size <span class="math inline">\(n = 50\)</span> players and compute the average salary for the new sample. How does it compare with the mean from the previous sample?</li>
</ol>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-4" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-4&#39;, &#39;sol-start-4&#39;)"></span>
</p>
<div id="sol-body-4" class="solution-body" style="display: none;">
<p><em>Do not worry if some of these functions are new to you, try to follow along and understand what each does.</em></p>
<p><strong>Question 1:</strong> Read in the data and state, with appropriate notation, what is the population parameter.</p>
<p>Let us start by loading the data, inspecting the initial rows of the tibble, and checking the dimensions:</p>
<div class="sourceCode" id="cb497"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb497-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb497-2" data-line-number="2"></a>
<a class="sourceLine" id="cb497-3" data-line-number="3">nfl &lt;-<span class="st"> </span><span class="kw">read_tsv</span>(<span class="st">&#39;https://edin.ac/2TexAFA&#39;</span>)</a>
<a class="sourceLine" id="cb497-4" data-line-number="4"><span class="kw">head</span>(nfl)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##   Player             Position Team     TotalMoney YearlySalary
##   &lt;chr&gt;              &lt;chr&gt;    &lt;chr&gt;         &lt;dbl&gt;        &lt;dbl&gt;
## 1 Aaron Rodgers      QB       Packers       110           22  
## 2 Russell Wilson     QB       Seahawks       87.6         21.9
## 3 Ben Roethlisberger QB       Steelers       87.4         21.8
## 4 Philip Rivers      QB       Chargers       83.2         20.8
## 5 Cam Newton         QB       Panthers      104.          20.8
## 6 Matt Ryan          QB       Falcons       104.          20.8</code></pre>
<div class="sourceCode" id="cb499"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb499-1" data-line-number="1"><span class="kw">dim</span>(nfl)</a></code></pre></div>
<pre><code>## [1] 2099    5</code></pre>
<p>The data comprise five measurements on 2099 units.
We have data on the players’ names, positions, team names, total money they received while playing on the NFL (cumulative over multiple years), and their yearly salary.</p>
<p>Since we are only interested in the yearly salary of the players, we can select only the relevant columns from the data:</p>
<div class="sourceCode" id="cb501"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb501-1" data-line-number="1">nfl &lt;-<span class="st"> </span>nfl <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb501-2" data-line-number="2"><span class="st">  </span><span class="kw">select</span>(Player, YearlySalary)</a>
<a class="sourceLine" id="cb501-3" data-line-number="3"></a>
<a class="sourceLine" id="cb501-4" data-line-number="4"><span class="kw">head</span>(nfl)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   Player             YearlySalary
##   &lt;chr&gt;                     &lt;dbl&gt;
## 1 Aaron Rodgers              22  
## 2 Russell Wilson             21.9
## 3 Ben Roethlisberger         21.8
## 4 Philip Rivers              20.8
## 5 Cam Newton                 20.8
## 6 Matt Ryan                  20.8</code></pre>
<p>We now calculate the average yearly salary for all players:</p>
<div class="sourceCode" id="cb503"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb503-1" data-line-number="1">nfl_mean &lt;-<span class="st"> </span>nfl <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb503-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg =</span> <span class="kw">mean</span>(YearlySalary))</a>
<a class="sourceLine" id="cb503-3" data-line-number="3"></a>
<a class="sourceLine" id="cb503-4" data-line-number="4">nfl_mean</a></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##     avg
##   &lt;dbl&gt;
## 1  2.24</code></pre>
<p>The population parameter is the average yearly salary in 2015, <span class="math inline">\(\mu =\)</span> 2.24.</p>
<p><strong>Question 2:</strong> Select a random sample of <span class="math inline">\(n = 50\)</span> players and compute the average yearly salary for the players in the sample. How does your statistic compare to the population parameter?</p>
<p>In order to randomly sample players, we will use the package <code>moderndive</code>. If you do not have it installed, run the following command:</p>
<div class="sourceCode" id="cb505"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb505-1" data-line-number="1"><span class="kw">install.packages</span>(<span class="st">&quot;moderndive&quot;</span>)</a></code></pre></div>
<p>We then load the package and create a sample of size <span class="math inline">\(n = 50\)</span> players:</p>
<div class="sourceCode" id="cb506"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb506-1" data-line-number="1"><span class="kw">library</span>(moderndive)</a>
<a class="sourceLine" id="cb506-2" data-line-number="2"></a>
<a class="sourceLine" id="cb506-3" data-line-number="3">nfl_sample_<span class="dv">1</span> &lt;-<span class="st"> </span>nfl <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb506-4" data-line-number="4"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">50</span>)</a>
<a class="sourceLine" id="cb506-5" data-line-number="5"></a>
<a class="sourceLine" id="cb506-6" data-line-number="6">nfl_sample_<span class="dv">1</span></a></code></pre></div>
<pre><code>## # A tibble: 50 x 3
## # Groups:   replicate [1]
##    replicate Player              YearlySalary
##        &lt;int&gt; &lt;chr&gt;                      &lt;dbl&gt;
##  1         1 Craig Dahl                 0.87 
##  2         1 Jarrett Bush               1.75 
##  3         1 Shayne Graham              0.98 
##  4         1 Christian Covington        0.593
##  5         1 Pat McAfee                 2.9  
##  6         1 Ron Parker                 5    
##  7         1 Bryan Walters              0.723
##  8         1 John Greco                 2.09 
##  9         1 Trenton Robinson           0.68 
## 10         1 Paul Worrilow              0.496
## # … with 40 more rows</code></pre>
<p>This returns a tibble of size <span class="math inline">\(50 \times 3\)</span>. The second column shows the names of the players included in the sample. The additional first column is equal to one for all cases in the sample. This indicates that the 50 rows all belong to the first sample. You are also invited to interactively scroll through the sample by typing the command <code>View(nfl_sample_1)</code>.</p>
<p>Let’s now compute the average salary for the players in the sample:</p>
<div class="sourceCode" id="cb508"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb508-1" data-line-number="1">nfl_sample_<span class="dv">1</span>_mean &lt;-<span class="st"> </span>nfl_sample_<span class="dv">1</span> <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb508-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg =</span> <span class="kw">mean</span>(YearlySalary))</a>
<a class="sourceLine" id="cb508-3" data-line-number="3"></a>
<a class="sourceLine" id="cb508-4" data-line-number="4">nfl_sample_<span class="dv">1</span>_mean</a></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   replicate   avg
##       &lt;int&gt; &lt;dbl&gt;
## 1         1  2.10</code></pre>
<p>We can see that the average salary in our sample is <span class="math inline">\(\bar{x} =\)</span> 2.1 million dollars.</p>
<p>The sample mean, 2.1, is close to the population mean, 2.24, even if not exactly the same. We are not surprised of this result: we do not expect the mean of every sample to be exactly equal to the population mean, but we do hope that they are somewhat close.</p>
<p><strong>Question 3:</strong> Take another sample of size <span class="math inline">\(n = 50\)</span> players and compute the average salary for the new sample. How does it compare with the mean from the previous sample?</p>
<p>Let’s take another random sample of size 50 and compute the mean salary:</p>
<div class="sourceCode" id="cb510"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb510-1" data-line-number="1">nfl_sample_<span class="dv">2</span> &lt;-<span class="st"> </span>nfl <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb510-2" data-line-number="2"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">50</span>)</a>
<a class="sourceLine" id="cb510-3" data-line-number="3"></a>
<a class="sourceLine" id="cb510-4" data-line-number="4">nfl_sample_<span class="dv">2</span></a></code></pre></div>
<pre><code>## # A tibble: 50 x 3
## # Groups:   replicate [1]
##    replicate Player           YearlySalary
##        &lt;int&gt; &lt;chr&gt;                   &lt;dbl&gt;
##  1         1 Trevor Scott            0.73 
##  2         1 Scott Crichton          0.755
##  3         1 NaVorro Bowman          9.05 
##  4         1 Brian Dixon             0.51 
##  5         1 Kyle Williams           0.745
##  6         1 Tony Jefferson          0.498
##  7         1 Anthony Hitchens        0.664
##  8         1 Cedric Ogbuehi          2.33 
##  9         1 Jordan Poyer            0.555
## 10         1 Brent Celek             4.88 
## # … with 40 more rows</code></pre>
<div class="sourceCode" id="cb512"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb512-1" data-line-number="1">nfl_sample_<span class="dv">2</span>_mean &lt;-<span class="st"> </span>nfl_sample_<span class="dv">2</span> <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb512-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg =</span> <span class="kw">mean</span>(YearlySalary))</a>
<a class="sourceLine" id="cb512-3" data-line-number="3"></a>
<a class="sourceLine" id="cb512-4" data-line-number="4">nfl_sample_<span class="dv">2</span>_mean</a></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   replicate   avg
##       &lt;int&gt; &lt;dbl&gt;
## 1         1  2.05</code></pre>
<p>The statistic computed on the second sample is <span class="math inline">\(\bar{x} =\)</span> 2.05. Again, this is similar to the population parameter, <span class="math inline">\(\mu =\)</span> 2.24.
We also note that the mean computed on the second sample (2.05) is different from the mean computed on the first sample (2.1).</p>
<p>We could have immediately obtained two samples, each of size <span class="math inline">\(n = 50\)</span> units. This requires that we repeat/replicate two times the activity of sampling 50 units from the entire population. Every replicated sampling of 50 units from the population is done “from scratch”, so that the population is always unchanged from replicate to replicate.
This is done in the function <code>rep_sample_n(size = 50)</code> by including the extra argument <code>reps = 2</code>:</p>
<div class="sourceCode" id="cb514"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb514-1" data-line-number="1">nfl_samples &lt;-<span class="st"> </span>nfl <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb514-2" data-line-number="2"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">50</span>, <span class="dt">reps =</span> <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb514-3" data-line-number="3"></a>
<a class="sourceLine" id="cb514-4" data-line-number="4">nfl_samples</a></code></pre></div>
<pre><code>## # A tibble: 100 x 3
## # Groups:   replicate [2]
##    replicate Player             YearlySalary
##        &lt;int&gt; &lt;chr&gt;                     &lt;dbl&gt;
##  1         1 Andrew Luck               7.65 
##  2         1 Antonio Brown             8.39 
##  3         1 Patrick Chung             2.4  
##  4         1 Chris Williams            3.29 
##  5         1 Chris Lewis-Harris        0.585
##  6         1 Lance Louis               1.01 
##  7         1 Adam Humphries            0.525
##  8         1 Wade Keliikipi            0.525
##  9         1 Dustin Colquitt           3.75 
## 10         1 Tyronne Green             0.745
## # … with 90 more rows</code></pre>
<p>If you explore this tibble, it has <span class="math inline">\(50 \times 2 = 100\)</span> rows. The column replicate takes value 1 for the first 50 rows, and the value 2 for the next 50 rows.
This indicates that the players in rows 1 to 50 are selected to be in the first sample, while the players in rows 51 to 100 are those selected to be in the second sample.</p>
<p>We can now compute the mean yearly salary for each of the two samples. The salaries of the 50 players in the first sample (replicate = 1) will be summarised by a single mean value, and the salaries of the 50 players in the second sample (replicate = 2) will be summarised into another mean value. In the end we will have a tibble with just two rows:</p>
<div class="sourceCode" id="cb516"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb516-1" data-line-number="1">nfl_sample_means &lt;-<span class="st"> </span>nfl_samples <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb516-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb516-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg =</span> <span class="kw">mean</span>(YearlySalary))</a>
<a class="sourceLine" id="cb516-4" data-line-number="4"></a>
<a class="sourceLine" id="cb516-5" data-line-number="5">nfl_sample_means</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   replicate   avg
##       &lt;int&gt; &lt;dbl&gt;
## 1         1  2.57
## 2         2  2.19</code></pre>
<p>We see that both are close to the population parameter which, if we remember, is equal to 2.24.</p>
<p>Figure <a href="chap-sampling-distributions.html#fig:two-sample-means">11.4</a> a histogram of the two means, with a vertical red line denoting the true population mean:</p>
<div class="sourceCode" id="cb518"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb518-1" data-line-number="1"><span class="kw">ggplot</span>(nfl_sample_means, <span class="kw">aes</span>(<span class="dt">x =</span> avg)) <span class="op">+</span></a>
<a class="sourceLine" id="cb518-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb518-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="kw">pull</span>(nfl_mean, avg), <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb518-4" data-line-number="4"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expression</span>(<span class="kw">bar</span>(x)))</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:two-sample-means"></span>
<img src="bookdown-demo_files/figure-html/two-sample-means-1.png" alt="Sample means from two samples of size $n = 50$ with population mean $\mu$ marked by a red vertical line." width="80%" />
<p class="caption">
Figure 11.4: Sample means from two samples of size <span class="math inline">\(n = 50\)</span> with population mean <span class="math inline">\(\mu\)</span> marked by a red vertical line.
</p>
</div>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>Clearly, we can extend the repeated sampling procedure to more than just two samples of size = 50.
Let us now obtain 2000 replicated samples, all of size 50, from the same NFL population:</p>
<div class="sourceCode" id="cb519"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb519-1" data-line-number="1">nfl_samples &lt;-<span class="st"> </span>nfl <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb519-2" data-line-number="2"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">50</span>, <span class="dt">reps =</span> <span class="dv">2000</span>)</a>
<a class="sourceLine" id="cb519-3" data-line-number="3"></a>
<a class="sourceLine" id="cb519-4" data-line-number="4">nfl_samples</a></code></pre></div>
<pre><code>## # A tibble: 100,000 x 3
## # Groups:   replicate [2,000]
##    replicate Player           YearlySalary
##        &lt;int&gt; &lt;chr&gt;                   &lt;dbl&gt;
##  1         1 Matthew Masifilo        0.555
##  2         1 Kyle Juszczyk           0.615
##  3         1 Gabe Jackson            0.714
##  4         1 Akeem Ayers             3    
##  5         1 Andy Mulumba            0.497
##  6         1 Corey Linsley           0.601
##  7         1 Billy Turner            0.787
##  8         1 Bennett Jackson         0.435
##  9         1 Chase Daniel            3.33 
## 10         1 Scott Lutrus            0.465
## # … with 99,990 more rows</code></pre>
<p>This tibble has <span class="math inline">\(50 \times 2000 = 100,000\)</span> rows. The first 50 players are part of the 1st sample, the next 50 belong to the 2nd sample, and so on…</p>
<p>We can now compute the mean of each of the 2000 samples of size 50, obtaining a tibble of 2000 sample means:</p>
<div class="sourceCode" id="cb521"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb521-1" data-line-number="1">nfl_sample_means &lt;-<span class="st"> </span>nfl_samples <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb521-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb521-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg =</span> <span class="kw">mean</span>(YearlySalary))</a>
<a class="sourceLine" id="cb521-4" data-line-number="4"></a>
<a class="sourceLine" id="cb521-5" data-line-number="5">nfl_sample_means</a></code></pre></div>
<pre><code>## # A tibble: 2,000 x 2
##    replicate   avg
##        &lt;int&gt; &lt;dbl&gt;
##  1         1  2.74
##  2         2  1.69
##  3         3  2.44
##  4         4  2.29
##  5         5  2.37
##  6         6  2.63
##  7         7  2.46
##  8         8  1.99
##  9         9  2.29
## 10        10  2.28
## # … with 1,990 more rows</code></pre>
<p>Let us plot the distribution of the sample mean for 2000 random samples, and superimpose in red the true value of the population parameter <span class="math inline">\(\mu\)</span>:</p>
<div class="sourceCode" id="cb523"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb523-1" data-line-number="1"><span class="kw">ggplot</span>(nfl_sample_means, <span class="kw">aes</span>(<span class="dt">x =</span> avg)) <span class="op">+</span></a>
<a class="sourceLine" id="cb523-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb523-3" data-line-number="3"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="kw">pull</span>(nfl_mean, avg), <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb523-4" data-line-number="4"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expression</span>(<span class="kw">bar</span>(x)))</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:sampling-distribution"></span>
<img src="bookdown-demo_files/figure-html/sampling-distribution-1.png" alt="Sampling distribution of the mean for $n = 50$ with population mean $\mu$ marked by a red vertical line." width="80%" />
<p class="caption">
Figure 11.5: Sampling distribution of the mean for <span class="math inline">\(n = 50\)</span> with population mean <span class="math inline">\(\mu\)</span> marked by a red vertical line.
</p>
</div>
<p>Figure <a href="chap-sampling-distributions.html#fig:sampling-distribution">11.5</a> shows the values of the sample mean computed from sample to sample. Hence, it shows the variability of the sample mean induced by sampling variation.
Such a plot is fundamental in statistical inference, and it is called <strong>sampling distribution</strong>.</p>
<div class="def">
<h4 id="sampling-distribution" class="unnumbered">Sampling distribution</h4>
<p>The <strong>sampling distribution</strong> of a statistic shows the distribution of the statistic for different samples of the same size from the same population.</p>
</div>
<p>Clearly, we can compute sampling distributions for other statistics too: the proportion, the standard deviation, …</p>
<p>This requires the following steps:</p>
<ol style="list-style-type: decimal">
<li>Obtaining multiple samples, all of the same size, from the same population;</li>
<li>For each sample, calculate the value of the statistic;</li>
<li>Plot the distribution of the computed statistics.</li>
</ol>
<p>In Figure <a href="chap-sampling-distributions.html#fig:sampling-distribution">11.5</a>, the distribution of sample means is centred around the population mean <span class="math inline">\(\mu\)</span> and has a shape that is similar to a bell. This can be generalised further:</p>
<div class="def">
<h4 id="centre-and-shape-of-a-sampling-distribution" class="unnumbered">Centre and shape of a sampling distribution</h4>
<ul>
<li><strong>Centre:</strong> If samples are randomly selected, the sampling distribution will be centred around the population parameter. (<strong>Accuracy</strong>)</li>
<li><strong>Shape:</strong> For most of the statistics we consider, if the sample size is large enough, the sampling distribution will be symmetric and bell-shaped. (<strong>Central Limit Theorem</strong>)</li>
</ul>
</div>
</div>
<div id="standard-error" class="section level2">
<h2><span class="header-section-number">11.5</span> The standard error of a statistic</h2>
<p>The variability, or spread, of the sampling distribution shows how much the sample statistics tend to vary from sample to sample.
This is key in understanding how accurate our estimate of the population parameter, based on just one sample, will be.</p>
<p>In Semester 1 you saw how to summarize the variability of data using the standard deviation: <code>sd()</code>.
So, the variability of a statistic can be quantified by calculating the standard deviation of its sampling distribution.</p>
<p>Technically, this is not different from an ordinary standard deviation as the code and formula is the same. However, the spread of a sample statistic is so fundamental that it has its own name: <strong>the standard error of the statistic</strong>.</p>
<p>In other words, we use:</p>
<ul>
<li><strong>standard deviation</strong> to denote the variability among the values in a particular sample;</li>
<li><strong>standard error</strong> to denote the variability of the statistics computed on many samples.</li>
</ul>
<div class="def">
<h4 id="standard-error-1" class="unnumbered">Standard error</h4>
<p>The <strong>standard error</strong> of a statistic, denoted <span class="math inline">\(SE\)</span>, is the standard deviation of its sampling distribution.</p>
</div>
<p>The standard error measures the <em>typical error</em> when estimating the population parameter with the sample statistic. You can think of the SE as a “typical distance” of a sample statistic from the population parameter.</p>
</div>
<div id="sample-size-standard-error" class="section level2">
<h2><span class="header-section-number">11.6</span> The effect of sample size on the sampling distribution</h2>
<p>It is of interest to see how the sampling distribution of the mean salary, shown in Figure <a href="chap-sampling-distributions.html#fig:sampling-distribution">11.5</a> for a sample size <span class="math inline">\(n = 50\)</span>, changes with the sample size.</p>
<p>In the following code chunk we compute the sampling distribution of the mean for samples of size <span class="math inline">\(n = 50\)</span>, <span class="math inline">\(n = 100\)</span>, and <span class="math inline">\(n = 500\)</span>, always repeating the sampling from the population 2000 times:</p>
<div class="sourceCode" id="cb524"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb524-1" data-line-number="1">nfl_sample_means_n_<span class="dv">50</span> &lt;-<span class="st"> </span>nfl <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb524-2" data-line-number="2"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">50</span>, <span class="dt">reps =</span> <span class="dv">2000</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb524-3" data-line-number="3"><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb524-4" data-line-number="4"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg =</span> <span class="kw">mean</span>(YearlySalary))</a>
<a class="sourceLine" id="cb524-5" data-line-number="5"></a>
<a class="sourceLine" id="cb524-6" data-line-number="6">nfl_sample_means_n_<span class="dv">100</span> &lt;-<span class="st"> </span>nfl <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb524-7" data-line-number="7"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">100</span>, <span class="dt">reps =</span> <span class="dv">2000</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb524-8" data-line-number="8"><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb524-9" data-line-number="9"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg =</span> <span class="kw">mean</span>(YearlySalary))</a>
<a class="sourceLine" id="cb524-10" data-line-number="10"></a>
<a class="sourceLine" id="cb524-11" data-line-number="11">nfl_sample_means_n_<span class="dv">500</span> &lt;-<span class="st"> </span>nfl <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb524-12" data-line-number="12"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">500</span>, <span class="dt">reps =</span> <span class="dv">2000</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb524-13" data-line-number="13"><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb524-14" data-line-number="14"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg =</span> <span class="kw">mean</span>(YearlySalary))</a></code></pre></div>
<p>We now combine the datasets for different sample sizes into a unique tibble, adding a column with the sample size, and then plot the distributions for different sample sizes.
Remember that <code>mutate()</code> takes a tibble and adds or changes a column. The function <code>bind_rows()</code> takes multiple tibbles and stacks them under each other.</p>
<div class="sourceCode" id="cb525"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb525-1" data-line-number="1">nfl_sample_means_vary_n &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(</a>
<a class="sourceLine" id="cb525-2" data-line-number="2">  nfl_sample_means_n_<span class="dv">50</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">n =</span> <span class="dv">50</span>),</a>
<a class="sourceLine" id="cb525-3" data-line-number="3">  nfl_sample_means_n_<span class="dv">100</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">n =</span> <span class="dv">100</span>),</a>
<a class="sourceLine" id="cb525-4" data-line-number="4">  nfl_sample_means_n_<span class="dv">500</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">n =</span> <span class="dv">500</span>)</a>
<a class="sourceLine" id="cb525-5" data-line-number="5">)</a>
<a class="sourceLine" id="cb525-6" data-line-number="6"></a>
<a class="sourceLine" id="cb525-7" data-line-number="7"><span class="kw">ggplot</span>(nfl_sample_means_vary_n, <span class="kw">aes</span>(<span class="dt">x =</span> avg)) <span class="op">+</span></a>
<a class="sourceLine" id="cb525-8" data-line-number="8"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb525-9" data-line-number="9"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="kw">pull</span>(nfl_mean, avg), <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb525-10" data-line-number="10"><span class="st">  </span><span class="kw">facet_grid</span>(<span class="dt">rows =</span> <span class="kw">vars</span>(n), <span class="dt">labeller =</span> label_both) <span class="op">+</span></a>
<a class="sourceLine" id="cb525-11" data-line-number="11"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expression</span>(<span class="kw">bar</span>(x)), <span class="dt">title =</span> <span class="st">&quot;Distribution of the sample mean for samples of size 50, 100, 500&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:sampling-distribution-vary-n"></span>
<img src="bookdown-demo_files/figure-html/sampling-distribution-vary-n-1.png" alt="Three sampling distributions of the mean, with population mean $\mu$ marked by a red vertical line." width="80%" />
<p class="caption">
Figure 11.6: Three sampling distributions of the mean, with population mean <span class="math inline">\(\mu\)</span> marked by a red vertical line.
</p>
</div>
<p>Figure <a href="chap-sampling-distributions.html#fig:sampling-distribution-vary-n">11.6</a> shows that as the sample size increases, the variability of the sampling distributions decreases, hence <strong>the standard error of the statistic decreases as the sample size increases</strong>.</p>
<p>We can create a tibble that shows, for each sample size, the standard error of the sample mean:</p>
<div class="sourceCode" id="cb526"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb526-1" data-line-number="1">nfl_sample_means_vary_n <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb526-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(n) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb526-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">SE =</span> <span class="kw">sd</span>(avg))</a></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##       n    SE
##   &lt;dbl&gt; &lt;dbl&gt;
## 1    50 0.421
## 2   100 0.299
## 3   500 0.121</code></pre>
<p>As we discussed, the tibble shows that as the sample size <span class="math inline">\(n\)</span> increases, the standard error <span class="math inline">\(SE\)</span> decreases.</p>
<p>The larger the sample size, the lower the typical error of our estimate will be, and for every sample we will obtain a calculated statistic that is more similar to the population parameter.</p>
</div>
<div id="take-home-message" class="section level2">
<h2><span class="header-section-number">11.7</span> Take-home message</h2>
<p>You might be wondering: why did we take repeated samples of size <span class="math inline">\(n\)</span> from the population when, in practice, we can only afford to take one?
This is a good question. We have taken multiple samples to show how the estimation error varies with the sample size.
We saw that smaller sample sizes lead to more variable statistics, while larger sample sizes lead to more <strong>precise</strong> statistics, i.e. the estimates are more concentrated around the true parameter value.</p>
<p><strong>This teaches us that, when we have to design a study, it is better to obtain just one sample with size <span class="math inline">\(n\)</span> as large as we can afford.</strong></p>
<div class="question">
<p class="question-begin">
► Example
</p>
<div class="question-body">
<p>What would the sampling distribution look like if we could afford to take samples as big as the entire population, i.e. of size <span class="math inline">\(n = N\)</span>?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-5" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-5&#39;, &#39;sol-start-5&#39;)"></span>
</p>
<div id="sol-body-5" class="solution-body" style="display: none;">
<p>If we could afford to census the entire population, then we would find the exact value of the parameter.
By taking repeated samples of size equal to the entire population, every time we would obtain the population parameter exactly, so the distribution would look like a histogram with a single bar on top of the true value: we would find the true parameter with a probability of one.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<p>To summarize:</p>
<ul>
<li>We have <strong>high precision</strong> when the estimates are less variable, and this happens for a <strong>large sample size</strong>.</li>
<li>We have <strong>high accuracy</strong> when our sampling strategy is not biased, and this happens when we do <strong>random sampling</strong>. High accuracy means that our sampling distribution is centred on the true parameter value.</li>
</ul>
These points are visually displayed in Figure <a href="chap-sampling-distributions.html#fig:accuracy-precision">11.7</a>, where the population parameter is represented as the centre of the target:
<div class="figure" style="text-align: center"><span id="fig:accuracy-precision"></span>
<img src="https://d33wubrfki0l68.cloudfront.net/7e9f4ffc8062b970b1b4dc6b76d3b58d77476b00/7e530/images/accuracy_vs_precision.jpg" alt="Comparing accuracy and precision. (From www.moderndive.com)" width="65%" />
<p class="caption">
Figure 11.7: Comparing accuracy and precision. (From www.moderndive.com)
</p>
</div>
</div>
<div id="lab-hollywood-movies" class="section level2">
<h2><span class="header-section-number">11.8</span> Lab: Hollywood movies</h2>
<p>The following code chunk reads in data from over 900 Hollywood movies produced between 2007 and 2013. Consider it as the entire population of movies produced in Hollywood in that time period.</p>
<div class="sourceCode" id="cb528"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb528-1" data-line-number="1">hollywood &lt;-<span class="st"> </span><span class="kw">read_tsv</span>(<span class="st">&#39;https://edin.ac/2N9yHms&#39;</span>)</a>
<a class="sourceLine" id="cb528-2" data-line-number="2">hollywood</a></code></pre></div>
<pre><code>## # A tibble: 970 x 16
##    Movie LeadStudio RottenTomatoes AudienceScore Story Genre TheatersOpenWeek OpeningWeekend
##    &lt;chr&gt; &lt;chr&gt;               &lt;dbl&gt;         &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;            &lt;dbl&gt;          &lt;dbl&gt;
##  1 Spid… Sony                   61            54 Meta… Acti…             4252          151. 
##  2 Shre… Paramount              42            57 Quest Anim…             4122          122. 
##  3 Tran… Paramount              57            89 Mons… Acti…             4011           70.5
##  4 Pira… Disney                 45            74 Resc… Acti…             4362          115. 
##  5 Harr… Warner Br…             78            82 Quest Adve…             4285           77.1
##  6 I Am… Warner Br…             69            69 Quest Thri…             3606           77.2
##  7 The … Universal              93            91 Purs… Thri…             3660           69.3
##  8 Nati… Disney                 31            72 The … Thri…             3832           44.8
##  9 Alvi… Fox                    26            73 Come… Anim…             3475           44.3
## 10 300   Warner Br…             60            90 Sacr… Acti…             3103           70.9
## # … with 960 more rows, and 8 more variables: BOAvgOpenWeekend &lt;dbl&gt;, DomesticGross &lt;dbl&gt;,
## #   ForeignGross &lt;dbl&gt;, WorldGross &lt;dbl&gt;, Budget &lt;dbl&gt;, Profitability &lt;dbl&gt;, OpenProfit &lt;dbl&gt;,
## #   Year &lt;dbl&gt;</code></pre>
<p>Among the recorded variables, three will be of interest:</p>
<ul>
<li>Movie;</li>
<li>Genre;</li>
<li>Budget.</li>
</ul>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p><strong>Extracting relevant variables</strong></p>
<p>Extract from the <code>hollywood</code> tibble the three variables of interest (Movie, Genre, Budget) and keep the movies for which we have all information (no missing entries).</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-6" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-6&#39;, &#39;sol-start-6&#39;)"></span>
</p>
<div id="sol-body-6" class="solution-body" style="display: none;">
<p>We can extract variables using the function <code>select()</code>, while to keep the rows for which we have all measurements we use <code>na.omit()</code>:</p>
<div class="sourceCode" id="cb530"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb530-1" data-line-number="1">hollywood &lt;-<span class="st"> </span>hollywood <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb530-2" data-line-number="2"><span class="st">  </span><span class="kw">select</span>(Movie, Genre, Budget) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb530-3" data-line-number="3"><span class="st">  </span>na.omit</a>
<a class="sourceLine" id="cb530-4" data-line-number="4">hollywood</a></code></pre></div>
<pre><code>## # A tibble: 665 x 3
##    Movie                                     Genre     Budget
##    &lt;chr&gt;                                     &lt;chr&gt;      &lt;dbl&gt;
##  1 Spider-Man 3                              Action       258
##  2 Shrek the Third                           Animation    160
##  3 Transformers                              Action       150
##  4 Pirates of the Caribbean: At World&#39;s End  Action       300
##  5 Harry Potter and the Order of the Phoenix Adventure    150
##  6 I Am Legend                               Thriller     150
##  7 The Bourne Ultimatum                      Thriller     110
##  8 National Treasure: Book of Secrets        Thriller     130
##  9 Alvin and the Chipmunks                   Animation     70
## 10 300                                       Action        65
## # … with 655 more rows</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p><strong>Proportion of comedy movies</strong></p>
<p>What is the population proportion of comedy movies?
What is an estimate of the proportion of comedy movies using a sample of size 20?
Using the appropriate notation, report your results in one or two sentences.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-7" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-7&#39;, &#39;sol-start-7&#39;)"></span>
</p>
<div id="sol-body-7" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb532"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb532-1" data-line-number="1">prop_comedy &lt;-<span class="st"> </span>hollywood <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb532-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">prop =</span> <span class="kw">mean</span>(Genre <span class="op">==</span><span class="st"> &quot;Comedy&quot;</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb532-3" data-line-number="3"><span class="st">  </span><span class="kw">pull</span>(prop)</a>
<a class="sourceLine" id="cb532-4" data-line-number="4">prop_comedy</a></code></pre></div>
<pre><code>## [1] 0.2541353</code></pre>
<div class="sourceCode" id="cb534"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb534-1" data-line-number="1">sample_prop_comedy &lt;-<span class="st"> </span>hollywood <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb534-2" data-line-number="2"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">20</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb534-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">prop =</span> <span class="kw">mean</span>(Genre <span class="op">==</span><span class="st"> &quot;Comedy&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb534-4" data-line-number="4"><span class="st">  </span><span class="kw">pull</span>(prop)</a>
<a class="sourceLine" id="cb534-5" data-line-number="5">sample_prop_comedy</a></code></pre></div>
<pre><code>## [1] 0.2</code></pre>
<p>The population proportion of comedy movies is <span class="math inline">\(p =\)</span> 0.25, while the proportion of comedy movies in the sample is <span class="math inline">\(\hat{p} =\)</span> 0.2.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p><strong>Sampling distributions</strong></p>
<p>What is a sampling distribution?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-8" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-8&#39;, &#39;sol-start-8&#39;)"></span>
</p>
<div id="sol-body-8" class="solution-body" style="display: none;">
<p>The sampling distribution is the distribution of the values that a statistic takes on different samples of the same size and from the same population.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p><strong>Sampling distribution of the proportion</strong></p>
<p>Compute the sampling distribution of the proportion of comedy movies for sample size <span class="math inline">\(n = 20\)</span>, using 1000 replicates. Is it centred at the population value?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-9" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-9&#39;, &#39;sol-start-9&#39;)"></span>
</p>
<div id="sol-body-9" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb536"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb536-1" data-line-number="1">sample_props &lt;-<span class="st"> </span>hollywood <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb536-2" data-line-number="2"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">20</span>, <span class="dt">reps =</span> <span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb536-3" data-line-number="3"><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb536-4" data-line-number="4"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">prop =</span> <span class="kw">mean</span>(Genre <span class="op">==</span><span class="st"> &#39;Comedy&#39;</span>))</a>
<a class="sourceLine" id="cb536-5" data-line-number="5"></a>
<a class="sourceLine" id="cb536-6" data-line-number="6"><span class="kw">ggplot</span>(sample_props, <span class="kw">aes</span>(<span class="dt">x =</span> prop)) <span class="op">+</span></a>
<a class="sourceLine" id="cb536-7" data-line-number="7"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&#39;white&#39;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb536-8" data-line-number="8"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> prop_comedy, <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb536-9" data-line-number="9"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expression</span>(<span class="kw">hat</span>(p)))</a></code></pre></div>
<div class="figure"><span id="fig:w11-lab-sampling-dist"></span>
<img src="bookdown-demo_files/figure-html/w11-lab-sampling-dist-1.png" alt="Sampling distribution of the proportion for $n = 20$ with population parameter $p$ marked by a red vertical line." width="672" />
<p class="caption">
Figure 11.8: Sampling distribution of the proportion for <span class="math inline">\(n = 20\)</span> with population parameter <span class="math inline">\(p\)</span> marked by a red vertical line.
</p>
</div>
<p>Yes, Figure <a href="chap-sampling-distributions.html#fig:w11-lab-sampling-dist">11.8</a> shows that the distribution is almost bell-shaped and centred at the population parameter.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p><strong>Standard error</strong></p>
<p>Using the replicated samples from the previous question, what is the standard error of the sample proportion of comedy movies?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-10" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-10&#39;, &#39;sol-start-10&#39;)"></span>
</p>
<div id="sol-body-10" class="solution-body" style="display: none;">
<p>The standard error of the sample proportion is simply the standard deviation of the distribution of sample proportions for many samples. Since we have already computed the proportions for 1000 samples in the previous question, we just have to compute their variability using the standard deviation:</p>
<div class="sourceCode" id="cb537"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb537-1" data-line-number="1">se_prop &lt;-<span class="st"> </span>sample_props <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb537-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">SE =</span> <span class="kw">sd</span>(prop)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb537-3" data-line-number="3"><span class="st">  </span><span class="kw">pull</span>(SE)</a>
<a class="sourceLine" id="cb537-4" data-line-number="4"></a>
<a class="sourceLine" id="cb537-5" data-line-number="5">se_prop</a></code></pre></div>
<pre><code>## [1] 0.09566467</code></pre>
<p>The standard error of the sample proportion for sample size <span class="math inline">\(n = 20\)</span>, based on 1000 replicated samples, is <span class="math inline">\(SE(\hat{p}) =\)</span> 0.1.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p><strong>The effect of sample size on the standard error of the sample proportion</strong></p>
<p>How does the sample size affect the standard error of the sample proportion?
Compute the sampling distribution for the proportion of comedy movies using samples of size <span class="math inline">\(n = 20\)</span>, <span class="math inline">\(n = 50\)</span>, <span class="math inline">\(n = 200\)</span> respectively and 1000 replicated samples.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-11" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-11&#39;, &#39;sol-start-11&#39;)"></span>
</p>
<div id="sol-body-11" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb539"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb539-1" data-line-number="1">sample_props_<span class="dv">20</span> &lt;-<span class="st"> </span>hollywood <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb539-2" data-line-number="2"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">20</span>, <span class="dt">reps =</span> <span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb539-3" data-line-number="3"><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb539-4" data-line-number="4"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">prop =</span> <span class="kw">mean</span>(Genre <span class="op">==</span><span class="st"> &#39;Comedy&#39;</span>))</a>
<a class="sourceLine" id="cb539-5" data-line-number="5"></a>
<a class="sourceLine" id="cb539-6" data-line-number="6">sample_props_<span class="dv">50</span> &lt;-<span class="st"> </span>hollywood <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb539-7" data-line-number="7"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">50</span>, <span class="dt">reps =</span> <span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb539-8" data-line-number="8"><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb539-9" data-line-number="9"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">prop =</span> <span class="kw">mean</span>(Genre <span class="op">==</span><span class="st"> &#39;Comedy&#39;</span>))</a>
<a class="sourceLine" id="cb539-10" data-line-number="10"></a>
<a class="sourceLine" id="cb539-11" data-line-number="11">sample_props_<span class="dv">200</span> &lt;-<span class="st"> </span>hollywood <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb539-12" data-line-number="12"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">200</span>, <span class="dt">reps =</span> <span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb539-13" data-line-number="13"><span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb539-14" data-line-number="14"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">prop =</span> <span class="kw">mean</span>(Genre <span class="op">==</span><span class="st"> &#39;Comedy&#39;</span>))</a>
<a class="sourceLine" id="cb539-15" data-line-number="15"></a>
<a class="sourceLine" id="cb539-16" data-line-number="16">sample_props_vary_n &lt;-<span class="st"> </span><span class="kw">bind_rows</span>(</a>
<a class="sourceLine" id="cb539-17" data-line-number="17">  sample_props_<span class="dv">20</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">n =</span> <span class="dv">20</span>),</a>
<a class="sourceLine" id="cb539-18" data-line-number="18">  sample_props_<span class="dv">50</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">n =</span> <span class="dv">50</span>),</a>
<a class="sourceLine" id="cb539-19" data-line-number="19">  sample_props_<span class="dv">200</span> <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">n =</span> <span class="dv">200</span>)</a>
<a class="sourceLine" id="cb539-20" data-line-number="20">)</a>
<a class="sourceLine" id="cb539-21" data-line-number="21"></a>
<a class="sourceLine" id="cb539-22" data-line-number="22"><span class="kw">ggplot</span>(sample_props_vary_n, <span class="kw">aes</span>(<span class="dt">x =</span> prop)) <span class="op">+</span></a>
<a class="sourceLine" id="cb539-23" data-line-number="23"><span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">color =</span> <span class="st">&#39;white&#39;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb539-24" data-line-number="24"><span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> prop_comedy, <span class="dt">color =</span> <span class="st">&#39;red&#39;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb539-25" data-line-number="25"><span class="st">  </span><span class="kw">facet_grid</span>(<span class="dt">rows =</span> <span class="kw">vars</span>(n), <span class="dt">labeller =</span> label_both) <span class="op">+</span></a>
<a class="sourceLine" id="cb539-26" data-line-number="26"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="kw">expression</span>(<span class="kw">hat</span>(p)), <span class="dt">title =</span> <span class="st">&quot;Sampling distribution of proportion for samples of size 20, 50, 200&quot;</span>)</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:w11-lab-vary-n"></span>
<img src="bookdown-demo_files/figure-html/w11-lab-vary-n-1.png" alt="Three sampling distributions of the proportion, with population parameter $p$ marked by a red vertical line." width="672" />
<p class="caption">
Figure 11.9: Three sampling distributions of the proportion, with population parameter <span class="math inline">\(p\)</span> marked by a red vertical line.
</p>
</div>
<p>From Figure <a href="chap-sampling-distributions.html#fig:w11-lab-vary-n">11.9</a> we can see that, as the sample size increases, the standard error of the sample proportion decreases. Increasing the sample size, the spread of the statistic values is reduced.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p><strong>Comparing the budget for action and comedy movies</strong></p>
<p>What is the population average budget (in millions of dollars) allocated for making action vs comedy movies? And the standard deviation?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-12" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-12&#39;, &#39;sol-start-12&#39;)"></span>
</p>
<div id="sol-body-12" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb540"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb540-1" data-line-number="1">budgets &lt;-<span class="st"> </span>hollywood <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb540-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(Genre <span class="op">==</span><span class="st"> &#39;Action&#39;</span> <span class="op">|</span><span class="st"> </span>Genre <span class="op">==</span><span class="st"> &#39;Comedy&#39;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb540-3" data-line-number="3"><span class="st">  </span><span class="kw">group_by</span>(Genre) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb540-4" data-line-number="4"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg_budget =</span> <span class="kw">mean</span>(Budget),</a>
<a class="sourceLine" id="cb540-5" data-line-number="5">            <span class="dt">sd_budget =</span> <span class="kw">sd</span>(Budget))</a>
<a class="sourceLine" id="cb540-6" data-line-number="6">budgets</a></code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   Genre  avg_budget sd_budget
##   &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;
## 1 Action       85.9      64.0
## 2 Comedy       36.9      26.7</code></pre>
<p>From the above tibble we see that action movies have been allocated a higher budget (<span class="math inline">\(\mu_{Action} =\)</span> 85.9) than comedy movies (<span class="math inline">\(\mu_{Comedy} =\)</span> 36.9). At the same time, action movies have a higher variability of budgets around the mean value (<span class="math inline">\(\sigma_{Action} =\)</span> 64 vs <span class="math inline">\(\sigma_{Comedy} =\)</span> 26.7).</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question (Optional)
</p>
<div class="question-body">
<p><strong>Estimate the average difference in budget for action vs comedy movies</strong></p>
<p>Estimate the average difference in budget for action vs comedy movies, using two samples of size 100. How does it compare to the population difference?</p>
<p><em><strong>Hint:</strong> Filter the <code>hollywood</code> tibble to keep only action movies. Then, obtain a sample of 100 action movies and estimate the average budget. Repeat the same steps for comedy movies.</em></p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-13" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-13&#39;, &#39;sol-start-13&#39;)"></span>
</p>
<div id="sol-body-13" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb542"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb542-1" data-line-number="1">sample_budget_action &lt;-<span class="st"> </span>hollywood <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb542-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(Genre <span class="op">==</span><span class="st"> &#39;Action&#39;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb542-3" data-line-number="3"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">100</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb542-4" data-line-number="4"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg_budget =</span> <span class="kw">mean</span>(Budget))</a>
<a class="sourceLine" id="cb542-5" data-line-number="5">sample_budget_action</a></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   replicate avg_budget
##       &lt;int&gt;      &lt;dbl&gt;
## 1         1       87.5</code></pre>
<div class="sourceCode" id="cb544"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb544-1" data-line-number="1">sample_budget_comedy &lt;-<span class="st"> </span>hollywood <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb544-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(Genre <span class="op">==</span><span class="st"> &#39;Comedy&#39;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb544-3" data-line-number="3"><span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">100</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb544-4" data-line-number="4"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg_budget =</span> <span class="kw">mean</span>(Budget))</a>
<a class="sourceLine" id="cb544-5" data-line-number="5">sample_budget_comedy</a></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   replicate avg_budget
##       &lt;int&gt;      &lt;dbl&gt;
## 1         1       36.6</code></pre>
<div class="sourceCode" id="cb546"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb546-1" data-line-number="1">est_diff &lt;-<span class="st"> </span><span class="kw">pull</span>(sample_budget_action, avg_budget) <span class="op">-</span><span class="st"> </span><span class="kw">pull</span>(sample_budget_comedy, avg_budget)</a>
<a class="sourceLine" id="cb546-2" data-line-number="2">est_diff</a></code></pre></div>
<pre><code>## [1] 50.869</code></pre>
<p>The estimated difference in mean budget is <span class="math inline">\(\bar{x}_{Action} - \bar{x}_{Comedy} =\)</span> 87.5 - 36.6 = 50.9.
The population difference in budget can be calculated from the previous question, and is equal to <span class="math inline">\(\mu_{Action} - \mu_{Comedy} =\)</span> 85.9 - 36.9 = 49.
The two values are not exactly equal, as we have estimated the parameter with a sample of size 100.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="summary" class="section level2">
<h2><span class="header-section-number">11.9</span> Summary</h2>
<p>In Section <a href="chap-sampling-distributions.html#parameter-statistic">11.3</a> we have reviewed the difference between a population parameter and a statistic computed on a sample [<strong>LO1</strong>].
Because of the sampling criteria, which select units at random, those included in the sample vary when the sampling procedure is repeated.
The distribution of the values that a sample statistics takes on the different samples is called sampling distribution, and has been defined in Section <a href="chap-sampling-distributions.html#sec-sampling-distributions">11.4</a> [<strong>LO2</strong>]. The spread of a statistic gives an idea of how close our estimate of the unknown population parameter is to the population value. Hence, lower variability means a better guess. We quantified the variability of a statistic with its standard error, defined as the standard deviation of the statistic’s sampling distribution, and in Section <a href="chap-sampling-distributions.html#sample-size-standard-error">11.6</a> we saw that as the sample size increases, the standard error decreases [<strong>LO3</strong>].</p>
</div>
<div id="glossary" class="section level2">
<h2><span class="header-section-number">11.10</span> Glossary</h2>
<ul>
<li><em>Statistical inference.</em> The process of drawing conclusions about the population from the data collected in a sample.</li>
<li><em>Population.</em> The entire collection of units of interest.</li>
<li><em>Sample.</em> A subset of the entire population.</li>
<li><em>Random sample.</em> A subset of the entire population, picked at random, so that any conclusion made from the sample data can be generalised to the entire population.</li>
<li><em>Representation bias.</em> Happens when some units of the population are systematically underrepresented in samples.</li>
<li><em>Generalisability.</em> When information from the sample can be used to draw conclusions about the entire population. This is only possible if the sampling procedure leads to samples that are representative of the entire population (such as those drawn at random).</li>
<li><em>Parameter.</em> A fixed but typically unknown quantity describing the population.</li>
<li><em>Statistic.</em> A quantity computed on a sample.</li>
<li><em>Sampling distribution.</em> The distribution of the values that a statistic takes on different samples of the same size and from the same population.</li>
<li><em>Standard error.</em> The standard error of a statistic is the standard deviation of the sampling distribution of the statistic.</li>
</ul>
</div>
<div id="references" class="section level2">
<h2><span class="header-section-number">11.11</span> References</h2>
<ul>
<li><p>Ismay, C., &amp; Kim, A. Y. (2019). <em>Statistical Inference via Data Science: A ModernDive into R and the Tidyverse</em>. CRC Press. Freely available online at: <a href="https://moderndive.com/" class="uri">https://moderndive.com/</a></p></li>
<li><p>Lock, R. Lock Morgan, K., Lock, E., &amp; Lock, D. (2013) <em>Statistics: Unlocking the power of data.</em> Wiley, Hoboken.</p></li>
</ul>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="3">
<li id="fn3"><p>You might remember it from the cartoon Wile E. Coyote and the Road Runner.<a href="chap-sampling-distributions.html#fnref3" class="footnote-back">↩</a></p></li>
<li id="fn4"><p>Of course a population might change over time, as people can enter or leave at any time, so you might wonder why did we say that a population parameter is fixed? Because of the large number of units in the entire population, it is reasonable to assume that the addition of comparatively few units to the entirety leads to a negligible change in the population parameter.<a href="chap-sampling-distributions.html#fnref4" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="week-10-lab-test.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="bootstrapping-and-confidence-intervals.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
