<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 18 Paired T-Test | Data Analysis for Psychology in R (dapR1) - Labs</title>
  <meta name="description" content="This is the page that contains the course labs materials" />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 18 Paired T-Test | Data Analysis for Psychology in R (dapR1) - Labs" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the page that contains the course labs materials" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 18 Paired T-Test | Data Analysis for Psychology in R (dapR1) - Labs" />
  
  <meta name="twitter:description" content="This is the page that contains the course labs materials" />
  

<meta name="author" content="Department of Psychology, University of Edinburgh" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="two-indep-samples.html"/>
<link rel="next" href="chap-chi-square.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script>
  $(document).ready(function() {
    $head = $('#header');
    $head.prepend('<img style="padding-right:25%; margin-bottom:10px;" src="https://www.ed.ac.uk/sites/all/themes/uoe/assets/logo.png" width="770px" align="left">')
  });
</script>

<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}
}
</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">DAPR1</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview of the Course</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#the-team"><i class="fa fa-check"></i>The team</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-cheatsheets"><i class="fa fa-check"></i>R Cheatsheets</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-community"><i class="fa fa-check"></i>R Community</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="week-1.html"><a href="week-1.html"><i class="fa fa-check"></i><b>1</b> Week 1</a><ul>
<li class="chapter" data-level="1.1" data-path="week-1.html"><a href="week-1.html#introduction-to-r-and-rstudio"><i class="fa fa-check"></i><b>1.1</b> Introduction to R and RStudio</a></li>
<li class="chapter" data-level="1.2" data-path="week-1.html"><a href="week-1.html#install-the-recent-version-of-r-and-r-studio"><i class="fa fa-check"></i><b>1.2</b> Install the recent version of R and R Studio</a><ul>
<li class="chapter" data-level="1.2.1" data-path="week-1.html"><a href="week-1.html#first-step"><i class="fa fa-check"></i><b>1.2.1</b> First Step</a></li>
<li class="chapter" data-level="1.2.2" data-path="week-1.html"><a href="week-1.html#second-step"><i class="fa fa-check"></i><b>1.2.2</b> Second Step</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="week-1.html"><a href="week-1.html#getting-started-in-rstudio"><i class="fa fa-check"></i><b>1.3</b> Getting Started in RStudio</a></li>
<li class="chapter" data-level="1.4" data-path="week-1.html"><a href="week-1.html#r-as-an-interactive-environment"><i class="fa fa-check"></i><b>1.4</b> R as an interactive environment</a></li>
<li class="chapter" data-level="1.5" data-path="week-1.html"><a href="week-1.html#check-your-settings"><i class="fa fa-check"></i><b>1.5</b> Check your settings</a><ul>
<li class="chapter" data-level="1.5.1" data-path="week-1.html"><a href="week-1.html#disable-automatic-saving-of-your-workspace"><i class="fa fa-check"></i><b>1.5.1</b> Disable automatic saving of your workspace</a></li>
<li class="chapter" data-level="1.5.2" data-path="week-1.html"><a href="week-1.html#adjust-fontscolours-if-you-like"><i class="fa fa-check"></i><b>1.5.2</b> Adjust fonts/colours if you like</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="week-1.html"><a href="week-1.html#setting-up-your-working-directory"><i class="fa fa-check"></i><b>1.6</b> Setting Up Your Working Directory</a></li>
<li class="chapter" data-level="1.7" data-path="week-1.html"><a href="week-1.html#the-console"><i class="fa fa-check"></i><b>1.7</b> The Console</a></li>
<li class="chapter" data-level="1.8" data-path="week-1.html"><a href="week-1.html#spacing"><i class="fa fa-check"></i><b>1.8</b> Spacing</a></li>
<li class="chapter" data-level="1.9" data-path="week-1.html"><a href="week-1.html#typos"><i class="fa fa-check"></i><b>1.9</b> Typos</a></li>
<li class="chapter" data-level="1.10" data-path="week-1.html"><a href="week-1.html#unfinishe.-d"><i class="fa fa-check"></i><b>1.10</b> Unfinishe…. d</a></li>
<li class="chapter" data-level="1.11" data-path="week-1.html"><a href="week-1.html#basic-arithmetic"><i class="fa fa-check"></i><b>1.11</b> Basic Arithmetic</a></li>
<li class="chapter" data-level="1.12" data-path="week-1.html"><a href="week-1.html#using-functions-for-calculations"><i class="fa fa-check"></i><b>1.12</b> Using Functions for Calculations</a></li>
<li class="chapter" data-level="1.13" data-path="week-1.html"><a href="week-1.html#r-scripts"><i class="fa fa-check"></i><b>1.13</b> R Scripts</a></li>
<li class="chapter" data-level="1.14" data-path="week-1.html"><a href="week-1.html#short-example"><i class="fa fa-check"></i><b>1.14</b> Short Example</a></li>
<li class="chapter" data-level="1.15" data-path="week-1.html"><a href="week-1.html#naming-variables"><i class="fa fa-check"></i><b>1.15</b> Naming variables</a></li>
<li class="chapter" data-level="1.16" data-path="week-1.html"><a href="week-1.html#now-over-to-you"><i class="fa fa-check"></i><b>1.16</b> Now over to you</a><ul>
<li class="chapter" data-level="1.16.1" data-path="week-1.html"><a href="week-1.html#exercise-1"><i class="fa fa-check"></i><b>1.16.1</b> Exercise 1</a></li>
<li class="chapter" data-level="1.16.2" data-path="week-1.html"><a href="week-1.html#exercise-2"><i class="fa fa-check"></i><b>1.16.2</b> Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="1.17" data-path="week-1.html"><a href="week-1.html#solutions"><i class="fa fa-check"></i><b>1.17</b> Solutions</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="week-2.html"><a href="week-2.html"><i class="fa fa-check"></i><b>2</b> Week 2</a><ul>
<li class="chapter" data-level="2.1" data-path="week-2.html"><a href="week-2.html#introduction-to-rmarkdown"><i class="fa fa-check"></i><b>2.1</b> Introduction to RMarkdown</a></li>
<li class="chapter" data-level="2.2" data-path="week-2.html"><a href="week-2.html#what-is-r-markdown"><i class="fa fa-check"></i><b>2.2</b> What is R Markdown?</a></li>
<li class="chapter" data-level="2.3" data-path="week-2.html"><a href="week-2.html#getting-things-ready"><i class="fa fa-check"></i><b>2.3</b> Getting things ready</a></li>
<li class="chapter" data-level="2.4" data-path="week-2.html"><a href="week-2.html#r-markdown-basics"><i class="fa fa-check"></i><b>2.4</b> R Markdown basics</a></li>
<li class="chapter" data-level="2.5" data-path="week-2.html"><a href="week-2.html#headings"><i class="fa fa-check"></i><b>2.5</b> Headings</a></li>
<li class="chapter" data-level="2.6" data-path="week-2.html"><a href="week-2.html#text"><i class="fa fa-check"></i><b>2.6</b> Text</a></li>
<li class="chapter" data-level="2.7" data-path="week-2.html"><a href="week-2.html#tables"><i class="fa fa-check"></i><b>2.7</b> Tables</a></li>
<li class="chapter" data-level="2.8" data-path="week-2.html"><a href="week-2.html#lists"><i class="fa fa-check"></i><b>2.8</b> Lists</a><ul>
<li class="chapter" data-level="2.8.1" data-path="week-2.html"><a href="week-2.html#unordered"><i class="fa fa-check"></i><b>2.8.1</b> Unordered</a></li>
<li class="chapter" data-level="2.8.2" data-path="week-2.html"><a href="week-2.html#ordered"><i class="fa fa-check"></i><b>2.8.2</b> Ordered</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="week-2.html"><a href="week-2.html#rmd-documents"><i class="fa fa-check"></i><b>2.9</b> Rmd documents</a></li>
<li class="chapter" data-level="2.10" data-path="week-2.html"><a href="week-2.html#code-chunks"><i class="fa fa-check"></i><b>2.10</b> Code chunks</a></li>
<li class="chapter" data-level="2.11" data-path="week-2.html"><a href="week-2.html#common-code-chunks-options"><i class="fa fa-check"></i><b>2.11</b> Common Code Chunks Options</a></li>
<li class="chapter" data-level="2.12" data-path="week-2.html"><a href="week-2.html#including-images-or-links"><i class="fa fa-check"></i><b>2.12</b> Including images or links</a><ul>
<li class="chapter" data-level="2.12.1" data-path="week-2.html"><a href="week-2.html#adding-links"><i class="fa fa-check"></i><b>2.12.1</b> Adding links</a></li>
<li class="chapter" data-level="2.12.2" data-path="week-2.html"><a href="week-2.html#adding-figures-pictures"><i class="fa fa-check"></i><b>2.12.2</b> Adding figures &amp; pictures</a></li>
</ul></li>
<li class="chapter" data-level="2.13" data-path="week-2.html"><a href="week-2.html#generating-documents"><i class="fa fa-check"></i><b>2.13</b> Generating documents</a></li>
<li class="chapter" data-level="2.14" data-path="week-2.html"><a href="week-2.html#extra-opensave-files-on-rstudio-cloud-chrome-users"><i class="fa fa-check"></i><b>2.14</b> Extra: Open/Save files on Rstudio Cloud (Chrome users)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-3.html"><a href="week-3.html"><i class="fa fa-check"></i><b>3</b> Week 3</a><ul>
<li class="chapter" data-level="3.1" data-path="week-3.html"><a href="week-3.html#vectors-lists-data-frames-and-data-types"><i class="fa fa-check"></i><b>3.1</b> Vectors, lists, data frames and data types</a></li>
<li class="chapter" data-level="3.2" data-path="week-3.html"><a href="week-3.html#get-the-package-first"><i class="fa fa-check"></i><b>3.2</b> Get the package first</a></li>
<li class="chapter" data-level="3.3" data-path="week-3.html"><a href="week-3.html#numeric-data"><i class="fa fa-check"></i><b>3.3</b> Numeric Data</a></li>
<li class="chapter" data-level="3.4" data-path="week-3.html"><a href="week-3.html#textcharacter-data"><i class="fa fa-check"></i><b>3.4</b> Text/Character Data</a></li>
<li class="chapter" data-level="3.5" data-path="week-3.html"><a href="week-3.html#logical-data"><i class="fa fa-check"></i><b>3.5</b> Logical Data</a></li>
<li class="chapter" data-level="3.6" data-path="week-3.html"><a href="week-3.html#variable-classes"><i class="fa fa-check"></i><b>3.6</b> Variable Classes</a></li>
<li class="chapter" data-level="3.7" data-path="week-3.html"><a href="week-3.html#factors"><i class="fa fa-check"></i><b>3.7</b> Factors</a></li>
<li class="chapter" data-level="3.8" data-path="week-3.html"><a href="week-3.html#lists-1"><i class="fa fa-check"></i><b>3.8</b> Lists</a></li>
<li class="chapter" data-level="3.9" data-path="week-3.html"><a href="week-3.html#practice.rmd-solutions"><i class="fa fa-check"></i><b>3.9</b> Practice.Rmd Solutions</a><ul>
<li class="chapter" data-level="3.9.1" data-path="week-3.html"><a href="week-3.html#exercise-1-1"><i class="fa fa-check"></i><b>3.9.1</b> Exercise 1</a></li>
<li class="chapter" data-level="3.9.2" data-path="week-3.html"><a href="week-3.html#exercise-2-1"><i class="fa fa-check"></i><b>3.9.2</b> Exercise 2</a></li>
<li class="chapter" data-level="3.9.3" data-path="week-3.html"><a href="week-3.html#exercise-3"><i class="fa fa-check"></i><b>3.9.3</b> Exercise 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-4.html"><a href="week-4.html"><i class="fa fa-check"></i><b>4</b> Week 4</a><ul>
<li class="chapter" data-level="4.1" data-path="week-4.html"><a href="week-4.html#introduction-to-plots-geoms-ggplot"><i class="fa fa-check"></i><b>4.1</b> Introduction to plots &amp; geoms (ggplot)</a></li>
<li class="chapter" data-level="4.2" data-path="week-4.html"><a href="week-4.html#visualisations"><i class="fa fa-check"></i><b>4.2</b> Visualisations</a></li>
<li class="chapter" data-level="4.3" data-path="week-4.html"><a href="week-4.html#get-our-data-sorted"><i class="fa fa-check"></i><b>4.3</b> Get our data sorted</a></li>
<li class="chapter" data-level="4.4" data-path="week-4.html"><a href="week-4.html#numerical-data"><i class="fa fa-check"></i><b>4.4</b> Numerical data</a></li>
<li class="chapter" data-level="4.5" data-path="week-4.html"><a href="week-4.html#simple-one-variable-plot-using-ggplot"><i class="fa fa-check"></i><b>4.5</b> Simple one-variable plot using ggplot()</a><ul>
<li class="chapter" data-level="4.5.1" data-path="week-4.html"><a href="week-4.html#continuous-variable"><i class="fa fa-check"></i><b>4.5.1</b> Continuous variable</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="week-4.html"><a href="week-4.html#categorical-variables"><i class="fa fa-check"></i><b>4.6</b> Categorical variables</a></li>
<li class="chapter" data-level="4.7" data-path="week-4.html"><a href="week-4.html#continuous-variables-grouped-by-a-categorical-one"><i class="fa fa-check"></i><b>4.7</b> Continuous variables grouped by a categorical one</a></li>
<li class="chapter" data-level="4.8" data-path="week-4.html"><a href="week-4.html#even-more-advanced"><i class="fa fa-check"></i><b>4.8</b> Even more advanced</a></li>
<li class="chapter" data-level="4.9" data-path="week-4.html"><a href="week-4.html#practice.rmd-solutions-1"><i class="fa fa-check"></i><b>4.9</b> Practice.Rmd Solutions</a><ul>
<li class="chapter" data-level="4.9.1" data-path="week-4.html"><a href="week-4.html#exercise-1-2"><i class="fa fa-check"></i><b>4.9.1</b> Exercise 1</a></li>
<li class="chapter" data-level="4.9.2" data-path="week-4.html"><a href="week-4.html#exercise-2-2"><i class="fa fa-check"></i><b>4.9.2</b> Exercise 2</a></li>
<li class="chapter" data-level="4.9.3" data-path="week-4.html"><a href="week-4.html#exercise-3---advanced"><i class="fa fa-check"></i><b>4.9.3</b> Exercise 3 - Advanced</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-5.html"><a href="week-5.html"><i class="fa fa-check"></i><b>5</b> Week 5</a><ul>
<li class="chapter" data-level="5.1" data-path="week-5.html"><a href="week-5.html#central-tendency-and-variability"><i class="fa fa-check"></i><b>5.1</b> Central Tendency and Variability</a></li>
<li class="chapter" data-level="5.2" data-path="week-5.html"><a href="week-5.html#load-all-the-necessary-packages"><i class="fa fa-check"></i><b>5.2</b> Load all the necessary packages</a></li>
<li class="chapter" data-level="5.3" data-path="week-5.html"><a href="week-5.html#descriptive-statistics"><i class="fa fa-check"></i><b>5.3</b> Descriptive Statistics</a></li>
<li class="chapter" data-level="5.4" data-path="week-5.html"><a href="week-5.html#central-tendency-variability"><i class="fa fa-check"></i><b>5.4</b> Central tendency &amp; variability</a></li>
<li class="chapter" data-level="5.5" data-path="week-5.html"><a href="week-5.html#mean-and-median"><i class="fa fa-check"></i><b>5.5</b> Mean and median</a><ul>
<li class="chapter" data-level="5.5.1" data-path="week-5.html"><a href="week-5.html#reading-data-in"><i class="fa fa-check"></i><b>5.5.1</b> Reading data in</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="week-5.html"><a href="week-5.html#using-piping-operator-for-descriptive-statistics"><i class="fa fa-check"></i><b>5.6</b> Using piping operator for descriptive statistics</a><ul>
<li class="chapter" data-level="5.6.1" data-path="week-5.html"><a href="week-5.html#mean"><i class="fa fa-check"></i><b>5.6.1</b> Mean</a></li>
<li class="chapter" data-level="5.6.2" data-path="week-5.html"><a href="week-5.html#median"><i class="fa fa-check"></i><b>5.6.2</b> Median</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="week-5.html"><a href="week-5.html#standard-deviation"><i class="fa fa-check"></i><b>5.7</b> Standard deviation</a></li>
<li class="chapter" data-level="5.8" data-path="week-5.html"><a href="week-5.html#visualise-your-data"><i class="fa fa-check"></i><b>5.8</b> Visualise your data</a></li>
<li class="chapter" data-level="5.9" data-path="week-5.html"><a href="week-5.html#practice.rmd-solutions-2"><i class="fa fa-check"></i><b>5.9</b> Practice.Rmd Solutions</a><ul>
<li class="chapter" data-level="5.9.1" data-path="week-5.html"><a href="week-5.html#income-distribution-example"><i class="fa fa-check"></i><b>5.9.1</b> Income Distribution Example</a></li>
<li class="chapter" data-level="5.9.2" data-path="week-5.html"><a href="week-5.html#visualisations-1"><i class="fa fa-check"></i><b>5.9.2</b> Visualisations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-6.html"><a href="week-6.html"><i class="fa fa-check"></i><b>6</b> Week 6</a><ul>
<li class="chapter" data-level="6.1" data-path="week-6.html"><a href="week-6.html#plotting-functions-and-simple-data-transformation"><i class="fa fa-check"></i><b>6.1</b> Plotting Functions and Simple Data Transformation</a></li>
<li class="chapter" data-level="6.2" data-path="week-6.html"><a href="week-6.html#load-all-the-necessary-packages-1"><i class="fa fa-check"></i><b>6.2</b> Load all the necessary packages</a></li>
<li class="chapter" data-level="6.3" data-path="week-6.html"><a href="week-6.html#part-1-hand-plotting-functions"><i class="fa fa-check"></i><b>6.3</b> Part 1: Hand plotting functions</a></li>
<li class="chapter" data-level="6.4" data-path="week-6.html"><a href="week-6.html#basics"><i class="fa fa-check"></i><b>6.4</b> Basics</a></li>
<li class="chapter" data-level="6.5" data-path="week-6.html"><a href="week-6.html#linear-functions"><i class="fa fa-check"></i><b>6.5</b> Linear functions</a><ul>
<li class="chapter" data-level="6.5.1" data-path="week-6.html"><a href="week-6.html#tree-height-example"><i class="fa fa-check"></i><b>6.5.1</b> Tree height example</a></li>
<li class="chapter" data-level="6.5.2" data-path="week-6.html"><a href="week-6.html#non-linear-functions-first-order-polynomials"><i class="fa fa-check"></i><b>6.5.2</b> Non-linear functions (first order polynomials)</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="week-6.html"><a href="week-6.html#practice-plotting"><i class="fa fa-check"></i><b>6.6</b> Practice plotting</a></li>
<li class="chapter" data-level="6.7" data-path="week-6.html"><a href="week-6.html#part-2-introduction-to-data-transformation"><i class="fa fa-check"></i><b>6.7</b> Part 2: Introduction to Data Transformation</a></li>
<li class="chapter" data-level="6.8" data-path="week-6.html"><a href="week-6.html#renaming"><i class="fa fa-check"></i><b>6.8</b> Renaming</a></li>
<li class="chapter" data-level="6.9" data-path="week-6.html"><a href="week-6.html#adding-new-variables"><i class="fa fa-check"></i><b>6.9</b> Adding new variables</a></li>
<li class="chapter" data-level="6.10" data-path="week-6.html"><a href="week-6.html#transformation-and-skewness"><i class="fa fa-check"></i><b>6.10</b> Transformation and skewness</a></li>
<li class="chapter" data-level="6.11" data-path="week-6.html"><a href="week-6.html#mean-centering"><i class="fa fa-check"></i><b>6.11</b> Mean Centering</a></li>
<li class="chapter" data-level="6.12" data-path="week-6.html"><a href="week-6.html#standardisation"><i class="fa fa-check"></i><b>6.12</b> Standardisation</a></li>
<li class="chapter" data-level="6.13" data-path="week-6.html"><a href="week-6.html#practice.rmd-solutions-3"><i class="fa fa-check"></i><b>6.13</b> Practice.Rmd Solutions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="week-7.html"><a href="week-7.html"><i class="fa fa-check"></i><b>7</b> Week 7</a><ul>
<li class="chapter" data-level="7.1" data-path="week-7.html"><a href="week-7.html#reading-in-data-merge-and-more-r-practice"><i class="fa fa-check"></i><b>7.1</b> Reading in Data, Merge and More R Practice</a></li>
<li class="chapter" data-level="7.2" data-path="week-7.html"><a href="week-7.html#dataset-1-.csv"><i class="fa fa-check"></i><b>7.2</b> Dataset 1 (.csv)</a></li>
<li class="chapter" data-level="7.3" data-path="week-7.html"><a href="week-7.html#dataset-2-.txt"><i class="fa fa-check"></i><b>7.3</b> Dataset 2 (.txt)</a></li>
<li class="chapter" data-level="7.4" data-path="week-7.html"><a href="week-7.html#dataset-3-.sav-and-.dta"><i class="fa fa-check"></i><b>7.4</b> Dataset 3 (.sav and .dta)</a></li>
<li class="chapter" data-level="7.5" data-path="week-7.html"><a href="week-7.html#merging-datasets-together"><i class="fa fa-check"></i><b>7.5</b> Merging datasets together</a></li>
<li class="chapter" data-level="7.6" data-path="week-7.html"><a href="week-7.html#sorting-and-arrange"><i class="fa fa-check"></i><b>7.6</b> Sorting and arrange()</a></li>
<li class="chapter" data-level="7.7" data-path="week-7.html"><a href="week-7.html#data-description"><i class="fa fa-check"></i><b>7.7</b> Data description</a></li>
<li class="chapter" data-level="7.8" data-path="week-7.html"><a href="week-7.html#using-filter"><i class="fa fa-check"></i><b>7.8</b> Using filter()</a></li>
<li class="chapter" data-level="7.9" data-path="week-7.html"><a href="week-7.html#visualisations-2"><i class="fa fa-check"></i><b>7.9</b> Visualisations</a></li>
<li class="chapter" data-level="7.10" data-path="week-7.html"><a href="week-7.html#save-the-file-in-your-folder"><i class="fa fa-check"></i><b>7.10</b> Save the file in your folder</a></li>
<li class="chapter" data-level="7.11" data-path="week-7.html"><a href="week-7.html#practice.rmd-solutions-4"><i class="fa fa-check"></i><b>7.11</b> Practice.Rmd Solutions</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="week-8.html"><a href="week-8.html"><i class="fa fa-check"></i><b>8</b> Week 8</a><ul>
<li class="chapter" data-level="8.1" data-path="week-8.html"><a href="week-8.html#introduction-to-probability"><i class="fa fa-check"></i><b>8.1</b> Introduction to Probability</a></li>
<li class="chapter" data-level="8.2" data-path="week-8.html"><a href="week-8.html#example-1-hot-hand"><i class="fa fa-check"></i><b>8.2</b> Example 1 (hot hand)</a></li>
<li class="chapter" data-level="8.3" data-path="week-8.html"><a href="week-8.html#example-2-coin-toss"><i class="fa fa-check"></i><b>8.3</b> Example 2 (coin toss)</a></li>
<li class="chapter" data-level="8.4" data-path="week-8.html"><a href="week-8.html#example-3-independent-shooter"><i class="fa fa-check"></i><b>8.4</b> Example 3 (Independent shooter)</a></li>
<li class="chapter" data-level="8.5" data-path="week-8.html"><a href="week-8.html#practice-rmd.-solutions"><i class="fa fa-check"></i><b>8.5</b> Practice Rmd. Solutions</a><ul>
<li class="chapter" data-level="8.5.1" data-path="week-8.html"><a href="week-8.html#sex-of-the-babies-born-in-the-uk"><i class="fa fa-check"></i><b>8.5.1</b> Sex of the babies born in the UK</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="week-8.html"><a href="week-8.html#pen-and-paper-exercises"><i class="fa fa-check"></i><b>8.6</b> Pen and Paper Exercises</a><ul>
<li class="chapter" data-level="8.6.1" data-path="week-8.html"><a href="week-8.html#boys-and-girls-paradox-mr.jones-and-mr.smith"><i class="fa fa-check"></i><b>8.6.1</b> Boys and girls paradox (Mr. Jones and Mr. Smith)</a></li>
<li class="chapter" data-level="8.6.2" data-path="week-8.html"><a href="week-8.html#rugby-captain"><i class="fa fa-check"></i><b>8.6.2</b> Rugby captain</a></li>
<li class="chapter" data-level="8.6.3" data-path="week-8.html"><a href="week-8.html#answers"><i class="fa fa-check"></i><b>8.6.3</b> Answers</a></li>
<li class="chapter" data-level="8.6.4" data-path="week-8.html"><a href="week-8.html#defective"><i class="fa fa-check"></i><b>8.6.4</b> Defective</a></li>
<li class="chapter" data-level="8.6.5" data-path="week-8.html"><a href="week-8.html#answers-1"><i class="fa fa-check"></i><b>8.6.5</b> Answers</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="week-9.html"><a href="week-9.html"><i class="fa fa-check"></i><b>9</b> Week 9</a><ul>
<li class="chapter" data-level="9.1" data-path="week-9.html"><a href="week-9.html#introduction-to-probability-distributions-and-revision"><i class="fa fa-check"></i><b>9.1</b> Introduction to Probability Distributions and Revision</a></li>
<li class="chapter" data-level="9.2" data-path="week-9.html"><a href="week-9.html#discrete-example-guessing-homework-answers"><i class="fa fa-check"></i><b>9.2</b> Discrete example (guessing homework answers)</a></li>
<li class="chapter" data-level="9.3" data-path="week-9.html"><a href="week-9.html#generate-a-homework-attempt"><i class="fa fa-check"></i><b>9.3</b> Generate a homework attempt</a></li>
<li class="chapter" data-level="9.4" data-path="week-9.html"><a href="week-9.html#changing-the-probability-truefalse"><i class="fa fa-check"></i><b>9.4</b> Changing the probability (TRUE/FALSE)</a></li>
<li class="chapter" data-level="9.5" data-path="week-9.html"><a href="week-9.html#studying-the-distribution"><i class="fa fa-check"></i><b>9.5</b> Studying the distribution</a></li>
<li class="chapter" data-level="9.6" data-path="week-9.html"><a href="week-9.html#cumulative-probability-advanced"><i class="fa fa-check"></i><b>9.6</b> Cumulative Probability (Advanced)</a></li>
<li class="chapter" data-level="9.7" data-path="week-9.html"><a href="week-9.html#revision-practice-rmd.-solutions"><i class="fa fa-check"></i><b>9.7</b> Revision Practice Rmd. Solutions</a><ul>
<li class="chapter" data-level="9.7.1" data-path="week-9.html"><a href="week-9.html#provide-descriptive-statistics-for-age-and-memory-score-variables"><i class="fa fa-check"></i><b>9.7.1</b> Provide descriptive statistics for age and memory score variables</a></li>
<li class="chapter" data-level="9.7.2" data-path="week-9.html"><a href="week-9.html#descriptives-by-groups"><i class="fa fa-check"></i><b>9.7.2</b> Descriptives by groups</a></li>
<li class="chapter" data-level="9.7.3" data-path="week-9.html"><a href="week-9.html#visualise"><i class="fa fa-check"></i><b>9.7.3</b> Visualise</a></li>
<li class="chapter" data-level="9.7.4" data-path="week-9.html"><a href="week-9.html#visualise-a-subset"><i class="fa fa-check"></i><b>9.7.4</b> Visualise a subset</a></li>
<li class="chapter" data-level="9.7.5" data-path="week-9.html"><a href="week-9.html#variable-by-a-group"><i class="fa fa-check"></i><b>9.7.5</b> Variable by a group</a></li>
<li class="chapter" data-level="9.7.6" data-path="week-9.html"><a href="week-9.html#create-a-new-variable-using-mutate"><i class="fa fa-check"></i><b>9.7.6</b> Create a new variable using mutate()</a></li>
<li class="chapter" data-level="9.7.7" data-path="week-9.html"><a href="week-9.html#subset-observations-using-filter"><i class="fa fa-check"></i><b>9.7.7</b> Subset observations using filter()</a></li>
<li class="chapter" data-level="9.7.8" data-path="week-9.html"><a href="week-9.html#sort-via-arrange"><i class="fa fa-check"></i><b>9.7.8</b> Sort via arrange()</a></li>
<li class="chapter" data-level="9.7.9" data-path="week-9.html"><a href="week-9.html#lets-do-some-specific-count-using-filter"><i class="fa fa-check"></i><b>9.7.9</b> Let’s do some specific count() using filter()</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="week-9.html"><a href="week-9.html#extra-probability-practice"><i class="fa fa-check"></i><b>9.8</b> Extra Probability Practice</a><ul>
<li class="chapter" data-level="9.8.1" data-path="week-9.html"><a href="week-9.html#truefalse-questions"><i class="fa fa-check"></i><b>9.8.1</b> TRUE/FALSE questions</a></li>
<li class="chapter" data-level="9.8.2" data-path="week-9.html"><a href="week-9.html#count-the-occurencies"><i class="fa fa-check"></i><b>9.8.2</b> Count the occurencies</a></li>
<li class="chapter" data-level="9.8.3" data-path="week-9.html"><a href="week-9.html#plot"><i class="fa fa-check"></i><b>9.8.3</b> Plot</a></li>
<li class="chapter" data-level="9.8.4" data-path="week-9.html"><a href="week-9.html#use-dbinom-to-study-the-probability"><i class="fa fa-check"></i><b>9.8.4</b> Use dbinom() to study the probability</a></li>
<li class="chapter" data-level="9.8.5" data-path="week-9.html"><a href="week-9.html#less-than-five-or-more-than-five"><i class="fa fa-check"></i><b>9.8.5</b> Less than five or more than five?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="week-10-lab-test.html"><a href="week-10-lab-test.html"><i class="fa fa-check"></i><b>10</b> Week 10: Lab test</a></li>
<li class="chapter" data-level="11" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html"><i class="fa fa-check"></i><b>11</b> Sampling distributions</a><ul>
<li class="chapter" data-level="11.1" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#recap"><i class="fa fa-check"></i><b>11.1</b> Recap</a></li>
<li class="chapter" data-level="11.2" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#population-sample"><i class="fa fa-check"></i><b>11.2</b> Population vs sample</a></li>
<li class="chapter" data-level="11.3" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#parameter-statistic"><i class="fa fa-check"></i><b>11.3</b> Population parameter vs sample statistic</a></li>
<li class="chapter" data-level="11.4" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#sec-sampling-distributions"><i class="fa fa-check"></i><b>11.4</b> Sampling distributions</a></li>
<li class="chapter" data-level="11.5" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#standard-error"><i class="fa fa-check"></i><b>11.5</b> The standard error of a statistic</a></li>
<li class="chapter" data-level="11.6" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#sample-size-standard-error"><i class="fa fa-check"></i><b>11.6</b> The effect of sample size on the sampling distribution</a></li>
<li class="chapter" data-level="11.7" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#take-home-message"><i class="fa fa-check"></i><b>11.7</b> Take-home message</a></li>
<li class="chapter" data-level="11.8" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#lab-hollywood-movies"><i class="fa fa-check"></i><b>11.8</b> Lab: Hollywood movies</a></li>
<li class="chapter" data-level="11.9" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#summary"><i class="fa fa-check"></i><b>11.9</b> Summary</a></li>
<li class="chapter" data-level="11.10" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#glossary"><i class="fa fa-check"></i><b>11.10</b> Glossary</a></li>
<li class="chapter" data-level="11.11" data-path="chap-sampling-distributions.html"><a href="chap-sampling-distributions.html#references"><i class="fa fa-check"></i><b>11.11</b> References</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html"><i class="fa fa-check"></i><b>12</b> Bootstrapping and Confidence Intervals</a><ul>
<li class="chapter" data-level="12.1" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#recap-1"><i class="fa fa-check"></i><b>12.1</b> Recap</a></li>
<li class="chapter" data-level="12.2" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#from-sampling-to-resampling"><i class="fa fa-check"></i><b>12.2</b> From Sampling to Resampling</a></li>
<li class="chapter" data-level="12.3" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#getting-to-the-bootstrap-distribution"><i class="fa fa-check"></i><b>12.3</b> Getting to the bootstrap distribution</a></li>
<li class="chapter" data-level="12.4" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#more-generally"><i class="fa fa-check"></i><b>12.4</b> More generally…</a></li>
<li class="chapter" data-level="12.5" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#confidence-intervals"><i class="fa fa-check"></i><b>12.5</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="12.5.1" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#calculating-confidence-intervals-using-a-bootstrap-standard-error"><i class="fa fa-check"></i><b>12.5.1</b> Calculating confidence intervals using a bootstrap standard error</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#summary-1"><i class="fa fa-check"></i><b>12.6</b> Summary</a></li>
<li class="chapter" data-level="12.7" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#take-home-message-1"><i class="fa fa-check"></i><b>12.7</b> Take-home message</a></li>
<li class="chapter" data-level="12.8" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#lab"><i class="fa fa-check"></i><b>12.8</b> Lab</a><ul>
<li class="chapter" data-level="" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#exercise-1-hollywood-movies"><i class="fa fa-check"></i>Exercise 1: Hollywood Movies</a></li>
<li class="chapter" data-level="" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#exercise-2-nfl-players"><i class="fa fa-check"></i>Exercise 2: NFL Players</a></li>
</ul></li>
<li class="chapter" data-level="12.9" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#glossary-1"><i class="fa fa-check"></i><b>12.9</b> Glossary</a></li>
<li class="chapter" data-level="12.10" data-path="bootstrapping-and-confidence-intervals.html"><a href="bootstrapping-and-confidence-intervals.html#references-1"><i class="fa fa-check"></i><b>12.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html"><i class="fa fa-check"></i><b>13</b> Testing hypotheses</a><ul>
<li class="chapter" data-level="13.1" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#recap-2"><i class="fa fa-check"></i><b>13.1</b> Recap</a></li>
<li class="chapter" data-level="13.2" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#walkthrough"><i class="fa fa-check"></i><b>13.2</b> Walkthrough</a><ul>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#extrasensory-perception-esp"><i class="fa fa-check"></i>Extrasensory perception (ESP)</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#example-esp-results"><i class="fa fa-check"></i>Example 1: ESP experimental results</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#example-in-class"><i class="fa fa-check"></i>Example 2: In-class activity</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#the-random-chance-model"><i class="fa fa-check"></i>The random chance model</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#the-alternative-explanation"><i class="fa fa-check"></i>The alternative explanation</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#statistical-test"><i class="fa fa-check"></i>Statistical test</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#understanding-statistical-evidence"><i class="fa fa-check"></i>Understanding statistical evidence</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#statistical-hypotheses"><i class="fa fa-check"></i>Statistical hypotheses</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#statistical-significance"><i class="fa fa-check"></i>Statistical significance</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#null-distribution"><i class="fa fa-check"></i>Null distribution</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#p-value"><i class="fa fa-check"></i>P-value</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#making-a-formal-decision"><i class="fa fa-check"></i>Making a formal decision</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#summary-2"><i class="fa fa-check"></i><b>13.3</b> Summary</a></li>
<li class="chapter" data-level="13.4" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#lab-1"><i class="fa fa-check"></i><b>13.4</b> Lab</a><ul>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#required-packages"><i class="fa fa-check"></i>Required packages</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#importing-the-data"><i class="fa fa-check"></i>Importing the data</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#data-inspection"><i class="fa fa-check"></i>Data inspection</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#sample-average-and-standard-deviation"><i class="fa fa-check"></i>Sample average and standard deviation</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#null-and-alternative-hypothesis"><i class="fa fa-check"></i>Null and alternative hypothesis</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#bootstrap-distribution-and-null-distribution"><i class="fa fa-check"></i>Bootstrap distribution and null distribution</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#visualise-the-observed-statistic-on-the-null-distribution"><i class="fa fa-check"></i>Visualise the observed statistic on the null distribution</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#p-value-2"><i class="fa fa-check"></i>P-value</a></li>
<li class="chapter" data-level="" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#interpreting-the-p-value"><i class="fa fa-check"></i>Interpreting the p-value</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#glossary-2"><i class="fa fa-check"></i><b>13.5</b> Glossary</a></li>
<li class="chapter" data-level="13.6" data-path="chap-hyp-test.html"><a href="chap-hyp-test.html#references-2"><i class="fa fa-check"></i><b>13.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="chap-typeerror.html"><a href="chap-typeerror.html"><i class="fa fa-check"></i><b>14</b> Type I, Type II errors and Power</a><ul>
<li class="chapter" data-level="14.1" data-path="chap-typeerror.html"><a href="chap-typeerror.html#overview-of-last-week"><i class="fa fa-check"></i><b>14.1</b> Overview of last week</a></li>
<li class="chapter" data-level="14.2" data-path="chap-typeerror.html"><a href="chap-typeerror.html#walkthrough-1"><i class="fa fa-check"></i><b>14.2</b> Walkthrough</a><ul>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#example-1-coin-flip"><i class="fa fa-check"></i>Example 1: Coin flip</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#an-analogy-in-law"><i class="fa fa-check"></i>An analogy in law</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#two-different-types-of-errors"><i class="fa fa-check"></i>Two different types of errors</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#type-i-errors"><i class="fa fa-check"></i>Type I errors</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#type-ii-errors-and-power"><i class="fa fa-check"></i>Type II Errors and Power</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#example-2-a-biased-coin"><i class="fa fa-check"></i>Example 2: A biased coin</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#overlapping-distributions"><i class="fa fa-check"></i>Overlapping distributions</a></li>
<li class="chapter" data-level="" data-path="chap-typeerror.html"><a href="chap-typeerror.html#generalising-it"><i class="fa fa-check"></i>Generalising it</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="chap-typeerror.html"><a href="chap-typeerror.html#summary-3"><i class="fa fa-check"></i><b>14.3</b> Summary</a></li>
<li class="chapter" data-level="14.4" data-path="chap-typeerror.html"><a href="chap-typeerror.html#lab-2"><i class="fa fa-check"></i><b>14.4</b> Lab</a><ul>
<li class="chapter" data-level="14.4.1" data-path="chap-typeerror.html"><a href="chap-typeerror.html#exercise-1-rock-paper-scissors"><i class="fa fa-check"></i><b>14.4.1</b> Exercise 1: Rock Paper Scissors!</a></li>
<li class="chapter" data-level="14.4.2" data-path="chap-typeerror.html"><a href="chap-typeerror.html#exercise-2-calculating-power-for-a-different-coin."><i class="fa fa-check"></i><b>14.4.2</b> Exercise 2: Calculating power for a different coin.</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="chap-typeerror.html"><a href="chap-typeerror.html#extra-exercises"><i class="fa fa-check"></i><b>14.5</b> Extra Exercises</a><ul>
<li class="chapter" data-level="14.5.1" data-path="chap-typeerror.html"><a href="chap-typeerror.html#exercise-3-sample-size-number-of-flips-and-power"><i class="fa fa-check"></i><b>14.5.1</b> Exercise 3: Sample size (number of flips) and power</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="chap-typeerror.html"><a href="chap-typeerror.html#glossary-3"><i class="fa fa-check"></i><b>14.6</b> Glossary</a></li>
<li class="chapter" data-level="14.7" data-path="chap-typeerror.html"><a href="chap-typeerror.html#references-3"><i class="fa fa-check"></i><b>14.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="chap-normal.html"><a href="chap-normal.html"><i class="fa fa-check"></i><b>15</b> Normal distribution &amp; probability</a><ul>
<li class="chapter" data-level="15.1" data-path="chap-normal.html"><a href="chap-normal.html#recap-3"><i class="fa fa-check"></i><b>15.1</b> Recap</a></li>
<li class="chapter" data-level="15.2" data-path="chap-normal.html"><a href="chap-normal.html#walkthrough-2"><i class="fa fa-check"></i><b>15.2</b> Walkthrough</a><ul>
<li class="chapter" data-level="15.2.1" data-path="chap-normal.html"><a href="chap-normal.html#from-histograms-to-normal-curves"><i class="fa fa-check"></i><b>15.2.1</b> From histograms to normal curves</a></li>
<li class="chapter" data-level="15.2.2" data-path="chap-normal.html"><a href="chap-normal.html#sec-area-and-prob"><i class="fa fa-check"></i><b>15.2.2</b> The relation between area and probability</a></li>
<li class="chapter" data-level="15.2.3" data-path="chap-normal.html"><a href="chap-normal.html#probabilities-for-normally-distributed-random-variables"><i class="fa fa-check"></i><b>15.2.3</b> Probabilities for normally distributed random variables</a></li>
<li class="chapter" data-level="15.2.4" data-path="chap-normal.html"><a href="chap-normal.html#z-scores"><i class="fa fa-check"></i><b>15.2.4</b> Z-scores</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="chap-normal.html"><a href="chap-normal.html#summary-4"><i class="fa fa-check"></i><b>15.3</b> Summary</a></li>
<li class="chapter" data-level="15.4" data-path="chap-normal.html"><a href="chap-normal.html#lab-3"><i class="fa fa-check"></i><b>15.4</b> Lab</a></li>
<li class="chapter" data-level="15.5" data-path="chap-normal.html"><a href="chap-normal.html#glossary-4"><i class="fa fa-check"></i><b>15.5</b> Glossary</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html"><i class="fa fa-check"></i><b>16</b> One Sample Mean Test</a><ul>
<li class="chapter" data-level="16.1" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#recap-4"><i class="fa fa-check"></i><b>16.1</b> Recap</a></li>
<li class="chapter" data-level="16.2" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#where-we-are-now"><i class="fa fa-check"></i><b>16.2</b> Where we are now</a></li>
<li class="chapter" data-level="16.3" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#where-we-are-going"><i class="fa fa-check"></i><b>16.3</b> Where we are going</a></li>
<li class="chapter" data-level="16.4" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#one-sample-mean-test"><i class="fa fa-check"></i><b>16.4</b> One sample mean test</a><ul>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#example-questions"><i class="fa fa-check"></i>Example questions</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#hypotheses"><i class="fa fa-check"></i>Hypotheses</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#formula"><i class="fa fa-check"></i>Formula</a></li>
<li><a href="chap-one-mean-test.html#t-distributions"><span class="math inline">\(t\)</span>-distributions</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#critical-values-significance"><i class="fa fa-check"></i>Critical values &amp; significance</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#walkthrough---tempo-of-rock-music-on-spotify"><i class="fa fa-check"></i><b>16.5</b> Walkthrough - Tempo of rock music on Spotify</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#all-in-one-line-of-code"><i class="fa fa-check"></i>ALL IN ONE LINE OF CODE!</a></li>
<li class="chapter" data-level="" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#assumptions"><i class="fa fa-check"></i>Assumptions</a></li>
<li class="chapter" data-level="16.6" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#summary-5"><i class="fa fa-check"></i><b>16.6</b> Summary</a></li>
<li class="chapter" data-level="16.7" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#lab-4"><i class="fa fa-check"></i><b>16.7</b> Lab</a><ul>
<li class="chapter" data-level="16.7.1" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#pets-weights"><i class="fa fa-check"></i><b>16.7.1</b> Pets’ weights</a></li>
<li class="chapter" data-level="16.7.2" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#procrastination-scores"><i class="fa fa-check"></i><b>16.7.2</b> Procrastination scores</a></li>
<li class="chapter" data-level="16.7.3" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#cat-weights"><i class="fa fa-check"></i><b>16.7.3</b> Cat weights!</a></li>
<li class="chapter" data-level="16.7.4" data-path="chap-one-mean-test.html"><a href="chap-one-mean-test.html#glossary-5"><i class="fa fa-check"></i><b>16.7.4</b> Glossary</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="two-indep-samples.html"><a href="two-indep-samples.html"><i class="fa fa-check"></i><b>17</b> Comparing two means (independent samples)</a><ul>
<li class="chapter" data-level="17.1" data-path="two-indep-samples.html"><a href="two-indep-samples.html#recap-5"><i class="fa fa-check"></i><b>17.1</b> Recap</a></li>
<li class="chapter" data-level="17.2" data-path="two-indep-samples.html"><a href="two-indep-samples.html#key-terminology"><i class="fa fa-check"></i><b>17.2</b> Key terminology</a></li>
<li class="chapter" data-level="17.3" data-path="two-indep-samples.html"><a href="two-indep-samples.html#walkthrough-got-a-friend"><i class="fa fa-check"></i><b>17.3</b> Walkthrough: Got a friend?</a></li>
<li class="chapter" data-level="17.4" data-path="two-indep-samples.html"><a href="two-indep-samples.html#lab-does-name-increase-tips"><i class="fa fa-check"></i><b>17.4</b> Lab: Does name increase tips?</a></li>
<li class="chapter" data-level="17.5" data-path="two-indep-samples.html"><a href="two-indep-samples.html#glossary-6"><i class="fa fa-check"></i><b>17.5</b> Glossary</a></li>
<li class="chapter" data-level="17.6" data-path="two-indep-samples.html"><a href="two-indep-samples.html#w17-references"><i class="fa fa-check"></i><b>17.6</b> References</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html"><i class="fa fa-check"></i><b>18</b> Paired T-Test</a><ul>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#recap-6"><i class="fa fa-check"></i>Recap</a></li>
<li><a href="chap-paired-t-test.html#paired-t-test">Paired <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="18.1" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#walkthrough-3"><i class="fa fa-check"></i><b>18.1</b> Walkthrough</a><ul>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#change-in-score-on-the-ace-iii"><i class="fa fa-check"></i>Change in score on the ACE-III</a></li>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#data-organisation---reshaping"><i class="fa fa-check"></i>Data organisation - reshaping</a></li>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#effect-sizes"><i class="fa fa-check"></i>Effect sizes</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#summary-6"><i class="fa fa-check"></i><b>18.2</b> Summary</a></li>
<li class="chapter" data-level="18.3" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#lab-5"><i class="fa fa-check"></i><b>18.3</b> Lab</a><ul>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#age-differences-in-heterosexual-marriages"><i class="fa fa-check"></i>Age differences in heterosexual marriages</a></li>
<li class="chapter" data-level="" data-path="chap-paired-t-test.html"><a href="chap-paired-t-test.html#smoking-interventions"><i class="fa fa-check"></i>Smoking interventions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="chap-chi-square.html"><a href="chap-chi-square.html"><i class="fa fa-check"></i><b>19</b> Chi-square tests</a><ul>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#recap-7"><i class="fa fa-check"></i>Recap</a></li>
<li><a href="chap-chi-square.html#walkthrough-birthdays-of-the-week-the-chi-square-goodness-of-fit-test">Walkthrough: Birthdays of the week <br>The chi-square goodness-of-fit test</a></li>
<li><a href="chap-chi-square.html#lab-joking-for-a-tip-the-chi-square-test-of-independence">Lab: Joking for a tip <br>The chi-square test of independence</a></li>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#summary-7"><i class="fa fa-check"></i>Summary</a></li>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#glossary-7"><i class="fa fa-check"></i>Glossary</a></li>
<li class="chapter" data-level="" data-path="chap-chi-square.html"><a href="chap-chi-square.html#references-4"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analysis for Psychology in R (dapR1) - Labs</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chap-paired-t-test" class="section level1">
<h1><span class="header-section-number">Chapter 18</span> Paired T-Test</h1>
<div class="lo">
<h4 id="instructions-7" class="unnumbered">Instructions</h4>
<ul>
<li>In this two-hour lab we will go through worked examples in the first hour, and you will attempt to answer some questions in the second hour.</li>
<li>The Rmarkdown file for this week is <a href="https://uoe-psychology.github.io/uoe_psystats/dapr1/labsheets/week_18_practice.Rmd">here</a>.</li>
</ul>
<h4 id="learning-outcomes-7" class="unnumbered">Learning outcomes</h4>
<p><strong>LO1.</strong> Understand how to perform a paired-sample <span class="math inline">\(t\)</span>-test and interpret the results.</p>
<p><strong>LO2.</strong> Learn how to compute Cohen’s <span class="math inline">\(D\)</span> for different types of <span class="math inline">\(t\)</span>-test.</p>
<!-- #### Reading {-} -->
</div>
<div id="recap-6" class="section level2 unnumbered">
<h2>Recap</h2>
<p>Last week we extended our understanding of the <span class="math inline">\(t\)</span>-test to compare the means of two populations (or the means of two treatment groups, if doing a randomized experiment).<br />
We therefore now have the tools to answer questions of the form:</p>
<ol style="list-style-type: decimal">
<li><em>is</em> [population mean] <em>different from</em> [hypothesized value] <em>?</em> (one sample <span class="math inline">\(t\)</span>-test)<br />
</li>
<li><em>is</em> [population mean 1] <em>different from</em> [population mean 2] <em>?</em> (independent samples <span class="math inline">\(t\)</span>-test)<br />
<small><strong>Note</strong>: this is the same as “<em>is the mean of</em> [variable] <em>different between</em> [group-1] and [group-2] <em>?</em>”</small></li>
</ol>
<hr />
<div id="one-sample-t-test-week-16" class="section level4 unnumbered">
<h4>One sample <span class="math inline">\(t\)</span>-test (<a href="chap-one-mean-test.html#chap-one-mean-test">Week 16</a>)</h4>
<center>
<span class="math display">\[
t = \frac{\bar{x} - \mu_0}{SE(\bar{x})}, \qquad SE(\bar{x}) = \frac{s}{\sqrt{n}}
\]</span>
</center>
<p><strong>Validity conditions:</strong><br />
i. The data are continuous (not discrete).<br />
ii. The quantitative variable of interest is normally distributed in the population OR the sample size is large enough (as a convention, <span class="math inline">\(n \geq 20\)</span>) and the data are not strongly skewed.<br />
iii. The data are randomly sampled from a population.</p>
<hr />
</div>
<div id="two-independent-samples-t-test-with-equal-variances-week-17" class="section level4 unnumbered">
<h4>Two independent samples <span class="math inline">\(t\)</span>-test (with equal variances) (<a href="two-indep-samples.html#two-indep-samples">Week 17</a>)</h4>
<p><span class="math display">\[
t = \frac{\bar x_1 - \bar x_2}{SE(\bar x_1 - \bar x_2)}, \qquad SE(\bar{x}_1 - \bar{x}_2) = S_p \sqrt{\frac{1}{n_1} + \frac{1}{n_2}}, \qquad S_p = \sqrt\frac{(n_1 - 1)s_1^2 + (n_2 - 1)s_2^2}{n_1 + n_2 - 2}
\]</span>
<strong>Validity conditions:</strong><br />
i. The data are continuous (not discrete).<br />
ii. The quantitative variable of interest is normally distributed in both populations OR both sample sizes are large (as a convention, <span class="math inline">\(n_1 \geq 20\)</span> and <span class="math inline">\(n_2 \geq 20\)</span>) and the sample distributions should not be strongly skewed.<br />
iii. Independence of observations within and across groups.<br />
iv. Homogeneity of variance across groups.</p>
<p>We also learnt that when the response variable does <strong>not</strong> have equal variance across groups, we could use the Welch-Satterthwaite approximation to the degrees of freedom, and set <code>var.equal=FALSE</code> in the <code>t.test()</code> function.</p>
</div>
</div>
<div id="paired-t-test" class="section level2 unnumbered">
<h2>Paired <span class="math inline">\(t\)</span>-test</h2>
<p>The last <span class="math inline">\(t\)</span>-test we are going to learn about is the paired <span class="math inline">\(t\)</span>-test, or ‘dependent samples <span class="math inline">\(t\)</span>-test’.</p>
<p>Recall that last week we were concerned with evaluating the differences in means between two groups, and one of our assumptions in conducting our test was that the two groups were independent.</p>
<p>However, we are often interested in asking whether there is a difference in means between two sets of observations which are <em>paired</em>.</p>
<div id="paired-data" class="section level4 unnumbered">
<h4>Paired data</h4>
<p>We say that two sets of observations <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are <em>paired</em> when there is some pairing in the sets such that <span class="math inline">\(A_1\)</span> is linked to <span class="math inline">\(B_1\)</span> in the same way that <span class="math inline">\(A_2\)</span> is linked to <span class="math inline">\(B_2\)</span>, and so on.</p>
<div class="noteBox">
<div class="solution">
<p class="solution-begin">
► <strong>Pairs of time points:</strong><span id="sol-start-126" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-126&#39;, &#39;sol-start-126&#39;)"></span>
</p>
<div id="sol-body-126" class="solution-body" style="display: none;">
<p><strong>Same person, same variable, different times</strong></p>
<p>Do peoples’ scores differ between timepoint one and timepoint two? (Same participants and same test administered at multiple timepoints)</p>
<table>
<thead>
<tr class="header">
<th align="left">subject</th>
<th align="left">time_1</th>
<th align="left">time_2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">sub1</td>
<td align="left">25</td>
<td align="left">25</td>
</tr>
<tr class="even">
<td align="left">sub2</td>
<td align="left">18</td>
<td align="left">19</td>
</tr>
<tr class="odd">
<td align="left">…</td>
<td align="left">…</td>
<td align="left">…</td>
</tr>
</tbody>
</table>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► <strong>Pairs of variables:</strong><span id="sol-start-127" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-127&#39;, &#39;sol-start-127&#39;)"></span>
</p>
<div id="sol-body-127" class="solution-body" style="display: none;">
<p><strong>Same person, different variables</strong></p>
<p>Do peoples’ scores on maths tests differ from their scores on English tests? (Same people taking both tests and producing a score on maths and score on English)</p>
<table>
<thead>
<tr class="header">
<th align="left">subject</th>
<th align="left">maths_test</th>
<th align="left">english_test</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">sub1</td>
<td align="left">42</td>
<td align="left">38</td>
</tr>
<tr class="even">
<td align="left">sub2</td>
<td align="left">46</td>
<td align="left">40</td>
</tr>
<tr class="odd">
<td align="left">…</td>
<td align="left">…</td>
<td align="left">…</td>
</tr>
</tbody>
</table>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► <strong>Pairs of people:</strong><span id="sol-start-128" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-128&#39;, &#39;sol-start-128&#39;)"></span>
</p>
<div id="sol-body-128" class="solution-body" style="display: none;">
<p><strong>Same variable, different individual from a dyad (pair of people)</strong></p>
<p>Do employees work different amount of hours to their bosses? (Same variable (hours worked per day) collected from each person in pairs of people (i.e., each employee and their respective bosses)).</p>
<table>
<thead>
<tr class="header">
<th align="left">pair</th>
<th align="left">line_manager_hours</th>
<th align="left">employee_hours</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">pair1</td>
<td align="left">10</td>
<td align="left">9</td>
</tr>
<tr class="even">
<td align="left">pair2</td>
<td align="left">8</td>
<td align="left">9</td>
</tr>
<tr class="odd">
<td align="left">…</td>
<td align="left">…</td>
<td align="left">…</td>
</tr>
</tbody>
</table>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div class="red">
<h4 id="comparing-the-means-of-two-dependent-groups-paired-t-test" class="unnumbered">Comparing the means of two dependent groups (paired <span class="math inline">\(t\)</span>-test)</h4>
<p>Suppose you wish to determine whether the mean difference between two dependent sets of observations is zero, and if the difference is significant, you wish to quantify the magnitude of the difference using a confidence interval.</p>
<h4 id="test-of-significance-1" class="unnumbered">Test of significance</h4>
<p><strong>Null hypothesis:</strong><br />
The null hypothesis assumes that the true mean difference (<span class="math inline">\(\mu_d\)</span>) is equal to zero.</p>
<center>
<span class="math inline">\(H_0: \mu_d = 0\)</span>
</center>
<p><strong>Alternative hypothesis:</strong><br />
The alternative hypothesis assumes that <span class="math inline">\(\mu_d\)</span> is less than/greater than/not equal to zero.</p>
<center>
<span class="math display">\[
\begin{matrix}
i.   &amp; H_1: \mu_d &lt; 0 \\
ii.  &amp; H_1: \mu_d &gt; 0 \\
iii. &amp; H_1: \mu_d \neq 0
\end{matrix}
\]</span>
</center>
<strong>Test statistic:</strong>
<center>
<span class="math display">\[
t = \frac{\bar{d} - 0}{SE(\bar{d})}, \qquad SE(\bar{d})= \frac{s_d}{\sqrt{n}}
\]</span>
</center>
<p><strong><span class="math inline">\(p\)</span>-value:</strong></p>
<center>
<span class="math display">\[
\begin{matrix}
i.   &amp; \mathrm{Pr}(T_{df} \leq t) \\
ii.  &amp; \mathrm{Pr}(T_{df} \geq t) \\
iii. &amp; 2 \times \mathrm{Pr}(T_{df} \geq |t|)
\end{matrix}
\]</span>
</center>
<p>where <span class="math inline">\(T_{df}\)</span> denotes a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df\)</span> degrees of freedom.</p>
<h4 id="confidence-interval-for-mu_d---0" class="unnumbered">Confidence interval for <span class="math inline">\(\mu_d - 0\)</span></h4>
<center>
<span class="math display">\[
(\bar d) \pm t^*_{df} \times SE(\bar d)
\]</span>
</center>
<p>where <span class="math inline">\(t^*_{df}\)</span> denotes the critical value corresponding to a desired <span class="math inline">\(\alpha\)</span> level for a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(df\)</span> degrees of freedom.</p>
<h4 id="validity-conditions" class="unnumbered">Validity conditions</h4>
<p>These above procedures are considered valid if:</p>
<ol style="list-style-type: lower-roman">
<li>Data are matched pairs (design issue).<br />
</li>
<li>The <em>differences score</em> arise from independent random samples from the population (i.e., independence within group/time).<br />
</li>
<li>Either the difference scores are normally distributed in the population OR the sample size is large (as a convention, <span class="math inline">\(n \geq 20\)</span>) and the sample distribution should not be strongly skewed.</li>
</ol>
</div>
</div>
<div id="the-paired-t-test-is-just-the-one-sample-t-test-in-disguise" class="section level4 unnumbered">
<h4><strong>THE PAIRED <span class="math inline">\(t\)</span>-TEST IS JUST THE ONE SAMPLE <span class="math inline">\(t\)</span>-TEST IN DISGUISE!!</strong></h4>
<p>Steps for the one sample <span class="math inline">\(t\)</span>-test:</p>
<ul>
<li><ol style="list-style-type: decimal">
<li>calculate the sample mean (<span class="math inline">\(\bar x\)</span>)</li>
</ol></li>
<li><ol start="2" style="list-style-type: decimal">
<li>calculate the sample standard deviation (<span class="math inline">\(s_x\)</span>)<br />
</li>
</ol></li>
<li><ol start="3" style="list-style-type: decimal">
<li>calculate <span class="math inline">\(t\)</span></li>
</ol></li>
<li><ol start="4" style="list-style-type: decimal">
<li>calculate the probability of observing a <span class="math inline">\(t\)</span>-statistic at least as extreme assuming the null hypothesis (<span class="math inline">\(\mu_1 = \mu_0\)</span>) to be true.</li>
</ol></li>
</ul>
<hr />
<p>Steps for paired <span class="math inline">\(t\)</span>-test:</p>
<ul>
<li><ol style="list-style-type: decimal">
<li><strong>calculate the difference score for each pairs</strong><br />
</li>
</ol></li>
<li><ol start="2" style="list-style-type: decimal">
<li>calculate the sample mean <strong>difference score</strong> (<span class="math inline">\(\bar d\)</span>)<br />
</li>
</ol></li>
<li><ol start="3" style="list-style-type: decimal">
<li>calculate the sample standard deviation <strong>of difference scores</strong> (<span class="math inline">\(s_d\)</span>)<br />
</li>
</ol></li>
<li><ol start="4" style="list-style-type: decimal">
<li>calculate <span class="math inline">\(t\)</span><br />
</li>
</ol></li>
<li><ol start="5" style="list-style-type: decimal">
<li>calculate the probability of observing a <span class="math inline">\(t\)</span>-statistic at least as extreme assuming the null hypothesis (<span class="math inline">\(\mu_d = 0\)</span>) to be true.</li>
</ol></li>
</ul>
<p>The formula for the <span class="math inline">\(t\)</span>-statistic, assessing statistical significance, and constructing confidence intervals is identical to the one-sample <span class="math inline">\(t\)</span>-test.<br />
We have simply changed the notation: Instead of talking about a population mean <span class="math inline">\(\mu\)</span> which is estimated by a sample mean <span class="math inline">\(\bar x\)</span>, we are talking about a population mean difference <span class="math inline">\(\mu_d\)</span> estimated by the sample mean difference <span class="math inline">\(\bar d\)</span>. And we are testing whether <span class="math inline">\(\mu_d\)</span> is different from 0.</p>
</div>
</div>
<div id="walkthrough-3" class="section level2">
<h2><span class="header-section-number">18.1</span> Walkthrough</h2>
<div id="change-in-score-on-the-ace-iii" class="section level3 unnumbered">
<h3>Change in score on the ACE-III</h3>
<p>Addenbrooke’s Cognitive Examination-III (ACE-III) is a brief cognitive test that assesses five cognitive domains: attention, memory, verbal fluency, language and visuospatial abilities. The total score is 100 with higher scores indicating better cognitive functioning.<br />
A research project is examining changes in cognitive functioning with age, and administers the ACE-III to a set of participants at age 60, then again at age 70.</p>
<div class="question">
<p class="question-begin">
► Question A.1
</p>
<div class="question-body">
<p>How is the data from this study paired?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-129" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-129&#39;, &#39;sol-start-129&#39;)"></span>
</p>
<div id="sol-body-129" class="solution-body" style="display: none;">
<p>Same people, same variable, different time points.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question A.2
</p>
<div class="question-body">
<p>Write out the null and alternative hypotheses in words, and using the appropriate symbols.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-130" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-130&#39;, &#39;sol-start-130&#39;)"></span>
</p>
<div id="sol-body-130" class="solution-body" style="display: none;">
<p>As the study is asking about the change in cognitive functioning with age, we are not presupposing that scores increase or decrease.</p>
<p>Our null hypothesis is that the population mean difference in scores on the ACE-III between ages 60 and 70 is equal to zero (i.e., no change).</p>
<p><span class="math inline">\(H_0: \mu_d = 0\)</span></p>
<p>Our alternative hypothesis is that the population mean difference in scores on the ACE-III between ages 60 and 70 is not equal to zero (e.g., scores at age 70 are different from scores at age 60).</p>
<p><span class="math inline">\(H_1: \mu_d \neq 0\)</span></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question A.3
</p>
<div class="question-body">
<p>Read in the data, and make a new column of the difference in scores for each pair.</p>
<p>The data is available as a <strong>.csv</strong> from <a href="https://edin.ac/2Tz1cNH">https://edin.ac/2Tz1cNH</a>.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-131" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-131&#39;, &#39;sol-start-131&#39;)"></span>
</p>
<div id="sol-body-131" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb831"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb831-1" data-line-number="1">acedata &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://edin.ac/2Tz1cNH&quot;</span>)</a>
<a class="sourceLine" id="cb831-2" data-line-number="2"></a>
<a class="sourceLine" id="cb831-3" data-line-number="3">acedata &lt;-</a>
<a class="sourceLine" id="cb831-4" data-line-number="4"><span class="st">  </span>acedata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb831-5" data-line-number="5"><span class="st">    </span><span class="kw">mutate</span>(</a>
<a class="sourceLine" id="cb831-6" data-line-number="6">      <span class="dt">diff_score =</span> ace_<span class="dv">70</span> <span class="op">-</span><span class="st"> </span>ace_<span class="dv">60</span></a>
<a class="sourceLine" id="cb831-7" data-line-number="7">    )</a></code></pre></div>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question A.4
</p>
<div class="question-body">
<p>Perform a one-sample <span class="math inline">\(t\)</span>-test to see whether the mean difference score is equal to 0.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-132" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-132&#39;, &#39;sol-start-132&#39;)"></span>
</p>
<div id="sol-body-132" class="solution-body" style="display: none;">
<p>Calculate the <span class="math inline">\(\bar d\)</span>, <span class="math inline">\(s_d\)</span>, <span class="math inline">\(n\)</span>:</p>
<div class="sourceCode" id="cb832"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb832-1" data-line-number="1">aceterms &lt;-<span class="st"> </span>acedata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb832-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb832-3" data-line-number="3">    <span class="dt">dbar =</span> <span class="kw">mean</span>(diff_score),</a>
<a class="sourceLine" id="cb832-4" data-line-number="4">    <span class="dt">s_d =</span> <span class="kw">sd</span>(diff_score),</a>
<a class="sourceLine" id="cb832-5" data-line-number="5">    <span class="dt">n =</span> <span class="kw">n</span>()</a>
<a class="sourceLine" id="cb832-6" data-line-number="6">  )</a>
<a class="sourceLine" id="cb832-7" data-line-number="7">aceterms</a></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##    dbar   s_d     n
##   &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
## 1 -2.48  5.50    25</code></pre>
<p>Calculate <span class="math inline">\(t\)</span>:</p>
<div class="sourceCode" id="cb834"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb834-1" data-line-number="1">t_stat =<span class="st"> </span>(aceterms<span class="op">$</span>dbar <span class="op">-</span><span class="st"> </span><span class="dv">0</span>)<span class="op">/</span>(aceterms<span class="op">$</span>s_d <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(aceterms<span class="op">$</span>n))</a>
<a class="sourceLine" id="cb834-2" data-line-number="2">t_stat</a></code></pre></div>
<pre><code>## [1] -2.254173</code></pre>
<p>Calculate the p-value: <span class="math inline">\(2 \times \mathrm{Pr}(T_{df} \geq |t|)\)</span>:</p>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-526-1.png" width="70%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb836"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb836-1" data-line-number="1"><span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(<span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">pt</span>(<span class="kw">abs</span>(t_stat), <span class="dt">df =</span> <span class="dv">24</span>))</a></code></pre></div>
<pre><code>## [1] 0.03358854</code></pre>
Compute the confidence interval:
<center>
<span class="math display">\[
(\bar d) \pm t^*_{df} \times SE(\bar d)
\]</span>
</center>
<div class="sourceCode" id="cb838"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb838-1" data-line-number="1"><span class="co">#We know dbar</span></a>
<a class="sourceLine" id="cb838-2" data-line-number="2">aceterms<span class="op">$</span>dbar</a></code></pre></div>
<pre><code>## [1] -2.48</code></pre>
<div class="sourceCode" id="cb840"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb840-1" data-line-number="1"><span class="co">#And we can calculate the SE(dbar)</span></a>
<a class="sourceLine" id="cb840-2" data-line-number="2">aceterms<span class="op">$</span>s_d <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(aceterms<span class="op">$</span>n)</a></code></pre></div>
<pre><code>## [1] 1.100182</code></pre>
<p>We need to know the critical values of <span class="math inline">\(t\)</span>, for our desired <span class="math inline">\(\alpha\)</span>, with our <span class="math inline">\(df=24\)</span>.</p>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-529-1.png" width="70%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb842"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb842-1" data-line-number="1">crit_t =<span class="st"> </span><span class="kw">qt</span>(.<span class="dv">975</span>, <span class="dt">df =</span> <span class="dv">24</span>)</a>
<a class="sourceLine" id="cb842-2" data-line-number="2"></a>
<a class="sourceLine" id="cb842-3" data-line-number="3">crit_t</a></code></pre></div>
<pre><code>## [1] 2.063899</code></pre>
<div class="sourceCode" id="cb844"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb844-1" data-line-number="1"><span class="co"># lower interval</span></a>
<a class="sourceLine" id="cb844-2" data-line-number="2">aceterms<span class="op">$</span>dbar <span class="op">-</span><span class="st"> </span>( crit_t <span class="op">*</span><span class="st"> </span>(aceterms<span class="op">$</span>s_d <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(aceterms<span class="op">$</span>n)))</a></code></pre></div>
<pre><code>## [1] -4.750664</code></pre>
<div class="sourceCode" id="cb846"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb846-1" data-line-number="1"><span class="co"># upper interval</span></a>
<a class="sourceLine" id="cb846-2" data-line-number="2">aceterms<span class="op">$</span>dbar <span class="op">+</span><span class="st"> </span>( crit_t <span class="op">*</span><span class="st"> </span>(aceterms<span class="op">$</span>s_d <span class="op">/</span><span class="st"> </span><span class="kw">sqrt</span>(aceterms<span class="op">$</span>n)))</a></code></pre></div>
<pre><code>## [1] -0.2093364</code></pre>
<p>Or all using <code>t.test()</code> function:</p>
<div class="sourceCode" id="cb848"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb848-1" data-line-number="1"><span class="kw">t.test</span>(acedata<span class="op">$</span>diff_score, <span class="dt">mu =</span> <span class="dv">0</span>)</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  acedata$diff_score
## t = -2.2542, df = 24, p-value = 0.03359
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -4.7506636 -0.2093364
## sample estimates:
## mean of x 
##     -2.48</code></pre>
<p>Or, equivalently:</p>
<div class="sourceCode" id="cb850"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb850-1" data-line-number="1"><span class="kw">t.test</span>(acedata<span class="op">$</span>ace_<span class="dv">70</span>, acedata<span class="op">$</span>ace_<span class="dv">60</span>, <span class="dt">paired =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  acedata$ace_70 and acedata$ace_60
## t = -2.2542, df = 24, p-value = 0.03359
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -4.7506636 -0.2093364
## sample estimates:
## mean of the differences 
##                   -2.48</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question A.5
</p>
<div class="question-body">
<p>Provide a write-up of the results.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-133" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-133&#39;, &#39;sol-start-133&#39;)"></span>
</p>
<div id="sol-body-133" class="solution-body" style="display: none;">
<p>A paired-sample <span class="math inline">\(t\)</span>-test was conducted in order to determine if a statistically significant (<span class="math inline">\(\alpha\)</span> = .05) mean change in cognitive functioning (as measured using the total scores on the ACE-III) was present between the ages of 60 and 70, in a sample of 25 participants.
The mean difference in score on the ACE-III from age 60 to age 70 was -2.48 (95% CI=(-4.75 - -0.21). The difference was statistically significant (<span class="math inline">\(t\)</span>(24)= -2.25, <span class="math inline">\(p\)</span> &lt; . 05, two-tailed). Thus, we reject the null hypothesis of no difference.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="data-organisation---reshaping" class="section level3 unnumbered">
<h3>Data organisation - reshaping</h3>
<p>In the lecture, we talked briefly about data organisation, and how we might <strong>reshape</strong> data to make it go from this (<em>long</em> format):</p>
<table>
<thead>
<tr class="header">
<th align="left">participant</th>
<th align="left">age</th>
<th align="left">ace_score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">sub1</td>
<td align="left">ace_60</td>
<td align="left">93</td>
</tr>
<tr class="even">
<td align="left">sub1</td>
<td align="left">ace_70</td>
<td align="left">85</td>
</tr>
<tr class="odd">
<td align="left">sub2</td>
<td align="left">ace_60</td>
<td align="left">95</td>
</tr>
<tr class="even">
<td align="left">sub2</td>
<td align="left">ace_70</td>
<td align="left">92</td>
</tr>
<tr class="odd">
<td align="left">sub3</td>
<td align="left">ace_60</td>
<td align="left">93</td>
</tr>
<tr class="even">
<td align="left">sub3</td>
<td align="left">ace_70</td>
<td align="left">90</td>
</tr>
<tr class="odd">
<td align="left">…</td>
<td align="left">…</td>
<td align="left">…</td>
</tr>
</tbody>
</table>
<p>To this (<em>wide</em> format):</p>
<table>
<thead>
<tr class="header">
<th align="left">participant</th>
<th align="left">ace_60</th>
<th align="left">ace_70</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">sub1</td>
<td align="left">93</td>
<td align="left">85</td>
</tr>
<tr class="even">
<td align="left">sub2</td>
<td align="left">95</td>
<td align="left">92</td>
</tr>
<tr class="odd">
<td align="left">sub3</td>
<td align="left">93</td>
<td align="left">90</td>
</tr>
<tr class="even">
<td align="left">sub4</td>
<td align="left">93</td>
<td align="left">95</td>
</tr>
<tr class="odd">
<td align="left">sub5</td>
<td align="left">96</td>
<td align="left">88</td>
</tr>
<tr class="even">
<td align="left">sub6</td>
<td align="left">91</td>
<td align="left">85</td>
</tr>
<tr class="odd">
<td align="left">…</td>
<td align="left">…</td>
<td align="left">…</td>
</tr>
</tbody>
</table>
<div id="new-r-stuff-1" class="section level4 unnumbered">
<h4>New R stuff!</h4>
<p>We can reshape datasets using the functions <code>pivot_longer()</code> and <code>pivot_wider()</code>, which we mentioned briefly in the lecture.</p>
<p><img src="https://www.fromthebottomoftheheap.net/assets/img/posts/tidyr-longer-wider.gif" /></p>
<p>(source: <a href="https://www.fromthebottomoftheheap.net/2019/10/25/pivoting-tidily/">https://www.fromthebottomoftheheap.net/2019/10/25/pivoting-tidily/</a>)</p>
<p>Recall that our data was <em>wide</em>:</p>
<div class="sourceCode" id="cb852"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb852-1" data-line-number="1">acedata</a></code></pre></div>
<pre><code>## # A tibble: 25 x 4
##    participant ace_60 ace_70 diff_score
##    &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;
##  1 sub1            93     85         -8
##  2 sub2            95     92         -3
##  3 sub3            93     90         -3
##  4 sub4            93     95          2
##  5 sub5            96     88         -8
##  6 sub6            91     85         -6
##  7 sub7            94     92         -2
##  8 sub8            90     90          0
##  9 sub9            90     92          2
## 10 sub10           96     91         -5
## # … with 15 more rows</code></pre>
<p>We can make it long, by:</p>
<div class="sourceCode" id="cb854"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb854-1" data-line-number="1">acedata_long &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb854-2" data-line-number="2"><span class="st">  </span>acedata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb854-3" data-line-number="3"><span class="st">  </span><span class="kw">pivot_longer</span>(ace_<span class="dv">60</span><span class="op">:</span>ace_<span class="dv">70</span>, <span class="dt">names_to =</span> <span class="st">&quot;age&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;ace_score&quot;</span>)</a>
<a class="sourceLine" id="cb854-4" data-line-number="4"></a>
<a class="sourceLine" id="cb854-5" data-line-number="5">acedata_long</a></code></pre></div>
<pre><code>## # A tibble: 50 x 4
##    participant diff_score age    ace_score
##    &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;      &lt;dbl&gt;
##  1 sub1                -8 ace_60        93
##  2 sub1                -8 ace_70        85
##  3 sub2                -3 ace_60        95
##  4 sub2                -3 ace_70        92
##  5 sub3                -3 ace_60        93
##  6 sub3                -3 ace_70        90
##  7 sub4                 2 ace_60        93
##  8 sub4                 2 ace_70        95
##  9 sub5                -8 ace_60        96
## 10 sub5                -8 ace_70        88
## # … with 40 more rows</code></pre>
<p>This takes the columns from <code>ace_60</code> to <code>ace_70</code> (and anything in between), and puts the <em>names</em> (i.e. the variable names) into a column we call “age”, and puts the <em>values</em> into a column we call “ace_score”.</p>
<div class="noteBox">
<p>Note that we could now run the same paired <span class="math inline">\(t\)</span>-test using:</p>
<div class="sourceCode" id="cb856"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb856-1" data-line-number="1"><span class="kw">t.test</span>(acedata_long<span class="op">$</span>ace_score <span class="op">~</span><span class="st"> </span>acedata_long<span class="op">$</span>age, <span class="dt">paired =</span> T)</a></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  acedata_long$ace_score by acedata_long$age
## t = 2.2542, df = 24, p-value = 0.03359
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.2093364 4.7506636
## sample estimates:
## mean of the differences 
##                    2.48</code></pre>
</div>
<p>We can turn it back to wide using <code>pivot_wider()</code>:</p>
<div class="sourceCode" id="cb858"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb858-1" data-line-number="1">acedata_long <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb858-2" data-line-number="2"><span class="st">  </span><span class="kw">pivot_wider</span>(<span class="dt">names_from =</span> age, <span class="dt">values_from =</span> ace_score)</a></code></pre></div>
<pre><code>## # A tibble: 25 x 4
##    participant diff_score ace_60 ace_70
##    &lt;chr&gt;            &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1 sub1                -8     93     85
##  2 sub2                -3     95     92
##  3 sub3                -3     93     90
##  4 sub4                 2     93     95
##  5 sub5                -8     96     88
##  6 sub6                -6     91     85
##  7 sub7                -2     94     92
##  8 sub8                 0     90     90
##  9 sub9                 2     90     92
## 10 sub10               -5     96     91
## # … with 15 more rows</code></pre>
<div class="question">
<p class="question-begin">
► Question A.6
</p>
<div class="question-body">
<p>The code below produces a visualisation of the scores on the ACE-III at ages 60 and 70.</p>
<div class="sourceCode" id="cb860"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb860-1" data-line-number="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> ace_iii, <span class="kw">aes</span>(<span class="dt">x =</span> age, <span class="dt">y =</span> score)) <span class="op">+</span></a>
<a class="sourceLine" id="cb860-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<ol style="list-style-type: decimal">
<li>Based on what we found out when we conducted our <span class="math inline">\(t\)</span>-test, sketch what you think the code will produce.<br />
</li>
<li>What does the data <code>ace_iii</code> need to look like for this to work?</li>
</ol>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-134" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-134&#39;, &#39;sol-start-134&#39;)"></span>
</p>
<div id="sol-body-134" class="solution-body" style="display: none;">
<p>We can tell that for the plot to work, it must find all the scores in a column called <code>score</code>, and all the ages (e.g., 60 and 70) in a column called <code>age</code>. So the data will have to look something like this (i.e., in <em>long</em> format):</p>
<table>
<thead>
<tr class="header">
<th align="left">participant</th>
<th align="left">age</th>
<th align="left">score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">sub1</td>
<td align="left">60</td>
<td align="left">93</td>
</tr>
<tr class="even">
<td align="left">sub1</td>
<td align="left">70</td>
<td align="left">85</td>
</tr>
<tr class="odd">
<td align="left">sub2</td>
<td align="left">60</td>
<td align="left">95</td>
</tr>
<tr class="even">
<td align="left">sub2</td>
<td align="left">70</td>
<td align="left">92</td>
</tr>
<tr class="odd">
<td align="left">sub3</td>
<td align="left">60</td>
<td align="left">93</td>
</tr>
<tr class="even">
<td align="left">sub3</td>
<td align="left">70</td>
<td align="left">90</td>
</tr>
<tr class="odd">
<td align="left">…</td>
<td align="left">…</td>
<td align="left">…</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb861"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb861-1" data-line-number="1">ace_iii &lt;-<span class="st"> </span>acedata <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb861-2" data-line-number="2"><span class="st">  </span><span class="kw">pivot_longer</span>(ace_<span class="dv">60</span><span class="op">:</span>ace_<span class="dv">70</span>, <span class="dt">names_to =</span> <span class="st">&quot;age&quot;</span>, <span class="dt">values_to=</span><span class="st">&quot;score&quot;</span>)</a>
<a class="sourceLine" id="cb861-3" data-line-number="3"></a>
<a class="sourceLine" id="cb861-4" data-line-number="4"><span class="kw">ggplot</span>(<span class="dt">data =</span> ace_iii, <span class="kw">aes</span>(<span class="dt">x =</span> age, <span class="dt">y =</span> score)) <span class="op">+</span></a>
<a class="sourceLine" id="cb861-5" data-line-number="5"><span class="st">  </span><span class="kw">geom_boxplot</span>()</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-542-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
</div>
<div id="effect-sizes" class="section level3 unnumbered">
<h3>Effect sizes</h3>
<p>We also learned in the lecture about Cohen’s <span class="math inline">\(D\)</span> - a means of reporting a standardised magnitude of our difference.</p>
<div id="formula-for-cohens-d" class="section level5 unnumbered">
<h5>Formula for Cohen’s <span class="math inline">\(D\)</span>:</h5>
<table>
<thead>
<tr class="header">
<th align="right">Test</th>
<th align="right">Cohen’s <span class="math inline">\(D\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">One sample <span class="math inline">\(t\)</span>-test</td>
<td align="right"><span class="math inline">\(D = \frac{ \bar x - \mu_0}{s_x}\)</span></td>
</tr>
<tr class="even">
<td align="right">Independent samples <span class="math inline">\(t\)</span>-test</td>
<td align="right"><span class="math inline">\(D = \frac{ \bar{x}_1 - \bar{x}_2}{s_p}\)</span></td>
</tr>
<tr class="odd">
<td align="right">Paired <span class="math inline">\(t\)</span>-test</td>
<td align="right"><span class="math inline">\(D = \frac{ \bar{d} - 0}{s_d}\)</span></td>
</tr>
</tbody>
</table>
</div>
<div id="interpreting-cohens-d" class="section level5 unnumbered">
<h5>Interpreting Cohen’s <span class="math inline">\(D\)</span>:</h5>
<ul>
<li>~ 0.2 = small effect</li>
<li>~ 0.5 = moderate effect<br />
</li>
<li>~ 0.8 = large effect</li>
</ul>
<div class="question">
<p class="question-begin">
► Question A.7
</p>
<div class="question-body">
<p>Calculate the effect size for the mean difference in scores on the ACE-III from age 60 to 70.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-135" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-135&#39;, &#39;sol-start-135&#39;)"></span>
</p>
<div id="sol-body-135" class="solution-body" style="display: none;">
<p>We know all the terms for this already. In fact, we calculated them and saved them in an object called <code>aceterms</code>.</p>
<div class="sourceCode" id="cb862"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb862-1" data-line-number="1">aceterms</a></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##    dbar   s_d     n
##   &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;
## 1 -2.48  5.50    25</code></pre>
<p>So we can calculate our effect size:</p>
<div class="sourceCode" id="cb864"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb864-1" data-line-number="1">(aceterms<span class="op">$</span>dbar <span class="op">-</span><span class="st"> </span><span class="dv">0</span>) <span class="op">/</span><span class="st"> </span>aceterms<span class="op">$</span>s_d</a></code></pre></div>
<pre><code>## [1] -0.4508346</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
</div>
</div>
<div id="summary-6" class="section level2">
<h2><span class="header-section-number">18.2</span> Summary</h2>
<ul>
<li>The paired <span class="math inline">\(t\)</span>-test is the same as the one sample <span class="math inline">\(t\)</span>-test.</li>
<li>Instead of assessing the distance from <span class="math inline">\(\bar x - \mu_0\)</span>, we are investigating the distance of <span class="math inline">\(\bar d - 0\)</span>.</li>
<li>We can conduct a paired <span class="math inline">\(t\)</span>-test in R by either:
<ul>
<li>calculating the difference scores and using <code>t.test(difference_scores, mu = 0)</code></li>
<li>running <code>t.test(score1, score2, paired = TRUE)</code></li>
</ul></li>
<li>We can compute Cohen’s <span class="math inline">\(D\)</span> for standardised size of our effect.<br />
</li>
<li>We can <em>reshape</em> our data between <em>long</em> to <em>wide</em>. This helps with plotting, and also means we can conduct our test using <code>t.test(score ~ group, paired = TRUE)</code>.</li>
</ul>
</div>
<div id="lab-5" class="section level2">
<h2><span class="header-section-number">18.3</span> Lab</h2>
<p><em>Please attempt the questions <strong>before</strong> looking at the solutions. Copy &amp; pasting the solutions will not help with learning!</em></p>
<div id="age-differences-in-heterosexual-marriages" class="section level3 unnumbered">
<h3>Age differences in heterosexual marriages</h3>
<div class="red">
<h5 id="research-q" class="unnumbered">Research Q</h5>
<p>Is there an age difference in heterosexual married couples? (and in what direction?)</p>
<p>Data on the ages of both brides and grooms at point of marriage is available at <a href="https://edin.ac/2TBoZMY">https://edin.ac/2TBoZMY</a>.<br />
You can read it in using the code below:</p>
<div class="sourceCode" id="cb866"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb866-1" data-line-number="1">marriages&lt;-<span class="kw">read_csv</span>(<span class="st">&quot;https://edin.ac/2TBoZMY&quot;</span>)</a></code></pre></div>
</div>
<div class="question">
<p class="question-begin">
► Question B.1
</p>
<div class="question-body">
<p>Add new column which is the husband’s age minus the wife’s age.<br />
As we plan on conducting a test on these differences, what assumptions are we making about them, and how can we check whether those assumptions hold?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-136" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-136&#39;, &#39;sol-start-136&#39;)"></span>
</p>
<div id="sol-body-136" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb867"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb867-1" data-line-number="1">marriages &lt;-<span class="st"> </span>marriages <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb867-2" data-line-number="2"><span class="st">  </span><span class="kw">mutate</span>(</a>
<a class="sourceLine" id="cb867-3" data-line-number="3">    <span class="dt">agediff =</span> Husband <span class="op">-</span><span class="st"> </span>Wife</a>
<a class="sourceLine" id="cb867-4" data-line-number="4">  )</a></code></pre></div>
<p>Remember, as this is just a one sample <span class="math inline">\(t\)</span>-test in disguise, we are assuming that the differences come from a normally distribution. Our sample size is quite large (<span class="math inline">\(n = 105\)</span>) so it is not essential to test for normality (using <code>shapiro.test()</code>), but we should always plot the data first, to check for thing like skew.</p>
<div class="sourceCode" id="cb868"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb868-1" data-line-number="1"><span class="kw">ggplot</span>(marriages, <span class="kw">aes</span>(<span class="dt">x=</span>agediff)) <span class="op">+</span></a>
<a class="sourceLine" id="cb868-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_density</span>()</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-547-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question B.2
</p>
<div class="question-body">
<p>Think carefully..
If we are about to conduct a <span class="math inline">\(t\)</span>-test on the difference scores we just calculated, what will the results mean?<br />
If we get a <strong>positive</strong> <span class="math inline">\(t\)</span>-statistic (<span class="math inline">\(t &gt; 0\)</span>), what direction is the difference? Who will it mean tends to be older than whom?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-137" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-137&#39;, &#39;sol-start-137&#39;)"></span>
</p>
<div id="sol-body-137" class="solution-body" style="display: none;">
<p>Because we calculated the husband’s age minus wife’s age, a positive <span class="math inline">\(t\)</span>-statistic will indicates that this value is &gt; 0 (meaning that in heterosexual marriages, husbands tend be the older of the two).</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question B.3
</p>
<div class="question-body">
<ol style="list-style-type: decimal">
<li>Conduct a one sample <span class="math inline">\(t\)</span>-test that the age differences are not equal to 0.<br />
</li>
<li>Using the <code>paired = TRUE</code> argument of <code>t.test()</code>, conduct the same test on the ages themselves (rather than the differences).</li>
<li>Check that the results from 1 and 2 match.</li>
</ol>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-138" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-138&#39;, &#39;sol-start-138&#39;)"></span>
</p>
<div id="sol-body-138" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb869"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb869-1" data-line-number="1"><span class="kw">t.test</span>(marriages<span class="op">$</span>agediff, <span class="dt">mu =</span> <span class="dv">0</span>)</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  marriages$agediff
## t = 5.596, df = 101, p-value = 1.888e-07
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  1.531495 3.213603
## sample estimates:
## mean of x 
##  2.372549</code></pre>
<div class="sourceCode" id="cb871"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb871-1" data-line-number="1"><span class="kw">t.test</span>(marriages<span class="op">$</span>Husband, marriages<span class="op">$</span>Wife, <span class="dt">paired =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  marriages$Husband and marriages$Wife
## t = 5.596, df = 101, p-value = 1.888e-07
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  1.531495 3.213603
## sample estimates:
## mean of the differences 
##                2.372549</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question B.4
</p>
<div class="question-body">
<p>Calculate Cohen’s <span class="math inline">\(D\)</span>.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-139" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-139&#39;, &#39;sol-start-139&#39;)"></span>
</p>
<div id="sol-body-139" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb873"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb873-1" data-line-number="1">marriages <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb873-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb873-3" data-line-number="3">    <span class="dt">dbar =</span> <span class="kw">mean</span>(agediff),</a>
<a class="sourceLine" id="cb873-4" data-line-number="4">    <span class="dt">s_d =</span> <span class="kw">sd</span>(agediff)</a>
<a class="sourceLine" id="cb873-5" data-line-number="5">  )</a></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##    dbar   s_d
##   &lt;dbl&gt; &lt;dbl&gt;
## 1  2.37  4.28</code></pre>
<div class="sourceCode" id="cb875"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb875-1" data-line-number="1"><span class="fl">2.37</span> <span class="op">/</span><span class="st"> </span><span class="fl">4.28</span></a></code></pre></div>
<pre><code>## [1] 0.5537383</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="smoking-interventions" class="section level3 unnumbered">
<h3>Smoking interventions</h3>
<div class="red">
<h5 id="research-q-1" class="unnumbered">Research Q</h5>
<p>A researcher has developed a cognitive behavioural therapy (CBT) based smartphone app, and is testing how effective it is in helping people to stop smoking.<br />
They recruit 60 participants who are trying to quit smoking, and over a week record the average number of cigarettes smoked per day for each participant.
Thirty participants are given the app, and asked that every time they feel like smoking they open the app on their phone and complete one five-minute task.
All 60 participants are followed up one month later, and the average number of cigarettes smoked per day (over a week) is recorded.</p>
<ol style="list-style-type: decimal">
<li>At point of recruitment, did the 60 participants smoke more or less than 20 cigarettes per day?<br />
</li>
<li>Calculate the average number of cigarettes smoked per day at both time-points for each group.</li>
<li>Did the average number of cigarettes smoked per day differ between the groups at the initial recruitment?<br />
</li>
<li>Did the group given the app change their smoking habits from the immediate to one month follow up? If so, was it a big change? (e.g, calculate the effect size).</li>
</ol>
</div>
<p>The data (<strong>.csv</strong>) is available at <a href="https://edin.ac/2vRr3r9">https://edin.ac/2vRr3r9</a>.</p>
<div class="question">
<p class="question-begin">
► Question C
</p>
<div class="question-body">
<p>Answer research questions 1 to 4.</p>
<p>This requires various things you have learned over the entire course, to do with data manipulation (grouping, summarising, filtering, etc.), as well as deciding on and conducting appropriate tests.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► C1<span id="sol-start-140" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-140&#39;, &#39;sol-start-140&#39;)"></span>
</p>
<div id="sol-body-140" class="solution-body" style="display: none;">
<ol style="list-style-type: decimal">
<li>At point of recruitment, did the 60 participants smoke more or less than 20 cigarettes per day?</li>
</ol>
<p>This is asking whether the mean number of cigarettes per day is different to 20. So we are asking whether a mean is different from an hypothesized number - this is a one sample <span class="math inline">\(t\)</span>-test!</p>
<p>First, lets check our assumptions. Our <span class="math inline">\(n \geq 20\)</span>, but let’s check normality anyway:</p>
<div class="sourceCode" id="cb877"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb877-1" data-line-number="1"><span class="kw">shapiro.test</span>(cbtsmoke<span class="op">$</span>cigs_pday)</a></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  cbtsmoke$cigs_pday
## W = 0.97845, p-value = 0.3666</code></pre>
<p>At a significance level of 0.05, the <span class="math inline">\(p\)</span>-value = 0.37 means that we fail to reject the null hypothesis that the data is drawn from a normally distributed population.<br />
We can now perform our <span class="math inline">\(t\)</span>-test:</p>
<div class="sourceCode" id="cb879"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb879-1" data-line-number="1"><span class="kw">t.test</span>(cbtsmoke<span class="op">$</span>cigs_pday, <span class="dt">mu =</span> <span class="dv">20</span>)</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  cbtsmoke$cigs_pday
## t = -11.095, df = 59, p-value = 4.544e-16
## alternative hypothesis: true mean is not equal to 20
## 95 percent confidence interval:
##  13.86217 15.73783
## sample estimates:
## mean of x 
##      14.8</code></pre>
<p>At a significance level of 0.05, we reject the null hypothesis that the average number of cigarettes smoked per day at point-of-recruitment is equal to 20 (<span class="math inline">\(t(39)=-11.1, p&lt;.05\)</span> two-sided).</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► C2<span id="sol-start-141" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-141&#39;, &#39;sol-start-141&#39;)"></span>
</p>
<div id="sol-body-141" class="solution-body" style="display: none;">
<ol start="2" style="list-style-type: decimal">
<li>Calculate the average number of cigarettes smoked per day at both time-points for each group.</li>
</ol>
<div class="sourceCode" id="cb881"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb881-1" data-line-number="1">cbtsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb881-2" data-line-number="2"><span class="st">  </span><span class="kw">group_by</span>(app_group) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb881-3" data-line-number="3"><span class="st">  </span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb881-4" data-line-number="4">    <span class="dt">initial =</span> <span class="kw">mean</span>(cigs_pday),</a>
<a class="sourceLine" id="cb881-5" data-line-number="5">    <span class="dt">followup =</span> <span class="kw">mean</span>(cigs_pday_1month)</a>
<a class="sourceLine" id="cb881-6" data-line-number="6">  )</a></code></pre></div>
<pre><code>## # A tibble: 2 x 3
##   app_group initial followup
##   &lt;fct&gt;       &lt;dbl&gt;    &lt;dbl&gt;
## 1 no           14.8     12.7
## 2 yes          14.8      9.7</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► C3<span id="sol-start-142" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-142&#39;, &#39;sol-start-142&#39;)"></span>
</p>
<div id="sol-body-142" class="solution-body" style="display: none;">
<ol start="3" style="list-style-type: decimal">
<li>Did the average number of cigarettes smoked per day differ between the groups at the initial recruitment?</li>
</ol>
<p>The two sets of observations (from the different groups) are independent, so we are going to conduct an independent samples <span class="math inline">\(t\)</span>-test.</p>
<p>First, we need to check the assumption of equal variances between groups:</p>
<div class="sourceCode" id="cb883"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb883-1" data-line-number="1"><span class="kw">var.test</span>(cbtsmoke<span class="op">$</span>cigs_pday <span class="op">~</span><span class="st"> </span>cbtsmoke<span class="op">$</span>app_group)</a></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  cbtsmoke$cigs_pday by cbtsmoke$app_group
## F = 0.72721, num df = 29, denom df = 29, p-value = 0.3961
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.3461274 1.5278697
## sample estimates:
## ratio of variances 
##          0.7272121</code></pre>
<p>At a significance level of 0.05, the <span class="math inline">\(p\)</span>-value = 0.4 leads us to not rejecting the null hypothesis of equal variances across the two populations.</p>
<p>Because <span class="math inline">\(n \geq 20\)</span>, we don’t <em>need</em> to check for normality, but it is important to look for the skew, especially when our <span class="math inline">\(n\)</span> is not <em>that</em> much bigger than 20. The plot below suggest that skew is not a problem</p>
<div class="sourceCode" id="cb885"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb885-1" data-line-number="1"><span class="kw">ggplot</span>(cbtsmoke, <span class="kw">aes</span>(<span class="dt">x =</span> cigs_pday, <span class="dt">col =</span> app_group)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb885-2" data-line-number="2"><span class="st">  </span><span class="kw">geom_density</span>()</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-555-1.png" width="70%" style="display: block; margin: auto;" /></p>
<p>We can now perform our <span class="math inline">\(t\)</span>-test:</p>
<div class="sourceCode" id="cb886"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb886-1" data-line-number="1"><span class="kw">t.test</span>(cbtsmoke<span class="op">$</span>cigs_pday <span class="op">~</span><span class="st"> </span>cbtsmoke<span class="op">$</span>app_group, <span class="dt">var.equal =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## 
##  Two Sample t-test
## 
## data:  cbtsmoke$cigs_pday by cbtsmoke$app_group
## t = -0.070519, df = 58, p-value = 0.944
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.959022  1.825689
## sample estimates:
##  mean in group no mean in group yes 
##          14.76667          14.83333</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► C4<span id="sol-start-143" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-143&#39;, &#39;sol-start-143&#39;)"></span>
</p>
<div id="sol-body-143" class="solution-body" style="display: none;">
<ol start="4" style="list-style-type: decimal">
<li>Did the group given the app change their smoking habits from the immediate to one month follow up? If so, was it a big change? (e.g, calculate the effect size).</li>
</ol>
<p>We will need to use only the data from the group who was given the app:</p>
<div class="sourceCode" id="cb888"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb888-1" data-line-number="1">appgroupsmoke &lt;-<span class="st"> </span>cbtsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb888-2" data-line-number="2"><span class="st">  </span><span class="kw">filter</span>(app_group <span class="op">==</span><span class="st"> &quot;yes&quot;</span>)</a></code></pre></div>
<p>We can then perform a paired <span class="math inline">\(t\)</span>-test:</p>
<div class="sourceCode" id="cb889"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb889-1" data-line-number="1"><span class="kw">t.test</span>(appgroupsmoke<span class="op">$</span>cigs_pday_1month, appgroupsmoke<span class="op">$</span>cigs_pday, <span class="dt">paired =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  appgroupsmoke$cigs_pday_1month and appgroupsmoke$cigs_pday
## t = -5.0883, df = 29, p-value = 1.985e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -7.196663 -3.070004
## sample estimates:
## mean of the differences 
##               -5.133333</code></pre>
<p>Or, we could calculate the difference scores…</p>
<div class="sourceCode" id="cb891"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb891-1" data-line-number="1">appgroupsmoke &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb891-2" data-line-number="2"><span class="st">  </span>appgroupsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb891-3" data-line-number="3"><span class="st">    </span><span class="kw">mutate</span>(</a>
<a class="sourceLine" id="cb891-4" data-line-number="4">      <span class="dt">change =</span> cigs_pday_1month <span class="op">-</span><span class="st"> </span>cigs_pday</a>
<a class="sourceLine" id="cb891-5" data-line-number="5">    )</a></code></pre></div>
<p>and run the same test using:</p>
<div class="sourceCode" id="cb892"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb892-1" data-line-number="1"><span class="kw">t.test</span>(appgroupsmoke<span class="op">$</span>change, <span class="dt">mu =</span> <span class="dv">0</span>)</a></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  appgroupsmoke$change
## t = -5.0883, df = 29, p-value = 1.985e-05
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  -7.196663 -3.070004
## sample estimates:
## mean of x 
## -5.133333</code></pre>
<p>To calculate Cohen’s <span class="math inline">\(D\)</span>, we use the mean difference (<span class="math inline">\(\bar d\)</span>) divided by the standard deviation of the differences (<span class="math inline">\(s_d\)</span>):</p>
<div class="sourceCode" id="cb894"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb894-1" data-line-number="1">appgroupsmoke <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb894-2" data-line-number="2"><span class="st">  </span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb894-3" data-line-number="3">    <span class="dt">dbar =</span> <span class="kw">mean</span>(change),</a>
<a class="sourceLine" id="cb894-4" data-line-number="4">    <span class="dt">s_d =</span> <span class="kw">sd</span>(change)</a>
<a class="sourceLine" id="cb894-5" data-line-number="5">  )</a></code></pre></div>
<pre><code>##        dbar      s_d
## 1 -5.133333 5.525698</code></pre>
<div class="sourceCode" id="cb896"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb896-1" data-line-number="1"><span class="kw">abs</span>(<span class="op">-</span><span class="fl">5.13</span>) <span class="op">/</span><span class="st"> </span><span class="fl">5.53</span></a></code></pre></div>
<pre><code>## [1] 0.9276673</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>

<div class="sourceCode" id="cb898"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb898-1" data-line-number="1">knitr<span class="op">::</span>opts_chunk<span class="op">$</span><span class="kw">set</span>(<span class="dt">fig.align=</span><span class="st">&#39;center&#39;</span>, <span class="dt">message=</span><span class="ot">FALSE</span>, <span class="dt">out.width =</span> <span class="st">&#39;80%&#39;</span>)</a></code></pre></div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="two-indep-samples.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="chap-chi-square.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
