<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Other random effects structures | Multivariate Statistics and Methodology using R</title>
  <meta name="description" content="This is the page that contains the course labs materials" />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Other random effects structures | Multivariate Statistics and Methodology using R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the page that contains the course labs materials" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Other random effects structures | Multivariate Statistics and Methodology using R" />
  
  <meta name="twitter:description" content="This is the page that contains the course labs materials" />
  

<meta name="author" content="Department of Psychology, University of Edinburgh" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="mlr-for-longitudinal-data-growth-curve-analysis.html"/>
<link rel="next" href="recap-individual-differences.html"/>
<script src="libs/jquery/jquery.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />









<script>
  $(document).ready(function() {
    $head = $('#header');
    $head.prepend('<img style="padding-right:25%; margin-bottom:10px;" src="https://www.ed.ac.uk/sites/all/themes/uoe/assets/logo.png" width="770px" align="left">')
  });
</script>

<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}
}
</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MSMR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview of the Course</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#the-team"><i class="fa fa-check"></i>The team</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-stuff"><i class="fa fa-check"></i>R stuff</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-cheatsheets"><i class="fa fa-check"></i>R Cheatsheets</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-community"><i class="fa fa-check"></i>R Community</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html"><i class="fa fa-check"></i><b>1</b> Tidyverse &amp; Markdown</a><ul>
<li class="chapter" data-level="" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#packages"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#lecture-slides"><i class="fa fa-check"></i>Lecture slides</a></li>
<li class="chapter" data-level="" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#background-reading"><i class="fa fa-check"></i>Background &amp; Reading</a></li>
<li class="chapter" data-level="1.1" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#data-visualization-with-ggplot"><i class="fa fa-check"></i><b>1.1</b> Data Visualization with <code>ggplot</code></a><ul>
<li class="chapter" data-level="1.1.1" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#geoms"><i class="fa fa-check"></i><b>1.1.1</b> Geoms</a></li>
<li class="chapter" data-level="1.1.2" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#recreating-a-plot"><i class="fa fa-check"></i><b>1.1.2</b> Recreating a plot</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#data-management-with-the-tidyverse"><i class="fa fa-check"></i><b>1.2</b> Data management with the Tidyverse</a><ul>
<li class="chapter" data-level="1.2.1" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#piping"><i class="fa fa-check"></i><b>1.2.1</b> Piping!</a></li>
<li class="chapter" data-level="1.2.2" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#grouping-summarising-filtering-mutating-and-selecting"><i class="fa fa-check"></i><b>1.2.2</b> Grouping, summarising, filtering, mutating and selecting</a></li>
<li class="chapter" data-level="1.2.3" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#reshaping"><i class="fa fa-check"></i><b>1.2.3</b> Reshaping</a></li>
<li class="chapter" data-level="" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#less-guidance"><i class="fa fa-check"></i>Less guidance</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#reproducible-research-with-rmarkdown"><i class="fa fa-check"></i><b>1.3</b> Reproducible research with RMarkdown</a><ul>
<li class="chapter" data-level="1.3.1" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#convert-a-script-into-a-r-notebook"><i class="fa fa-check"></i><b>1.3.1</b> Convert a script into a R Notebook</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html"><i class="fa fa-check"></i><b>2</b> Basic Multilevel Regression</a><ul>
<li class="chapter" data-level="" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#packages-1"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#lecture-slides-1"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#background-reading-1"><i class="fa fa-check"></i>Background &amp; Reading</a></li>
<li class="chapter" data-level="2.1" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#lme4"><i class="fa fa-check"></i><b>2.1</b> LME4</a></li>
<li class="chapter" data-level="2.2" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#introduction-to-mlr"><i class="fa fa-check"></i><b>2.2</b> Introduction to MLR</a><ul>
<li class="chapter" data-level="2.2.1" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#exercise-1"><i class="fa fa-check"></i><b>2.2.1</b> Exercise 1</a></li>
<li class="chapter" data-level="2.2.2" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#exercise-2"><i class="fa fa-check"></i><b>2.2.2</b> Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#logistic-mlr"><i class="fa fa-check"></i><b>2.3</b> Logistic MLR</a><ul>
<li class="chapter" data-level="2.3.1" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#exercise-3"><i class="fa fa-check"></i><b>2.3.1</b> Exercise 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html"><i class="fa fa-check"></i><b>3</b> MLR for longitudinal data (growth curve analysis)</a><ul>
<li class="chapter" data-level="" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#packages-2"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#lecture-slides-2"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#background-reading-2"><i class="fa fa-check"></i>Background &amp; Reading</a></li>
<li class="chapter" data-level="3.1" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#introduction"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#exercise-1-1"><i class="fa fa-check"></i><b>3.2</b> Exercise 1</a><ul>
<li class="chapter" data-level="" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#interpret-the-results-of-your-full-model"><i class="fa fa-check"></i>Interpret the results of your full model</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#exercise-2-writing-up-and-logistic-gca"><i class="fa fa-check"></i><b>3.3</b> Exercise 2: Writing up, and Logistic GCA</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html"><i class="fa fa-check"></i><b>4</b> Other random effects structures</a><ul>
<li class="chapter" data-level="" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#packages-3"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#lecture-slides-3"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#background-reading-3"><i class="fa fa-check"></i>Background &amp; Reading</a></li>
<li class="chapter" data-level="4.1" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#crossed-random-effects"><i class="fa fa-check"></i><b>4.1</b> Crossed random effects</a><ul>
<li class="chapter" data-level="4.1.1" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#exercise-1-2"><i class="fa fa-check"></i><b>4.1.1</b> Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#dealing-with-issue-of-non-convergence-and-singular-fits"><i class="fa fa-check"></i><b>4.2</b> Dealing with issue of non-convergence and singular fits</a><ul>
<li class="chapter" data-level="4.2.1" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#exercise-2-1"><i class="fa fa-check"></i><b>4.2.1</b> Exercise 2</a></li>
<li class="chapter" data-level="4.2.2" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#exercise-3-1"><i class="fa fa-check"></i><b>4.2.2</b> Exercise 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html"><i class="fa fa-check"></i><b>5</b> Recap &amp; Individual differences</a><ul>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#packages-4"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#lecture-slides-4"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#mixed-model-recap"><i class="fa fa-check"></i>Mixed model recap</a><ul>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#simple-regression"><i class="fa fa-check"></i>Simple regression</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#clustered-multi-level-data-structures"><i class="fa fa-check"></i>Clustered (multi-level) data structures</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#random-intercept-models"><i class="fa fa-check"></i>Random intercept models</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#random-slopes"><i class="fa fa-check"></i>Random slopes</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#fixef-ranef-and-coef"><i class="fa fa-check"></i>Fixef(), Ranef, and Coef</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#more-levels-nested-and-crossed-random-effects"><i class="fa fa-check"></i>More levels: Nested and Crossed random-effects</a></li>
</ul></li>
<li class="chapter" data-level="5.1" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#the-lab"><i class="fa fa-check"></i><b>5.1</b> THE LAB</a><ul>
<li class="chapter" data-level="5.1.1" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#exercise-1-3"><i class="fa fa-check"></i><b>5.1.1</b> Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#exercise-2-2"><i class="fa fa-check"></i><b>5.2</b> Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="break-week.html"><a href="break-week.html"><i class="fa fa-check"></i><b>6</b> <font color="red">Break Week</font></a></li>
<li class="chapter" data-level="7" data-path="efa-and-pca.html"><a href="efa-and-pca.html"><i class="fa fa-check"></i><b>7</b> EFA and PCA</a><ul>
<li class="chapter" data-level="" data-path="efa-and-pca.html"><a href="efa-and-pca.html#packages-5"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="efa-and-pca.html"><a href="efa-and-pca.html#lecture-slides-5"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="7.1" data-path="efa-and-pca.html"><a href="efa-and-pca.html#todays-exercises"><i class="fa fa-check"></i><b>7.1</b> Today’s Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html"><i class="fa fa-check"></i><b>8</b> Confirmatory Factor Analysis (CFA)</a><ul>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#packages-6"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#lecture-slides-6"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#quick-recap"><i class="fa fa-check"></i>Quick recap</a></li>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#data"><i class="fa fa-check"></i>Data</a></li>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#one-factor-model"><i class="fa fa-check"></i>One factor model</a></li>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#two-factor-model"><i class="fa fa-check"></i>Two factor model</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="path-analysis.html"><a href="path-analysis.html"><i class="fa fa-check"></i><b>9</b> Path Analysis</a><ul>
<li class="chapter" data-level="" data-path="path-analysis.html"><a href="path-analysis.html#packages-7"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="path-analysis.html"><a href="path-analysis.html#lecture-slides-7"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="path-analysis.html"><a href="path-analysis.html#quick-recap-1"><i class="fa fa-check"></i>Quick recap</a></li>
<li class="chapter" data-level="" data-path="path-analysis.html"><a href="path-analysis.html#exercises"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="sem-i.html"><a href="sem-i.html"><i class="fa fa-check"></i><b>10</b> SEM I</a><ul>
<li class="chapter" data-level="" data-path="sem-i.html"><a href="sem-i.html#packages-8"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="sem-i.html"><a href="sem-i.html#lecture-slides-8"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="sem-i.html"><a href="sem-i.html#overview"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="sem-i.html"><a href="sem-i.html#exercises-1"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Multivariate Statistics and Methodology using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="other-random-effects-structures" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Other random effects structures</h1>
<div id="packages-3" class="section level3 unnumbered">
<h3>Packages</h3>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" title="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb75-2" title="2"><span class="kw">library</span>(lme4)</a>
<a class="sourceLine" id="cb75-3" title="3"><span class="kw">library</span>(lmerTest)</a>
<a class="sourceLine" id="cb75-4" title="4"><span class="kw">library</span>(effects)</a></code></pre></div>
</div>
<div id="lecture-slides-3" class="section level3 unnumbered">
<h3>Lecture Slides</h3>
<p>The lecture slides can be accessed <a href="https://uoe-psychology.github.io/uoe_psystats/multivar/lectures/Lecture04_RanEf.html">here</a>.<br />
Data from the lecture can be found at <a href="https://edin.ac/36UYA00">https://edin.ac/36UYA00 (active_math_sim.csv)</a> and <a href="https://edin.ac/2ShRCNl">https://edin.ac/2ShRCNl (problem_solving.Rdata)</a>.</p>
</div>
<div id="background-reading-3" class="section level3 unnumbered">
<h3>Background &amp; Reading</h3>
<ul>
<li><a href="https://doi.org/10.1016/j.jml.2007.12.005">Baayen et al., 2008</a><br />
</li>
<li><a href="https://doi.org/10.1016/j.jml.2012.11.001">Barr et al., 2013</a><br />
</li>
<li><a href="https://doi.org/10.1016/j.jml.2017.01.001">Matuschek et al., 2017</a></li>
</ul>
</div>
<div id="crossed-random-effects" class="section level2">
<h2><span class="header-section-number">4.1</span> Crossed random effects</h2>
<div id="exercise-1-2" class="section level3">
<h3><span class="header-section-number">4.1.1</span> Exercise 1</h3>
<div class="red">
<h4 id="the-data" class="unnumbered">The data</h4>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" title="1"><span class="kw">load</span>(<span class="kw">url</span>(<span class="st">&quot;https://edin.ac/2ShRCNl&quot;</span>))</a>
<a class="sourceLine" id="cb76-2" title="2"><span class="kw">str</span>(problem_solving)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    2864 obs. of  5 variables:
##  $ Item     : Factor w/ 30 levels &quot;AA&quot;,&quot;AB&quot;,&quot;AC&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Prob_Type: Factor w/ 2 levels &quot;Hard&quot;,&quot;Easy&quot;: 1 1 1 1 1 1 1 1 1 1 ...
##   ..- attr(*, &quot;contrasts&quot;)= chr &quot;contr.sum&quot;
##  $ Subject  : Factor w/ 120 levels &quot;S101&quot;,&quot;S102&quot;,..: 119 25 1 102 65 105 56 53 84 86 ...
##  $ Condition: Factor w/ 2 levels &quot;Control&quot;,&quot;Treatment&quot;: 2 1 1 1 2 2 1 1 1 2 ...
##   ..- attr(*, &quot;contrasts&quot;)= chr &quot;contr.sum&quot;
##  $ RT       : int  3366 1584 2008 3089 1831 2863 3444 4102 2251 1950 ...</code></pre>
<ul>
<li><code>Item</code>: word problem, can be <em>Hard</em> or <em>Easy</em></li>
<li><code>Prob_Type</code>: difficulty level of word problem (16 hard problems, 14 easy problems)</li>
<li><code>Subject</code>: Participant ID, N=120</li>
<li><code>Condition</code>: whether the participant received the <code>Treatment</code> or not</li>
<li><code>RT</code>: time to solve the problem</li>
<li>Note: there is some missing data because trials where the participants failed to solve the problem are excluded.</li>
</ul>
</div>
<div class="question">
<p class="question-begin">
► Question 1
</p>
<div class="question-body">
<p>Check the contrasts of the <code>Condition</code> and <code>Prob_Type</code> variables.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-221" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-221&#39;, &#39;sol-start-221&#39;)"></span>
</p>
<div id="sol-body-221" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" title="1"><span class="kw">contrasts</span>(problem_solving<span class="op">$</span>Condition)</a></code></pre></div>
<pre><code>##           [,1]
## Control      1
## Treatment   -1</code></pre>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" title="1"><span class="kw">contrasts</span>(problem_solving<span class="op">$</span>Prob_Type)</a></code></pre></div>
<pre><code>##      [,1]
## Hard    1
## Easy   -1</code></pre>
<p>They are sum-coded. Remember what this means when you are interpreting the intercept and coefficients!</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question 2
</p>
<div class="question-body">
<ul>
<li>Does <code>Prob_Type</code> vary within subjects?</li>
<li>Does <code>Prob_Type</code> vary within items?</li>
<li>Does <code>Condition</code> vary within subjects?</li>
<li>Does <code>Condition</code> vary within items?</li>
</ul>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-222" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-222&#39;, &#39;sol-start-222&#39;)"></span>
</p>
<div id="sol-body-222" class="solution-body" style="display: none;">
<ul>
<li>Yes: Each subject solved both Easy and Hard problems.</li>
<li>No: Each item was either Easy or Hard.</li>
<li>No: Each subject was either in the control condition or the treatment condition.</li>
<li>Yes: Each item was solved both by subjects in the control condition and subjects in the treatment condition.</li>
</ul>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question 3
</p>
<div class="question-body">
<p>Conduct MLR with crossed random effects of subjects and items to answer these research questions</p>
<ol style="list-style-type: decimal">
<li>Did the treatment improve problem solving ability?</li>
<li>Did the treatment effect differ between hard and easy problems?</li>
</ol>
<p><strong>Hint:</strong> You can do this with one model, given what you know about the contrasts.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-223" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-223&#39;, &#39;sol-start-223&#39;)"></span>
</p>
<div id="sol-body-223" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" title="1">mod_ps &lt;-<span class="st"> </span><span class="kw">lmer</span>(RT <span class="op">~</span><span class="st"> </span>Prob_Type<span class="op">*</span>Condition <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb82-2" title="2"><span class="st">                   </span>(Prob_Type <span class="op">|</span><span class="st"> </span>Subject) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb82-3" title="3"><span class="st">                   </span>(Condition <span class="op">|</span><span class="st"> </span>Item), </a>
<a class="sourceLine" id="cb82-4" title="4">                 <span class="dt">data=</span>problem_solving, <span class="dt">REML=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb82-5" title="5"></a>
<a class="sourceLine" id="cb82-6" title="6"><span class="kw">summary</span>(mod_ps)</a></code></pre></div>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: RT ~ Prob_Type * Condition + (Prob_Type | Subject) + (Condition |      Item)
##    Data: problem_solving
## 
##      AIC      BIC   logLik deviance df.resid 
##  46245.1  46310.7 -23111.6  46223.1     2853 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -2.8354 -0.5429 -0.1105  0.3643 12.3008 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev. Corr
##  Subject  (Intercept)  74023   272.07       
##           Prob_Type1    8912    94.40   1.00
##  Item     (Intercept) 153298   391.53       
##           Condition1    1391    37.29   1.00
##  Residual             541953   736.17       
## Number of obs: 2864, groups:  Subject, 120; Item, 30
## 
## Fixed effects:
##                       Estimate Std. Error      df t value Pr(&gt;|t|)    
## (Intercept)            1753.51      77.16   37.28  22.726  &lt; 2e-16 ***
## Prob_Type1              325.24      73.50   30.88   4.425 0.000111 ***
## Condition1               58.34      29.43  111.64   1.982 0.049891 *  
## Prob_Type1:Condition1    36.14      17.73   86.76   2.038 0.044607 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) Prb_T1 Cndtn1
## Prob_Type1  -0.023              
## Condition1   0.217 -0.015       
## Prb_Typ1:C1 -0.024  0.379  0.398
## convergence code: 0
## boundary (singular) fit: see ?isSingular</code></pre>
<ul>
<li>Because both <code>Condition</code> and <code>Prob_Type</code> are sum-coded, the intercept term is the grand mean.<br />
</li>
<li>The <code>Prob_Type1</code> coefficient corresponds to the mean for <code>Prob_Type == "Hard"</code> minus the grand mean.
<small>Note that sum-coding means that we no longer interpret this as the effect of <code>Prob_Type</code> at a reference level of <code>Condition</code> - instead it may help to think of it as the effect of <code>Prob_Type</code> ‘when <code>Condition == 0</code>’. In the default coding, 0 corresponds to the reference level, but in sum-coding, where Control = 1 and Treatment = -1, what is 0? It’s mid-way between the two (it may help to think of sum-coding similar to what happens when we ‘center’ continuous variables).</small></li>
<li>The <code>Condition1</code> coefficient corresponds to the mean for <code>Condition == "Control"</code> minus the grand mean.</li>
<li>The <code>Prob_Type1:Condition1</code> coefficient corresponds to the effect of <code>Prob_Type</code> when <code>Condition == "Control"</code> relative to the effect of <code>Prob_Type</code> at the grand mean. Or, equivalently, the effect of <code>Condition</code> when <code>Prob_Type == "Hard"</code> relative to the effect of <code>Condition</code> at the grand mean.<br />
<br></li>
</ul>
<ol style="list-style-type: decimal">
<li>Treatment improves problem solving ability (slower reaction times in the control group across both easy and hard problems), <span class="math inline">\(\beta = 58.34, SE = 29.43, p = 0.0499\)</span></li>
<li>Treatment effect differs between easy and hard problems, with a greater effect for harder problems (greater difference in reaction times between control and treatment groups for hard problems), <span class="math inline">\(\beta = 36.14, SE = 17.73, p = 0.0446\)</span></li>
</ol>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question 4
</p>
<div class="question-body">
<p>Make a graph of the condition means and variability based on your analysis model.<br />
<strong>Hint:</strong> start with<code>as.data.frame(effect(........))</code>, and pass to it the parameter you’re interested in and your model.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-224" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-224&#39;, &#39;sol-start-224&#39;)"></span>
</p>
<div id="sol-body-224" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb84-1" title="1">efx &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">effect</span>(<span class="st">&quot;Prob_Type:Condition&quot;</span>, mod_ps))</a>
<a class="sourceLine" id="cb84-2" title="2"></a>
<a class="sourceLine" id="cb84-3" title="3"><span class="kw">ggplot</span>(efx, <span class="kw">aes</span>(Condition, fit, <span class="dt">color=</span>Prob_Type, <span class="dt">ymin=</span>fit<span class="op">-</span>se, <span class="dt">ymax=</span>fit<span class="op">+</span>se)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb84-4" title="4"><span class="st">  </span><span class="kw">geom_pointrange</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb84-5" title="5"><span class="st">  </span><span class="kw">theme_light</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb84-6" title="6"><span class="st">  </span><span class="kw">scale_color_manual</span>(<span class="dt">values=</span><span class="kw">c</span>(<span class="st">&quot;lightgreen&quot;</span>,<span class="st">&quot;tomato1&quot;</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb84-7" title="7"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y=</span><span class="st">&quot;Response Time&quot;</span>, <span class="dt">color=</span><span class="st">&quot;Problem</span><span class="ch">\n</span><span class="st">Type&quot;</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-65-1.png" width="480" /></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
</div>
<div id="dealing-with-issue-of-non-convergence-and-singular-fits" class="section level2">
<h2><span class="header-section-number">4.2</span> Dealing with issue of non-convergence and singular fits</h2>
<div class="lo">
<h3 id="singular-fits" class="unnumbered">Singular fits</h3>
<p>You may have noticed that a lot of our models over the last few weeks have been giving a warning: <code>boundary (singular) fit: see ?isSingular</code>.<br />
Up to now, we’ve been largely ignoring these warnings. However, in this exercise we’re going to look at how to deal with this issue.
<br>
The warning is telling us that our model has resulted in a ‘singular fit’. Singular fits often indicate that the model is ‘overfitted’ - that is, the random effects structure which we have specified is too complex to be supported by the data.</p>
<p>Perhaps the most intuitive advice would be remove the most complex part of the random effects structure (i.e. random slopes). This leads to a simpler model that is not over-fitted.<br />
Additionally, when variance estimates are very low for a specific random effect term, this indicates that the model is not estimating this parameter to differ much between the levels of your grouping variable. It might, in some experimental designs, be perfectly acceptable to remove this.<br />
<br>
A key point here is that when fitting a mixed model, we should think about how the data are generated. Asking yourself questions such as “do we have good reason to assume subjects might vary over time, or to assume that they will have different starting points (i.e., different intercepts)?” can help you in specifying your random effect structure
<br>
You can read in depth about what this means by reading the help documentation for <code>?isSingular</code>. For our purposes, a relevant section is copied below:</p>
<p><em>…intercept-only models, or 2-dimensional random effects such as intercept+slope models, singularity is relatively easy to detect because it leads to random-effect variance estimates of (nearly) zero, or estimates of correlations that are (almost) exactly -1 or 1.</em></p>
</div>
<div class="lo">
<h3 id="convergence-warnings" class="unnumbered">Convergence warnings</h3>
<p>Issues of non-convergence can be caused by many things. If you’re model doesn’t converge, it does <em>not necessarily</em> mean the fit is incorrect, however it is <strong>is cause for concern</strong>, and should be addressed, else you may end up reporting inferences which do not hold.</p>
<p><br>
There are lots of different things which you could do which <em>might</em> help your model to converge. A select few are detailed below:</p>
<ul>
<li>double-check the model specification and the data<br />
</li>
<li>adjust stopping (convergence) tolerances for the nonlinear optimizer, using the optCtrl argument to [g]lmerControl. (see <code>?convergence</code> for convergence controls).<br />
</li>
<li>center and scale continuous predictor variables (e.g. with <code>scale</code>)<br />
</li>
<li>change the optimiser, or use <code>allFit()</code> to try the fit with all available optimizers. This will of course be slow, but is considered ‘the gold standard’; <em>“if all optimizers converge to values that are practically equivalent, then we would consider the convergence warnings to be false positives.”</em></li>
</ul>
</div>
<div id="exercise-2-1" class="section level3">
<h3><span class="header-section-number">4.2.1</span> Exercise 2</h3>
<div class="red">
<h4 id="the-data-1" class="unnumbered">The data</h4>
<p>An experiment was run to replicate “test-enhanced learning” (Roediger &amp; Karpicke, 2006): two groups of 25 participants were presented with material to learn. One group studied the material twice (<code>StudyStudy</code>), the other group studied the material once then did a test (<code>StudyTest</code>). Recall was tested immediately (one minute) after the learning session and one week later. The recall tests were composed of 175 items identified by a keyword (<code>Test_word</code>).<br />
<br><br />
The critical (replication) prediction is that the <code>StudyStudy</code> group should perform somewhat better on the immediate recall test, but the <code>StudyTest</code> group will retain the material better and thus perform better on the 1-week follow-up test.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb85-1" title="1"><span class="kw">load</span>(<span class="kw">url</span>(<span class="st">&quot;https://edin.ac/2RWbl6g&quot;</span>))</a>
<a class="sourceLine" id="cb85-2" title="2"><span class="kw">str</span>(tel)</a></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    17498 obs. of  5 variables:
##  $ Subject_ID: chr  &quot;StudyTest_L&quot; &quot;StudyTest_L&quot; &quot;StudyTest_L&quot; &quot;StudyTest_L&quot; ...
##  $ Group     : chr  &quot;StudyTest&quot; &quot;StudyTest&quot; &quot;StudyTest&quot; &quot;StudyTest&quot; ...
##  $ Delay     : chr  &quot;min&quot; &quot;week&quot; &quot;min&quot; &quot;min&quot; ...
##  $ Test_word : chr  &quot;van&quot; &quot;dinosaur&quot; &quot;typewriter&quot; &quot;chimney&quot; ...
##  $ Correct   : num  1 0 0 0 1 1 1 1 0 0 ...</code></pre>
</div>
<div class="question">
<p class="question-begin">
► Question 5
</p>
<div class="question-body">
<p>Plot the data. Does it look like the effect was replicated?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-225" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-225&#39;, &#39;sol-start-225&#39;)"></span>
</p>
<div id="sol-body-225" class="solution-body" style="display: none;">
<p>You can make use of <code>stat_summary()</code> again!</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb87-1" title="1"><span class="kw">ggplot</span>(tel, <span class="kw">aes</span>(Delay, Correct, <span class="dt">col=</span>Group)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb87-2" title="2"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data=</span>mean_se, <span class="dt">geom=</span><span class="st">&quot;pointrange&quot;</span>)<span class="op">+</span></a>
<a class="sourceLine" id="cb87-3" title="3"><span class="st">  </span><span class="kw">theme_light</span>()</a></code></pre></div>
<p>It’s more work, but some people might rather calculate the numbers and then plot them directly. It does just the same thing:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" title="1">tel <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb88-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(Delay, Group) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb88-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(</a>
<a class="sourceLine" id="cb88-4" title="4">    <span class="dt">mean =</span> <span class="kw">mean</span>(Correct),</a>
<a class="sourceLine" id="cb88-5" title="5">    <span class="dt">se =</span> <span class="kw">sd</span>(Correct)<span class="op">/</span><span class="kw">sqrt</span>(<span class="kw">n</span>())</a>
<a class="sourceLine" id="cb88-6" title="6">  ) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb88-7" title="7"><span class="st">  </span><span class="kw">ggplot</span>(., <span class="kw">aes</span>(<span class="dt">x=</span>Delay, <span class="dt">col =</span> Group)) <span class="op">+</span></a>
<a class="sourceLine" id="cb88-8" title="8"><span class="st">  </span><span class="kw">geom_pointrange</span>(<span class="kw">aes</span>(<span class="dt">y=</span>mean, <span class="dt">ymin=</span>mean<span class="op">-</span>se, <span class="dt">ymax=</span>mean<span class="op">+</span>se))<span class="op">+</span></a>
<a class="sourceLine" id="cb88-9" title="9"><span class="st">  </span><span class="kw">theme_light</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb88-10" title="10"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y =</span> <span class="st">&quot;Correct&quot;</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<p>That looks like test-enhanced learning to me!</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question 6
</p>
<div class="question-body">
<p>Test the critical hypothesis using a mixed-effects model. Fit the maximal random effect structure supported by the experimental design.</p>
<p>Some questions to consider:</p>
<ul>
<li>Item accuracy is a binary variable. What kind of model will you use?<br />
</li>
<li>We can expect variability across subjects (some people are better at learning than others) and across items (some of the recall items are harder than others). How should this be represented in the random effects?</li>
</ul>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-226" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-226&#39;, &#39;sol-start-226&#39;)"></span>
</p>
<div id="sol-body-226" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb89-1" title="1">m &lt;-<span class="st"> </span><span class="kw">glmer</span>(Correct <span class="op">~</span><span class="st"> </span>Delay<span class="op">*</span>Group <span class="op">+</span></a>
<a class="sourceLine" id="cb89-2" title="2"><span class="st">             </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>Delay <span class="op">|</span><span class="st"> </span>Subject_ID) <span class="op">+</span></a>
<a class="sourceLine" id="cb89-3" title="3"><span class="st">             </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>Delay <span class="op">+</span><span class="st"> </span>Group <span class="op">|</span><span class="st"> </span>Test_word),</a>
<a class="sourceLine" id="cb89-4" title="4">           <span class="dt">data=</span>tel, <span class="dt">family=</span><span class="st">&quot;binomial&quot;</span>,</a>
<a class="sourceLine" id="cb89-5" title="5">           <span class="kw">glmerControl</span>(<span class="dt">optimizer =</span> <span class="st">&quot;bobyqa&quot;</span>))</a>
<a class="sourceLine" id="cb89-6" title="6"><span class="kw">summary</span>(m)</a></code></pre></div>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) [&#39;glmerMod&#39;]
##  Family: binomial  ( logit )
## Formula: Correct ~ Delay * Group + (1 + Delay | Subject_ID) + (1 + Delay +      Group | Test_word)
##    Data: tel
## Control: glmerControl(optimizer = &quot;bobyqa&quot;)
## 
##      AIC      BIC   logLik deviance df.resid 
##  16289.8  16390.8  -8131.9  16263.8    17485 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -7.4352 -0.4778  0.2763  0.5182  7.5360 
## 
## Random effects:
##  Groups     Name           Variance Std.Dev. Corr       
##  Test_word  (Intercept)    1.160006 1.07704             
##             Delayweek      0.005543 0.07445  -0.80      
##             GroupStudyTest 0.011905 0.10911  -0.93  0.97
##  Subject_ID (Intercept)    2.527104 1.58969             
##             Delayweek      0.044399 0.21071  -0.60      
## Number of obs: 17498, groups:  Test_word, 175; Subject_ID, 50
## 
## Fixed effects:
##                          Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)               1.28215    0.33082   3.876 0.000106 ***
## Delayweek                -1.07133    0.07068 -15.157  &lt; 2e-16 ***
## GroupStudyTest           -0.42866    0.45344  -0.945 0.344480    
## Delayweek:GroupStudyTest  0.79433    0.10189   7.796 6.41e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) Delywk GrpStT
## Delayweek   -0.441              
## GropStdyTst -0.688  0.309       
## Dlywk:GrpST  0.292 -0.679 -0.430
## convergence code: 0
## boundary (singular) fit: see ?isSingular</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question 7
</p>
<div class="question-body">
<p>Your model with maximal random effects will probably not converge, or will obtain a singular fit. Simplify the model until you achieve convergence.<br />
<br>
What we’re aiming to do here is to follow <a href="https://doi.org/10.1016/j.jml.2012.11.001">Barr et al.’s</a> advice of defining our maximal model and then removing only the terms to allow a non-singular fit.<br />
<br>
<strong>Note:</strong> This strategy - starting with the maximal random effects structure and removing terms until obtaining model convergence, is just <em>one</em> approach, and there are drawbacks (see <a href="https://doi.org/10.1016/j.jml.2017.01.001">Matuschek et al., 2017</a>). There is no consensus on what approach is best (see <code>?isSingular</code>).<br />
<br>
<br>
<em>Tip:</em> you can look at the variance estimates and correlations easily by using the <code>VarCorr()</code> function. What jumps out?<br />
<br>
<em>Hint:</em> Generalization over subjects could be considered more important than over items - if the estimated variance of slopes for <code>Delay</code> and <code>Group</code> by-items are comparatively small, it might be easier to remove them?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-227" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-227&#39;, &#39;sol-start-227&#39;)"></span>
</p>
<div id="sol-body-227" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb91-1" title="1"><span class="kw">VarCorr</span>(m)</a></code></pre></div>
<pre><code>##  Groups     Name           Std.Dev. Corr         
##  Test_word  (Intercept)    1.077036              
##             Delayweek      0.074453 -0.803       
##             GroupStudyTest 0.109112 -0.930  0.966
##  Subject_ID (Intercept)    1.589687              
##             Delayweek      0.210710 -0.600</code></pre>
<p>The by-item slope of <code>Group</code> seems to be quite highly correlated with other by-item terms.</p>
<p>For now, we will just simply remove the term (however, we could - if we had theoretical justification - constrain our model so that there was 0 correlation)</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb93-1" title="1">m2 &lt;-<span class="st"> </span><span class="kw">glmer</span>(Correct <span class="op">~</span><span class="st"> </span>Delay<span class="op">*</span>Group <span class="op">+</span></a>
<a class="sourceLine" id="cb93-2" title="2"><span class="st">             </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>Delay <span class="op">|</span><span class="st"> </span>Subject_ID) <span class="op">+</span></a>
<a class="sourceLine" id="cb93-3" title="3"><span class="st">             </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>Delay <span class="op">|</span><span class="st"> </span>Test_word),</a>
<a class="sourceLine" id="cb93-4" title="4">            <span class="dt">data=</span>tel, <span class="dt">family=</span><span class="st">&quot;binomial&quot;</span>,</a>
<a class="sourceLine" id="cb93-5" title="5">            <span class="kw">glmerControl</span>(<span class="dt">optimizer =</span> <span class="st">&quot;bobyqa&quot;</span>))</a>
<a class="sourceLine" id="cb93-6" title="6"><span class="kw">VarCorr</span>(m2)</a></code></pre></div>
<pre><code>##  Groups     Name        Std.Dev. Corr  
##  Test_word  (Intercept) 1.027503       
##             Delayweek   0.055413 -1.000
##  Subject_ID (Intercept) 1.598988       
##             Delayweek   0.208731 -0.599</code></pre>
<p>It’s still a singular fit, and the <code>Delay</code> random slope by <code>Test_word</code> variance is extremely low and perfectly correlated with the intercept, let’s try removing that:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb95-1" title="1">m3 &lt;-<span class="st"> </span><span class="kw">glmer</span>(Correct <span class="op">~</span><span class="st"> </span>Delay<span class="op">*</span>Group <span class="op">+</span></a>
<a class="sourceLine" id="cb95-2" title="2"><span class="st">              </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>Delay <span class="op">|</span><span class="st"> </span>Subject_ID) <span class="op">+</span></a>
<a class="sourceLine" id="cb95-3" title="3"><span class="st">              </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>Test_word),</a>
<a class="sourceLine" id="cb95-4" title="4">            <span class="dt">data=</span>tel, <span class="dt">family=</span><span class="st">&quot;binomial&quot;</span>,</a>
<a class="sourceLine" id="cb95-5" title="5">            <span class="kw">glmerControl</span>(<span class="dt">optimizer =</span> <span class="st">&quot;bobyqa&quot;</span>))</a></code></pre></div>
<p>Hooray, the model converged!</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb96-1" title="1"><span class="kw">summary</span>(m3)</a></code></pre></div>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace Approximation) [&#39;glmerMod&#39;]
##  Family: binomial  ( logit )
## Formula: Correct ~ Delay * Group + (1 + Delay | Subject_ID) + (1 | Test_word)
##    Data: tel
## Control: glmerControl(optimizer = &quot;bobyqa&quot;)
## 
##      AIC      BIC   logLik deviance df.resid 
##  16285.3  16347.4  -8134.6  16269.3    17490 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -7.5190 -0.4795  0.2758  0.5199  8.0698 
## 
## Random effects:
##  Groups     Name        Variance Std.Dev. Corr 
##  Test_word  (Intercept) 0.9961   0.9980        
##  Subject_ID (Intercept) 2.5170   1.5865        
##             Delayweek   0.0387   0.1967   -0.52
## Number of obs: 17498, groups:  Test_word, 175; Subject_ID, 50
## 
## Fixed effects:
##                          Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)               1.25720    0.32837   3.829 0.000129 ***
## Delayweek                -1.04684    0.06750 -15.510  &lt; 2e-16 ***
## GroupStudyTest           -0.39822    0.45243  -0.880 0.378765    
## Delayweek:GroupStudyTest  0.77634    0.09916   7.829 4.91e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) Delywk GrpStT
## Delayweek   -0.370              
## GropStdyTst -0.687  0.267       
## Dlywk:GrpST  0.252 -0.679 -0.371</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<!-- You can also get some odds-ratios and quick confidence intervals using the following: -->
<!-- *Note, the `method = "Wald"` corresponds to a quick-and-easy method of calculating confidence intervals (simply $1.96 \times SE$). The gold standard for confidence intervals is `method = "boot"`, which obtains them via bootstrapping, but this will take too long!  -->
<!-- ```{r} -->
<!-- exp(fixef(m4)) -->
<!-- exp(confint(m4, method="Wald"))[8:11,] -->
<!-- ``` -->
<!-- No difference between groups on the immediate test.  -->
<!-- For the `StudyStudy` group, there was a decreased likelihood of getting an item correct on the follow-up test relative to the immediate test ($OR = 0.35, \text{95% CI} = [0.31, 0.40]$).   -->
<!-- For the The likelihood of correctly answering an item  -->
<hr />
<div class="question">
<p class="question-begin">
► Question 8
</p>
<div class="question-body">
<p>Plot the model-estimated condition means and variability.</p>
<p><em>Hint:</em> This is very similar to question 4.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-228" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-228&#39;, &#39;sol-start-228&#39;)"></span>
</p>
<div id="sol-body-228" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb98-1" title="1">ef &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">effect</span>(<span class="st">&quot;Delay:Group&quot;</span>, m3))</a>
<a class="sourceLine" id="cb98-2" title="2"></a>
<a class="sourceLine" id="cb98-3" title="3"><span class="kw">ggplot</span>(ef, <span class="kw">aes</span>(Delay, fit, <span class="dt">color=</span>Group)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb98-4" title="4"><span class="st">  </span><span class="kw">geom_pointrange</span>(<span class="kw">aes</span>(<span class="dt">ymax=</span>upper, <span class="dt">ymin=</span>lower), <span class="dt">position=</span><span class="kw">position_dodge</span>(<span class="dt">width =</span> <span class="fl">0.2</span>))<span class="op">+</span></a>
<a class="sourceLine" id="cb98-5" title="5"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="co"># just for a change :)</span></a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-74-1.png" width="672" /></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question 9
</p>
<div class="question-body">
<p>What should we do with this information? How can we apply test-enhanced learning to learning R and statistics?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-229" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-229&#39;, &#39;sol-start-229&#39;)"></span>
</p>
<div id="sol-body-229" class="solution-body" style="display: none;">
<p>You’ll get the benefits of test-enhanced learning if you try yourself before looking at the solutions! If you don’t test yourself, you’re more likely to forget it in the long run.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="exercise-3-1" class="section level3">
<h3><span class="header-section-number">4.2.2</span> Exercise 3</h3>
<div class="red">
<h4 id="the-data-2" class="unnumbered">The data</h4>
<p>Made-up data from a RCT treatment study: 5 therapists randomly assigned participants to control or treatment group and monitored the participants’ performance over time. There was a baseline test, then 6 weeks of treatment, with test sessions every week (7 total sessions).</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb99-1" title="1"><span class="kw">load</span>(<span class="kw">url</span>(<span class="st">&quot;https://edin.ac/2GPGgev&quot;</span>))</a>
<a class="sourceLine" id="cb99-2" title="2"><span class="kw">summary</span>(tx)</a></code></pre></div>
<pre><code>##        group        session   therapist             Score            PID           
##  treatment:490   Min.   :1   Length:945         Min.   :0.1091   Length:945        
##  control  :455   1st Qu.:2   Class :character   1st Qu.:0.5149   Class :character  
##                  Median :4   Mode  :character   Median :0.6164   Mode  :character  
##                  Mean   :4                      Mean   :0.6315                     
##                  3rd Qu.:6                      3rd Qu.:0.7427                     
##                  Max.   :7                      Max.   :1.2244</code></pre>
</div>
<div class="question">
<p class="question-begin">
► Question 10
</p>
<div class="question-body">
<p>Plot the data. Does it look like the treatment had an effect on the performance score?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-230" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-230&#39;, &#39;sol-start-230&#39;)"></span>
</p>
<div id="sol-body-230" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb101-1" title="1"><span class="kw">ggplot</span>(tx, <span class="kw">aes</span>(session, Score, <span class="dt">color=</span>group)) <span class="op">+</span></a>
<a class="sourceLine" id="cb101-2" title="2"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data =</span> mean_se, <span class="dt">geom=</span><span class="st">&quot;pointrange&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb101-3" title="3"><span class="st">  </span><span class="kw">stat_smooth</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb101-4" title="4"><span class="st">  </span><span class="kw">theme_classic</span>()</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-76-1.png" width="672" /></p>
<p>Just for fun, let’s add on the individual participant scores, and also make a plot for each therapist.</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb102-1" title="1"><span class="kw">ggplot</span>(tx, <span class="kw">aes</span>(session, Score, <span class="dt">color=</span>group)) <span class="op">+</span></a>
<a class="sourceLine" id="cb102-2" title="2"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data =</span> mean_se, <span class="dt">geom=</span><span class="st">&quot;pointrange&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb102-3" title="3"><span class="st">  </span><span class="kw">stat_smooth</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb102-4" title="4"><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb102-5" title="5"><span class="st">  </span><span class="kw">geom_line</span>(<span class="kw">aes</span>(<span class="dt">group=</span>PID), <span class="dt">alpha=</span>.<span class="dv">2</span>)<span class="op">+</span><span class="kw">facet_wrap</span>(<span class="op">~</span>therapist)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-77-1.png" width="672" /></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question 11
</p>
<div class="question-body">
<p>Consider these questions when you’re designing your model(s) and use your answers to motivate your model design and interpretation of results:</p>
<ol style="list-style-type: lower-alpha">
<li>What are the levels of nesting? How should that be reflected in the random effect structure?</li>
<li>What is the shape of change over time? Do you need polynomials to model this shape? If yes, what order polynomials?</li>
</ol>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-231" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-231&#39;, &#39;sol-start-231&#39;)"></span>
</p>
<div id="sol-body-231" class="solution-body" style="display: none;">
<ol style="list-style-type: lower-alpha">
<li>There are repeated measures of participants (session). There are also repeated measures of therapists (each one treated many participants).</li>
<li>Looks like linear change, don’t need polynomials. Good to know that there is no difference at baseline, so no need for orthogonal time.</li>
</ol>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question 12
</p>
<div class="question-body">
<p>Test whether the treatment had an effect using mixed-effects modeling. Specify the maximal model.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-232" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-232&#39;, &#39;sol-start-232&#39;)"></span>
</p>
<div id="sol-body-232" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb103-1" title="1"><span class="co"># start with maximal model</span></a>
<a class="sourceLine" id="cb103-2" title="2">m1 &lt;-<span class="st"> </span><span class="kw">lmer</span>(Score <span class="op">~</span><span class="st"> </span>session <span class="op">*</span><span class="st"> </span>group <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb103-3" title="3"><span class="st">             </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>session <span class="op">|</span><span class="st"> </span>PID) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb103-4" title="4"><span class="st">             </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>session <span class="op">|</span><span class="st"> </span>therapist),</a>
<a class="sourceLine" id="cb103-5" title="5">           <span class="dt">data=</span>tx, <span class="dt">REML=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb103-6" title="6"><span class="kw">summary</span>(m1)</a></code></pre></div>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: Score ~ session * group + (1 + session | PID) + (1 + session |      therapist)
##    Data: tx
## 
##      AIC      BIC   logLik deviance df.resid 
##  -1643.8  -1590.4    832.9  -1665.8      934 
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -2.63292 -0.58800  0.01438  0.55505  2.87871 
## 
## Random effects:
##  Groups    Name        Variance  Std.Dev.  Corr 
##  PID       (Intercept) 1.373e-02 1.172e-01      
##            session     9.848e-04 3.138e-02 -0.60
##  therapist (Intercept) 1.225e-09 3.500e-05      
##            session     1.267e-11 3.560e-06 -1.00
##  Residual              5.368e-03 7.327e-02      
## Number of obs: 945, groups:  PID, 135; therapist, 5
## 
## Fixed effects:
##                        Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)            0.526849   0.015841 134.976208  33.258  &lt; 2e-16 ***
## session                0.033688   0.004100 134.987110   8.217 1.51e-13 ***
## groupcontrol           0.018136   0.022830 134.980597   0.794 0.428360    
## session:groupcontrol  -0.020138   0.005908 134.988836  -3.408 0.000862 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) sessin grpcnt
## session     -0.655              
## groupcontrl -0.694  0.454       
## sssn:grpcnt  0.454 -0.694 -0.655
## convergence code: 0
## boundary (singular) fit: see ?isSingular</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question 13
</p>
<div class="question-body">
<p>Try adjusting your model by removing random effects or correlations, examine the model again, and so on..</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-233" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-233&#39;, &#39;sol-start-233&#39;)"></span>
</p>
<div id="sol-body-233" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb105-1" title="1"><span class="kw">VarCorr</span>(m1)</a></code></pre></div>
<pre><code>##  Groups    Name        Std.Dev.   Corr  
##  PID       (Intercept) 1.1718e-01       
##            session     3.1382e-02 -0.601
##  therapist (Intercept) 3.5001e-05       
##            session     3.5595e-06 -1.000
##  Residual              7.3269e-02</code></pre>
<p>There’s a correlation of exactly -1 between the random intercepts and slopes for therapists, and the standard deviation estimate for <code>session|therapist</code> is pretty small. Let’s remove it.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb107-1" title="1">m2 &lt;-<span class="st"> </span><span class="kw">lmer</span>(Score <span class="op">~</span><span class="st"> </span>session <span class="op">*</span><span class="st"> </span>group <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb107-2" title="2"><span class="st">             </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>session <span class="op">|</span><span class="st"> </span>PID) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb107-3" title="3"><span class="st">             </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>therapist),</a>
<a class="sourceLine" id="cb107-4" title="4">           <span class="dt">data=</span>tx, <span class="dt">REML=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb107-5" title="5"><span class="kw">VarCorr</span>(m2)</a></code></pre></div>
<pre><code>##  Groups    Name        Std.Dev. Corr  
##  PID       (Intercept) 0.11717        
##            session     0.03138  -0.601
##  therapist (Intercept) 0.00000        
##  Residual              0.07327</code></pre>
<p>It now looks like estimates for random intercepts for therapists is now 0. If we remove this, our model finally is non-singular:</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb109-1" title="1">m3 &lt;-<span class="st"> </span><span class="kw">lmer</span>(Score <span class="op">~</span><span class="st"> </span>session <span class="op">*</span><span class="st"> </span>group <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb109-2" title="2"><span class="st">             </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>session <span class="op">|</span><span class="st"> </span>PID),</a>
<a class="sourceLine" id="cb109-3" title="3">           <span class="dt">data=</span>tx, <span class="dt">REML=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb109-4" title="4"><span class="kw">summary</span>(m3)</a></code></pre></div>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: Score ~ session * group + (1 + session | PID)
##    Data: tx
## 
##      AIC      BIC   logLik deviance df.resid 
##  -1649.8  -1611.0    832.9  -1665.8      937 
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -2.63284 -0.58803  0.01439  0.55505  2.87860 
## 
## Random effects:
##  Groups   Name        Variance  Std.Dev. Corr 
##  PID      (Intercept) 0.0137278 0.11717       
##           session     0.0009847 0.03138  -0.60
##  Residual             0.0053686 0.07327       
## Number of obs: 945, groups:  PID, 135
## 
## Fixed effects:
##                        Estimate Std. Error         df t value Pr(&gt;|t|)    
## (Intercept)            0.526849   0.015840 135.024518  33.262  &lt; 2e-16 ***
## session                0.033688   0.004100 135.003868   8.217 1.51e-13 ***
## groupcontrol           0.018136   0.022827 135.024519   0.794 0.428305    
## session:groupcontrol  -0.020138   0.005908 135.003868  -3.409 0.000861 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) sessin grpcnt
## session     -0.655              
## groupcontrl -0.694  0.454       
## sssn:grpcnt  0.454 -0.694 -0.655</code></pre>
<p>Lastly, it’s then a good idea to check that the parameter estimates and SE are not radically different across these models (they are virtually identical)</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb111-1" title="1"><span class="kw">summary</span>(m1)<span class="op">$</span>coefficients</a></code></pre></div>
<pre><code>##                         Estimate  Std. Error       df    t value     Pr(&gt;|t|)
## (Intercept)           0.52684907 0.015841487 134.9762 33.2575521 6.821583e-67
## session               0.03368821 0.004099740 134.9871  8.2171564 1.511024e-13
## groupcontrol          0.01813605 0.022830001 134.9806  0.7943954 4.283598e-01
## session:groupcontrol -0.02013829 0.005908354 134.9888 -3.4084434 8.616018e-04</code></pre>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb113-1" title="1"><span class="kw">summary</span>(m2)<span class="op">$</span>coefficients</a></code></pre></div>
<pre><code>##                         Estimate  Std. Error       df    t value     Pr(&gt;|t|)
## (Intercept)           0.52684907 0.015840424 135.0051 33.2597829 6.637414e-67
## session               0.03368821 0.004099570 135.0026  8.2174987 1.507284e-13
## groupcontrol          0.01813605 0.022828481 135.0051  0.7944483 4.283288e-01
## session:groupcontrol -0.02013829 0.005908109 135.0026 -3.4085852 8.611671e-04</code></pre>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb115-1" title="1"><span class="kw">summary</span>(m3)<span class="op">$</span>coefficients</a></code></pre></div>
<pre><code>##                         Estimate  Std. Error       df    t value     Pr(&gt;|t|)
## (Intercept)           0.52684907 0.015839602 135.0245 33.2615092 6.511331e-67
## session               0.03368821 0.004099593 135.0039  8.2174516 1.507605e-13
## groupcontrol          0.01813605 0.022827296 135.0245  0.7944895 4.283047e-01
## session:groupcontrol -0.02013829 0.005908142 135.0039 -3.4085656 8.612216e-04</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► EXTRA: Question 14
</p>
<div class="question-body">
<p>Try the code below to use the <code>allFit()</code> function to fit your final model with all the available optimizers.</p>
<ul>
<li>You might need to install the <code>dfoptim</code> package to get one of the optimizers<br />
</li>
<li>If you have an older version of <code>lme4</code>, then <code>allFit()</code> might not be directly available, and you will need to run the following: <code>source(system.file("utils", "allFit.R", package="lme4"))</code>.</li>
</ul>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb117-1" title="1">fits &lt;-<span class="st"> </span><span class="kw">allFit</span>(yourmodel)</a>
<a class="sourceLine" id="cb117-2" title="2"><span class="kw">summary</span>(fits)</a></code></pre></div>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="mlr-for-longitudinal-data-growth-curve-analysis.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="recap-individual-differences.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/lunr.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
