<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Recap &amp; Individual differences | Multivariate Statistics and Methodology using R</title>
  <meta name="description" content="This is the page that contains the course labs materials" />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Recap &amp; Individual differences | Multivariate Statistics and Methodology using R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the page that contains the course labs materials" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Recap &amp; Individual differences | Multivariate Statistics and Methodology using R" />
  
  <meta name="twitter:description" content="This is the page that contains the course labs materials" />
  

<meta name="author" content="Department of Psychology, University of Edinburgh" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="other-random-effects-structures.html"/>
<link rel="next" href="break-week.html"/>
<script src="libs/jquery/jquery.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />









<script>
  $(document).ready(function() {
    $head = $('#header');
    $head.prepend('<img style="padding-right:25%; margin-bottom:10px;" src="https://www.ed.ac.uk/sites/all/themes/uoe/assets/logo.png" width="770px" align="left">')
  });
</script>

<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}
}
</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MSMR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview of the Course</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#the-team"><i class="fa fa-check"></i>The team</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-stuff"><i class="fa fa-check"></i>R stuff</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-cheatsheets"><i class="fa fa-check"></i>R Cheatsheets</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-community"><i class="fa fa-check"></i>R Community</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html"><i class="fa fa-check"></i><b>1</b> Tidyverse &amp; Markdown</a><ul>
<li class="chapter" data-level="" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#packages"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#lecture-slides"><i class="fa fa-check"></i>Lecture slides</a></li>
<li class="chapter" data-level="" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#background-reading"><i class="fa fa-check"></i>Background &amp; Reading</a></li>
<li class="chapter" data-level="1.1" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#data-visualization-with-ggplot"><i class="fa fa-check"></i><b>1.1</b> Data Visualization with <code>ggplot</code></a><ul>
<li class="chapter" data-level="1.1.1" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#geoms"><i class="fa fa-check"></i><b>1.1.1</b> Geoms</a></li>
<li class="chapter" data-level="1.1.2" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#recreating-a-plot"><i class="fa fa-check"></i><b>1.1.2</b> Recreating a plot</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#data-management-with-the-tidyverse"><i class="fa fa-check"></i><b>1.2</b> Data management with the Tidyverse</a><ul>
<li class="chapter" data-level="1.2.1" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#piping"><i class="fa fa-check"></i><b>1.2.1</b> Piping!</a></li>
<li class="chapter" data-level="1.2.2" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#grouping-summarising-filtering-mutating-and-selecting"><i class="fa fa-check"></i><b>1.2.2</b> Grouping, summarising, filtering, mutating and selecting</a></li>
<li class="chapter" data-level="1.2.3" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#reshaping"><i class="fa fa-check"></i><b>1.2.3</b> Reshaping</a></li>
<li class="chapter" data-level="" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#less-guidance"><i class="fa fa-check"></i>Less guidance</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#reproducible-research-with-rmarkdown"><i class="fa fa-check"></i><b>1.3</b> Reproducible research with RMarkdown</a><ul>
<li class="chapter" data-level="1.3.1" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#convert-a-script-into-a-r-notebook"><i class="fa fa-check"></i><b>1.3.1</b> Convert a script into a R Notebook</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html"><i class="fa fa-check"></i><b>2</b> Basic Multilevel Regression</a><ul>
<li class="chapter" data-level="" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#packages-1"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#lecture-slides-1"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#background-reading-1"><i class="fa fa-check"></i>Background &amp; Reading</a></li>
<li class="chapter" data-level="2.1" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#lme4"><i class="fa fa-check"></i><b>2.1</b> LME4</a></li>
<li class="chapter" data-level="2.2" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#introduction-to-mlr"><i class="fa fa-check"></i><b>2.2</b> Introduction to MLR</a><ul>
<li class="chapter" data-level="2.2.1" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#exercise-1"><i class="fa fa-check"></i><b>2.2.1</b> Exercise 1</a></li>
<li class="chapter" data-level="2.2.2" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#exercise-2"><i class="fa fa-check"></i><b>2.2.2</b> Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#logistic-mlr"><i class="fa fa-check"></i><b>2.3</b> Logistic MLR</a><ul>
<li class="chapter" data-level="2.3.1" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#exercise-3"><i class="fa fa-check"></i><b>2.3.1</b> Exercise 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html"><i class="fa fa-check"></i><b>3</b> MLR for longitudinal data (growth curve analysis)</a><ul>
<li class="chapter" data-level="" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#packages-2"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#lecture-slides-2"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#background-reading-2"><i class="fa fa-check"></i>Background &amp; Reading</a></li>
<li class="chapter" data-level="3.1" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#introduction"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#exercise-1-1"><i class="fa fa-check"></i><b>3.2</b> Exercise 1</a><ul>
<li class="chapter" data-level="" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#interpret-the-results-of-your-full-model"><i class="fa fa-check"></i>Interpret the results of your full model</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#exercise-2-writing-up-and-logistic-gca"><i class="fa fa-check"></i><b>3.3</b> Exercise 2: Writing up, and Logistic GCA</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html"><i class="fa fa-check"></i><b>4</b> Other random effects structures</a><ul>
<li class="chapter" data-level="" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#packages-3"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#lecture-slides-3"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#background-reading-3"><i class="fa fa-check"></i>Background &amp; Reading</a></li>
<li class="chapter" data-level="4.1" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#crossed-random-effects"><i class="fa fa-check"></i><b>4.1</b> Crossed random effects</a><ul>
<li class="chapter" data-level="4.1.1" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#exercise-1-2"><i class="fa fa-check"></i><b>4.1.1</b> Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#dealing-with-issue-of-non-convergence-and-singular-fits"><i class="fa fa-check"></i><b>4.2</b> Dealing with issue of non-convergence and singular fits</a><ul>
<li class="chapter" data-level="4.2.1" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#exercise-2-1"><i class="fa fa-check"></i><b>4.2.1</b> Exercise 2</a></li>
<li class="chapter" data-level="4.2.2" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#exercise-3-1"><i class="fa fa-check"></i><b>4.2.2</b> Exercise 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html"><i class="fa fa-check"></i><b>5</b> Recap &amp; Individual differences</a><ul>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#packages-4"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#lecture-slides-4"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#mixed-model-recap"><i class="fa fa-check"></i>Mixed model recap</a><ul>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#simple-regression"><i class="fa fa-check"></i>Simple regression</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#clustered-multi-level-data-structures"><i class="fa fa-check"></i>Clustered (multi-level) data structures</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#random-intercept-models"><i class="fa fa-check"></i>Random intercept models</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#random-slopes"><i class="fa fa-check"></i>Random slopes</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#fixef-ranef-and-coef"><i class="fa fa-check"></i>Fixef(), Ranef, and Coef</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#more-levels-nested-and-crossed-random-effects"><i class="fa fa-check"></i>More levels: Nested and Crossed random-effects</a></li>
</ul></li>
<li class="chapter" data-level="5.1" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#the-lab"><i class="fa fa-check"></i><b>5.1</b> THE LAB</a><ul>
<li class="chapter" data-level="5.1.1" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#exercise-1-3"><i class="fa fa-check"></i><b>5.1.1</b> Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#exercise-2-2"><i class="fa fa-check"></i><b>5.2</b> Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="break-week.html"><a href="break-week.html"><i class="fa fa-check"></i><b>6</b> <font color="red">Break Week</font></a></li>
<li class="chapter" data-level="7" data-path="efa-and-pca.html"><a href="efa-and-pca.html"><i class="fa fa-check"></i><b>7</b> EFA and PCA</a><ul>
<li class="chapter" data-level="" data-path="efa-and-pca.html"><a href="efa-and-pca.html#packages-5"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="efa-and-pca.html"><a href="efa-and-pca.html#lecture-slides-5"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="7.1" data-path="efa-and-pca.html"><a href="efa-and-pca.html#todays-exercises"><i class="fa fa-check"></i><b>7.1</b> Today’s Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html"><i class="fa fa-check"></i><b>8</b> Confirmatory Factor Analysis (CFA)</a><ul>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#packages-6"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#lecture-slides-6"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#quick-recap"><i class="fa fa-check"></i>Quick recap</a></li>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#data"><i class="fa fa-check"></i>Data</a></li>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#one-factor-model"><i class="fa fa-check"></i>One factor model</a></li>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#two-factor-model"><i class="fa fa-check"></i>Two factor model</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="path-analysis.html"><a href="path-analysis.html"><i class="fa fa-check"></i><b>9</b> Path Analysis</a><ul>
<li class="chapter" data-level="" data-path="path-analysis.html"><a href="path-analysis.html#packages-7"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="path-analysis.html"><a href="path-analysis.html#lecture-slides-7"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="path-analysis.html"><a href="path-analysis.html#quick-recap-1"><i class="fa fa-check"></i>Quick recap</a></li>
<li class="chapter" data-level="" data-path="path-analysis.html"><a href="path-analysis.html#exercises"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="sem-i.html"><a href="sem-i.html"><i class="fa fa-check"></i><b>10</b> SEM I</a><ul>
<li class="chapter" data-level="" data-path="sem-i.html"><a href="sem-i.html#packages-8"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="sem-i.html"><a href="sem-i.html#lecture-slides-8"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="sem-i.html"><a href="sem-i.html#overview"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="sem-i.html"><a href="sem-i.html#exercises-1"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Multivariate Statistics and Methodology using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="recap-individual-differences" class="section level1">
<h1><span class="header-section-number">Chapter 5</span> Recap &amp; Individual differences</h1>
<div id="packages-4" class="section level3 unnumbered">
<h3>Packages</h3>
<ul>
<li>lme4</li>
</ul>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb118-1" title="1"><span class="kw">require</span>(tidyverse)</a>
<a class="sourceLine" id="cb118-2" title="2"><span class="kw">require</span>(lme4)</a>
<a class="sourceLine" id="cb118-3" title="3"><span class="kw">library</span>(lmerTest)</a>
<a class="sourceLine" id="cb118-4" title="4"><span class="kw">library</span>(effects)</a></code></pre></div>
</div>
<div id="lecture-slides-4" class="section level3 unnumbered">
<h3>Lecture Slides</h3>
<ul>
<li>Lecture slides are available <a href="https://uoe-psychology.github.io/uoe_psystats/multivar/lectures/Lecture05_IndivDiffs.html">here</a></li>
</ul>
</div>
<div id="mixed-model-recap" class="section level2 unnumbered">
<h2>Mixed model recap</h2>
<p>In a simple linear regression, there is only considered to be one source of random variability: any variability left unexplained by a set of predictors (which are modelled as fixed estimates) is captured in the model residuals.<br />
<br>
Multi-level (or ‘mixed-effects’) approaches involve modelling more than one source of random variability - as well as variance resulting from taking a random sample of observations, we can identify random variability across different groups of observations. For example, if we are studying a patient population in a hospital, we would expect there to be variability across the our sample of patients, but also across the doctors who treat them.
<br>
We can account for this variability by allowing the outcome to be lower/higher for each group (a random intercept) and by allowing the estimated effect of a predictor vary across groups (random slopes).<br />
<br>
The first part of this lab will guide you through a walkthrough of these concepts, before you tackle some exercises.</p>
<div id="simple-regression" class="section level3 unnumbered">
<h3>Simple regression</h3>
<div class="noteBox">
<p><strong>Formula:</strong></p>
<ul>
<li><span class="math inline">\(Y_i = \beta_0 + \beta_1 X_i + \epsilon_i\)</span></li>
</ul>
<p><strong>R command:</strong></p>
<ul>
<li><code>lm(outcome ~ predictor, data = dataframe)</code></li>
</ul>
<p><em>Note:</em> this is the same as <code>lm(outcome ~ 1 + predictor, data = dataframe)</code>. The <code>1 +</code> is always there unless we specify otherwise (e.g., by using <code>0 +</code>).</p>
</div>
<p><br>
<img src="bookdown-demo_files/figure-html/unnamed-chunk-86-1.png" width="672" /></p>
</div>
<div id="clustered-multi-level-data-structures" class="section level3 unnumbered">
<h3>Clustered (multi-level) data structures</h3>
<p>When our data is clustered (or ‘grouped’) such that datapoints are no longer independent, but belong to some grouping such as that of multiple observations from the same subject, we have multiple sources of random variability. A simple regression does not capture this.</p>
<p>If we separate out our data to show an individual plot for each subject, we can see how the fitted regression line from <code>lm()</code> is assumed to be the same for each subject.</p>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-87-1.png" width="672" /></p>
</div>
<div id="random-intercept-models" class="section level3 unnumbered">
<h3>Random intercept models</h3>
<p>By including a random-intercept term, we are letting our model estimate random variability around an average parameter (represented by the fixed effects) for the clusters.</p>
<div class="noteBox">
<p><strong>Formula:</strong><br />
Level 1:</p>
<ul>
<li><span class="math inline">\(Y_{ij} = \beta_{0j} + \beta_{1j}X_{ij} + \epsilon_{ij}\)</span></li>
</ul>
<p>Level 2:</p>
<ul>
<li><span class="math inline">\(\beta_{0j} = \gamma_{00} + u_{0j}\)</span></li>
</ul>
<p>Where the expected values of <span class="math inline">\(u_0\)</span>, and <span class="math inline">\(\epsilon\)</span> are 0, and their variances are <span class="math inline">\(\sigma_{u_0}^2\)</span> and <span class="math inline">\(\sigma_\epsilon^2\)</span> respectively. We will further assume that these are normally distributed.</p>
<p>We can now see that the <span class="math inline">\(\beta_0\)</span> estimate for a particular group <span class="math inline">\(j\)</span> is represented by the combination of a mean estimate for the parameter (<span class="math inline">\(\gamma_{00}\)</span>) and a random effect for that group (<span class="math inline">\(u_{0j}\)</span>).</p>
<p><strong>R command:</strong></p>
<ul>
<li><code>lmer(outcome ~ predictor + (1 | grouping), data = dataframe)</code></li>
</ul>
</div>
<p>Notice how the fitted line of the random intercept model has an adjustment for each subject.<br />
Each subject’s line has been moved up or down accordingly.</p>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-88-1.png" width="1152" /></p>
<div class="lo">
<h4 id="shrinkage" class="unnumbered">Shrinkage</h4>
<p>If you think about it, we might have done a similar thing with the tools we already had at our disposal, by using <code>lm(y~x+subject)</code>.<br />
This would give us a coefficient for the difference between each subject and the reference level intercept.</p>
<p>However, the estimate of these models will be slightly different:</p>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-89-1.png" width="672" /></p>
<p><strong>Why?</strong> One of the benefits of multi-level models is that our cluster-level estimates are shrunk towards the average depending on a) the level of across-cluster variation and b) the number of datapoints in clusters.</p>
</div>
</div>
<div id="random-slopes" class="section level3 unnumbered">
<h3>Random slopes</h3>
<div class="noteBox">
<p><strong>Formula:</strong><br />
Level 1:</p>
<ul>
<li><span class="math inline">\(Y_{ij} = \beta_{0j} + \beta_{1j}X_{ij} + \epsilon_{ij}\)</span></li>
</ul>
<p>Level 2:</p>
<ul>
<li><span class="math inline">\(\beta_{0j} = \gamma_{00} + u_{0j}\)</span><br />
</li>
<li><span class="math inline">\(\beta_{1j} = \gamma_{10} + u_{1j}\)</span></li>
</ul>
<p>Where the expected values of <span class="math inline">\(u_0\)</span>, <span class="math inline">\(u_1\)</span>, and <span class="math inline">\(\epsilon\)</span> are 0, and their variances are <span class="math inline">\(\sigma_{u_0}^2\)</span>, <span class="math inline">\(\sigma_{u_1}^2\)</span>, <span class="math inline">\(\sigma_\epsilon^2\)</span> respectively. We will further assume that these are normally distributed.</p>
<p>As with the intercept <span class="math inline">\(\beta_0\)</span>, the slope of the predictor <span class="math inline">\(\beta_1\)</span> is now modelled by a mean and a random effect for each group (<span class="math inline">\(u_{1j}\)</span>).</p>
<p><strong>R command:</strong></p>
<ul>
<li><code>lmer(outcome ~ predictor + (1 + predictor | grouping), data = dataframe)</code></li>
</ul>
<p><em>Note:</em> this is the same as <code>lmer(outcome ~ predictor + (predictor | grouping), data = dataframe)</code> . Like in the fixed-effects part, the <code>1 +</code> is assumed in the random-effects part.</p>
</div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-90-1.png" width="1152" /></p>
</div>
<div id="fixef-ranef-and-coef" class="section level3 unnumbered">
<h3>Fixef(), Ranef, and Coef</h3>
<p>The plots below show the fitted values from each model for each subject:</p>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-91-1.png" width="1152" /></p>
<p>In the random-intercept model (center panel), the differences from each of the subjects’ intercepts to the fixed intercept (thick green line) have mean 0 and standard deviation <span class="math inline">\(\sigma_u\)</span>. The standard deviation (and variance, which is <span class="math inline">\(\sigma_u^2\)</span>) is what we see in the random effects part of our model summary (or using the <code>VarCorr()</code> function).</p>
<p><img src="images/varcors.PNG" width="400px" /></p>
<p>In the random-slope model (right panel), the same is true for the differences from each subjects’ slope to the fixed slope.</p>
<div class="solution">
<p class="solution-begin">
► Fixed effects<span id="sol-start-234" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-234&#39;, &#39;sol-start-234&#39;)"></span>
</p>
<div id="sol-body-234" class="solution-body" style="display: none;">
<p>We can extract the <em>fixed effects</em> using the <code>fixef()</code> function:</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb119-1" title="1"><span class="kw">fixef</span>(random_intercept_model)</a></code></pre></div>
<pre><code>## (Intercept)          x1 
## 413.3736136  -0.9135829</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Random effects<span id="sol-start-235" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-235&#39;, &#39;sol-start-235&#39;)"></span>
</p>
<div id="sol-body-235" class="solution-body" style="display: none;">
<p>We can extract the deviations for each group from these fixed effect estimates using the <code>ranef()</code> function.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb121-1" title="1"><span class="kw">ranef</span>(random_intercept_model)</a></code></pre></div>
<pre><code>## $subject
##         (Intercept)
## sub_308  -29.278163
## sub_309   -6.830994
## sub_310    8.492231
## sub_330   78.673944
## sub_331   84.713164
## sub_332   82.639416
## sub_333   91.245686
## sub_334  -74.788101
## sub_335   27.022779
## sub_337    3.361008
## sub_349  -93.706202
## sub_350  -57.004012
## sub_351   65.920694
## sub_352  -33.857447
## sub_369  -64.358442
## sub_370  -78.286762
## sub_371   70.669067
## sub_372  -52.841464
## sub_373 -119.756827
## sub_374   97.970426
## 
## with conditional variances for &quot;subject&quot;</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Group-level coefficients<span id="sol-start-236" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-236&#39;, &#39;sol-start-236&#39;)"></span>
</p>
<div id="sol-body-236" class="solution-body" style="display: none;">
<p>We can also see the estimate for each subject directly, using the <code>coef()</code> function.<br />
These sometimes get referred to as “Best Linear Unbiased Estimates (BLUPS)”.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb123-1" title="1"><span class="kw">coef</span>(random_intercept_model)</a></code></pre></div>
<pre><code>## $subject
##         (Intercept)         x1
## sub_308    384.0955 -0.9135829
## sub_309    406.5426 -0.9135829
## sub_310    421.8658 -0.9135829
## sub_330    492.0476 -0.9135829
## sub_331    498.0868 -0.9135829
## sub_332    496.0130 -0.9135829
## sub_333    504.6193 -0.9135829
## sub_334    338.5855 -0.9135829
## sub_335    440.3964 -0.9135829
## sub_337    416.7346 -0.9135829
## sub_349    319.6674 -0.9135829
## sub_350    356.3696 -0.9135829
## sub_351    479.2943 -0.9135829
## sub_352    379.5162 -0.9135829
## sub_369    349.0152 -0.9135829
## sub_370    335.0869 -0.9135829
## sub_371    484.0427 -0.9135829
## sub_372    360.5321 -0.9135829
## sub_373    293.6168 -0.9135829
## sub_374    511.3440 -0.9135829
## 
## attr(,&quot;class&quot;)
## [1] &quot;coef.mer&quot;</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Plotting random effects<span id="sol-start-237" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-237&#39;, &#39;sol-start-237&#39;)"></span>
</p>
<div id="sol-body-237" class="solution-body" style="display: none;">
<p>The quick and easy way to plot your random effects is to use the <code>dotplot.ranef.mer()</code> function in <code>lme4</code>.</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb125-1" title="1">randoms &lt;-<span class="st"> </span><span class="kw">ranef</span>(random_intercept_model, <span class="dt">condVar=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb125-2" title="2"></a>
<a class="sourceLine" id="cb125-3" title="3"><span class="kw">dotplot.ranef.mer</span>(randoms)</a></code></pre></div>
<pre><code>## $subject</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-96-1.png" width="672" /></p>
<!-- Sometimes, however, we might want to have a bit more control over our plotting, we can extract the estimates and correlations for each subject using the `condVar=TRUE`: -->
<p>–&gt;
<!-- ```{r} -->
<!-- #we can get the random effects: -->
<!-- #(note that we use $subject because there might be other groupings, and the ranef() function will give us a list, with one element for each grouping variable) -->
<!-- randoms <-  -->
<!--   ranef(random_slopes_model)$subject %>% -->
<!--   mutate(subject = row.names(randoms)) %>%  # the subject IDs are stored in the rownames, so lets add them as a variable -->
<!--   pivot_longer(cols=1:2, names_to="term",values_to="estimate") # finally, let's reshape it for plotting --></p>
<!-- #and the same for the standard errors (from the arm package): -->
<!-- randoms_se <-  -->
<!--   se.ranef(random_slopes_model)$subject %>% -->
<!--   enframe %>% -->
<!--   mutate(subject = row.names(randoms_se)) %>% -->
<!--   pivot_longer(cols=1:2, names_to="term",values_to="se") -->
<!-- # join them together: -->
<!-- left_join(randoms, randoms_se) -->
<!-- # it's easier for plotting if we  -->
<!-- ggplot(ranefs_plotting, aes(y=)) -->
<!-- ``` -->
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
<div id="more-levels-nested-and-crossed-random-effects" class="section level3 unnumbered">
<h3>More levels: Nested and Crossed random-effects</h3>
<p>The same principle we have seen for one level of clustering can be extended to clustering at different levels (for instance, observations are clustered within subjects, which are in turn clustered within groups).</p>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>Consider the example where we have observations for each student in every class within a number of schools:</p>
<p><img src="images/structure_id.png" width="1200px" /></p>
<p>Is “Class 1” in “School 1” the same as “Class 1” in “School 2”?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-238" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-238&#39;, &#39;sol-start-238&#39;)"></span>
</p>
<div id="sol-body-238" class="solution-body" style="display: none;">
<p>No.<br />
<br>
The classes in one school are distinct from the classes in another <em>even though they are named the same</em>.</p>
<p>The classes-within-schools example is a good case of <strong>nested random effects</strong> - one factor level (one group in a grouping varible) appears <em>only within</em> a particular level of another grouping variable.</p>
<p>In R, we can specify this using:</p>
<p><code>(1 | school) + (1 | class:school)</code></p>
<p>or, more succinctly:</p>
<p><code>(1 | school/class)</code></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question
</p>
<div class="question-body">
<p>Consider another example, where we administer the same set of tasks at multiple time-points for every participant.<br />
Are tasks nested within participants?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-239" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-239&#39;, &#39;sol-start-239&#39;)"></span>
</p>
<div id="sol-body-239" class="solution-body" style="display: none;">
<p>No - tasks are seen by multiple participants (and participants see multiple tasks).</p>
<p>We could visualise this as the below:<br />
<img src="images/structure_crossed.png" width="400px" /></p>
<p>In the sense that these are not nested, they are <strong>crossed</strong> random effects.</p>
<p>In R, we can specify this using:</p>
<p><code>(1 | subject) + (1 | task)</code></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="red">
<h4 id="nested-vs-crossed" class="unnumbered">Nested vs Crossed</h4>
<p><em>Nested:</em> Each group belongs uniquely to a higher-level group.</p>
<p><em>Crossed:</em> Not-nested.</p>
</div>
<p>Note that in the schools and classes example, had we changed data such that the classes had unique IDs (e.g., see below), then the structures <code>(1 | school) + (1 | class)</code> and <code>(1 | school/class)</code> would give the same results.<br />
<img src="images/structure_nested.png" width="1200px" /></p>
<!-- ## Fitting models   -->
<!-- A simple regression can be solved using *Ordinary Least Squares (OLS)*, to find the values of $\beta_0$ and $\beta_1$ which minimise the sum of the squared residuals (the distance from the predicted values of $y$ to the observed values of $y$). -->
<!-- We saw in USMR that we could extend the principles of linear regression to non-numeric outcomes such as a binomial variable. In this case, we modelled the log-odds, and we left OLS behind in favour of *Maximum Likelihood Estimation (MLE)*. MLE can only be found by *numerical optimization*. Optimisation consists of maximising/minimising a function through iteration (choosing a set of input values, computing the output of the function, and refitting). In its simplest form, think of it as finding the highest or lowest point of a curve.   -->
<!-- Maximum likelihood estimation:  -->
<!-- 1. Begin with some an initial guess (start values) for parameter values. -->
<!-- 1. Compute the log-likelihood, and adjust the guess at parameter values. (Each time this is done is an *iteration*) -->
<!-- 1. Recompute the likelihood. -->
<!-- 1. Repeat until improvements in likelihood value are neglible across iterations -->
<!-- When we have multiple parameters, this problem becomes a lot more complex as likelihood is not a simple curve but a mult-dimensional  -->
<!-- There are different approaches to optimisation. For our purposes, this means that we have a choice of optimisers. Some may converge (find a solution) when other's don't. See [Week 4](#other-random-effects-structures) for more details on convergence.   -->
<hr />
<hr />
</div>
</div>
<div id="the-lab" class="section level2">
<h2><span class="header-section-number">5.1</span> THE LAB</h2>
<div class="red">
<h4 id="the-data-3" class="unnumbered">The data</h4>
<p>44 participants across 4 groups (between-subjects) were tested 5 times (waves) in 11 domains.
In each wave, participants received a score (on a 20-point scale) for each domain and a set of questions which were they answered either correctly or incorrectly.</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb127-1" title="1"><span class="kw">load</span>(<span class="kw">url</span>(<span class="st">&quot;https://edin.ac/2Hd6V4Q&quot;</span>))</a>
<a class="sourceLine" id="cb127-2" title="2"></a>
<a class="sourceLine" id="cb127-3" title="3"><span class="kw">summary</span>(dat5)</a></code></pre></div>
<pre><code>##  Anonymous_Subject_ID   IndivDiff          Wave          Domain             Correct           Error            Group          
##  Length:2011          Min.   :39.30   Min.   :1.000   Length:2011        Min.   : 0.000   Min.   :0.00000   Length:2011       
##  Class :character     1st Qu.:69.20   1st Qu.:2.000   Class :character   1st Qu.: 4.000   1st Qu.:0.00000   Class :character  
##  Mode  :character     Median :79.70   Median :3.000   Mode  :character   Median : 8.000   Median :0.00000   Mode  :character  
##                       Mean   :77.73   Mean   :2.712                      Mean   : 9.904   Mean   :0.06216                     
##                       3rd Qu.:88.10   3rd Qu.:4.000                      3rd Qu.:12.000   3rd Qu.:0.00000                     
##                       Max.   :95.20   Max.   :5.000                      Max.   :45.000   Max.   :1.00000                     
##                       NA&#39;s   :1474                                                                                            
##      Score     
##  Min.   : 0.0  
##  1st Qu.: 8.0  
##  Median :14.0  
##  Mean   :12.2  
##  3rd Qu.:17.0  
##  Max.   :20.0  
## </code></pre>
</div>
<div id="exercise-1-3" class="section level3">
<h3><span class="header-section-number">5.1.1</span> Exercise 1</h3>
<div class="lo">
<h4 id="research-question" class="unnumbered">Research question</h4>
<p>Did the groups differ in overall performance?</p>
</div>
<p>There are different ways to test this: use the 20-point score or the accuracy? Keep the domains separate or calculate an aggregate across all domains? Which way makes the most sense to you?</p>
<div class="question">
<p class="question-begin">
► Question 1
</p>
<div class="question-body">
<p>Make a plot that corresponds to the reseach question. Does it look like there’s a difference?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-240" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-240&#39;, &#39;sol-start-240&#39;)"></span>
</p>
<div id="sol-body-240" class="solution-body" style="display: none;">
<p>Lots of options for this one, here is one that shows Group and Domain differences:</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb129-1" title="1"><span class="kw">ggplot</span>(dat5, <span class="kw">aes</span>(Domain, Score, <span class="dt">color=</span>Group)) <span class="op">+</span></a>
<a class="sourceLine" id="cb129-2" title="2"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data=</span>mean_se, <span class="dt">geom=</span><span class="st">&quot;pointrange&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb129-3" title="3"><span class="st">  </span><span class="kw">coord_flip</span>()</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-101-1.png" width="672" /></p>
<p>Looks like there are group differences and domain differences, but not much in the way of group-by-domain differences.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question 2
</p>
<div class="question-body">
<p>Use a mixed-effects model to test the difference.</p>
<ul>
<li>Will you use a linear or logistic model?</li>
<li>What should the fixed(s) effect be?</li>
<li>What should the random effect(s) be? We have observations clustered by subjects and by domains - are they nested?</li>
</ul>
<p><em>Tip:</em> For now, forget about the longitudinal aspect to the data.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-241" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-241&#39;, &#39;sol-start-241&#39;)"></span>
</p>
<div id="sol-body-241" class="solution-body" style="display: none;">
<p>We’re interested in the amount to which Groups vary in their overall performance, so we want a fixed effect of Group. Subjects and Domains are not nested - each subject sees different domains, and each domain is seen by multiple subjects.</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" title="1"><span class="co"># maximal model doesn&#39;t converge, removed random Group slopes for Domain</span></a>
<a class="sourceLine" id="cb130-2" title="2">mod_grp &lt;-<span class="st"> </span><span class="kw">lmer</span>(Score <span class="op">~</span><span class="st"> </span>Group <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb130-3" title="3"><span class="st">                   </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>Anonymous_Subject_ID) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb130-4" title="4"><span class="st">                   </span>(<span class="dv">1</span> <span class="op">|</span><span class="st"> </span>Domain), </a>
<a class="sourceLine" id="cb130-5" title="5">                 <span class="dt">data=</span>dat5, <span class="dt">REML=</span><span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb130-6" title="6"><span class="kw">summary</span>(mod_grp)</a></code></pre></div>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: Score ~ Group + (1 | Anonymous_Subject_ID) + (1 | Domain)
##    Data: dat5
## 
##      AIC      BIC   logLik deviance df.resid 
##  10398.2  10437.5  -5192.1  10384.2     2004 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -5.0251 -0.4981  0.0639  0.6338  3.2779 
## 
## Random effects:
##  Groups               Name        Variance Std.Dev.
##  Anonymous_Subject_ID (Intercept) 19.486   4.414   
##  Domain               (Intercept)  1.064   1.031   
##  Residual                          9.122   3.020   
## Number of obs: 2011, groups:  Anonymous_Subject_ID, 44; Domain, 11
## 
## Fixed effects:
##             Estimate Std. Error     df t value Pr(&gt;|t|)    
## (Intercept)   15.832      1.121 50.067  14.122  &lt; 2e-16 ***
## GroupB        -4.159      2.262 44.369  -1.839   0.0727 .  
## GroupC        -3.621      1.768 43.968  -2.048   0.0465 *  
## GroupW        -7.270      1.673 44.042  -4.345 8.09e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##        (Intr) GroupB GroupC
## GroupB -0.457              
## GroupC -0.585  0.290       
## GroupW -0.618  0.306  0.392</code></pre>
<p>Yes, substantial Group differences: overall, group A does the best, group B is slightly behind, group C next, and group W does the worst.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
</div>
</div>
<div id="exercise-2-2" class="section level2">
<h2><span class="header-section-number">5.2</span> Exercise 2</h2>
<div class="lo">
<h4 id="research-question-1" class="unnumbered">Research question</h4>
<p>Did performance change over time (across waves)? Did the groups differ in pattern of change?</p>
</div>
<div class="question">
<p class="question-begin">
► Question 3
</p>
<div class="question-body">
<p>Make a plot that corresponds to the reseach question. Does it look like there was a change? A group difference?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-242" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-242&#39;, &#39;sol-start-242&#39;)"></span>
</p>
<div id="sol-body-242" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb132"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb132-1" title="1"><span class="kw">ggplot</span>(dat5, <span class="kw">aes</span>(Wave, Score, <span class="dt">color=</span>Group, <span class="dt">fill=</span>Group)) <span class="op">+</span></a>
<a class="sourceLine" id="cb132-2" title="2"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data=</span>mean_se, <span class="dt">geom=</span><span class="st">&quot;ribbon&quot;</span>, <span class="dt">alpha=</span><span class="fl">0.3</span>, <span class="dt">color=</span><span class="ot">NA</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb132-3" title="3"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.y=</span>mean, <span class="dt">geom=</span><span class="st">&quot;line&quot;</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-103-1.png" width="480" /></p>
<p>Yes, looks like groups A, C, and W are improving, but group B is getting worse.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question 4
</p>
<div class="question-body">
<p>Use mixed-effects model(s) to test this.<br />
<br>
<em>Hint:</em> Fit a baseline model in which scores change over time (wave), then assess improvement in model fit due to inclusion of overall group effect and finally the interaction of group with time.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-243" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-243&#39;, &#39;sol-start-243&#39;)"></span>
</p>
<div id="sol-body-243" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb133-1" title="1">mod_wv &lt;-<span class="st"> </span><span class="kw">lmer</span>(Score <span class="op">~</span><span class="st"> </span>Wave <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb133-2" title="2"><span class="st">                   </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>Wave <span class="op">|</span><span class="st"> </span>Anonymous_Subject_ID) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb133-3" title="3"><span class="st">                   </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>Wave <span class="op">|</span><span class="st"> </span>Domain), </a>
<a class="sourceLine" id="cb133-4" title="4">                 <span class="dt">data=</span>dat5, <span class="dt">REML=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb133-5" title="5">                 <span class="kw">lmerControl</span>(<span class="dt">optimizer =</span> <span class="st">&quot;bobyqa&quot;</span>))</a>
<a class="sourceLine" id="cb133-6" title="6"></a>
<a class="sourceLine" id="cb133-7" title="7">mod_wv_grp &lt;-<span class="st"> </span><span class="kw">lmer</span>(Score <span class="op">~</span><span class="st"> </span>Wave<span class="op">+</span>Group <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb133-8" title="8"><span class="st">                   </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>Wave <span class="op">|</span><span class="st"> </span>Anonymous_Subject_ID) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb133-9" title="9"><span class="st">                   </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>Wave <span class="op">|</span><span class="st"> </span>Domain), </a>
<a class="sourceLine" id="cb133-10" title="10">                 <span class="dt">data=</span>dat5, <span class="dt">REML=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb133-11" title="11">                 <span class="kw">lmerControl</span>(<span class="dt">optimizer =</span> <span class="st">&quot;bobyqa&quot;</span>))</a>
<a class="sourceLine" id="cb133-12" title="12"></a>
<a class="sourceLine" id="cb133-13" title="13">mod_wv_x_grp &lt;-<span class="st"> </span><span class="kw">lmer</span>(Score <span class="op">~</span><span class="st"> </span>Wave<span class="op">*</span>Group <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb133-14" title="14"><span class="st">                   </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>Wave <span class="op">|</span><span class="st"> </span>Anonymous_Subject_ID) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb133-15" title="15"><span class="st">                   </span>(<span class="dv">1</span> <span class="op">+</span><span class="st"> </span>Wave <span class="op">|</span><span class="st"> </span>Domain), </a>
<a class="sourceLine" id="cb133-16" title="16">                 <span class="dt">data=</span>dat5, <span class="dt">REML=</span><span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb133-17" title="17">                 <span class="kw">lmerControl</span>(<span class="dt">optimizer =</span> <span class="st">&quot;bobyqa&quot;</span>))</a>
<a class="sourceLine" id="cb133-18" title="18"></a>
<a class="sourceLine" id="cb133-19" title="19"><span class="kw">anova</span>(mod_wv, mod_wv_grp, mod_wv_x_grp)</a></code></pre></div>
<pre><code>## Data: dat5
## Models:
## mod_wv: Score ~ Wave + (1 + Wave | Anonymous_Subject_ID) + (1 + Wave | 
## mod_wv:     Domain)
## mod_wv_grp: Score ~ Wave + Group + (1 + Wave | Anonymous_Subject_ID) + (1 + 
## mod_wv_grp:     Wave | Domain)
## mod_wv_x_grp: Score ~ Wave * Group + (1 + Wave | Anonymous_Subject_ID) + (1 + 
## mod_wv_x_grp:     Wave | Domain)
##              Df    AIC    BIC  logLik deviance   Chisq Chi Df Pr(&gt;Chisq)   
## mod_wv        9 9719.6 9770.1 -4850.8   9701.6                             
## mod_wv_grp   12 9710.3 9777.6 -4843.1   9686.3 15.3456      3   0.001544 **
## mod_wv_x_grp 15 9710.5 9794.6 -4840.2   9680.5  5.8105      3   0.121204   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb135-1" title="1"><span class="kw">summary</span>(mod_wv_x_grp)</a></code></pre></div>
<pre><code>## Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite&#39;s method [&#39;lmerModLmerTest&#39;]
## Formula: Score ~ Wave * Group + (1 + Wave | Anonymous_Subject_ID) + (1 +      Wave | Domain)
##    Data: dat5
## Control: lmerControl(optimizer = &quot;bobyqa&quot;)
## 
##      AIC      BIC   logLik deviance df.resid 
##   9710.5   9794.6  -4840.2   9680.5     1996 
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -5.0053 -0.5764  0.0049  0.6132  3.7519 
## 
## Random effects:
##  Groups               Name        Variance Std.Dev. Corr 
##  Anonymous_Subject_ID (Intercept) 22.36604 4.7293        
##                       Wave         0.74787 0.8648   -0.34
##  Domain               (Intercept)  2.05332 1.4329        
##                       Wave         0.02189 0.1479   -0.99
##  Residual                          6.06856 2.4634        
## Number of obs: 2011, groups:  Anonymous_Subject_ID, 44; Domain, 11
## 
## Fixed effects:
##             Estimate Std. Error       df t value Pr(&gt;|t|)    
## (Intercept) 12.77276    1.24928 52.57242  10.224 4.23e-14 ***
## Wave         1.25475    0.23886 44.74521   5.253 4.00e-06 ***
## GroupB      -1.36480    2.47446 45.83802  -0.552  0.58393    
## GroupC      -4.14669    1.91661 43.86581  -2.164  0.03599 *  
## GroupW      -6.31853    1.81665 44.18633  -3.478  0.00115 ** 
## Wave:GroupB -1.14231    0.52920 50.14297  -2.159  0.03570 *  
## Wave:GroupC -0.03687    0.36863 36.73490  -0.100  0.92087    
## Wave:GroupW -0.50887    0.35468 38.78415  -1.435  0.15937    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) Wave   GroupB GroupC GroupW Wv:GrB Wv:GrC
## Wave        -0.412                                          
## GroupB      -0.444  0.175                                   
## GroupC      -0.574  0.226  0.290                            
## GroupW      -0.605  0.239  0.306  0.395                     
## Wave:GroupB  0.157 -0.436 -0.389 -0.102 -0.108              
## Wave:GroupC  0.225 -0.625 -0.114 -0.366 -0.155  0.282       
## Wave:GroupW  0.234 -0.650 -0.118 -0.153 -0.370  0.293  0.421</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question 5
</p>
<div class="question-body">
<p>Plot the group-level data (see Question 3) and model fitted values for each group from your final model from Question 4.<br />
<br>
<em>Hint:</em> using <code>fortify(model)</code> or <code>broom::augment(model)</code> as your starting point will help.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-244" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-244&#39;, &#39;sol-start-244&#39;)"></span>
</p>
<div id="sol-body-244" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb137-1" title="1"><span class="kw">ggplot</span>(<span class="kw">fortify</span>(mod_wv_x_grp), <span class="kw">aes</span>(Wave, Score, <span class="dt">color=</span>Group)) <span class="op">+</span></a>
<a class="sourceLine" id="cb137-2" title="2"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data=</span>mean_se, <span class="dt">geom=</span><span class="st">&quot;pointrange&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb137-3" title="3"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="kw">aes</span>(<span class="dt">y=</span>.fitted), <span class="dt">fun.y=</span>mean, <span class="dt">geom=</span><span class="st">&quot;line&quot;</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-105-1.png" width="672" /></p>
<p><em>We fit a linear model, but the model fit lines are not straight lines. Why is that?</em></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question 6
</p>
<div class="question-body">
<p>Create individual subject plots for the data and the model’s fitted values. Will these show straight lines?<br />
<br>
<em>Hint:</em> make use of <code>facet_wrap()</code> to create a different panel for each level of a grouping variable.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-245" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-245&#39;, &#39;sol-start-245&#39;)"></span>
</p>
<div id="sol-body-245" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb138-1" title="1"><span class="kw">ggplot</span>(<span class="kw">fortify</span>(mod_wv_x_grp), <span class="kw">aes</span>(Wave, Score, <span class="dt">color=</span>Group)) <span class="op">+</span></a>
<a class="sourceLine" id="cb138-2" title="2"><span class="st">  </span><span class="kw">facet_wrap</span>(<span class="op">~</span><span class="st"> </span>Anonymous_Subject_ID) <span class="op">+</span></a>
<a class="sourceLine" id="cb138-3" title="3"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data=</span>mean_se, <span class="dt">geom=</span><span class="st">&quot;pointrange&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb138-4" title="4"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="kw">aes</span>(<span class="dt">y=</span>.fitted), <span class="dt">fun.y=</span>mean, <span class="dt">geom=</span><span class="st">&quot;line&quot;</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-106-1.png" width="672" /></p>
<p>The individual subject plots show linear fits, which is a better match to the model. But now we see the missing data – some participants only completed the first few waves.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question 7
</p>
<div class="question-body">
<p>Make a plot of the actual (linear) model prediction.<br />
<br>
<em>Hint:</em> Use the <code>effect()</code> function from the <code>effects</code> package.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-246" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-246&#39;, &#39;sol-start-246&#39;)"></span>
</p>
<div id="sol-body-246" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb139-1" title="1">ef &lt;-<span class="st"> </span><span class="kw">as.data.frame</span>(<span class="kw">effect</span>(<span class="st">&quot;Wave:Group&quot;</span>, mod_wv_x_grp))</a>
<a class="sourceLine" id="cb139-2" title="2"><span class="kw">ggplot</span>(ef, <span class="kw">aes</span>(Wave, fit, <span class="dt">color=</span>Group, <span class="dt">fill=</span>Group)) <span class="op">+</span></a>
<a class="sourceLine" id="cb139-3" title="3"><span class="st">  </span><span class="kw">geom_ribbon</span>(<span class="kw">aes</span>(<span class="dt">ymax=</span>fit<span class="op">+</span>se, <span class="dt">ymin=</span>fit<span class="op">-</span>se), <span class="dt">color=</span><span class="ot">NA</span>, <span class="dt">alpha=</span><span class="fl">0.1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb139-4" title="4"><span class="st">  </span><span class="kw">geom_line</span>()</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-107-1.png" width="672" /></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question 8
</p>
<div class="question-body">
<p>What important things are different between the plot from question 7 and that from question 5?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution
</p>
<div class="solution-body">
<p><em>Group B was not actually getting worse. The appearance that it was getting worse is an artifact of selective drop-out: there’s only a few people in this group and the better-performing ones only did the first few waves so they are not represented in the later waves, but the worse-performing ones are contributing to the later waves. The model estimates how the better-performing ones would have done in later waves based on their early-wave performance and the pattern of performance of other participants in the study.</em></p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb140-1" title="1"><span class="kw">summary</span>(mod_wv_x_grp)<span class="op">$</span>coefficients</a></code></pre></div>
<pre><code>##                Estimate Std. Error       df    t value     Pr(&gt;|t|)
## (Intercept) 12.77275565  1.2492775 52.57242 10.2241143 4.233953e-14
## Wave         1.25474611  0.2388610 44.74521  5.2530381 3.998024e-06
## GroupB      -1.36479858  2.4744579 45.83802 -0.5515546 5.839325e-01
## GroupC      -4.14668919  1.9166107 43.86581 -2.1635532 3.598767e-02
## GroupW      -6.31853259  1.8166464 44.18633 -3.4781301 1.146411e-03
## Wave:GroupB -1.14230833  0.5292011 50.14297 -2.1585523 3.569665e-02
## Wave:GroupC -0.03687025  0.3686301 36.73490 -0.1000196 9.208726e-01
## Wave:GroupW -0.50887203  0.3546769 38.78415 -1.4347482 1.593740e-01</code></pre>
<p>Note that the Group A slope (coefficient for <code>Wave</code>) is 1.255 and, relative to that slope, the Group B slope is -1.142 (coefficient for <code>Wave:GroupB</code>). This means that the model-estimated slope for Group B is 0.112, which is very slightly positive, not strongly negative as appeared in the initial plots.</p>
<p>One of the valuable things about mixed-effects (aka multilevel) modeling is that individual-level and group-level trajectories are estimated. This helps the model overcome missing data in a sensible way. In fact, MLM/MLR models are sometimes used for imputing missing data. However, one has to think carefully about <em>why</em> data are missing. Group B is small and it might just be a coincidence that the better-performing participants dropped out after the first few waves, which would make it easier to generalize the patterns to them. On the other hand, it might be the case that there is something about the study that makes better-performing members of Group B drop out, which should make us suspicious of generalizing to them.</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<hr />
<div class="question">
<p class="question-begin">
► Question 9
</p>
<div class="question-body">
<p>Create a plot of the subject and domain random effects.
Notice the pattern between the random intercept and random slope estimates for the 11 domains - what in our model is this pattern representing?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-248" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-248&#39;, &#39;sol-start-248&#39;)"></span>
</p>
<div id="sol-body-248" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb142-1" title="1">randoms &lt;-<span class="st"> </span><span class="kw">ranef</span>(mod_wv_x_grp, <span class="dt">condVar=</span><span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb142-2" title="2"><span class="kw">dotplot.ranef.mer</span>(randoms)</a></code></pre></div>
<pre><code>## $Anonymous_Subject_ID</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-110-1.png" width="672" /></p>
<pre><code>## 
## $Domain</code></pre>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-110-2.png" width="672" /></p>
<p>Notice that the domains with the lower relative intercept tend to have a higher relative slope (and vice versa). This is the negative correlation between random intercepts and slopes for domain in our model:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb145-1" title="1"><span class="kw">VarCorr</span>(mod_wv_x_grp)</a></code></pre></div>
<pre><code>##  Groups               Name        Std.Dev. Corr  
##  Anonymous_Subject_ID (Intercept) 4.72927        
##                       Wave        0.86479  -0.336
##  Domain               (Intercept) 1.43294        
##                       Wave        0.14795  -0.993
##  Residual                         2.46344</code></pre>
<p>Try removing the correlation (hint: use the <code>||</code>) to see what happens. Does it make sense that these would be correlated? (Answer: we don’t really know enough about the study, but it’s something to think about!)</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="other-random-effects-structures.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="break-week.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/lunr.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
