---
title: "Week 17: Two-sample t-test (independent samples)"
output: html_document
---


# A. Walkthrough: Got a friend?


## Question A.1

Identify the observational units in this study.  

**Solution**

...


## Question A.2

- Identify the recorded variables in this study.
- Classify each variable either as categorical (also binary) or quantitative.
- Identify each variable's role: explanatory or response.

**Solution**

| Variable's name | Type            | Role            |
|:----------------|:----------------|:----------------|
| ?               | ?               | ?               |
| ?               | ?               | ?               |



## Question A.3

Did the study make use of random assignment, random sampling, both or neither?

**Solution**

...


## Question A.4

Is this an observational study or an experiment? Explain why.

**Solution**

...



## Question A.5

State, in words, the null and alternative hypotheses to test whether the sample data provide evidence that American males and females tend to differ with regard to the average number of close friends they mention.

**Solution**

...


## Question A.6

Define the parameters of interest in this study, and identify appropriate symbols for them.

**Solution**

...


## Question A.7

State the null and alternative hypotheses in symbols.

**Solution**

...


## Question A.8

Explain why the one-sample $t$-test is not appropriate to answer the research question of this study.

**Solution**

...


## Question A.9

Load the data into R and inspect it. The data are stored at the following link: https://edin.ac/2vQrCBi

Pay particular attention to:

- the variable names;
- the dimensions of the tibble;
- the format of the data (i.e., make sure that variables are correctly encoded).

**Solution**

...



## Question A.10

Summarise the survey responses by showing the counts of the number of close friends by sex.

Try sketching by hand histograms showing, for each sex, the frequency of each reported number of close friends.

**Solution**

...


## Question A.11

Report a table of descriptive summaries by sex.

Include the sample size, mean, SD, minimum, lower quartile, median, upper quartile, and maximum for each sex.

**Solution**

...


## Question A.12

Are the descriptive summaries from the previous question parameters or statistics? Explain why.

**Solution**

...


## Question A.13

Produce a visual display of the five-number summaries by sex.

**Solution**

...


## Question A.14

Visualise the distribution of the number of close friends by sex.

**Solution**

...


## Question A.15

Comment on what the histograms reveal about the shapes of the distributions.

**Solution**

...


## Question A.16

Report the sample mean and sample standard deviation of the number of close friends for each sex using appropriate symbols.

**Solution**

...


## Question A.17

Compute the difference in the sample mean number of close friends between females and males.

Do you think it could be possible to obtain sample means this far apart even if the population means were actually equal? Explain why.

**Solution**

...


## Question A.18

Use the summary statistics computed in Question A.11 to calculate the value of the $t$-statistic for testing the hypotheses stated in Question A.7.

**Solution**

...


## Question A.19

Compare the $t$-statistic with the appropriate 5% critical value from a $t$-distribution. 

Compute the $p$-value and interpret the results.

**Solution**

...


## Question A.20

Verify your results using the built-in R function `t.test`. 

Before applying it though, you need to check with `var.test` whether the population variances are different or can be assumed to be equal.

**Solution**

...


## Question A.21

State the assumptions of the two-sample $t$-test.

Should the strong skewness in the sample distributions cause you any concerns about the validity of your results?

**Solution**

...


## Question A.22

Now that we have established that there is significant evidence of a difference in the population mean number of close friends between females and males, what is the magnitude of this difference in the population means?

Construct and interpret a 95% confidence interval for the difference in population mean number of close friends between females and males.

Pay particular attention on whether the interval is negative, positive, or contains zero.

**Solution**

...


## Question A.23

_Causation:_ Do the data provide evidence that how many close friends one has is _caused_ by ones' sex? Explain why.

**Solution**

...


## Question A.24

_Generalisation:_ To which population can the results of this study be applied to? Explain why.

**Solution**

...












# B. Lab: Does name increase tips?

## Question B.1

Identify the observational units in this study.

**Solution**

...


## Question B.2

Is this an observational study or a randomized experiment? Explain why.

**Solution**

...


## Question B.3

What are the explanatory and response variables in this study?

Classify them as either categorical (also binary) or quantitative.

**Solution**

...


## Question B.4

State, in words and in symbols, the waitress' null and alternative hypotheses.

**Solution**

...


## Question B.5

Comment on what a Type I error and a Type II error would mean in this particular study.

Would you consider one of these two errors to be more worrying than the other? Explain why.

**Solution**

...


## Question B.6

Assuming that the population variances are __not__ equal, calculate the test statistic and the $p$-value.

For your convenience, we have already calculated the degrees of freedom, which are $df = 32.5$.

_**Hint:** As you do not have the party-by-party tipping amounts, but only summary statistics, you can not use the `t.test()` function, which requires the data at the finest level (the observational units)._

**Solution**

...


## Question B.7

At the significance level $\alpha = 0.05$, what would you conclude?

**Solution**

...


## Question B.8

The paper only reports the sample mean tips and standard deviations for the name and no name conditions.

Does the paper provide enough information to check whether the validity conditions of the two-sample $t$-test are satisfied? 

If yes, check that the conditions are met. If not, explain which additional information you would need.

**Solution**

...


## Question B.9

Calculate a 95% confidence interval for the difference in population mean tipping amount between the name and no name conditions.

Write a sentence or two interpreting what the interval reveals. 

_**Hint**: The degrees of freedom were given in Question B.6._

**Solution**

...


## Question B.10

Regardless of whether the validity conditions of the $t$-test are met, summarise your conclusions from this test.

Make sure to also comment on causation and generalisability of your results.

**Solution**

...

