<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 MLR for longitudinal data (growth curve analysis) | Multivariate Statistics and Methodology using R</title>
  <meta name="description" content="This is the page that contains the course labs materials" />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 MLR for longitudinal data (growth curve analysis) | Multivariate Statistics and Methodology using R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is the page that contains the course labs materials" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 MLR for longitudinal data (growth curve analysis) | Multivariate Statistics and Methodology using R" />
  
  <meta name="twitter:description" content="This is the page that contains the course labs materials" />
  

<meta name="author" content="Department of Psychology, University of Edinburgh" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="basic-multilevel-regression.html"/>
<link rel="next" href="other-random-effects-structures.html"/>
<script src="libs/jquery/jquery.min.js"></script>
<link href="libs/gitbook/css/style.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook/css/plugin-clipboard.css" rel="stylesheet" />









<script>
  $(document).ready(function() {
    $head = $('#header');
    $head.prepend('<img style="padding-right:25%; margin-bottom:10px;" src="https://www.ed.ac.uk/sites/all/themes/uoe/assets/logo.png" width="770px" align="left">')
  });
</script>

<script>
function toggle_visibility(id1, id2) {
var e = document.getElementById(id1);
var f = document.getElementById(id2);
e.style.display = ((e.style.display!='none') ? 'none' : 'block');
if(f.classList.contains('fa-plus-square')) {
    f.classList.add('fa-minus-square')
    f.classList.remove('fa-plus-square')
} else {
    f.classList.add('fa-plus-square')
    f.classList.remove('fa-minus-square')
}
}
</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(data-line-number);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MSMR</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Overview of the Course</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#the-team"><i class="fa fa-check"></i>The team</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-stuff"><i class="fa fa-check"></i>R stuff</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-cheatsheets"><i class="fa fa-check"></i>R Cheatsheets</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#r-community"><i class="fa fa-check"></i>R Community</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html"><i class="fa fa-check"></i><b>1</b> Tidyverse &amp; Markdown</a><ul>
<li class="chapter" data-level="" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#packages"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#lecture-slides"><i class="fa fa-check"></i>Lecture slides</a></li>
<li class="chapter" data-level="" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#background-reading"><i class="fa fa-check"></i>Background &amp; Reading</a></li>
<li class="chapter" data-level="1.1" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#data-visualization-with-ggplot"><i class="fa fa-check"></i><b>1.1</b> Data Visualization with <code>ggplot</code></a><ul>
<li class="chapter" data-level="1.1.1" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#geoms"><i class="fa fa-check"></i><b>1.1.1</b> Geoms</a></li>
<li class="chapter" data-level="1.1.2" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#recreating-a-plot"><i class="fa fa-check"></i><b>1.1.2</b> Recreating a plot</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#data-management-with-the-tidyverse"><i class="fa fa-check"></i><b>1.2</b> Data management with the Tidyverse</a><ul>
<li class="chapter" data-level="1.2.1" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#piping"><i class="fa fa-check"></i><b>1.2.1</b> Piping!</a></li>
<li class="chapter" data-level="1.2.2" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#grouping-summarising-filtering-mutating-and-selecting"><i class="fa fa-check"></i><b>1.2.2</b> Grouping, summarising, filtering, mutating and selecting</a></li>
<li class="chapter" data-level="1.2.3" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#reshaping"><i class="fa fa-check"></i><b>1.2.3</b> Reshaping</a></li>
<li class="chapter" data-level="" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#less-guidance"><i class="fa fa-check"></i>Less guidance</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#reproducible-research-with-rmarkdown"><i class="fa fa-check"></i><b>1.3</b> Reproducible research with RMarkdown</a><ul>
<li class="chapter" data-level="1.3.1" data-path="tidyverse-markdown.html"><a href="tidyverse-markdown.html#convert-a-script-into-a-r-notebook"><i class="fa fa-check"></i><b>1.3.1</b> Convert a script into a R Notebook</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html"><i class="fa fa-check"></i><b>2</b> Basic Multilevel Regression</a><ul>
<li class="chapter" data-level="" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#packages-1"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#lecture-slides-1"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#background-reading-1"><i class="fa fa-check"></i>Background &amp; Reading</a></li>
<li class="chapter" data-level="2.1" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#lme4"><i class="fa fa-check"></i><b>2.1</b> LME4</a></li>
<li class="chapter" data-level="2.2" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#introduction-to-mlr"><i class="fa fa-check"></i><b>2.2</b> Introduction to MLR</a><ul>
<li class="chapter" data-level="2.2.1" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#exercise-1"><i class="fa fa-check"></i><b>2.2.1</b> Exercise 1</a></li>
<li class="chapter" data-level="2.2.2" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#exercise-2"><i class="fa fa-check"></i><b>2.2.2</b> Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#logistic-mlr"><i class="fa fa-check"></i><b>2.3</b> Logistic MLR</a><ul>
<li class="chapter" data-level="2.3.1" data-path="basic-multilevel-regression.html"><a href="basic-multilevel-regression.html#exercise-3"><i class="fa fa-check"></i><b>2.3.1</b> Exercise 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html"><i class="fa fa-check"></i><b>3</b> MLR for longitudinal data (growth curve analysis)</a><ul>
<li class="chapter" data-level="" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#packages-2"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#lecture-slides-2"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#background-reading-2"><i class="fa fa-check"></i>Background &amp; Reading</a></li>
<li class="chapter" data-level="3.1" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#introduction"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#exercise-1-1"><i class="fa fa-check"></i><b>3.2</b> Exercise 1</a><ul>
<li class="chapter" data-level="" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#interpret-the-results-of-your-full-model"><i class="fa fa-check"></i>Interpret the results of your full model</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="mlr-for-longitudinal-data-growth-curve-analysis.html"><a href="mlr-for-longitudinal-data-growth-curve-analysis.html#exercise-2-writing-up-and-logistic-gca"><i class="fa fa-check"></i><b>3.3</b> Exercise 2: Writing up, and Logistic GCA</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html"><i class="fa fa-check"></i><b>4</b> Other random effects structures</a><ul>
<li class="chapter" data-level="" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#packages-3"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#lecture-slides-3"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#background-reading-3"><i class="fa fa-check"></i>Background &amp; Reading</a></li>
<li class="chapter" data-level="4.1" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#crossed-random-effects"><i class="fa fa-check"></i><b>4.1</b> Crossed random effects</a><ul>
<li class="chapter" data-level="4.1.1" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#exercise-1-2"><i class="fa fa-check"></i><b>4.1.1</b> Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#dealing-with-issue-of-non-convergence-and-singular-fits"><i class="fa fa-check"></i><b>4.2</b> Dealing with issue of non-convergence and singular fits</a><ul>
<li class="chapter" data-level="4.2.1" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#exercise-2-1"><i class="fa fa-check"></i><b>4.2.1</b> Exercise 2</a></li>
<li class="chapter" data-level="4.2.2" data-path="other-random-effects-structures.html"><a href="other-random-effects-structures.html#exercise-3-1"><i class="fa fa-check"></i><b>4.2.2</b> Exercise 3</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html"><i class="fa fa-check"></i><b>5</b> Recap &amp; Individual differences</a><ul>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#packages-4"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#lecture-slides-4"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#mixed-model-recap"><i class="fa fa-check"></i>Mixed model recap</a><ul>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#simple-regression"><i class="fa fa-check"></i>Simple regression</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#clustered-multi-level-data-structures"><i class="fa fa-check"></i>Clustered (multi-level) data structures</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#random-intercept-models"><i class="fa fa-check"></i>Random intercept models</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#random-slopes"><i class="fa fa-check"></i>Random slopes</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#fixef-ranef-and-coef"><i class="fa fa-check"></i>Fixef(), Ranef, and Coef</a></li>
<li class="chapter" data-level="" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#more-levels-nested-and-crossed-random-effects"><i class="fa fa-check"></i>More levels: Nested and Crossed random-effects</a></li>
</ul></li>
<li class="chapter" data-level="5.1" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#the-lab"><i class="fa fa-check"></i><b>5.1</b> THE LAB</a><ul>
<li class="chapter" data-level="5.1.1" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#exercise-1-3"><i class="fa fa-check"></i><b>5.1.1</b> Exercise 1</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="recap-individual-differences.html"><a href="recap-individual-differences.html#exercise-2-2"><i class="fa fa-check"></i><b>5.2</b> Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="break-week.html"><a href="break-week.html"><i class="fa fa-check"></i><b>6</b> <font color="red">Break Week</font></a></li>
<li class="chapter" data-level="7" data-path="efa-and-pca.html"><a href="efa-and-pca.html"><i class="fa fa-check"></i><b>7</b> EFA and PCA</a><ul>
<li class="chapter" data-level="" data-path="efa-and-pca.html"><a href="efa-and-pca.html#packages-5"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="efa-and-pca.html"><a href="efa-and-pca.html#lecture-slides-5"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="7.1" data-path="efa-and-pca.html"><a href="efa-and-pca.html#todays-exercises"><i class="fa fa-check"></i><b>7.1</b> Today’s Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html"><i class="fa fa-check"></i><b>8</b> Confirmatory Factor Analysis (CFA)</a><ul>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#packages-6"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#lecture-slides-6"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#quick-recap"><i class="fa fa-check"></i>Quick recap</a></li>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#data"><i class="fa fa-check"></i>Data</a></li>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#one-factor-model"><i class="fa fa-check"></i>One factor model</a></li>
<li class="chapter" data-level="" data-path="confirmatory-factor-analysis-cfa.html"><a href="confirmatory-factor-analysis-cfa.html#two-factor-model"><i class="fa fa-check"></i>Two factor model</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="path-analysis.html"><a href="path-analysis.html"><i class="fa fa-check"></i><b>9</b> Path Analysis</a><ul>
<li class="chapter" data-level="" data-path="path-analysis.html"><a href="path-analysis.html#packages-7"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="path-analysis.html"><a href="path-analysis.html#lecture-slides-7"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="path-analysis.html"><a href="path-analysis.html#quick-recap-1"><i class="fa fa-check"></i>Quick recap</a></li>
<li class="chapter" data-level="" data-path="path-analysis.html"><a href="path-analysis.html#exercises"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="sem-i.html"><a href="sem-i.html"><i class="fa fa-check"></i><b>10</b> SEM I</a><ul>
<li class="chapter" data-level="" data-path="sem-i.html"><a href="sem-i.html#packages-8"><i class="fa fa-check"></i>Packages</a></li>
<li class="chapter" data-level="" data-path="sem-i.html"><a href="sem-i.html#lecture-slides-8"><i class="fa fa-check"></i>Lecture Slides</a></li>
<li class="chapter" data-level="" data-path="sem-i.html"><a href="sem-i.html#overview"><i class="fa fa-check"></i>Overview</a></li>
<li class="chapter" data-level="" data-path="sem-i.html"><a href="sem-i.html#exercises-1"><i class="fa fa-check"></i>Exercises</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Multivariate Statistics and Methodology using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="mlr-for-longitudinal-data-growth-curve-analysis" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> MLR for longitudinal data (growth curve analysis)</h1>
<div id="packages-2" class="section level3 unnumbered">
<h3>Packages</h3>
<ul>
<li>lme4<br />
</li>
<li>tidyverse<br />
</li>
<li>effects</li>
</ul>
<p>We will also be needing to access some useful functions from Dan for getting p-values and coding polynomials.<br />
<br>
The <code>source()</code> function basically takes in R code and evaluates it. You can download R scripts with Dan’s code <a href="https://uoe-psychology.github.io/uoe_psystats/multivar/functions/get_pvalues.R">here</a> and <a href="https://uoe-psychology.github.io/uoe_psystats/multivar/functions/code_poly.R">here</a>.<br />
However, you can also source them directly from the URLs, and read them into your environment:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" data-line-number="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb58-2" data-line-number="2"><span class="kw">library</span>(lme4)</a>
<a class="sourceLine" id="cb58-3" data-line-number="3"><span class="kw">library</span>(effects)</a>
<a class="sourceLine" id="cb58-4" data-line-number="4"><span class="kw">source</span>(<span class="st">&#39;https://uoe-psychology.github.io/uoe_psystats/multivar/functions/get_pvalues.R&#39;</span>)</a>
<a class="sourceLine" id="cb58-5" data-line-number="5"><span class="kw">source</span>(<span class="st">&quot;https://uoe-psychology.github.io/uoe_psystats/multivar/functions/code_poly.R&quot;</span>)</a></code></pre></div>
</div>
<div id="lecture-slides-2" class="section level3 unnumbered">
<h3>Lecture Slides</h3>
<p>The lecture slides can be accessed <a href="https://uoe-psychology.github.io/uoe_psystats/multivar/lectures/Lecture03_MLRforLDA.html">here</a>.
The data for the lecture can be found at <a href="https://edin.ac/2TieJK0">https://edin.ac/2TieJK0</a>.</p>
</div>
<div id="background-reading-2" class="section level3 unnumbered">
<h3>Background &amp; Reading</h3>
<ul>
<li><a href="https://doi.org/10.1080/15248371003699969">Curran et al., 2010</a><br />
</li>
<li><a href="https://doi.org/10.1093/jole/lzv003">Winter &amp; Wieling, 2016</a></li>
</ul>
</div>
<div id="introduction" class="section level2">
<h2><span class="header-section-number">3.1</span> Introduction</h2>
<p>This week we are going to look at how we might use MLR to study longitudinal data. That is, data in which repeated measurements are taken over a continuous domain, with the potential for observations to be unevenly spaced, or missing at certain points, and which are likely to display <strong>non-linear patterns</strong>. The lab will focus on including higher-order polynomials in MLR to capture non-linearity.
<br></p>
<div class="red">
<h5 id="solutions-are-available" class="unnumbered">Solutions are available</h5>
<p>Solutions are already available for the first half of today’s lab.<br />
We encourage you to try working through the questions yourself before looking at the solutions.</p>
</div>
</div>
<div id="exercise-1-1" class="section level2">
<h2><span class="header-section-number">3.2</span> Exercise 1</h2>
<p><strong>Use natural (not orthogonal) polynomials to analyze decline in performance of 30 individuals with probable Alzheimer’s disease on three different kinds of tasks - Memory, complex activities of daily living (ADL), and simple activities of daily living.</strong></p>
<div class="question">
<p class="question-begin">
► Question 1
</p>
<div class="question-body">
<p>Read the data in to R from the following url: <a href="https://edin.ac/35Njwpl">https://edin.ac/35Njwpl</a>
. The data is in .rda format.</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-24" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-24&#39;, &#39;sol-start-24&#39;)"></span>
</p>
<div id="sol-body-24" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" data-line-number="1"><span class="kw">load</span>(<span class="kw">url</span>(<span class="st">&quot;https://edin.ac/35Njwpl&quot;</span>))</a>
<a class="sourceLine" id="cb59-2" data-line-number="2"><span class="kw">summary</span>(Az)</a></code></pre></div>
<pre><code>##     Subject         Time          Task      Performance   
##  1      : 30   Min.   : 1.0   cADL  :300   Min.   : 2.00  
##  2      : 30   1st Qu.: 3.0   sADL  :300   1st Qu.:40.00  
##  3      : 30   Median : 5.5   Memory:300   Median :52.00  
##  4      : 30   Mean   : 5.5                Mean   :49.27  
##  5      : 30   3rd Qu.: 8.0                3rd Qu.:61.00  
##  6      : 30   Max.   :10.0                Max.   :85.00  
##  (Other):720</code></pre>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<br>
<hr />
<p><br><br></p>
<div class="question">
<p class="question-begin">
► Question 2
</p>
<div class="question-body">
<p>Plot the observed data (the performance over time for each type of task).</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-25" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-25&#39;, &#39;sol-start-25&#39;)"></span>
</p>
<div id="sol-body-25" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" data-line-number="1"><span class="kw">ggplot</span>(Az, <span class="kw">aes</span>(Time, Performance, <span class="dt">color=</span>Task, <span class="dt">fill=</span>Task)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb61-2" data-line-number="2"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data=</span>mean_se, <span class="dt">geom=</span><span class="st">&quot;ribbon&quot;</span>, <span class="dt">color=</span><span class="ot">NA</span>, <span class="dt">alpha=</span><span class="fl">0.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb61-3" data-line-number="3"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun=</span>mean, <span class="dt">geom=</span><span class="st">&quot;line&quot;</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<br>
<hr />
<p><br><br></p>
<div class="question">
<p class="question-begin">
► Question 3
</p>
<div class="question-body">
<p>Why are natural polynomials more useful for these data?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-26" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-26&#39;, &#39;sol-start-26&#39;)"></span>
</p>
<div id="sol-body-26" class="solution-body" style="display: none;">
<p>Because it’s useful to know whether there are task differences at the starting baseline point</p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<br>
<hr />
<p><br><br></p>
<div class="question">
<p class="question-begin">
► Question 4
</p>
<div class="question-body">
<p>Fit the GCA model(s).</p>
<p>Steps required:</p>
<ol style="list-style-type: decimal">
<li>Add 1st and 2nd order natural polynomials to the data using the <code>code_poly()</code> function.</li>
<li>Create a baseline model, in which performance varies over time, but no differences in Task are estimated. Think about random effect structure - what are the observations grouped by? Are observations nested?</li>
<li>Create a new model with a fixed effect of Task</li>
<li>Create a new model in which performance varies linearly over time between Task type.</li>
<li>Create a new model in which linear and quadratic performance over time varies between Task type.</li>
<li>Run model comparisons.</li>
</ol>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-27" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-27&#39;, &#39;sol-start-27&#39;)"></span>
</p>
<div id="sol-body-27" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" data-line-number="1"><span class="co"># prep for analysis</span></a>
<a class="sourceLine" id="cb62-2" data-line-number="2">Az &lt;-<span class="st"> </span><span class="kw">code_poly</span>(Az, <span class="dt">predictor=</span><span class="st">&quot;Time&quot;</span>, <span class="dt">poly.order=</span><span class="dv">2</span>, <span class="dt">orthogonal=</span>F, <span class="dt">draw.poly =</span> F)</a>
<a class="sourceLine" id="cb62-3" data-line-number="3"></a>
<a class="sourceLine" id="cb62-4" data-line-number="4"><span class="co"># fit the full model incrementally</span></a>
<a class="sourceLine" id="cb62-5" data-line-number="5">m.base &lt;-<span class="st"> </span><span class="kw">lmer</span>(Performance <span class="op">~</span><span class="st"> </span>(poly1 <span class="op">+</span><span class="st"> </span>poly2) <span class="op">+</span></a>
<a class="sourceLine" id="cb62-6" data-line-number="6"><span class="st">                 </span>(poly1 <span class="op">+</span><span class="st"> </span>poly2 <span class="op">|</span><span class="st"> </span>Subject) <span class="op">+</span><span class="st"> </span>(poly1 <span class="op">+</span><span class="st"> </span>poly2 <span class="op">|</span><span class="st"> </span>Subject<span class="op">:</span>Task),</a>
<a class="sourceLine" id="cb62-7" data-line-number="7">               <span class="dt">data=</span>Az, <span class="dt">REML=</span>F)</a>
<a class="sourceLine" id="cb62-8" data-line-number="8">m<span class="fl">.0</span> &lt;-<span class="st"> </span><span class="kw">lmer</span>(Performance <span class="op">~</span><span class="st"> </span>(poly1 <span class="op">+</span><span class="st"> </span>poly2) <span class="op">+</span><span class="st"> </span>Task <span class="op">+</span></a>
<a class="sourceLine" id="cb62-9" data-line-number="9"><span class="st">              </span>(poly1 <span class="op">+</span><span class="st"> </span>poly2 <span class="op">|</span><span class="st"> </span>Subject) <span class="op">+</span><span class="st"> </span>(poly1 <span class="op">+</span><span class="st"> </span>poly2 <span class="op">|</span><span class="st"> </span>Subject<span class="op">:</span>Task),</a>
<a class="sourceLine" id="cb62-10" data-line-number="10">            <span class="dt">data=</span>Az, <span class="dt">REML=</span>F)</a>
<a class="sourceLine" id="cb62-11" data-line-number="11">m<span class="fl">.1</span> &lt;-<span class="st"> </span><span class="kw">lmer</span>(Performance <span class="op">~</span><span class="st"> </span>poly1<span class="op">*</span>Task <span class="op">+</span><span class="st"> </span>poly2 <span class="op">+</span></a>
<a class="sourceLine" id="cb62-12" data-line-number="12"><span class="st">              </span>(poly1 <span class="op">+</span><span class="st"> </span>poly2 <span class="op">|</span><span class="st"> </span>Subject) <span class="op">+</span><span class="st"> </span>(poly1 <span class="op">+</span><span class="st"> </span>poly2 <span class="op">|</span><span class="st"> </span>Subject<span class="op">:</span>Task),</a>
<a class="sourceLine" id="cb62-13" data-line-number="13">            <span class="dt">data=</span>Az, <span class="dt">REML=</span>F)</a>
<a class="sourceLine" id="cb62-14" data-line-number="14">m.Az.full &lt;-<span class="st"> </span><span class="kw">lmer</span>(Performance <span class="op">~</span><span class="st"> </span>(poly1 <span class="op">+</span><span class="st"> </span>poly2)<span class="op">*</span>Task <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb62-15" data-line-number="15"><span class="st">                  </span>(poly1 <span class="op">+</span><span class="st"> </span>poly2 <span class="op">|</span><span class="st"> </span>Subject) <span class="op">+</span><span class="st"> </span>(poly1 <span class="op">+</span><span class="st"> </span>poly2 <span class="op">|</span><span class="st"> </span>Subject<span class="op">:</span>Task), </a>
<a class="sourceLine" id="cb62-16" data-line-number="16">                <span class="dt">data=</span>Az, <span class="dt">REML=</span>F)</a>
<a class="sourceLine" id="cb62-17" data-line-number="17"><span class="kw">anova</span>(m.base, m<span class="fl">.0</span>, m<span class="fl">.1</span>, m.Az.full)</a></code></pre></div>
<pre><code>## Data: Az
## Models:
## m.base: Performance ~ (poly1 + poly2) + (poly1 + poly2 | Subject) + (poly1 + 
## m.base:     poly2 | Subject:Task)
## m.0: Performance ~ (poly1 + poly2) + Task + (poly1 + poly2 | Subject) + 
## m.0:     (poly1 + poly2 | Subject:Task)
## m.1: Performance ~ poly1 * Task + poly2 + (poly1 + poly2 | Subject) + 
## m.1:     (poly1 + poly2 | Subject:Task)
## m.Az.full: Performance ~ (poly1 + poly2) * Task + (poly1 + poly2 | Subject) + 
## m.Az.full:     (poly1 + poly2 | Subject:Task)
##           Df    AIC    BIC  logLik deviance    Chisq Chi Df Pr(&gt;Chisq)    
## m.base    16 3804.6 3881.5 -1886.3   3772.6                               
## m.0       18 3807.8 3894.2 -1885.9   3771.8   0.8242      2     0.6623    
## m.1       20 3781.2 3877.3 -1870.6   3741.2  30.5611      2  2.311e-07 ***
## m.Az.full 22 3612.9 3718.5 -1784.4   3568.9 172.3620      2  &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="red">
<p>In these solutions we are using Dan’s <code>code_poly()</code> function. All that this does is add polynomial terms to your dataframe (it can also give you a plot if you want one by setting <code>draw.poly = TRUE</code>).
<br>
As always with R, you can do the same thing in lots of different ways.<br />
We could, for example, pass the <code>poly()</code> function directly to our model (without making storing them as variables in our dataframe), for instance:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" data-line-number="1">m.base &lt;-<span class="st"> </span><span class="kw">lmer</span>(Performance <span class="op">~</span><span class="st"> </span><span class="kw">poly</span>(Time, <span class="dt">degree =</span> <span class="dv">2</span>, <span class="dt">raw =</span> <span class="ot">TRUE</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb64-2" data-line-number="2"><span class="st">                 </span>(<span class="kw">poly</span>(Time, <span class="dt">degree =</span> <span class="dv">2</span>, <span class="dt">raw =</span> <span class="ot">TRUE</span>) <span class="op">|</span><span class="st"> </span>Subject) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb64-3" data-line-number="3"><span class="st">                 </span>(<span class="kw">poly</span>(Time, <span class="dt">degree =</span> <span class="dv">2</span>, <span class="dt">raw =</span> <span class="ot">TRUE</span>) <span class="op">|</span><span class="st"> </span>Subject<span class="op">:</span>Task),</a>
<a class="sourceLine" id="cb64-4" data-line-number="4">               <span class="dt">data=</span>Az, <span class="dt">REML=</span>F)</a></code></pre></div>
<p><br>
If you’re struggling with the idea of polynomials, try looking at the output of the following commands:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" data-line-number="1"><span class="co"># note, the &quot;raw&quot; here is the same as &quot;natural&quot;.</span></a>
<a class="sourceLine" id="cb65-2" data-line-number="2"><span class="kw">poly</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dv">3</span>, <span class="dt">raw =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb65-3" data-line-number="3"><span class="kw">poly</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dv">3</span>, <span class="dt">raw =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb65-4" data-line-number="4"></a>
<a class="sourceLine" id="cb65-5" data-line-number="5"><span class="co"># let&#39;s plot them quickly using matplot() </span></a>
<a class="sourceLine" id="cb65-6" data-line-number="6"><span class="kw">matplot</span>(<span class="kw">poly</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dv">3</span>, <span class="dt">raw =</span> <span class="ot">TRUE</span>), <span class="dt">type =</span> <span class="st">&#39;l&#39;</span>)</a>
<a class="sourceLine" id="cb65-7" data-line-number="7"><span class="kw">matplot</span>(<span class="kw">poly</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dv">3</span>, <span class="dt">raw =</span> <span class="ot">FALSE</span>), <span class="dt">type =</span> <span class="st">&#39;l&#39;</span>)</a></code></pre></div>
</div>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div id="interpret-the-results-of-your-full-model" class="section level3 unnumbered">
<h3>Interpret the results of your full model</h3>
<div class="question">
<p class="question-begin">
► Question 5
</p>
<div class="question-body">
<p>Look at the <code>summary()</code> of your full model, and try using the <code>get_pvalues()</code> function on it.</p>
<p>Which terms show significant effects of experimental factors?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-28" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-28&#39;, &#39;sol-start-28&#39;)"></span>
</p>
<div id="sol-body-28" class="solution-body" style="display: none;">
<p>Get p-values for your full model:</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" data-line-number="1"><span class="kw">get_pvalues</span>(m.Az.full)</a></code></pre></div>
<pre><code>##                      Estimate Std..Error     t.value     p.normal p.normal.star
## (Intercept)      67.161666666 0.92669108  72.4747097 0.000000e+00           ***
## poly1            -3.287803030 0.34111997  -9.6382602 0.000000e+00           ***
## poly2             0.009469697 0.01243576   0.7614891 4.463650e-01              
## TasksADL          0.095000000 0.81069066   0.1171840 9.067142e-01              
## TaskMemory        1.240000000 0.81069066   1.5295600 1.261257e-01              
## poly1:TasksADL    1.362196970 0.26753689   5.0916229 3.550117e-07           ***
## poly1:TaskMemory -3.977070707 0.26753689 -14.8655038 0.000000e+00           ***
## poly2:TasksADL   -0.013257576 0.01748015  -0.7584360 4.481900e-01              
## poly2:TaskMemory  0.338888889 0.01748015  19.3870696 0.000000e+00           ***</code></pre>
<ul>
<li>Intercepts are not different: performance in all tasks starts out the same (thanks, natural polynomials)</li>
<li>Linear slopes are different: compared to complex ADL tasks, decline in simple ADL tasks is slower and decline in Memory is faster.</li>
<li>Quadratic term is different for Memory: decline in cADL and sADL tasks is approximately linear, decline in Memory has more curvature (reaching floor?)</li>
</ul>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<br>
<hr />
<p><br><br></p>
<div class="question">
<p class="question-begin">
► Question 6
</p>
<div class="question-body">
<p>To what extent do model comparisons and the parameter-specific p-values yield the same results?</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-29" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-29&#39;, &#39;sol-start-29&#39;)"></span>
</p>
<div id="sol-body-29" class="solution-body" style="display: none;">
<p>Model comparisons suggest:</p>
<ul>
<li>Linear slopes are different: <span class="math inline">\(\chi^2(2)=30.56, p &lt;&lt; 0.0001\)</span> (comparison <code>m.0</code> and <code>m.1</code> above).<br />
</li>
<li>Quadratic term is different: <span class="math inline">\(\chi^2(2)=172.36, p &lt;&lt; 0.0001\)</span> (comparison <code>m.1</code> and <code>m.Az.full</code> above).</li>
</ul>
<p><em>Note:</em> We can’t investigate the intercept difference via the model comparisons above. Comparison between <code>m.base</code> and <code>m.0</code> indicates difference holding polynomial terms constant (not the conditional effect where poly1 and poly2 are 0).**</p>
<div class="red">
<p><br>
<strong>Please note:</strong> There was an error in last week’s lab about assessing ‘baseline’ differences between groups.
Model comparison between <code>y~time</code> and <code>y~time+g</code> does <em>not</em> assess the difference in <code>y</code> between groups in <code>g</code> where <code>time==0</code>, but instead assesses the difference in <code>y</code> between groups in <code>g</code> holding time constant.
<br>
Last week’s lab has been amended. Apologies for any confusion!</p>
</div>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<br>
<hr />
<p><br><br></p>
<div class="question">
<p class="question-begin">
► Question 7
</p>
<div class="question-body">
<p>Plot model fit</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-30" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-30&#39;, &#39;sol-start-30&#39;)"></span>
</p>
<div id="sol-body-30" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" data-line-number="1"><span class="kw">ggplot</span>(Az, <span class="kw">aes</span>(Time, Performance, <span class="dt">color=</span>Task)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb68-2" data-line-number="2"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data=</span>mean_se, <span class="dt">geom=</span><span class="st">&quot;pointrange&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb68-3" data-line-number="3"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun=</span>mean, <span class="dt">geom=</span><span class="st">&quot;line&quot;</span>, <span class="kw">aes</span>(<span class="dt">y=</span><span class="kw">fitted</span>(m.Az.full)))</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-56-1.png" width="576" /></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
</div>
</div>
<div id="exercise-2-writing-up-and-logistic-gca" class="section level2">
<h2><span class="header-section-number">3.3</span> Exercise 2: Writing up, and Logistic GCA</h2>
<p>We saw in the <a href="https://uoe-psychology.github.io/uoe_psystats/multivar/lectures/Lecture03_MLRforLDA.html#(4)">lecture</a> a walk-through of using GCA to model the eye-tracking data from a spoken word-to-picture matching task.</p>
<div class="question">
<p class="question-begin">
► Question 8
</p>
<div class="question-body">
<p>The model we saw in the lecture had the following structure and results:</p>
<pre><code>&gt; m.full &lt;- lmer(meanFix ~ (poly1+poly2+poly3)*Condition + 
                 (poly1+poly2+poly3 | Subject) + 
                 (poly1+poly2 | Subject:Condition), 
               control = lmerControl(optimizer=&quot;bobyqa&quot;),
               data=TargetFix, REML=F)

&gt; coef(summary(m.full))
                      Estimate Std. Error      t value
(Intercept)       0.4773227513 0.01385240 34.457775306
poly1               0.6385603705 0.05993519 10.654181583
poly2              -0.1095979256 0.03848819 -2.847573180
poly3              -0.0932611870 0.02041640 -4.567955536
ConditionLow     -0.0581122429 0.01901291 -3.056462582
poly1:ConditionLow  0.0003188189 0.06330556  0.005036191
poly2:ConditionLow  0.1635455113 0.05426498  3.013831365
poly3:ConditionLow -0.0020869051 0.02014728 -0.103582452</code></pre>
<p><br>
Write up the results of the model</p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-31" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-31&#39;, &#39;sol-start-31&#39;)"></span>
</p>
<div id="sol-body-31" class="solution-body" style="display: none;">
<p>There are two rules of thumb for reporting growth curve analysis results:</p>
<ul>
<li><strong>Clearly describe each of the three key components of the model</strong>: the functional form (third-order orthogonal polynomial), the fixed effects (effect of Condition on all time terms), and the random effects (effect of Subject on each of the time terms and nested effects of Subject-by-Condition on each of the time terms except the cubic). Depending on the circumstances and complexity of the model, you may want to include additional information about the factors and why they were included or not. It’s also a good idea to report which method was used for computing p-values.<br />
</li>
<li><strong>For key findings, report parameter estimates and standard errors along with significance tests</strong>. In some cases the model comparison is going to be enough, but for key findings, the readers should want to see the parameter estimates. The parameter estimate standard errors are critical for interpreting the estimates, so those should be reported as well. The t-values are not critical to report (they are just Estimate divided by the Std Error, so they can always be computed from the reported estimates and standard errors). If there are many estimated parameters, it may be a good idea to focus the main text discussion on the most important ones and report the full set in a table or appendix.<br />
<br>
<br>
Here is how we might report the results from the example above:<br>
<small>[Note, we haven’t included Table 1 here. If you want a nice way of creating tables, try installing the <code>sjPlot</code> package, and using <code>tab_model()</code> on your model.]</small>
<br>
<br>
<div class="noteBox">
Growth curve analysis (Mirman, 2014) was used to analyze the target gaze data from 300ms to 1000ms after word onset. The overall time course of target fixations was modeled with a third-order (cubic) orthogonal polynomial and fixed effects of Condition (Low vs. High frequency; within-participants) on all time terms. The model also included participant random effects on all time terms and participant-by-condition random effects on all time terms except the cubic (estimating random effects is “expensive” in terms of the number of observation required, so this cubic term was excluded because it tends to capture less-relevant effects in the tails). There was a significant effect of Condition on the intercept term, indicating lower overall target fixation proportions for the Low condition relative to the High condition (Estimate = -0.058, SE = 0.019, p &lt; 0.01). There was also a significant effect on the quadratic term, indicating shallower curvature - slower word recognition - in the Low condition relative to the High condition (Estimate = 0.16, SE = 0.054, p &lt; 0.01). All other effects of Condition were not significant (see Table 1 for full results).</li>
</ul>
</div>
<p><br></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="question">
<p class="question-begin">
► Question 9
</p>
<div class="question-body">
<p>Above, we analysed the proportion of fixations to the target picture in a given 50~ms time bin (the <code>meanFix</code> variable). We can express this differently, in terms of the number of samples in each 50~ms bin in which there were fixations to the target, and the total number of samples. This can lend itself to being modelled as a binomial (where success is fixation on the target).
<br>
In the data, the <code>sumFix</code> variable contains the number of samples in which the target was fixated upon, and the <code>N</code> variable contains the total number of samples in that bin. Like we saw last week, we can model a binomial using <code>cbind(num_successes, num_failures)</code>, so here we can use <code>cbind(sumFix, N-sumFix)~ ...</code>
<br>
<br>
<strong>Re-analyze <code>TargetFix</code> data using logistic GCA.</strong>
<br>
<br>
The data (.rda format) is available at <a href="https://edin.ac/2TieJK0">https://edin.ac/2TieJK0</a></p>
<p class="question-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>
<div class="solution">
<p class="solution-begin">
► Solution<span id="sol-start-32" class="fa fa-plus-square solution-icon clickable" onclick="toggle_visibility(&#39;sol-body-32&#39;, &#39;sol-start-32&#39;)"></span>
</p>
<div id="sol-body-32" class="solution-body" style="display: none;">
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" data-line-number="1"><span class="kw">load</span>(<span class="kw">url</span>(<span class="st">&quot;https://edin.ac/2TieJK0&quot;</span>))</a>
<a class="sourceLine" id="cb70-2" data-line-number="2"><span class="co">#make 3rd-order orth poly</span></a>
<a class="sourceLine" id="cb70-3" data-line-number="3">TargetFix &lt;-<span class="st"> </span><span class="kw">code_poly</span>(TargetFix, <span class="dt">predictor=</span><span class="st">&quot;timeBin&quot;</span>, <span class="dt">poly.order=</span><span class="dv">3</span>, <span class="dt">draw.poly=</span>F)</a>
<a class="sourceLine" id="cb70-4" data-line-number="4"><span class="co"># fit logisitc GCA model</span></a>
<a class="sourceLine" id="cb70-5" data-line-number="5">m.log &lt;-<span class="st"> </span><span class="kw">glmer</span>(<span class="kw">cbind</span>(sumFix, N<span class="op">-</span>sumFix) <span class="op">~</span><span class="st"> </span>(poly1<span class="op">+</span>poly2<span class="op">+</span>poly3)<span class="op">*</span>Condition <span class="op">+</span></a>
<a class="sourceLine" id="cb70-6" data-line-number="6"><span class="st">                 </span>(poly1<span class="op">+</span>poly2<span class="op">+</span>poly3 <span class="op">|</span><span class="st"> </span>Subject) <span class="op">+</span></a>
<a class="sourceLine" id="cb70-7" data-line-number="7"><span class="st">                 </span>(poly1<span class="op">+</span>poly2 <span class="op">|</span><span class="st"> </span>Subject<span class="op">:</span>Condition),</a>
<a class="sourceLine" id="cb70-8" data-line-number="8">               <span class="dt">data=</span>TargetFix, <span class="dt">family=</span>binomial, <span class="dt">control =</span> <span class="kw">glmerControl</span>(<span class="dt">optimizer =</span> <span class="st">&quot;bobyqa&quot;</span>))</a>
<a class="sourceLine" id="cb70-9" data-line-number="9"><span class="kw">summary</span>(m.log)</a></code></pre></div>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: binomial  ( logit )
## Formula: cbind(sumFix, N - sumFix) ~ (poly1 + poly2 + poly3) * Condition +  
##     (poly1 + poly2 + poly3 | Subject) + (poly1 + poly2 | Subject:Condition)
##    Data: TargetFix
## Control: glmerControl(optimizer = &quot;bobyqa&quot;)
## 
##      AIC      BIC   logLik deviance df.resid 
##   1419.1   1508.0   -685.6   1371.1      276 
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.75431 -0.40973 -0.00307  0.37868  2.06240 
## 
## Random effects:
##  Groups            Name        Variance Std.Dev. Corr             
##  Subject:Condition (Intercept) 0.032340 0.17983                   
##                    poly1       0.401862 0.63393  -0.68            
##                    poly2       0.147989 0.38469  -0.23  0.73      
##  Subject           (Intercept) 0.001751 0.04185                   
##                    poly1       0.343615 0.58619   1.00            
##                    poly2       0.001991 0.04462  -1.00 -1.00      
##                    poly3       0.027493 0.16581  -1.00 -1.00  1.00
## Number of obs: 300, groups:  Subject:Condition, 20; Subject, 10
## 
## Fixed effects:
##                    Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)        -0.11675    0.06548  -1.783 0.074589 .  
## poly1               2.81834    0.29833   9.447  &lt; 2e-16 ***
## poly2              -0.55911    0.16952  -3.298 0.000973 ***
## poly3              -0.32075    0.12771  -2.512 0.012017 *  
## ConditionLow       -0.26157    0.09095  -2.876 0.004030 ** 
## poly1:ConditionLow  0.06399    0.33134   0.193 0.846851    
## poly2:ConditionLow  0.69502    0.23977   2.899 0.003747 ** 
## poly3:ConditionLow -0.07066    0.16617  -0.425 0.670679    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) poly1  poly2  poly3  CndtnL pl1:CL pl2:CL
## poly1       -0.288                                          
## poly2       -0.128  0.272                                   
## poly3       -0.100 -0.228 -0.015                            
## ConditionLw -0.690  0.297  0.081  0.012                     
## ply1:CndtnL  0.372 -0.552 -0.292 -0.024 -0.541              
## ply2:CndtnL  0.080 -0.230 -0.701  0.034 -0.116  0.415       
## ply3:CndtnL  0.013 -0.020  0.037 -0.637 -0.003  0.031 -0.056
## convergence code: 0
## boundary (singular) fit: see ?isSingular</code></pre>
<p>Simpler random effects: note that the correlations between Subject-level random effects are all +1.00 or -1.00, so can simplify the structure by removing them:</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" data-line-number="1">m.log_zc &lt;-<span class="st"> </span><span class="kw">glmer</span>(<span class="kw">cbind</span>(sumFix, N<span class="op">-</span>sumFix) <span class="op">~</span><span class="st"> </span>(poly1<span class="op">+</span>poly2<span class="op">+</span>poly3)<span class="op">*</span>Condition <span class="op">+</span></a>
<a class="sourceLine" id="cb72-2" data-line-number="2"><span class="st">                 </span>(poly1<span class="op">+</span>poly2<span class="op">+</span>poly3 <span class="op">||</span><span class="st"> </span>Subject) <span class="op">+</span></a>
<a class="sourceLine" id="cb72-3" data-line-number="3"><span class="st">                 </span>(poly1<span class="op">+</span>poly2 <span class="op">|</span><span class="st"> </span>Subject<span class="op">:</span>Condition),</a>
<a class="sourceLine" id="cb72-4" data-line-number="4">               <span class="dt">data=</span>TargetFix, <span class="dt">family=</span>binomial, <span class="dt">control =</span> <span class="kw">glmerControl</span>(<span class="dt">optimizer =</span> <span class="st">&quot;bobyqa&quot;</span>))</a>
<a class="sourceLine" id="cb72-5" data-line-number="5"><span class="kw">summary</span>(m.log_zc)</a></code></pre></div>
<pre><code>## Generalized linear mixed model fit by maximum likelihood (Laplace
##   Approximation) [glmerMod]
##  Family: binomial  ( logit )
## Formula: cbind(sumFix, N - sumFix) ~ (poly1 + poly2 + poly3) * Condition +  
##     (poly1 + poly2 + poly3 || Subject) + (poly1 + poly2 | Subject:Condition)
##    Data: TargetFix
## Control: glmerControl(optimizer = &quot;bobyqa&quot;)
## 
##      AIC      BIC   logLik deviance df.resid 
##   1411.6   1478.3   -687.8   1375.6      282 
## 
## Scaled residuals: 
##      Min       1Q   Median       3Q      Max 
## -1.69598 -0.41491 -0.00141  0.33691  2.07563 
## 
## Random effects:
##  Groups            Name        Variance Std.Dev. Corr       
##  Subject.Condition (Intercept) 0.03404  0.1845              
##                    poly1       0.42307  0.6504   -0.63      
##                    poly2       0.15312  0.3913   -0.25  0.70
##  Subject           poly3       0.00000  0.0000              
##  Subject.1         poly2       0.00000  0.0000              
##  Subject.2         poly1       0.44471  0.6669              
##  Subject.3         (Intercept) 0.00000  0.0000              
## Number of obs: 300, groups:  Subject:Condition, 20; Subject, 10
## 
## Fixed effects:
##                    Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)        -0.11770    0.06544  -1.798  0.07210 .  
## poly1               2.82162    0.31822   8.867  &lt; 2e-16 ***
## poly2              -0.55892    0.17054  -3.277  0.00105 ** 
## poly3              -0.31340    0.11646  -2.691  0.00712 ** 
## ConditionLow       -0.26066    0.09280  -2.809  0.00497 ** 
## poly1:ConditionLow  0.06593    0.33782   0.195  0.84527    
## poly2:ConditionLow  0.69049    0.24206   2.853  0.00434 ** 
## poly3:ConditionLow -0.06654    0.16627  -0.400  0.68903    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##             (Intr) poly1  poly2  poly3  CndtnL pl1:CL pl2:CL
## poly1       -0.379                                          
## poly2       -0.129  0.301                                   
## poly3       -0.018  0.029 -0.054                            
## ConditionLw -0.705  0.267  0.092  0.012                     
## ply1:CndtnL  0.357 -0.528 -0.284 -0.027 -0.509              
## ply2:CndtnL  0.092 -0.212 -0.703  0.038 -0.131  0.402       
## ply3:CndtnL  0.012 -0.020  0.037 -0.699 -0.003  0.033 -0.056
## convergence code: 0
## boundary (singular) fit: see ?isSingular</code></pre>
<p>Plot model fit</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" data-line-number="1"><span class="kw">ggplot</span>(TargetFix, <span class="kw">aes</span>(Time, meanFix, <span class="dt">color=</span>Condition)) <span class="op">+</span></a>
<a class="sourceLine" id="cb74-2" data-line-number="2"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="dt">fun.data=</span>mean_se, <span class="dt">geom=</span><span class="st">&quot;pointrange&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb74-3" data-line-number="3"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="kw">aes</span>(<span class="dt">y=</span><span class="kw">fitted</span>(m.log)), <span class="dt">fun=</span>mean, <span class="dt">geom=</span><span class="st">&quot;line&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb74-4" data-line-number="4"><span class="st">  </span><span class="kw">stat_summary</span>(<span class="kw">aes</span>(<span class="dt">y=</span><span class="kw">fitted</span>(m.log_zc)), <span class="dt">fun=</span>mean, <span class="dt">geom=</span><span class="st">&quot;line&quot;</span>, <span class="dt">linetype=</span><span class="st">&quot;dashed&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb74-5" data-line-number="5"><span class="st">  </span><span class="kw">theme_bw</span>() <span class="op">+</span><span class="st"> </span><span class="kw">expand_limits</span>(<span class="dt">y=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">1</span>)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb74-6" data-line-number="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">y=</span><span class="st">&quot;Fixation Proportion&quot;</span>, <span class="dt">x=</span><span class="st">&quot;Time since word onset (ms)&quot;</span>)</a></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-59-1.png" width="576" /></p>
<p class="solution-end">
<span class="fa fa-square-o solution-icon"></span>
</p>
</div>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="basic-multilevel-regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="other-random-effects-structures.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook/js/app.min.js"></script>
<script src="libs/gitbook/js/lunr.js"></script>
<script src="libs/gitbook/js/clipboard.min.js"></script>
<script src="libs/gitbook/js/plugin-search.js"></script>
<script src="libs/gitbook/js/plugin-sharing.js"></script>
<script src="libs/gitbook/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook/js/plugin-bookdown.js"></script>
<script src="libs/gitbook/js/jquery.highlight.js"></script>
<script src="libs/gitbook/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
